# Generated by Django 6.0.5 on 2026-07-03 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('simulacros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulacro',
            name='area',
            field=models.CharField(choices=[('general', 'General'), ('ingles', 'Ingles'), ('tecnologia', 'Tecnologia e Informatica'), ('matematicas', 'Matematicas'), ('ciencias_naturales', 'Ciencias Naturales'), ('ciencias_sociales', 'Ciencias Sociales'), ('lectura_critica', 'Lectura Critica'), ('perfil_docente', 'Perfil Docente'), ('componente_pedagogico', 'Componente Pedagogico'), ('psicotecnico', 'Psicotecnico')], default='general', max_length=40),
        ),
        migrations.AddField(
            model_name='simulacro',
            name='es_premium',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='simulacro',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulacros', to='academics.module'),
        ),
        migrations.AddField(
            model_name='simulacro',
            name='paquete_codigo',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='simulacro',
            name='tiempo_por_pregunta_segundos',
            field=models.PositiveIntegerField(default=120),
        ),
        migrations.AlterField(
            model_name='simulacro',
            name='tipo',
            field=models.CharField(choices=[('simulacro', 'Simulacro'), ('diagnostico', 'Diagnostico'), ('tematico', 'Tematico'), ('tjs', 'TJS Premium'), ('elite', 'CNSC Elite'), ('area', 'Simulacro por area')], default='simulacro', max_length=20),
        ),
    ]
