# Generated by Django 6.0.5 on 2026-07-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulacros', '0002_simulacro_area_simulacro_es_premium_simulacro_module_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulacro',
            name='area',
            field=models.CharField(choices=[('general', 'General'), ('ingles', 'Inglés'), ('tecnologia', 'Tecnología e Informática'), ('matematicas', 'Matemáticas'), ('ciencias_naturales', 'Ciencias Naturales'), ('ciencias_sociales', 'Ciencias Sociales'), ('lectura_critica', 'Lectura Crítica'), ('perfil_docente', 'Rol Docente'), ('componente_pedagogico', 'Competencias Pedagógicas'), ('psicotecnico', 'Análisis de Casos')], default='general', max_length=40),
        ),
        migrations.AlterField(
            model_name='simulacro',
            name='tipo',
            field=models.CharField(choices=[('simulacro', 'Simulacro'), ('diagnostico', 'Diagnostico'), ('tematico', 'Tematico'), ('tjs', 'TJS Premium'), ('elite', 'CNSC Elite'), ('area', 'Simulacro por área')], default='simulacro', max_length=20),
        ),
    ]
