# Generated by Django 6.0.4 on 2026-05-19 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='banco.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='BancoPregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=250)),
                ('contexto', models.TextField()),
                ('enunciado', models.TextField()),
                ('opcion_a', models.TextField()),
                ('opcion_b', models.TextField()),
                ('opcion_c', models.TextField()),
                ('opcion_d', models.TextField()),
                ('respuesta_correcta', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('justificacion', models.TextField()),
                ('fuente_normativa', models.CharField(blank=True, max_length=300)),
                ('dificultad', models.CharField(choices=[('intermedia', 'Intermedia'), ('alta', 'Alta'), ('premium', 'Premium'), ('elite', 'Elite')], default='alta', max_length=20)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banco.categoria')),
                ('subcategoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='banco.subcategoria')),
            ],
        ),
    ]
