# Generated by Django 6.0.5 on 2026-07-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bancopregunta',
            options={'ordering': ['categoria__nombre', 'subcategoria__nombre', 'id']},
        ),
        migrations.AddField(
            model_name='bancopregunta',
            name='area',
            field=models.CharField(choices=[('general', 'General'), ('ingles', 'Ingles'), ('tecnologia', 'Tecnologia e Informatica'), ('matematicas', 'Matematicas'), ('ciencias_naturales', 'Ciencias Naturales'), ('ciencias_sociales', 'Ciencias Sociales'), ('lectura_critica', 'Lectura Critica'), ('perfil_docente', 'Perfil Docente'), ('componente_pedagogico', 'Componente Pedagogico'), ('psicotecnico', 'Psicotecnico')], default='general', max_length=40),
        ),
        migrations.AddField(
            model_name='bancopregunta',
            name='competencia',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='bancopregunta',
            name='es_premium',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bancopregunta',
            name='tiempo_limite_segundos',
            field=models.PositiveIntegerField(default=120),
        ),
    ]
