# Generated by Codex on 2026-07-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0002_alter_bancopregunta_options_bancopregunta_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bancopregunta',
            name='hash_contenido',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AddField(
            model_name='bancopregunta',
            name='nivel_dificultad',
            field=models.CharField(choices=[('basico', 'Basico'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado'), ('intermedia', 'Intermedia'), ('alta', 'Alta'), ('premium', 'Premium'), ('elite', 'Elite')], default='avanzado', max_length=20),
        ),
        migrations.AlterField(
            model_name='bancopregunta',
            name='dificultad',
            field=models.CharField(choices=[('basico', 'Basico'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado'), ('intermedia', 'Intermedia'), ('alta', 'Alta'), ('premium', 'Premium'), ('elite', 'Elite')], default='alta', max_length=20),
        ),
    ]
