# Generated by Django 6.0.4 on 2026-07-17 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0003_bancopregunta_hash_contenido_bancopregunta_nivel_dificultad'),
    ]

    operations = [
        migrations.AddField(
            model_name='bancopregunta',
            name='idoneidad_a',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bancopregunta',
            name='idoneidad_b',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bancopregunta',
            name='idoneidad_c',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bancopregunta',
            name='idoneidad_d',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bancopregunta',
            name='tipo_item',
            field=models.CharField(choices=[('estandar', 'Pregunta estandar (correcto/incorrecto)'), ('mas_adecuada', 'TJS - Respuesta MAS adecuada'), ('menos_adecuada', 'TJS - Respuesta MENOS adecuada')], default='estandar', max_length=20),
        ),
        migrations.AlterField(
            model_name='bancopregunta',
            name='area',
            field=models.CharField(choices=[('general', 'General'), ('ingles', 'Inglés'), ('tecnologia', 'Tecnología e Informática'), ('matematicas', 'Matemáticas'), ('ciencias_naturales', 'Ciencias Naturales'), ('ciencias_sociales', 'Ciencias Sociales'), ('lectura_critica', 'Lectura Crítica'), ('perfil_docente', 'Perfil Docente'), ('componente_pedagogico', 'Componente Pedagogico'), ('psicotecnico', 'Psicotecnico')], default='general', max_length=40),
        ),
    ]
