# Generated by Django 6.0.4 on 2026-07-19 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0004_bancopregunta_idoneidad_a_bancopregunta_idoneidad_b_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bancopregunta',
            name='autor',
            field=models.CharField(default='IA', max_length=60),
        ),
        migrations.AddField(
            model_name='bancopregunta',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('en_revision', 'En revision'), ('aprobado', 'Aprobado'), ('publicado', 'Publicado'), ('rechazado', 'Rechazado')], default='borrador', max_length=20),
        ),
        migrations.AddField(
            model_name='bancopregunta',
            name='proceso_cognitivo',
            field=models.CharField(blank=True, choices=[('identificacion', 'Nivel 1 - Identificacion'), ('comprension_aplicada', 'Nivel 2 - Comprension aplicada'), ('analisis_situacional', 'Nivel 3 - Analisis situacional'), ('evaluacion_juicio', 'Nivel 4 - Evaluacion y juicio')], max_length=25),
        ),
        migrations.AddField(
            model_name='bancopregunta',
            name='puntaje_validacion',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bancopregunta',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='bancopregunta',
            name='area',
            field=models.CharField(choices=[('general', 'General'), ('ingles', 'Inglés'), ('tecnologia', 'Tecnología e Informática'), ('matematicas', 'Matemáticas'), ('ciencias_naturales', 'Ciencias Naturales'), ('ciencias_sociales', 'Ciencias Sociales'), ('lectura_critica', 'Lectura Crítica'), ('perfil_docente', 'Rol Docente'), ('componente_pedagogico', 'Competencias Pedagógicas'), ('psicotecnico', 'Análisis de Casos')], default='general', max_length=40),
        ),
    ]
