# Generated by Django 6.0.4 on 2026-07-19 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0005_bancopregunta_autor_bancopregunta_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bancopregunta',
            name='dificultad',
            field=models.CharField(choices=[('facil', 'Fácil'), ('medio', 'Medio'), ('alto', 'Alto'), ('muy_alto', 'Muy Alto')], default='alto', max_length=20),
        ),
        migrations.AlterField(
            model_name='bancopregunta',
            name='nivel_dificultad',
            field=models.CharField(choices=[('facil', 'Fácil'), ('medio', 'Medio'), ('alto', 'Alto'), ('muy_alto', 'Muy Alto')], default='alto', max_length=20),
        ),
    ]
