# Generated by Django 6.0.4 on 2026-04-19 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('componente', models.CharField(choices=[('pedagogico', 'Conocimientos Pedagógicos'), ('especifico', 'Conocimientos Específicos'), ('lectura_critica', 'Lectura Crítica'), ('razonamiento', 'Razonamiento Cuantitativo'), ('normativo', 'Normatividad')], max_length=20)),
                ('dificultad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=10)),
                ('enunciado', models.TextField()),
                ('contexto', models.TextField(blank=True, help_text='Caso o texto previo a la pregunta')),
                ('opcion_a', models.TextField()),
                ('opcion_b', models.TextField()),
                ('opcion_c', models.TextField()),
                ('opcion_d', models.TextField()),
                ('respuesta_correcta', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('justificacion', models.TextField(help_text='Explicación del porqué la respuesta es correcta')),
                ('fuente_normativa', models.CharField(blank=True, max_length=200)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('sesion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preguntas', to='contenidos.sesion')),
                ('tema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenidos.tema')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
            },
        ),
        migrations.CreateModel(
            name='Simulacro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('tiempo_limite_minutos', models.PositiveIntegerField(default=60)),
                ('puntaje_minimo_aprobacion', models.PositiveIntegerField(default=60)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('preguntas', models.ManyToManyField(related_name='simulacros', to='evaluaciones.pregunta')),
            ],
        ),
    ]
