from django.core.management.base import BaseCommand
from django.db import transaction
from contenidos.models import Sesion
from evaluaciones.models import Pregunta, Simulacro


class Command(BaseCommand):
    help = 'Script maestro: limpia duplicados y carga 25 preguntas para sesiones 3, 4 y 5'

    def handle(self, *args, **kwargs):
        self.stdout.write(self.style.WARNING('🧹 Limpiando preguntas duplicadas...'))
        
        # Eliminar duplicados manteniendo solo los IDs más bajos por sesión
        for sesion in Sesion.objects.all():
            preguntas = Pregunta.objects.filter(sesion=sesion).order_by('id')
            total = preguntas.count()
            if total > 25:
                ids_borrar = list(preguntas.values_list('id', flat=True)[25:])
                Pregunta.objects.filter(id__in=ids_borrar).delete()
                self.stdout.write(f'  Sesión {sesion.numero}: eliminados {len(ids_borrar)} duplicados')

        self.stdout.write(self.style.SUCCESS('✅ Limpieza completada\n'))
        
        # ============================================================
        # SESIÓN 3 — Estrategias Didácticas Activas
        # ============================================================
        self._cargar_sesion(3, self._preguntas_sesion3())
        
        # ============================================================
        # SESIÓN 4 — Evaluación Educativa y Decreto 1290
        # ============================================================
        self._cargar_sesion(4, self._preguntas_sesion4())
        
        # ============================================================
        # SESIÓN 5 — Planeación de Clase y DBA
        # ============================================================
        self._cargar_sesion(5, self._preguntas_sesion5())

        self.stdout.write(self.style.SUCCESS('\n✅ CARGA MASIVA COMPLETADA'))
        total = Pregunta.objects.count()
        self.stdout.write(self.style.SUCCESS(f'📊 Total preguntas en la base de datos: {total}'))

    def _cargar_sesion(self, numero, preguntas_data):
        try:
            sesion = Sesion.objects.get(numero=numero)
        except Sesion.DoesNotExist:
            self.stdout.write(self.style.ERROR(f'❌ Sesión {numero} no existe. Ejecuta: python manage.py cargar_sesiones'))
            return

        existentes = Pregunta.objects.filter(sesion=sesion).count()
        if existentes >= 25:
            self.stdout.write(self.style.WARNING(f'⚠ Sesión {numero} ya tiene {existentes} preguntas. Omitiendo.'))
            return

        self.stdout.write(self.style.WARNING(f'\n📚 Cargando Sesión {numero}: {sesion.titulo}'))
        creadas = 0
        with transaction.atomic():
            for data in preguntas_data:
                data['sesion'] = sesion
                Pregunta.objects.create(**data)
                creadas += 1
        self.stdout.write(self.style.SUCCESS(f'  ✅ {creadas} preguntas cargadas para Sesión {numero}'))

    def _preguntas_sesion3(self):
        return [
            {
                'componente': 'pedagogico', 'dificultad': 'media',
                'enunciado': 'El Aprendizaje Basado en Problemas (ABP) se diferencia de la enseñanza tradicional principalmente porque:',
                'opcion_a': 'El docente presenta el problema y la solución simultáneamente para ahorrar tiempo.',
                'opcion_b': 'Los estudiantes parten de un problema real o simulado para construir el conocimiento de forma activa.',
                'opcion_c': 'Se evalúa únicamente el producto final sin considerar el proceso.',
                'opcion_d': 'El docente resuelve el problema mientras los estudiantes toman nota.',
                'respuesta_correcta': 'B',
                'justificacion': 'En el ABP el problema es el punto de partida del aprendizaje, no su aplicación final. Los estudiantes investigan, colaboran y construyen conocimiento activamente para resolverlo. El docente actúa como tutor o facilitador.',
                'fuente_normativa': 'Barrows - ABP / MEN Colombia',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'alta',
                'enunciado': 'Una docente de ciencias sociales de grado 9° presenta a sus estudiantes la siguiente situación: "En su municipio hay un conflicto entre una empresa minera y la comunidad indígena. ¿Qué harían ustedes como líderes comunitarios?" Los estudiantes investigan, debaten y presentan propuestas. Esta estrategia corresponde a:',
                'opcion_a': 'Aprendizaje memorístico, porque los estudiantes deben recordar información sobre minería.',
                'opcion_b': 'Aprendizaje Basado en Problemas con enfoque de pedagogía crítica y contextualización colombiana.',
                'opcion_c': 'Evaluación sumativa, porque los estudiantes presentan un producto final.',
                'opcion_d': 'Enseñanza directa, porque el docente define claramente el problema a resolver.',
                'respuesta_correcta': 'B',
                'justificacion': 'La situación combina ABP (problema real como detonador) con pedagogía crítica (cuestionamiento del poder, defensa de derechos). El contexto colombiano de minería y comunidades indígenas ancla el aprendizaje en la realidad social del estudiante.',
                'fuente_normativa': 'ABP - Freire - Pedagogía crítica - Ley 115 Art. 5',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'media',
                'enunciado': 'El modelo de Aula Invertida (Flipped Classroom) propone que:',
                'opcion_a': 'Los estudiantes estudian los contenidos teóricos en casa y el tiempo de clase se usa para actividades prácticas, resolución de dudas y trabajo colaborativo.',
                'opcion_b': 'Los estudiantes realizan las tareas en clase y el docente explica la teoría en casa mediante videos.',
                'opcion_c': 'El docente invierte los roles con los estudiantes para que ellos enseñen el contenido.',
                'opcion_d': 'Se invierte el orden del currículo comenzando por los temas más difíciles.',
                'respuesta_correcta': 'A',
                'justificacion': 'En el aula invertida la instrucción directa se traslada fuera del aula (videos, lecturas en casa) y el tiempo presencial se dedica a actividades de mayor nivel cognitivo: discusión, aplicación, resolución de problemas.',
                'fuente_normativa': 'Bergmann y Sams - Flipped Classroom',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'alta',
                'enunciado': 'Un docente de matemáticas implementa aula invertida. Les asigna videos sobre ecuaciones para ver en casa y en clase trabajan en grupos resolviendo problemas reales. Desde la Guía 31, esta práctica evidencia la competencia:',
                'opcion_a': 'Uso de recursos, porque el docente usa videos digitales.',
                'opcion_b': 'Pedagógica y didáctica, porque usa estrategias variadas ajustadas a las necesidades del grupo y optimiza el tiempo presencial.',
                'opcion_c': 'Comunicación institucional, porque comparte materiales con la comunidad.',
                'opcion_d': 'Seguimiento de procesos administrativos.',
                'respuesta_correcta': 'B',
                'justificacion': 'La Guía 31 del MEN describe la competencia pedagógica como la capacidad de usar variadas estrategias de enseñanza ajustadas a las características del grupo. El aula invertida es exactamente eso: una estrategia diferenciada que optimiza el aprendizaje activo.',
                'fuente_normativa': 'Guía 31 MEN - Decreto 1278 de 2002',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'media',
                'enunciado': 'El aprendizaje colaborativo se diferencia del trabajo en grupo tradicional porque:',
                'opcion_a': 'En el colaborativo los estudiantes trabajan individualmente y al final comparten resultados.',
                'opcion_b': 'En el colaborativo existe interdependencia positiva: cada miembro necesita de los demás para alcanzar el objetivo común.',
                'opcion_c': 'En el colaborativo el docente asigna roles fijos que no pueden cambiar durante el proceso.',
                'opcion_d': 'En el colaborativo solo participan los estudiantes con mejor desempeño académico.',
                'respuesta_correcta': 'B',
                'justificacion': 'Johnson y Johnson identifican la interdependencia positiva como el elemento central del aprendizaje colaborativo. El éxito individual está ligado al éxito del grupo. Esto lo diferencia del trabajo grupal donde cada quien hace su parte de forma independiente.',
                'fuente_normativa': 'Johnson y Johnson - Aprendizaje Colaborativo',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'alta',
                'enunciado': 'En una institución educativa de Medellín, el docente forma grupos heterogéneos de 4 estudiantes. Cada uno tiene un rol: líder, relator, verificador y presentador. Trabajan juntos para resolver un problema de estadística. Al finalizar, cada estudiante expone una parte diferente. Esta estrategia evidencia:',
                'opcion_a': 'Aprendizaje por descubrimiento individual de Bruner.',
                'opcion_b': 'Aprendizaje colaborativo con roles definidos e interdependencia positiva.',
                'opcion_c': 'Enseñanza directa con distribución de tareas.',
                'opcion_d': 'Evaluación diagnóstica mediante observación grupal.',
                'respuesta_correcta': 'B',
                'justificacion': 'Los grupos heterogéneos, los roles complementarios y la presentación compartida son características del aprendizaje colaborativo estructurado. La heterogeneidad del grupo activa la ZDP vygotskiana entre pares.',
                'fuente_normativa': 'Aprendizaje colaborativo - Vygotsky ZDP',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'media',
                'enunciado': 'La gamificación en el aula se define como:',
                'opcion_a': 'Reemplazar las clases por videojuegos comerciales.',
                'opcion_b': 'Aplicar mecánicas y dinámicas propias de los juegos (puntos, niveles, retos, recompensas) en contextos educativos para aumentar motivación y compromiso.',
                'opcion_c': 'Evaluar a los estudiantes mediante juegos de azar para eliminar el sesgo del docente.',
                'opcion_d': 'Usar juegos de mesa únicamente en educación preescolar y primaria.',
                'respuesta_correcta': 'B',
                'justificacion': 'La gamificación no convierte la clase en un juego, sino que toma elementos del diseño de juegos (retos progresivos, retroalimentación inmediata, sentido de logro) para aumentar la motivación intrínseca y el compromiso del estudiante.',
                'fuente_normativa': 'Kapp - Gamificación educativa / MEN TIC',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'alta',
                'enunciado': 'El Aprendizaje Basado en Proyectos (ABPr) se diferencia del ABP (Basado en Problemas) principalmente en que:',
                'opcion_a': 'El ABPr no requiere trabajo colaborativo mientras que el ABP sí.',
                'opcion_b': 'En el ABPr el producto final es un proyecto tangible y público; en el ABP el foco es el proceso de resolución del problema.',
                'opcion_c': 'El ABP es exclusivo para ciencias exactas y el ABPr para ciencias sociales.',
                'opcion_d': 'En el ABPr el docente define la solución y los estudiantes la ejecutan.',
                'respuesta_correcta': 'B',
                'justificacion': 'Aunque comparten principios constructivistas, en el ABPr los estudiantes desarrollan un producto final concreto (maqueta, campaña, app, propuesta) que se presenta a una audiencia real. En el ABP el énfasis está en el proceso de razonamiento para resolver el problema.',
                'fuente_normativa': 'Buck Institute - ABPr / Barrows - ABP',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'media',
                'enunciado': 'Una estrategia de pensamiento visible como la rutina "Ver-Pensar-Preguntarse" busca principalmente:',
                'opcion_a': 'Evaluar la capacidad visual de los estudiantes ante imágenes.',
                'opcion_b': 'Hacer explícito el pensamiento del estudiante para que el docente y los pares puedan comprenderlo y enriquecerlo.',
                'opcion_c': 'Reducir el tiempo de clase dedicado a explicaciones teóricas.',
                'opcion_d': 'Clasificar a los estudiantes según su estilo de aprendizaje visual.',
                'respuesta_correcta': 'B',
                'justificacion': 'Las rutinas de pensamiento visible (Project Zero - Harvard) tienen como objetivo externalizar el pensamiento para hacerlo observable, discutible y enriquecible. Ver-Pensar-Preguntarse activa la observación, la inferencia y la curiosidad.',
                'fuente_normativa': 'Project Zero - Harvard - Pensamiento Visible',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'alta',
                'enunciado': 'Desde el Decreto 1278 de 2002, un docente que implementa estrategias didácticas activas como ABP y aprendizaje colaborativo demuestra que sus funciones van más allá del aula porque:',
                'opcion_a': 'Sale del aula frecuentemente para gestionar recursos.',
                'opcion_b': 'Contribuye al desarrollo del PEI mediante innovación pedagógica y aporta a la comunidad de práctica docente de la institución.',
                'opcion_c': 'Reduce la carga académica de los estudiantes con actividades lúdicas.',
                'opcion_d': 'Cumple con el mínimo de horas exigidas en el contrato laboral.',
                'respuesta_correcta': 'B',
                'justificacion': 'El Art. 4 del Decreto 1278 establece que las funciones del docente incluyen actividades curriculares no lectivas, el servicio de orientación a estudiantes, la atención a la comunidad y la participación en actividades de actualización. La innovación pedagógica contribuye al PEI.',
                'fuente_normativa': 'Decreto 1278 de 2002 - Art. 4',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'media',
                'enunciado': 'El aprendizaje por indagación (Inquiry-Based Learning) es especialmente relevante en la enseñanza de ciencias porque:',
                'opcion_a': 'Permite que el docente controle totalmente el proceso experimental.',
                'opcion_b': 'Desarrolla el pensamiento científico: observar, preguntar, hipotetizar, experimentar y concluir.',
                'opcion_c': 'Elimina la necesidad de conocimientos teóricos previos.',
                'opcion_d': 'Es la única estrategia válida para educación básica primaria.',
                'respuesta_correcta': 'B',
                'justificacion': 'La indagación científica desarrolla las mismas habilidades que usa un científico: formulación de preguntas, planteamiento de hipótesis, diseño experimental, análisis de datos y comunicación de conclusiones. Esto es coherente con las competencias científicas del MEN.',
                'fuente_normativa': 'MEN - Estándares Básicos de Competencias en Ciencias',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'alta',
                'enunciado': 'Una docente de lenguaje implementa el debate socrático como estrategia didáctica. Los estudiantes leen un texto, formulan preguntas abiertas y debaten en círculo. El rol de la docente es hacer preguntas que profundicen el pensamiento. Esta estrategia desarrolla principalmente:',
                'opcion_a': 'Habilidades de memorización del texto leído.',
                'opcion_b': 'Pensamiento crítico, argumentación y escucha activa en el marco de la competencia comunicativa.',
                'opcion_c': 'Competencias matemáticas mediante el uso de la lógica formal.',
                'opcion_d': 'Habilidades sociales para el trabajo en equipo.',
                'respuesta_correcta': 'B',
                'justificacion': 'El método socrático desarrolla el pensamiento crítico a través de preguntas que cuestionan supuestos. En lenguaje, fortalece la argumentación, la escucha activa y el pensamiento inferencial, componentes centrales de la competencia comunicativa según los EBC del MEN.',
                'fuente_normativa': 'MEN - EBC Lenguaje / Método Socrático',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'media',
                'enunciado': 'El aprendizaje situado plantea que el conocimiento se aprende mejor cuando:',
                'opcion_a': 'Se presenta en un ambiente completamente controlado y libre de distracciones.',
                'opcion_b': 'Está contextualizado en situaciones reales y auténticas similares a las que el estudiante enfrentará en su vida.',
                'opcion_c': 'Se enseña de forma abstracta para que el estudiante pueda generalizarlo.',
                'opcion_d': 'Se repite suficientes veces hasta que quede automatizado.',
                'respuesta_correcta': 'B',
                'justificacion': 'El aprendizaje situado (Lave y Wenger) sostiene que el conocimiento es inseparable del contexto donde se aprende y usa. La cognición situada propone actividades auténticas que repliquen prácticas reales, lo que aumenta la transferencia del aprendizaje.',
                'fuente_normativa': 'Lave y Wenger - Aprendizaje Situado',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'alta',
                'enunciado': 'En una institución de Cali, el docente de tecnología implementa un proyecto donde los estudiantes diseñan una app para reportar problemas del barrio. Trabajan en equipos, investigan, prototipan y presentan a la comunidad. ¿Qué estrategias didácticas integra esta práctica?',
                'opcion_a': 'Solo aprendizaje memorístico de programación.',
                'opcion_b': 'ABPr + aprendizaje colaborativo + aprendizaje situado + competencias ciudadanas.',
                'opcion_c': 'Enseñanza directa con apoyo tecnológico.',
                'opcion_d': 'Evaluación diagnóstica con componente digital.',
                'respuesta_correcta': 'B',
                'justificacion': 'La situación integra: ABPr (producto tangible: app), colaborativo (equipos), situado (problema real del barrio), y competencias ciudadanas (participación comunitaria). Esta integración es el ideal del docente competente según el MEN.',
                'fuente_normativa': 'MEN - Competencias TIC / ABPr / Decreto 1075',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'media',
                'enunciado': 'La diferencia entre estrategia didáctica, técnica didáctica y actividad didáctica es:',
                'opcion_a': 'Son sinónimos que se usan indistintamente en pedagogía.',
                'opcion_b': 'La estrategia es el plan global (ABP, aula invertida); la técnica es el procedimiento específico (debate, mapa conceptual); la actividad es la tarea concreta del estudiante.',
                'opcion_c': 'La actividad es el plan global y la estrategia es la tarea específica.',
                'opcion_d': 'La técnica incluye a la estrategia y la actividad como subcategorías.',
                'respuesta_correcta': 'B',
                'justificacion': 'Existe una jerarquía: la estrategia es el enfoque amplio (ABP), dentro de ella se usan técnicas (lluvia de ideas, debate) y cada técnica se implementa mediante actividades concretas (responder preguntas, elaborar un mapa). Confundirlas es un error frecuente en el concurso.',
                'fuente_normativa': 'Didáctica general - Díaz Barriga',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'alta',
                'enunciado': 'Desde la perspectiva del DUA (Diseño Universal para el Aprendizaje), las estrategias didácticas activas como ABP y aprendizaje colaborativo favorecen la inclusión porque:',
                'opcion_a': 'Reducen la cantidad de contenido para estudiantes con dificultades.',
                'opcion_b': 'Ofrecen múltiples medios de representación, expresión y motivación, permitiendo que cada estudiante acceda al aprendizaje según sus características.',
                'opcion_c': 'Son exclusivas para estudiantes con discapacidad cognitiva.',
                'opcion_d': 'Eliminan la evaluación para no discriminar.',
                'respuesta_correcta': 'B',
                'justificacion': 'El DUA (Decreto 1421/2017) propone que el currículo sea flexible desde su diseño. Las estrategias activas naturalmente ofrecen múltiples formas de participar (oral, escrito, gráfico, kinestésico), lo que facilita el acceso de todos los estudiantes.',
                'fuente_normativa': 'Decreto 1421 de 2017 - DUA',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'media',
                'enunciado': 'El aprendizaje cooperativo estructurado de Kagan propone estructuras como "Numerados" o "Lápices al centro". El valor pedagógico de estas estructuras radica en:',
                'opcion_a': 'Asegurarse de que todos los estudiantes respondan en silencio.',
                'opcion_b': 'Garantizar la participación equitativa e interdependencia positiva mediante procedimientos claros.',
                'opcion_c': 'Evaluar individualmente sin que los compañeros influyan.',
                'opcion_d': 'Reducir el tiempo de clase evitando debates.',
                'respuesta_correcta': 'B',
                'justificacion': 'Las estructuras de Kagan garantizan participación simultánea e igualitaria. "Lápices al centro" asegura que todos contribuyen antes de escribir. "Numerados" responsabiliza a cualquier miembro de responder. Esto previene el fenómeno del "polizón" en grupos.',
                'fuente_normativa': 'Kagan - Aprendizaje Cooperativo Estructurado',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'alta',
                'enunciado': 'En el concurso docente CNSC, la competencia "Enseñar" evalúa si el docente puede diseñar e implementar estrategias de enseñanza. Un docente que solo usa exposición magistral demuestra:',
                'opcion_a': 'Dominio total de la disciplina y por tanto competencia pedagógica alta.',
                'opcion_b': 'Limitación en su competencia pedagógica al no diversificar estrategias según características del grupo.',
                'opcion_c': 'Eficiencia didáctica porque optimiza el tiempo de clase.',
                'opcion_d': 'Cumplimiento del Decreto 1278 que exige transmisión de conocimientos.',
                'respuesta_correcta': 'B',
                'justificacion': 'La Guía 31 y los simulacros del concurso valoran que el docente use estrategias variadas y las ajuste según características, necesidades y ritmos de aprendizaje. La clase magistral exclusiva no evidencia adaptabilidad pedagógica.',
                'fuente_normativa': 'Guía 31 MEN - Competencia Pedagógica y Didáctica',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'media',
                'enunciado': 'El aprendizaje por estaciones (learning stations) es especialmente útil para:',
                'opcion_a': 'Que todos los estudiantes hagan exactamente la misma actividad al mismo tiempo.',
                'opcion_b': 'Atender distintos ritmos y estilos de aprendizaje permitiendo que grupos rotan por diferentes tareas simultáneas.',
                'opcion_c': 'Eliminar la evaluación formativa del proceso.',
                'opcion_d': 'Reducir la interacción entre estudiantes para evitar distracciones.',
                'respuesta_correcta': 'B',
                'justificacion': 'Las estaciones de aprendizaje permiten diferenciación: mientras un grupo trabaja con material concreto, otro lee, otro usa tecnología. Favorece la atención a la diversidad y el trabajo autónomo, coherente con el DUA del Decreto 1421/2017.',
                'fuente_normativa': 'Aprendizaje diferenciado - Decreto 1421/2017 DUA',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'alta',
                'enunciado': 'Una docente de primaria usa la técnica "Jigsaw" (rompecabezas): divide el tema en 4 partes, forma grupos de expertos donde cada uno profundiza su parte y luego se reintegran para enseñarse mutuamente. Esta técnica desarrolla:',
                'opcion_a': 'Solo habilidades de memorización individual.',
                'opcion_b': 'Interdependencia positiva, responsabilidad individual y habilidades de comunicación pedagógica entre pares.',
                'opcion_c': 'Competencias exclusivamente disciplinares sin componente colaborativo.',
                'opcion_d': 'Evaluación sumativa del contenido dividido.',
                'respuesta_correcta': 'B',
                'justificacion': 'El Jigsaw (Aronson) genera interdependencia positiva porque cada estudiante posee información que los demás necesitan. Desarrolla responsabilidad individual (debe aprender bien su parte para enseñarla) y habilidades comunicativas al explicar a sus pares.',
                'fuente_normativa': 'Aronson - Técnica Jigsaw / Aprendizaje Cooperativo',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'media',
                'enunciado': 'El uso pedagógico de las TIC en el aula, según el MEN colombiano, se clasifica en tres niveles. El nivel más alto es:',
                'opcion_a': 'Uso de TIC para presentar información (proyector, diapositivas).',
                'opcion_b': 'Uso de TIC para practicar (ejercicios digitales, quizzes).',
                'opcion_c': 'Transformación: las TIC permiten hacer cosas que antes eran imposibles (crear, colaborar globalmente, producir contenido).',
                'opcion_d': 'Uso de TIC para guardar documentos en la nube.',
                'respuesta_correcta': 'C',
                'justificacion': 'El modelo SAMR (Puentedura) clasifica el uso de TIC en: Sustitución, Aumento, Modificación y Redefinición. La Redefinición (transformación) es el nivel más alto: las TIC permiten crear tareas cognitivas nuevas imposibles sin tecnología.',
                'fuente_normativa': 'MEN - Competencias TIC para el Desarrollo Profesional Docente / SAMR',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'alta',
                'enunciado': 'Según el simulacro de competencias pedagógicas del concurso, un docente que implementa ABP y logra que sus estudiantes "relacionen la teoría con la vida cotidiana" demuestra la competencia funcional de:',
                'opcion_a': 'Seguimiento de procesos administrativos.',
                'opcion_b': 'Pedagógica y didáctica, específicamente en fundamentación teórica de la práctica y contextualización.',
                'opcion_c': 'Comunicación institucional con padres de familia.',
                'opcion_d': 'Uso de recursos tecnológicos en el aula.',
                'respuesta_correcta': 'B',
                'justificacion': 'La Guía 31 define la competencia pedagógica y didáctica como la capacidad para "fundamentar teóricamente sus prácticas pedagógicas y relacionar la teoría con la vida cotidiana". El ABP contextualizado en situaciones reales es la estrategia que mejor evidencia esta competencia.',
                'fuente_normativa': 'Guía 31 MEN - Decreto 1278 de 2002',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'media',
                'enunciado': 'La metacognición como estrategia didáctica consiste en:',
                'opcion_a': 'Enseñar a los estudiantes a pensar sobre su propio proceso de aprendizaje para regularlo.',
                'opcion_b': 'Usar la memorización como estrategia principal de estudio.',
                'opcion_c': 'Evaluar exclusivamente los resultados académicos finales.',
                'opcion_d': 'Eliminar la autorregulación para que el docente controle el proceso.',
                'respuesta_correcta': 'A',
                'justificacion': 'La metacognición (Flavell) es el conocimiento y regulación que el individuo tiene sobre sus propios procesos cognitivos. Enseñar estrategias metacognitivas desarrolla estudiantes autónomos que saben cómo aprenden, identifican dificultades y las corrigen.',
                'fuente_normativa': 'Flavell - Metacognición / Aprendizaje autónomo',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'alta',
                'enunciado': 'En el contexto colombiano, la aplicación del ABP en una escuela rural multigrado requiere adaptaciones porque:',
                'opcion_a': 'El ABP no aplica en contextos rurales por falta de tecnología.',
                'opcion_b': 'La diversidad de edades y grados se convierte en una fortaleza: los mayores tutoran a los menores mientras todos trabajan el mismo problema con diferentes niveles de profundidad.',
                'opcion_c': 'En multigrado solo se puede usar enseñanza directa por limitaciones de tiempo.',
                'opcion_d': 'El ABP requiere laboratorios y recursos que las escuelas rurales no tienen.',
                'respuesta_correcta': 'B',
                'justificacion': 'La escuela multigrado colombiana puede usar el ABP con ajustes: el mismo problema se aborda con profundidades distintas por grado. La mezcla de edades activa la ZDP vygotskiana naturalmente. El MEN ha promovido modelos flexibles como Escuela Nueva que integran estos principios.',
                'fuente_normativa': 'MEN - Modelo Escuela Nueva / Decreto 1075 de 2015',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'media',
                'enunciado': 'La evaluación formativa integrada en las estrategias activas (como el ABP) se diferencia de la evaluación sumativa porque:',
                'opcion_a': 'La formativa solo se aplica al inicio del año escolar.',
                'opcion_b': 'La formativa ocurre durante el proceso para retroalimentar y ajustar; la sumativa valora el resultado final.',
                'opcion_c': 'La sumativa es más justa porque usa instrumentos estandarizados.',
                'opcion_d': 'La formativa no genera calificaciones mientras que la sumativa sí.',
                'respuesta_correcta': 'B',
                'justificacion': 'Según el Decreto 1290 de 2009, la evaluación formativa es continua y busca identificar avances y dificultades para retroalimentar oportunamente. La sumativa valora el nivel de logro al final de un período. En el ABP la evaluación formativa es permanente durante el proceso.',
                'fuente_normativa': 'Decreto 1290 de 2009 - Evaluación del Aprendizaje',
            },
        ]

    def _preguntas_sesion4(self):
        return [
            {
                'componente': 'pedagogico', 'dificultad': 'media',
                'enunciado': 'El Decreto 1290 de 2009 establece que la evaluación del aprendizaje de los estudiantes en Colombia debe ser:',
                'opcion_a': 'Exclusivamente cuantitativa para garantizar objetividad.',
                'opcion_b': 'Continua, integral, sistemática, flexible, interpretativa y participativa.',
                'opcion_c': 'Anual y sumativa para cumplir con los períodos académicos.',
                'opcion_d': 'Estandarizada a nivel nacional con los mismos instrumentos para todas las instituciones.',
                'respuesta_correcta': 'B',
                'justificacion': 'El Art. 3 del Decreto 1290/2009 establece que la evaluación debe ser continua (permanente), integral (dimensiones del ser humano), sistemática (con criterios claros), flexible (reconoce ritmos), interpretativa (comprende los procesos) y participativa (involucra al estudiante).',
                'fuente_normativa': 'Decreto 1290 de 2009 - Art. 3',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'media',
                'enunciado': 'La evaluación diagnóstica se aplica principalmente:',
                'opcion_a': 'Al final del año para determinar si el estudiante puede pasar al siguiente grado.',
                'opcion_b': 'Al inicio de un proceso para identificar saberes previos, fortalezas y necesidades de los estudiantes.',
                'opcion_c': 'Durante el proceso para retroalimentar y ajustar la enseñanza.',
                'opcion_d': 'Solo cuando el estudiante presenta dificultades de aprendizaje graves.',
                'respuesta_correcta': 'B',
                'justificacion': 'La evaluación diagnóstica tiene carácter predictivo: se aplica antes de iniciar un proceso para conocer el punto de partida. Permite al docente planear con base en la realidad del grupo, identificar necesidades especiales y diseñar estrategias diferenciadas.',
                'fuente_normativa': 'Decreto 1290/2009 - Tipos de evaluación',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'alta',
                'enunciado': 'Un docente aplica una evaluación al inicio de la unidad sobre la Revolución Industrial y descubre que el 70% de los estudiantes confunde "industrialización" con "urbanización". ¿Cuál es la acción más coherente con la evaluación diagnóstica formativa?',
                'opcion_a': 'Continuar con la planeación original porque los errores se corrigen durante el proceso.',
                'opcion_b': 'Ajustar la planeación para dedicar tiempo específico a aclarar esa confusión conceptual antes de avanzar.',
                'opcion_c': 'Reportar a los padres que los estudiantes tienen bajo nivel de conocimientos previos.',
                'opcion_d': 'Asignar una tarea individual para que cada estudiante corrija sus errores en casa.',
                'respuesta_correcta': 'B',
                'justificacion': 'El propósito de la evaluación diagnóstica es informar la planeación. Si el 70% tiene un error conceptual, ignorarlo y continuar con la planeación original sería un error pedagógico grave. El docente competente ajusta su intervención según los hallazgos.',
                'fuente_normativa': 'Decreto 1290/2009 - Evaluación formativa',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'media',
                'enunciado': 'La evaluación formativa se distingue de la sumativa principalmente porque:',
                'opcion_a': 'La formativa no genera calificaciones y la sumativa sí.',
                'opcion_b': 'La formativa ocurre durante el proceso para retroalimentar y mejorar; la sumativa valora el nivel de logro al finalizar.',
                'opcion_c': 'La formativa la aplica el docente y la sumativa la aplica el MEN.',
                'opcion_d': 'La formativa es oral y la sumativa es escrita.',
                'respuesta_correcta': 'B',
                'justificacion': 'Scriven y Black & Wiliam establecen que la evaluación formativa tiene propósito regulador: orienta el proceso mientras ocurre. La sumativa tiene propósito certificador: valora el resultado final. Ambas pueden generar calificaciones.',
                'fuente_normativa': 'Decreto 1290/2009 - Black y Wiliam - Evaluación para el aprendizaje',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'alta',
                'enunciado': 'Según el Simulacro de Competencias Pedagógicas del concurso, un docente que ante el bajo desempeño de sus estudiantes "realiza una sesión de retroalimentación donde analiza errores comunes y ajusta su estrategia de enseñanza" aplica:',
                'opcion_a': 'Evaluación sumativa con oportunidad de mejora.',
                'opcion_b': 'Evaluación formativa con uso pedagógico de los resultados para transformar la práctica.',
                'opcion_c': 'Evaluación diagnóstica posterior al proceso.',
                'opcion_d': 'Heteroevaluación con criterios externos.',
                'respuesta_correcta': 'B',
                'justificacion': 'Este es exactamente el escenario del Simulacro de Enseñar y Evaluar del concurso. La evaluación formativa no solo retroalimenta al estudiante sino que obliga al docente a reflexionar sobre su propia práctica y ajustar sus estrategias.',
                'fuente_normativa': 'Decreto 1290/2009 - Simulacro CNSC Competencias Pedagógicas',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'media',
                'enunciado': 'Una rúbrica de evaluación es:',
                'opcion_a': 'Una lista de chequeo con respuestas de sí o no.',
                'opcion_b': 'Un instrumento que describe niveles de desempeño en criterios específicos con indicadores cualitativos y/o cuantitativos.',
                'opcion_c': 'Una prueba escrita con respuesta única.',
                'opcion_d': 'Un registro anecdótico de las observaciones del docente.',
                'respuesta_correcta': 'B',
                'justificacion': 'La rúbrica (Mertler) describe explícitamente qué se espera en cada nivel de desempeño para cada criterio. Tiene dos formatos: holística (valoración global) y analítica (criterio por criterio). Favorece la transparencia y la autoevaluación.',
                'fuente_normativa': 'Mertler - Rúbricas / Decreto 1290/2009',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'alta',
                'enunciado': 'El Sistema Institucional de Evaluación de Estudiantes (SIEE) que establece el Decreto 1290 de 2009 debe ser construido por:',
                'opcion_a': 'El Ministerio de Educación Nacional para todas las instituciones del país.',
                'opcion_b': 'Cada institución educativa con participación de la comunidad educativa, respetando los lineamientos del MEN.',
                'opcion_c': 'El rector de la institución sin consultar a docentes ni padres.',
                'opcion_d': 'La Secretaría de Educación del municipio o departamento.',
                'respuesta_correcta': 'B',
                'justificacion': 'El Art. 4 del Decreto 1290/2009 establece que cada establecimiento educativo debe definir su SIEE con participación de la comunidad educativa (docentes, padres, estudiantes). Esto garantiza la autonomía institucional mientras respeta los mínimos nacionales.',
                'fuente_normativa': 'Decreto 1290 de 2009 - Art. 4',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'media',
                'enunciado': 'La autoevaluación como instrumento de evaluación favorece principalmente:',
                'opcion_a': 'La reducción de la carga de trabajo del docente.',
                'opcion_b': 'La autorregulación del aprendizaje y el desarrollo de la metacognición del estudiante.',
                'opcion_c': 'La eliminación de la subjetividad en los procesos de calificación.',
                'opcion_d': 'La comparación objetiva entre estudiantes del mismo grupo.',
                'respuesta_correcta': 'B',
                'justificacion': 'La autoevaluación desarrolla metacognición: el estudiante reflexiona sobre su proceso, identifica fortalezas y debilidades, y autorregula su aprendizaje. El Decreto 1290 la incluye como parte del proceso evaluativo.',
                'fuente_normativa': 'Decreto 1290/2009 - Autoevaluación / Metacognición',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'alta',
                'enunciado': 'En el marco del Decreto 1290, cuando un estudiante o su acudiente no está de acuerdo con una calificación, el proceso correcto es:',
                'opcion_a': 'Aceptar la calificación del docente sin posibilidad de revisión.',
                'opcion_b': 'Seguir el proceso de reclamación establecido en el SIEE de la institución, que debe garantizar el debido proceso.',
                'opcion_c': 'Acudir directamente al MEN para que modifique la nota.',
                'opcion_d': 'Solicitar al rector que cambie la calificación por decisión directiva.',
                'respuesta_correcta': 'B',
                'justificacion': 'El Art. 10 del Decreto 1290/2009 establece el derecho de los estudiantes a recibir oportuna retroalimentación y el Art. 11 los derechos de los padres. El SIEE debe contemplar instancias y procedimientos de reclamación garantizando el debido proceso.',
                'fuente_normativa': 'Decreto 1290 de 2009 - Art. 10 y 11',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'media',
                'enunciado': 'La coevaluación es el proceso donde:',
                'opcion_a': 'El docente evalúa al estudiante usando múltiples criterios.',
                'opcion_b': 'Los estudiantes se evalúan entre sí usando criterios establecidos previamente.',
                'opcion_c': 'El coordinador evalúa al docente en su desempeño de aula.',
                'opcion_d': 'El estudiante se autoevalúa sin intervención del docente.',
                'respuesta_correcta': 'B',
                'justificacion': 'La coevaluación (evaluación entre pares) desarrolla pensamiento crítico, capacidad de dar y recibir retroalimentación constructiva. Requiere criterios claros previamente establecidos para ser efectiva y justa.',
                'fuente_normativa': 'Decreto 1290/2009 - Tipos de evaluación',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'alta',
                'enunciado': 'Una docente diseña una rúbrica analítica para evaluar un ensayo con tres criterios: argumentación, coherencia y uso de fuentes. Para cada criterio define cuatro niveles: Sobresaliente, Alto, Básico e Inferior. Esta rúbrica favorece la evaluación porque:',
                'opcion_a': 'Elimina la subjetividad del docente al definir niveles numéricos únicos.',
                'opcion_b': 'Hace transparente qué se espera en cada nivel, permite retroalimentación específica y facilita la autoevaluación del estudiante.',
                'opcion_c': 'Reduce el tiempo de calificación al tener respuestas predefinidas.',
                'opcion_d': 'Garantiza que todos los estudiantes obtengan la misma nota final.',
                'respuesta_correcta': 'B',
                'justificacion': 'La rúbrica analítica desglosa el desempeño por criterio, permitiendo retroalimentación precisa ("tu argumentación es básica porque..."). La transparencia previa permite que el estudiante se autoevalúe antes de entregar, desarrollando metacognición.',
                'fuente_normativa': 'Rúbricas analíticas - Decreto 1290/2009',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'media',
                'enunciado': 'Las pruebas Saber (ICFES) son un ejemplo de evaluación:',
                'opcion_a': 'Diagnóstica institucional.',
                'opcion_b': 'Formativa y continua.',
                'opcion_c': 'Externa, estandarizada y de carácter sumativo-certificador.',
                'opcion_d': 'Autoevaluación del sistema educativo.',
                'respuesta_correcta': 'C',
                'justificacion': 'Las pruebas Saber son externas (las aplica el ICFES, no el docente), estandarizadas (mismos ítems para todos) y sumativas-certificadoras (determinan grado de avance y acceso a la educación superior). Se diferencian de la evaluación formativa interna del aula.',
                'fuente_normativa': 'ICFES - Decreto 1290/2009 - Evaluación externa',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'alta',
                'enunciado': 'Desde el enfoque de la evaluación auténtica, la diferencia con la evaluación tradicional radica en:',
                'opcion_a': 'La evaluación auténtica usa solo pruebas orales.',
                'opcion_b': 'La evaluación auténtica propone tareas complejas y contextualizadas que replican desafíos del mundo real, en lugar de medir la reproducción de información.',
                'opcion_c': 'La evaluación auténtica elimina los criterios de evaluación para ser más flexible.',
                'opcion_d': 'La evaluación auténtica solo se aplica en educación superior.',
                'respuesta_correcta': 'B',
                'justificacion': 'La evaluación auténtica (Wiggins) propone tareas que tienen valor intrínseco más allá del aula: diseñar un proyecto, resolver un problema real, crear un producto. Contrasta con las pruebas que solo miden la capacidad de recordar información descontextualizada.',
                'fuente_normativa': 'Wiggins - Evaluación Auténtica / MEN Competencias',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'media',
                'enunciado': 'Según el Decreto 1290 de 2009, la escala nacional de valoración del desempeño académico en Colombia es:',
                'opcion_a': 'Excelente, Bueno, Regular, Deficiente.',
                'opcion_b': 'Desempeño Superior, Alto, Básico e Inferior.',
                'opcion_c': 'A, B, C, D, F.',
                'opcion_d': '5.0, 4.0, 3.0, 2.0, 1.0.',
                'respuesta_correcta': 'B',
                'justificacion': 'El Art. 5 del Decreto 1290/2009 establece la escala de valoración nacional: Desempeño Superior, Alto, Básico e Inferior. Sin embargo, cada institución puede adoptar su propia escala siempre que la incluya en el SIEE y la articule con la nacional.',
                'fuente_normativa': 'Decreto 1290 de 2009 - Art. 5',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'alta',
                'enunciado': 'Un docente observa que varios estudiantes obtienen "desempeño básico" repetidamente. Según el Decreto 1290 y la evaluación formativa, la acción más adecuada es:',
                'opcion_a': 'Asignar más tareas del mismo tipo para que practiquen.',
                'opcion_b': 'Identificar las causas del bajo desempeño, diseñar actividades de apoyo diferenciadas y hacer seguimiento individual.',
                'opcion_c': 'Remitir inmediatamente a los padres para que busquen apoyo externo.',
                'opcion_d': 'Bajar el nivel de exigencia para que todos alcancen el básico.',
                'respuesta_correcta': 'B',
                'justificacion': 'El Decreto 1290 establece en su Art. 11 el derecho del estudiante a recibir apoyo pedagógico. El docente debe identificar causas (¿es conceptual, procedimental, actitudinal, socioemocional?) y diseñar estrategias diferenciadas de apoyo, no simplemente repetir lo mismo.',
                'fuente_normativa': 'Decreto 1290/2009 - Art. 11 - Apoyo pedagógico',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'media',
                'enunciado': 'La lista de chequeo como instrumento de evaluación es más adecuada para:',
                'opcion_a': 'Evaluar la profundidad del pensamiento crítico en un ensayo.',
                'opcion_b': 'Verificar la presencia o ausencia de elementos específicos en un producto o proceso.',
                'opcion_c': 'Describir los niveles de calidad en la argumentación oral.',
                'opcion_d': 'Evaluar actitudes y valores de forma holística.',
                'respuesta_correcta': 'B',
                'justificacion': 'La lista de chequeo registra si un elemento está presente (✓) o ausente (✗). Es ideal para evaluar procedimientos, protocolos o requisitos mínimos. No sirve para capturar matices cualitativos del desempeño, para lo cual se usa la rúbrica.',
                'fuente_normativa': 'Instrumentos de evaluación - Decreto 1290/2009',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'alta',
                'enunciado': 'En el contexto colombiano, la evaluación de los aprendizajes de estudiantes con discapacidad debe:',
                'opcion_a': 'Aplicar los mismos instrumentos y criterios que al resto del grupo sin modificaciones.',
                'opcion_b': 'Realizarse mediante ajustes razonables que permitan evidenciar el aprendizaje según las características del estudiante, en coherencia con el PIAR.',
                'opcion_c': 'Ser realizada exclusivamente por el docente de apoyo, no por el docente de aula.',
                'opcion_d': 'Eximir al estudiante de todas las evaluaciones del período.',
                'respuesta_correcta': 'B',
                'justificacion': 'El Decreto 1421/2017 establece que la evaluación de estudiantes con discapacidad debe incluir ajustes razonables coherentes con el PIAR. Esto no significa reducir exigencia sino adaptar el formato, el tiempo o los medios para que el estudiante pueda demostrar sus aprendizajes.',
                'fuente_normativa': 'Decreto 1421 de 2017 - PIAR - Ajustes razonables',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'media',
                'enunciado': 'El portafolio de aprendizaje como instrumento de evaluación es valioso porque:',
                'opcion_a': 'Reemplaza todas las demás formas de evaluación.',
                'opcion_b': 'Muestra la evolución del aprendizaje a lo largo del tiempo, permite la reflexión del estudiante sobre su proceso y evidencia el progreso real.',
                'opcion_c': 'Facilita la calificación rápida por parte del docente.',
                'opcion_d': 'Es exclusivo para evaluar habilidades artísticas.',
                'respuesta_correcta': 'B',
                'justificacion': 'El portafolio (Barrett) recoge evidencias del aprendizaje a lo largo del tiempo. Su valor radica en la reflexión metacognitiva que el estudiante hace sobre su proceso. Muestra la trayectoria del aprendizaje, no solo un momento puntual.',
                'fuente_normativa': 'Barrett - Portafolios / Evaluación formativa',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'alta',
                'enunciado': 'Desde la perspectiva de la evaluación para el aprendizaje (Assessment for Learning), la retroalimentación efectiva debe:',
                'opcion_a': 'Informar la nota final sin explicar los criterios.',
                'opcion_b': 'Ser específica, oportuna, orientada a la mejora y centrada en la tarea, no en la persona.',
                'opcion_c': 'Comparar al estudiante con sus compañeros para motivarlo.',
                'opcion_d': 'Darse solo al finalizar el período académico.',
                'respuesta_correcta': 'B',
                'justificacion': 'Hattie y Timperley identifican que la retroalimentación más efectiva es la que se enfoca en la tarea (no en el ego), es específica (no "bien hecho" sino "tu argumento principal es sólido pero falta evidencia en el párrafo 3"), oportuna y orientada a acciones concretas de mejora.',
                'fuente_normativa': 'Hattie y Timperley - Retroalimentación efectiva / Decreto 1290',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'media',
                'enunciado': 'La promoción anticipada al grado siguiente que contempla el Decreto 1290 de 2009 aplica para estudiantes que:',
                'opcion_a': 'Tienen bajo rendimiento y necesitan recuperar el grado.',
                'opcion_b': 'Demuestran capacidades excepcionales de aprendizaje y desarrollo que superan los objetivos del grado cursado.',
                'opcion_c': 'Tienen más de dos años de extra-edad.',
                'opcion_d': 'Presentan dificultades de convivencia que afectan su proceso.',
                'respuesta_correcta': 'B',
                'justificacion': 'El Art. 7 del Decreto 1290/2009 establece la promoción anticipada para estudiantes con capacidades o talentos excepcionales. El Consejo Académico puede autorizar el avance a grados superiores cuando el estudiante supera claramente los objetivos del grado actual.',
                'fuente_normativa': 'Decreto 1290 de 2009 - Art. 7',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'alta',
                'enunciado': 'La evaluación de desempeño docente establecida en la Guía 31 del MEN evalúa al docente del Decreto 1278 en competencias funcionales y comportamentales. Las competencias funcionales representan:',
                'opcion_a': 'El 30% de la evaluación total.',
                'opcion_b': 'El 70% de la evaluación total.',
                'opcion_c': 'El 50% de la evaluación total.',
                'opcion_d': 'El 100% porque las comportamentales son opcionales.',
                'respuesta_correcta': 'B',
                'justificacion': 'La Guía 31 establece que las competencias funcionales (dominio curricular, planeación, pedagógica-didáctica, evaluación del aprendizaje, uso de recursos, seguimiento y comunicación) representan el 70% y las comportamentales (liderazgo, trabajo en equipo, etc.) el 30%.',
                'fuente_normativa': 'Guía 31 MEN - Decreto 1278 de 2002',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'media',
                'enunciado': 'El registro anecdótico como instrumento de evaluación consiste en:',
                'opcion_a': 'Un cuestionario estructurado con preguntas de opción múltiple.',
                'opcion_b': 'Descripciones narrativas de situaciones significativas observadas durante el proceso de aprendizaje.',
                'opcion_c': 'Una lista de comportamientos esperados con casillas de verificación.',
                'opcion_d': 'Una rúbrica con niveles de desempeño cuantitativos.',
                'respuesta_correcta': 'B',
                'justificacion': 'El registro anecdótico documenta observaciones concretas de comportamientos o situaciones significativas en su contexto natural. Es especialmente útil para evaluar actitudes, habilidades sociales y procesos que no se capturan con instrumentos escritos.',
                'fuente_normativa': 'Instrumentos de observación - Evaluación cualitativa',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'alta',
                'enunciado': 'Cuando el SIEE de una institución establece que el período académico tiene un valor del 25% sobre la nota final del año, y un estudiante pierde dos períodos, el docente debe:',
                'opcion_a': 'Reprobar automáticamente al estudiante sin oportunidades de mejora.',
                'opcion_b': 'Seguir el proceso establecido en el SIEE que debe contemplar actividades de apoyo, seguimiento y oportunidades de recuperación antes de determinar la reprobación.',
                'opcion_c': 'Pasar al estudiante de grado para no afectar su autoestima.',
                'opcion_d': 'Solicitar al rector que tome la decisión sin consultar el SIEE.',
                'respuesta_correcta': 'B',
                'justificacion': 'El Decreto 1290 garantiza el debido proceso. El SIEE debe contemplar actividades de apoyo y recuperación. La reprobación solo procede después de agotar las instancias de apoyo establecidas institucionalmente, respetando siempre los derechos del estudiante.',
                'fuente_normativa': 'Decreto 1290/2009 - SIEE - Debido proceso',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'media',
                'enunciado': 'La diferencia entre un indicador de logro y un estándar básico de competencia es:',
                'opcion_a': 'Son sinónimos usados indistintamente por el MEN.',
                'opcion_b': 'El estándar define qué debe saber hacer el estudiante al finalizar un ciclo; el indicador de logro evidencia si se está avanzando hacia ese estándar en un momento específico.',
                'opcion_c': 'Los indicadores son nacionales y los estándares son institucionales.',
                'opcion_d': 'Los estándares reemplazaron a los indicadores de logro en 2002.',
                'respuesta_correcta': 'B',
                'justificacion': 'Los EBC (MEN 2006) definen metas de calidad por ciclos (grupos de grados). Los indicadores de logro son evidencias observables que permiten valorar el avance hacia esos estándares en momentos específicos del proceso de aprendizaje.',
                'fuente_normativa': 'MEN - EBC 2006 / Decreto 1290/2009',
            },
        ]

    def _preguntas_sesion5(self):
        return [
            {
                'componente': 'pedagogico', 'dificultad': 'media',
                'enunciado': 'Los Derechos Básicos de Aprendizaje (DBA) son:',
                'opcion_a': 'Pruebas estandarizadas que aplica el ICFES para medir calidad.',
                'opcion_b': 'Aprendizajes estructurantes que deben alcanzar todos los estudiantes en cada grado, expresados como enunciados de desempeño.',
                'opcion_c': 'Documentos que reemplazan definitivamente los Estándares Básicos de Competencias.',
                'opcion_d': 'Lineamientos curriculares que aplican solo para matemáticas y lenguaje.',
                'respuesta_correcta': 'B',
                'justificacion': 'Los DBA (MEN 2016) son aprendizajes estructurantes por grado específico, expresados como desempeños observables. Complementan los EBC sin reemplazarlos. Orientan la planeación de clase y son referente para la evaluación formativa.',
                'fuente_normativa': 'MEN - Derechos Básicos de Aprendizaje v2',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'media',
                'enunciado': 'Los Estándares Básicos de Competencias (EBC) del MEN definen:',
                'opcion_a': 'Las metodologías obligatorias que debe usar el docente en cada clase.',
                'opcion_b': 'Los criterios claros y públicos que permiten juzgar si un estudiante, institución o sistema educativo cumple con unas expectativas de calidad en competencias al finalizar un ciclo.',
                'opcion_c': 'El número de horas mínimas de clase por área y grado.',
                'opcion_d': 'Los libros de texto que debe usar cada institución educativa.',
                'respuesta_correcta': 'B',
                'justificacion': 'Los EBC (MEN 2006) son criterios de calidad que describen lo que los estudiantes deben saber y saber hacer al finalizar cada grupo de grados (1-3, 4-5, 6-7, 8-9, 10-11). Son referentes para la planeación curricular y la evaluación.',
                'fuente_normativa': 'MEN - Estándares Básicos de Competencias 2006',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'alta',
                'enunciado': 'Al planear una clase de grado 5° en matemáticas, el docente toma como referente el DBA que dice: "El estudiante comprende el sistema de numeración decimal y lo usa para resolver problemas en contextos reales". Los objetivos de aprendizaje deben:',
                'opcion_a': 'Ser idénticos al enunciado del DBA sin modificaciones.',
                'opcion_b': 'Ser más específicos que el DBA, describiendo los desempeños concretos observables en esa clase particular.',
                'opcion_c': 'Ignorar el DBA y centrarse exclusivamente en el libro de texto.',
                'opcion_d': 'Ser más amplios que el DBA para abarcar todo el área.',
                'respuesta_correcta': 'B',
                'justificacion': 'El DBA es un referente amplio para el grado. El objetivo de clase debe ser más específico y observable: "Al finalizar la clase, el estudiante resolverá problemas de adición y sustracción con números hasta 10.000 en contextos de compra y venta". Debe ser medible en esa sesión.',
                'fuente_normativa': 'MEN - DBA / Planeación de clase',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'media',
                'enunciado': 'Un objetivo de aprendizaje bien formulado según la taxonomía de Bloom debe:',
                'opcion_a': 'Describir lo que el docente va a enseñar durante la clase.',
                'opcion_b': 'Contener un verbo de acción observable, el contenido específico y el nivel cognitivo esperado.',
                'opcion_c': 'Ser lo suficientemente general para incluir todos los temas del período.',
                'opcion_d': 'Coincidir exactamente con el título del tema del libro de texto.',
                'respuesta_correcta': 'B',
                'justificacion': 'Un objetivo de aprendizaje efectivo debe estar centrado en el estudiante, usar verbos observables y medibles, especificar el contenido y el nivel cognitivo. Ejemplo: "El estudiante analizará (nivel: análisis-Bloom) las causas de la Independencia colombiana (contenido)".',
                'fuente_normativa': 'Bloom - Taxonomía revisada (Anderson y Krathwohl)',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'alta',
                'enunciado': 'La taxonomía de Bloom revisada por Anderson y Krathwohl ordena los procesos cognitivos de menor a mayor complejidad. El orden correcto es:',
                'opcion_a': 'Crear, Evaluar, Analizar, Aplicar, Comprender, Recordar.',
                'opcion_b': 'Recordar, Comprender, Aplicar, Analizar, Evaluar, Crear.',
                'opcion_c': 'Comprender, Recordar, Aplicar, Crear, Analizar, Evaluar.',
                'opcion_d': 'Aplicar, Recordar, Analizar, Comprender, Evaluar, Crear.',
                'respuesta_correcta': 'B',
                'justificacion': 'La taxonomía revisada va de menor a mayor complejidad cognitiva: Recordar (recuperar) → Comprender (interpretar) → Aplicar (usar) → Analizar (descomponer) → Evaluar (juzgar) → Crear (producir nuevo). Las preguntas del concurso frecuentemente ubican situaciones en estos niveles.',
                'fuente_normativa': 'Anderson y Krathwohl - Taxonomía de Bloom revisada',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'media',
                'enunciado': 'El Proyecto Educativo Institucional (PEI) es el documento que:',
                'opcion_a': 'Define el presupuesto anual de la institución educativa.',
                'opcion_b': 'Expresa la identidad, filosofía, misión, visión y propósitos de la institución, orientando todos los procesos pedagógicos y administrativos.',
                'opcion_c': 'Lista los docentes y sus áreas de enseñanza para el año escolar.',
                'opcion_d': 'Establece el reglamento disciplinario de estudiantes.',
                'respuesta_correcta': 'B',
                'justificacion': 'La Ley 115/1994 (Art. 73) establece que toda institución educativa debe elaborar y poner en práctica un PEI que incluya los principios y fines, los recursos docentes y didácticos, la estrategia pedagógica, el reglamento y el sistema de gestión.',
                'fuente_normativa': 'Ley 115 de 1994 - Art. 73',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'alta',
                'enunciado': 'La malla curricular de una institución debe articularse con los DBA y EBC porque:',
                'opcion_a': 'Es un requisito legal que obliga a copiar los documentos del MEN directamente.',
                'opcion_b': 'Garantiza coherencia vertical (entre grados) y horizontal (entre áreas) del currículo, asegurando que los aprendizajes sean progresivos y pertinentes.',
                'opcion_c': 'Evita que los docentes tengan que planear sus clases individualmente.',
                'opcion_d': 'Permite que la institución acceda a recursos financieros del MEN.',
                'respuesta_correcta': 'B',
                'justificacion': 'La articulación curricular garantiza coherencia vertical (los aprendizajes de grado 4 preparan para grado 5) y horizontal (las áreas se complementan en cada grado). Los DBA y EBC son los referentes que aseguran que la malla responda a estándares de calidad nacionales.',
                'fuente_normativa': 'Ley 115/1994 - MEN - DBA y EBC',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'media',
                'enunciado': 'En la planeación de una unidad didáctica, los criterios de evaluación deben definirse:',
                'opcion_a': 'Al finalizar la unidad una vez conocidos los resultados de los estudiantes.',
                'opcion_b': 'Al inicio, junto con los objetivos, para que docente y estudiantes sepan desde el comienzo qué se espera y cómo se valorará.',
                'opcion_c': 'Solo en el período final del año escolar.',
                'opcion_d': 'Por el coordinador académico sin intervención del docente de aula.',
                'respuesta_correcta': 'B',
                'justificacion': 'El diseño hacia atrás (Wiggins y McTighe) propone comenzar definiendo qué evidencias demostrarán el aprendizaje antes de planear las actividades. Los criterios de evaluación deben ser conocidos por los estudiantes desde el inicio para orientar su proceso.',
                'fuente_normativa': 'Wiggins y McTighe - Diseño hacia atrás / Decreto 1290',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'alta',
                'enunciado': 'Un docente planea su clase de lenguaje para grado 7° tomando como referente el EBC: "Produzco textos escritos que responden a diversas necesidades comunicativas". El DBA complementario indica que el estudiante debe "planear y escribir textos argumentativos sencillos". ¿Cuál objetivo de clase está mejor formulado?',
                'opcion_a': 'El estudiante aprenderá sobre los textos argumentativos.',
                'opcion_b': 'El estudiante elaborará el plan de escritura de un texto argumentativo sobre una problemática de su comunidad, identificando tesis, argumentos y conclusión.',
                'opcion_c': 'El docente explicará las características del texto argumentativo.',
                'opcion_d': 'Se trabajarán los textos argumentativos según el libro guía.',
                'respuesta_correcta': 'B',
                'justificacion': 'La opción B cumple todos los criterios: está centrada en el estudiante, usa un verbo observable (elaborará), especifica el producto (plan de escritura), el tipo de texto (argumentativo), el contexto (problemática de su comunidad) y los componentes esperados.',
                'fuente_normativa': 'MEN - EBC Lenguaje / DBA / Planeación de clase',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'media',
                'enunciado': 'El plan de área es el documento institucional que:',
                'opcion_a': 'Es elaborado por el MEN y enviado a cada institución.',
                'opcion_b': 'Define los propósitos, contenidos, metodologías, recursos y criterios de evaluación de un área para todos los grados de la institución, articulado con el PEI.',
                'opcion_c': 'Solo aplica para áreas obligatorias como matemáticas y lenguaje.',
                'opcion_d': 'Es elaborado individualmente por cada docente sin coordinación institucional.',
                'respuesta_correcta': 'B',
                'justificacion': 'El plan de área es un documento institucional construido colectivamente por los docentes del área, articulado con el PEI, los EBC, los DBA y el contexto local. Define la propuesta curricular del área para toda la institución.',
                'fuente_normativa': 'Ley 115/1994 - Decreto 1860 de 1994',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'alta',
                'enunciado': 'Desde la Resolución 3842 de 2022 y el Manual de Funciones, el docente del Decreto 1278 tiene entre sus funciones relacionadas con la planeación:',
                'opcion_a': 'Solo dictar clases según el horario asignado.',
                'opcion_b': 'Planear y desarrollar el trabajo curricular, participar en la definición del currículo y aportar al mejoramiento continuo del proceso educativo institucional.',
                'opcion_c': 'Elaborar el presupuesto del área para el año escolar.',
                'opcion_d': 'Diseñar el PEI sin participación del equipo docente.',
                'respuesta_correcta': 'B',
                'justificacion': 'La Resolución 3842/2022 establece que las funciones del docente incluyen planear el trabajo académico, participar en el desarrollo del currículo, contribuir al diseño y evaluación del PEI y apoyar la gestión académica de la institución. La planeación es una función esencial, no opcional.',
                'fuente_normativa': 'Resolución 3842 de 2022 - Manual de Funciones Docente',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'media',
                'enunciado': 'La secuencia didáctica es una herramienta de planeación que se diferencia de un plan de clase porque:',
                'opcion_a': 'La secuencia se aplica en un solo día y el plan de clase en varias semanas.',
                'opcion_b': 'La secuencia articula varias clases progresivas con propósito formativo claro, mostrando la relación entre actividades de apertura, desarrollo y cierre a lo largo del tiempo.',
                'opcion_c': 'La secuencia es para educación básica y el plan de clase para media.',
                'opcion_d': 'Son sinónimos con diferente nombre según la región.',
                'respuesta_correcta': 'B',
                'justificacion': 'La secuencia didáctica (Díaz Barriga) articula un conjunto de actividades de aprendizaje relacionadas entre sí, con un hilo conductor, que llevan al estudiante de lo simple a lo complejo progresivamente. Cada clase de la secuencia tiene sentido en relación con las anteriores y las siguientes.',
                'fuente_normativa': 'Díaz Barriga - Secuencias didácticas / Planeación curricular',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'alta',
                'enunciado': 'El currículo oculto en una institución educativa colombiana se refiere a:',
                'opcion_a': 'Los temas que el docente decide no enseñar por falta de tiempo.',
                'opcion_b': 'Los aprendizajes no intencionales transmitidos a través de las rutinas, normas, relaciones de poder, actitudes del docente y la cultura institucional.',
                'opcion_c': 'El PEI que no ha sido aprobado por el Consejo Directivo.',
                'opcion_d': 'Los contenidos que el MEN prohíbe enseñar en las instituciones públicas.',
                'respuesta_correcta': 'B',
                'justificacion': 'El currículo oculto (Jackson, Giroux) comprende todo lo que se aprende sin estar explícitamente planeado: valores, jerarquías, relaciones de género, actitudes ante la autoridad. La pedagogía crítica lo analiza críticamente porque puede reproducir desigualdades sociales.',
                'fuente_normativa': 'Jackson - Giroux - Pedagogía Crítica / Currículo oculto',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'media',
                'enunciado': 'El enfoque de planeación "hacia atrás" (Backward Design) propone el siguiente orden:',
                'opcion_a': 'Primero las actividades, luego los recursos y finalmente los objetivos.',
                'opcion_b': 'Primero definir los resultados deseados, luego determinar las evidencias de aprendizaje y finalmente planear las experiencias de aprendizaje.',
                'opcion_c': 'Primero seleccionar el libro de texto y luego adaptar los objetivos a él.',
                'opcion_d': 'Primero la evaluación sumativa y luego la diagnóstica.',
                'respuesta_correcta': 'B',
                'justificacion': 'Wiggins y McTighe proponen comenzar con el fin en mente: ¿Qué queremos que los estudiantes aprendan? → ¿Qué evidencias demostrarán ese aprendizaje? → ¿Qué actividades llevarán a ese aprendizaje? Este enfoque garantiza coherencia entre objetivos, evaluación y actividades.',
                'fuente_normativa': 'Wiggins y McTighe - Understanding by Design',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'alta',
                'enunciado': 'En Colombia, la autonomía escolar establecida en la Ley 115 de 1994 implica que las instituciones educativas pueden:',
                'opcion_a': 'Diseñar su currículo sin ningún referente nacional.',
                'opcion_b': 'Adaptar y contextualizar el currículo según su contexto, necesidades e identidad institucional, dentro del marco de los fines de la educación y los estándares nacionales.',
                'opcion_c': 'Cambiar los fines de la educación establecidos en el Art. 5 de la Ley 115.',
                'opcion_d': 'No aplicar el Decreto 1290 si su SIEE es diferente.',
                'respuesta_correcta': 'B',
                'justificacion': 'La Ley 115/1994 (Art. 77) reconoce la autonomía escolar como la capacidad de las instituciones para organizar las áreas del conocimiento, adoptar métodos de enseñanza y administrar su labor, dentro de los límites fijados por la ley y los lineamientos nacionales.',
                'fuente_normativa': 'Ley 115 de 1994 - Art. 77 - Autonomía escolar',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'media',
                'enunciado': 'El plan de mejoramiento institucional (PMI) se articula con la planeación docente porque:',
                'opcion_a': 'El PMI es exclusivo del área administrativa y no afecta la práctica pedagógica.',
                'opcion_b': 'Las metas del PMI en gestión académica orientan las prioridades de la planeación de área y de aula para mejorar los resultados de aprendizaje.',
                'opcion_c': 'El PMI lo elabora el rector y el docente solo lo firma.',
                'opcion_d': 'El PMI aplica solo cuando la institución es intervenida por la Secretaría de Educación.',
                'respuesta_correcta': 'B',
                'justificacion': 'El PMI articula los resultados de la autoevaluación institucional con metas de mejora. En gestión académica, las metas del PMI (mejorar resultados en matemáticas, reducir deserción, fortalecer lectura) deben reflejarse en la planeación de área y de aula del docente.',
                'fuente_normativa': 'MEN - Guía 34 - Gestión escolar / PMI',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'alta',
                'enunciado': 'Una docente de ciencias naturales planea una unidad sobre el cuerpo humano para grado 4°. Toma el DBA correspondiente, define objetivos, selecciona estrategias (ABP, trabajo colaborativo), diseña la evaluación (rúbrica + autoevaluación) y prepara los recursos. Desde el Decreto 1278, esta práctica evidencia la competencia funcional de:',
                'opcion_a': 'Uso de recursos tecnológicos.',
                'opcion_b': 'Planeación y organización académica, articulada con las competencias pedagógica-didáctica y de evaluación del aprendizaje.',
                'opcion_c': 'Comunicación con la comunidad educativa.',
                'opcion_d': 'Seguimiento de procesos administrativos.',
                'respuesta_correcta': 'B',
                'justificacion': 'La Guía 31 describe la competencia de planeación y organización académica como la capacidad para diseñar, planear y organizar el trabajo curricular articulando objetivos, estrategias, recursos y evaluación coherentemente. La docente integra todas estas dimensiones en su planeación.',
                'fuente_normativa': 'Guía 31 MEN - Decreto 1278/2002 - Planeación académica',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'media',
                'enunciado': 'La diferencia entre contenidos conceptuales, procedimentales y actitudinales en la planeación curricular es:',
                'opcion_a': 'Solo los conceptuales son evaluables por el docente.',
                'opcion_b': 'Los conceptuales son el saber (conocimiento), los procedimentales el saber hacer (habilidades) y los actitudinales el saber ser (valores y actitudes).',
                'opcion_c': 'Los actitudinales no deben incluirse en la planeación por ser subjetivos.',
                'opcion_d': 'Son tres formas de nombrar lo mismo en diferentes niveles educativos.',
                'respuesta_correcta': 'B',
                'justificacion': 'Esta tríada (Zabala) corresponde a la integración del saber (conceptos, hechos, principios), saber hacer (procedimientos, técnicas, métodos) y saber ser (actitudes, valores, normas). Una planeación integral las incluye todas, coherente con el enfoque por competencias del MEN.',
                'fuente_normativa': 'Zabala - Contenidos de aprendizaje / MEN EBC',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'alta',
                'enunciado': 'En el concurso docente CNSC 2026, la prueba de conocimientos pedagógicos evalúa si el docente puede "planear situaciones de enseñanza-aprendizaje". Un docente demuestra esta competencia cuando:',
                'opcion_a': 'Memoriza el libro de texto y lo reproduce fielmente en clase.',
                'opcion_b': 'Diseña situaciones de aprendizaje que articulan DBA, objetivos observables, estrategias pertinentes al contexto y evaluación coherente con los propósitos.',
                'opcion_c': 'Cumple puntualmente el horario de clases asignado.',
                'opcion_d': 'Usa las mismas actividades del año anterior sin modificaciones.',
                'respuesta_correcta': 'B',
                'justificacion': 'El concurso evalúa la competencia de planeación como la capacidad de diseñar coherentemente situaciones de aprendizaje que articulen referentes curriculares (DBA, EBC), objetivos claros, estrategias pertinentes al contexto colombiano y evaluación alineada con los propósitos.',
                'fuente_normativa': 'CNSC - Competencias pedagógicas / Resolución 3842/2022',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'media',
                'enunciado': 'La pregunta esencial (Essential Question) como herramienta de planeación curricular tiene como propósito:',
                'opcion_a': 'Definir el tema del examen final del período.',
                'opcion_b': 'Provocar indagación profunda y sostenida, conectar el aprendizaje con situaciones reales y mantener el foco de la unidad hacia la comprensión duradera.',
                'opcion_c': 'Reemplazar los objetivos de aprendizaje en la planeación.',
                'opcion_d': 'Ser respondida correctamente por el docente al inicio de la clase.',
                'respuesta_correcta': 'B',
                'justificacion': 'Las preguntas esenciales (Wiggins y McTighe) no tienen respuesta única ni definitiva. Su propósito es provocar pensamiento, debate y conexión con el mundo real. Ejemplo: "¿Cómo la historia de Colombia explica nuestra situación actual?" orienta toda una unidad.',
                'fuente_normativa': 'Wiggins y McTighe - Understanding by Design / Planeación curricular',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'alta',
                'enunciado': 'Según la Ley 115 de 1994, las áreas obligatorias y fundamentales del currículo de la educación básica y media incluyen:',
                'opcion_a': 'Solo matemáticas, lenguaje, ciencias y educación física.',
                'opcion_b': 'Ciencias naturales, ciencias sociales, educación artística, educación ética y en valores, educación física, humanidades (lengua castellana e idiomas), matemáticas, tecnología e informática, y educación religiosa.',
                'opcion_c': 'Las que cada institución defina según su PEI sin restricción.',
                'opcion_d': 'Solo las establecidas en las pruebas Saber del ICFES.',
                'respuesta_correcta': 'B',
                'justificacion': 'El Art. 23 de la Ley 115/1994 establece las nueve áreas obligatorias y fundamentales. La educación religiosa es obligatoria con reserva de conciencia (no puede imponerse). Las instituciones pueden ofrecer áreas optativas adicionales según su PEI.',
                'fuente_normativa': 'Ley 115 de 1994 - Art. 23',
            },
        ]
