from django.core.management.base import BaseCommand
from django.db import transaction
from contenidos.models import Sesion
from evaluaciones.models import Pregunta


class Command(BaseCommand):
    help = 'Carga 30 preguntas para sesiones 6 (Inclusión), 7 (Convivencia) y 8 (Ley 115)'

    def handle(self, *args, **kwargs):
        self._cargar_sesion(6, self._preguntas_sesion6())
        self._cargar_sesion(7, self._preguntas_sesion7())
        self._cargar_sesion(8, self._preguntas_sesion8())

        self.stdout.write(self.style.SUCCESS('\n✅ CARGA COMPLETADA SESIONES 6-7-8'))
        total = Pregunta.objects.count()
        self.stdout.write(self.style.SUCCESS(f'📊 Total preguntas en la base de datos: {total}'))

    def _cargar_sesion(self, numero, preguntas_data):
        try:
            sesion = Sesion.objects.get(numero=numero)
        except Sesion.DoesNotExist:
            self.stdout.write(self.style.ERROR(f'❌ Sesión {numero} no existe.'))
            return
        existentes = Pregunta.objects.filter(sesion=sesion).count()
        if existentes >= 30:
            self.stdout.write(self.style.WARNING(f'⚠ Sesión {numero} ya tiene {existentes} preguntas. Omitiendo.'))
            return
        self.stdout.write(self.style.WARNING(f'\n📚 Cargando Sesión {numero}: {sesion.titulo}'))
        creadas = 0
        with transaction.atomic():
            for data in preguntas_data:
                data['sesion'] = sesion
                Pregunta.objects.create(**data)
                creadas += 1
        self.stdout.write(self.style.SUCCESS(f'  ✅ {creadas} preguntas cargadas'))

    def _preguntas_sesion6(self):
        return [
            {
                'componente': 'pedagogico', 'dificultad': 'media',
                'enunciado': 'El Decreto 1421 de 2017 define la educación inclusiva como:',
                'opcion_a': 'La educación especial brindada en aulas separadas para estudiantes con discapacidad.',
                'opcion_b': 'Un proceso permanente que reconoce, valora y responde a la diversidad mediante la eliminación de barreras para el aprendizaje y la participación.',
                'opcion_c': 'La integración de estudiantes con discapacidad al aula regular sin ningún apoyo adicional.',
                'opcion_d': 'Un programa voluntario que las instituciones pueden adoptar según su capacidad.',
                'respuesta_correcta': 'B',
                'justificacion': 'El Decreto 1421/2017 adopta el enfoque social de la discapacidad: la barrera no está en el estudiante sino en el entorno. La educación inclusiva elimina barreras actitudinales, físicas y curriculares para garantizar participación y aprendizaje de todos.',
                'fuente_normativa': 'Decreto 1421 de 2017 - Art. 2.3.3.5.1.4',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'alta',
                'enunciado': 'El PIAR (Plan Individual de Ajustes Razonables) según el Decreto 1421 de 2017 debe ser liderado por:',
                'opcion_a': 'El médico tratante del estudiante con discapacidad.',
                'opcion_b': 'El docente de apoyo pedagógico exclusivamente.',
                'opcion_c': 'El docente de aula como líder, con participación del docente de apoyo, la familia y el estudiante.',
                'opcion_d': 'El rector y el coordinador académico sin intervención del docente de aula.',
                'respuesta_correcta': 'C',
                'justificacion': 'El Art. 2.3.3.5.2.3.5 del Decreto 1421/2017 establece que el PIAR es liderado por el docente de aula con el apoyo del docente de apoyo pedagógico. La familia y el estudiante son participantes activos. El diagnóstico médico no es requisito para elaborarlo.',
                'fuente_normativa': 'Decreto 1421 de 2017 - Art. 2.3.3.5.2.3.5',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'media',
                'enunciado': 'El Diseño Universal para el Aprendizaje (DUA) propone que el currículo debe ofrecer:',
                'opcion_a': 'Un único método de enseñanza para garantizar igualdad entre todos los estudiantes.',
                'opcion_b': 'Múltiples medios de representación, múltiples medios de acción y expresión, y múltiples medios de motivación.',
                'opcion_c': 'Adaptaciones curriculares individuales para cada estudiante con diagnóstico médico.',
                'opcion_d': 'Reducción de contenidos para estudiantes con discapacidad.',
                'respuesta_correcta': 'B',
                'justificacion': 'El DUA (CAST) se basa en tres principios: múltiples formas de representar la información (el qué del aprendizaje), múltiples formas de acción y expresión (el cómo) y múltiples formas de motivación (el por qué). Beneficia a TODOS los estudiantes, no solo a los que tienen discapacidad.',
                'fuente_normativa': 'Decreto 1421/2017 - DUA - CAST',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'alta',
                'enunciado': 'Según el Decreto 1421 de 2017, para construir el PIAR NO es requisito indispensable:',
                'opcion_a': 'La valoración pedagógica del estudiante.',
                'opcion_b': 'El diagnóstico médico clínico del estudiante.',
                'opcion_c': 'La participación de la familia.',
                'opcion_d': 'La identificación de barreras para el aprendizaje.',
                'respuesta_correcta': 'B',
                'justificacion': 'El Numeral 4 del Art. 2.3.3.5.2.3.5 establece que el PIAR se basa en la valoración pedagógica, no médica. Esperar un diagnóstico clínico para iniciar el PIAR es una barrera actitudinal que viola el decreto. La valoración pedagógica es suficiente para comenzar.',
                'fuente_normativa': 'Decreto 1421/2017 - Art. 2.3.3.5.2.3.5 Numeral 4',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'media',
                'enunciado': 'Los ajustes razonables en educación inclusiva se definen como:',
                'opcion_a': 'La reducción del nivel de exigencia académica para estudiantes con discapacidad.',
                'opcion_b': 'Modificaciones y adaptaciones necesarias y adecuadas para garantizar el goce de derechos en igualdad de condiciones, sin imponer una carga desproporcionada.',
                'opcion_c': 'La creación de aulas especiales separadas del aula regular.',
                'opcion_d': 'La exención total de evaluaciones para estudiantes con discapacidad.',
                'respuesta_correcta': 'B',
                'justificacion': 'Los ajustes razonables (Convención ONU sobre Discapacidad - Ley 1346/2009) son modificaciones necesarias para garantizar participación en igualdad. No implican reducir la exigencia sino adaptar el formato, el tiempo, los materiales o los medios de comunicación.',
                'fuente_normativa': 'Decreto 1421/2017 - Convención ONU Discapacidad',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'alta',
                'enunciado': 'Un rector afirma que no puede matricular a un estudiante con discapacidad cognitiva porque "no tiene cupo en el aula de apoyo". Según el Decreto 1421 de 2017, esta situación es:',
                'opcion_a': 'Válida porque el aula de apoyo es requisito previo para la inclusión.',
                'opcion_b': 'Una barrera actitudinal e institucional que viola el derecho a la educación inclusiva, pues la matrícula no puede negarse por razón de discapacidad.',
                'opcion_c': 'Aceptable si la institución no cuenta con docente de apoyo.',
                'opcion_d': 'Una decisión autónoma de la institución según su PEI.',
                'respuesta_correcta': 'B',
                'justificacion': 'El Decreto 1421/2017 prohíbe explícitamente negar la matrícula por razón de discapacidad. El aula de apoyo no es requisito para la matrícula sino un apoyo adicional. Negar la matrícula constituye discriminación y puede ser sancionada.',
                'fuente_normativa': 'Decreto 1421/2017 - Derecho a la matrícula',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'media',
                'enunciado': 'El docente de apoyo pedagógico en el marco del Decreto 1421 de 2017 cumple la función de:',
                'opcion_a': 'Reemplazar al docente de aula cuando hay estudiantes con discapacidad.',
                'opcion_b': 'Asesorar y acompañar al docente de aula, a la familia y a la institución en la implementación de estrategias inclusivas.',
                'opcion_c': 'Atender exclusivamente a los estudiantes con discapacidad en un espacio separado.',
                'opcion_d': 'Elaborar el PIAR sin involucrar al docente de aula.',
                'respuesta_correcta': 'B',
                'justificacion': 'El docente de apoyo pedagógico es un profesional de la educación que orienta y acompaña los procesos de inclusión. Su función es fortalecer las capacidades del docente de aula, no reemplazarlo ni atender en paralelo a los estudiantes con discapacidad.',
                'fuente_normativa': 'Decreto 1421/2017 - Docente de apoyo pedagógico',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'alta',
                'enunciado': 'La diferencia entre integración escolar e inclusión educativa radica en:',
                'opcion_a': 'La integración y la inclusión son sinónimos modernos del mismo concepto.',
                'opcion_b': 'En la integración el estudiante debe adaptarse al sistema; en la inclusión el sistema se transforma para responder a la diversidad.',
                'opcion_c': 'La inclusión solo aplica para estudiantes con discapacidad y la integración para todos.',
                'opcion_d': 'La integración es más avanzada pedagógicamente que la inclusión.',
                'respuesta_correcta': 'B',
                'justificacion': 'La integración (modelo médico-rehabilitador) exige que el estudiante con discapacidad se adapte al sistema regular. La inclusión (modelo social) transforma el sistema para que responda a la diversidad de todos. El Decreto 1421/2017 adopta el enfoque de inclusión.',
                'fuente_normativa': 'Decreto 1421/2017 - UNESCO - Enfoque inclusivo',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'media',
                'enunciado': 'Las barreras para el aprendizaje y la participación en educación inclusiva pueden ser de tipo:',
                'opcion_a': 'Solo físicas y arquitectónicas.',
                'opcion_b': 'Actitudinales, físicas, comunicativas, curriculares e institucionales.',
                'opcion_c': 'Exclusivamente médicas y neurológicas.',
                'opcion_d': 'Solo económicas y familiares.',
                'respuesta_correcta': 'B',
                'justificacion': 'El Decreto 1421/2017 adopta el concepto de barreras del Index for Inclusion (Booth y Ainscow): actitudinales (prejuicios), físicas (accesibilidad), comunicativas (formatos), curriculares (rigidez del currículo) e institucionales (políticas excluyentes). La discapacidad no está en la persona sino en la interacción con las barreras.',
                'fuente_normativa': 'Decreto 1421/2017 - Index for Inclusion',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'alta',
                'enunciado': 'Un estudiante con discapacidad visual ingresa a grado 6°. El docente de matemáticas debe:',
                'opcion_a': 'Eximir al estudiante de las actividades que requieren visión.',
                'opcion_b': 'Construir el PIAR con ajustes razonables (material en braille o audio, tiempo adicional) y aplicar el DUA para garantizar acceso al currículo.',
                'opcion_c': 'Remitir al estudiante al aula de apoyo para toda la clase de matemáticas.',
                'opcion_d': 'Esperar el diagnóstico oftalmológico antes de tomar cualquier medida.',
                'respuesta_correcta': 'B',
                'justificacion': 'El docente de aula es el responsable principal de la inclusión. Debe construir el PIAR con ajustes razonables (formato braille, audio, tiempo adicional) e implementar DUA (múltiples medios de representación). No puede eximir ni segregar al estudiante.',
                'fuente_normativa': 'Decreto 1421/2017 - PIAR - DUA',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'media',
                'enunciado': 'El índice de inclusión (Index for Inclusion) es una herramienta que permite:',
                'opcion_a': 'Clasificar a los estudiantes según su tipo de discapacidad.',
                'opcion_b': 'Autoevaluar las culturas, políticas y prácticas inclusivas de una institución para identificar barreras y promover mejoras.',
                'opcion_c': 'Medir el cociente intelectual de los estudiantes con necesidades educativas especiales.',
                'opcion_d': 'Determinar cuántos estudiantes con discapacidad puede atender una institución.',
                'respuesta_correcta': 'B',
                'justificacion': 'El Index for Inclusion (Booth y Ainscow) es un instrumento de autoevaluación institucional que analiza tres dimensiones: culturas inclusivas (valores compartidos), políticas inclusivas (gestión) y prácticas inclusivas (aula). Ayuda a las instituciones a identificar y eliminar barreras.',
                'fuente_normativa': 'Booth y Ainscow - Index for Inclusion / MEN Colombia',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'alta',
                'enunciado': 'Según el Decreto 1421 de 2017, el PIAR debe revisarse y actualizarse:',
                'opcion_a': 'Una sola vez al inicio del año escolar.',
                'opcion_b': 'Periódicamente durante el año según los avances y necesidades del estudiante, y obligatoriamente al cambiar de grado o institución.',
                'opcion_c': 'Solo cuando el estudiante presenta una nueva discapacidad.',
                'opcion_d': 'Cada tres años independiente del avance del estudiante.',
                'respuesta_correcta': 'B',
                'justificacion': 'El PIAR es un documento vivo que debe actualizarse continuamente según los progresos del estudiante. Al cambiar de grado o institución debe transferirse para garantizar continuidad en los apoyos. No es un documento estático de inicio de año.',
                'fuente_normativa': 'Decreto 1421/2017 - Continuidad del PIAR',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'media',
                'enunciado': 'La educación para estudiantes con capacidades y talentos excepcionales en Colombia está regulada por:',
                'opcion_a': 'El Decreto 1421 de 2017 exclusivamente.',
                'opcion_b': 'La Ley 115 de 1994 (Art. 49-50) y el Decreto 1075 de 2015, que establecen el derecho a una educación que potencie sus capacidades.',
                'opcion_c': 'No existe regulación específica para esta población.',
                'opcion_d': 'Solo por el ICFES mediante pruebas de admisión especiales.',
                'respuesta_correcta': 'B',
                'justificacion': 'La Ley 115/1994 (Art. 49) establece que el servicio educativo atenderá a personas con capacidades excepcionales. El Decreto 1075/2015 regula la atención educativa de esta población, que también hace parte de la educación inclusiva.',
                'fuente_normativa': 'Ley 115/1994 Art. 49 - Decreto 1075/2015',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'alta',
                'enunciado': 'En una institución de Antioquia llega un estudiante con autismo (TEA). El rector debe:',
                'opcion_a': 'Negar la matrícula hasta contar con aula especializada.',
                'opcion_b': 'Matricularlo, solicitar el apoyo del docente de apoyo pedagógico, iniciar la construcción del PIAR y aplicar DUA en todas las aulas.',
                'opcion_c': 'Remitirlo a una institución de educación especial.',
                'opcion_d': 'Condicionar la matrícula a que la familia contrate un acompañante terapéutico.',
                'respuesta_correcta': 'B',
                'justificacion': 'El Decreto 1421/2017 prohíbe negar la matrícula. El proceso correcto es: matrícula inmediata, solicitud de docente de apoyo a la secretaría de educación, construcción del PIAR y aplicación de DUA. El TEA no justifica segregación ni condicionamientos.',
                'fuente_normativa': 'Decreto 1421/2017 - Proceso de matrícula inclusiva',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'media',
                'enunciado': 'La atención educativa a población étnica (indígenas, afrocolombianos, raizales, palenqueros y ROM) en Colombia se fundamenta en el derecho a:',
                'opcion_a': 'Recibir exactamente la misma educación que el resto de la población sin adaptaciones.',
                'opcion_b': 'Una educación que reconozca y fortalezca su identidad cultural, lengua y cosmovisión mediante etnoeducación.',
                'opcion_c': 'Estudiar en instituciones separadas del resto de la población.',
                'opcion_d': 'Ser eximidos del currículo nacional por autonomía étnica.',
                'respuesta_correcta': 'B',
                'justificacion': 'La Ley 115/1994 (Art. 55-63) y el Decreto 1075/2015 establecen la etnoeducación como el derecho de los grupos étnicos a una educación que respete y desarrolle su identidad cultural, lengua propia y cosmovisión, articulada con el currículo nacional.',
                'fuente_normativa': 'Ley 115/1994 Art. 55-63 - Etnoeducación',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'alta',
                'enunciado': 'Un docente tiene en su aula un estudiante con hipoacusia (pérdida auditiva). Desde el DUA, el primer ajuste que debe implementar es:',
                'opcion_a': 'Hablar más despacio y en voz más alta durante toda la clase.',
                'opcion_b': 'Ofrecer múltiples formas de representación: apoyos visuales, subtítulos en videos, lenguaje de señas cuando sea necesario, y ubicar al estudiante estratégicamente.',
                'opcion_c': 'Remitir todas las instrucciones al docente de apoyo para que las traduzca.',
                'opcion_d': 'Evaluar solo mediante pruebas escritas para no discriminarlo.',
                'respuesta_correcta': 'B',
                'justificacion': 'El DUA propone múltiples medios de representación para atender diversidad sensorial. Para un estudiante con hipoacusia: apoyos visuales (esquemas, imágenes), subtítulos, lengua de señas cuando aplique, y ubicación estratégica en el aula. Estos ajustes benefician a todo el grupo.',
                'fuente_normativa': 'Decreto 1421/2017 - DUA - Múltiples medios de representación',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'media',
                'enunciado': 'La educación inclusiva, según el Decreto 1421 de 2017, beneficia:',
                'opcion_a': 'Solo a los estudiantes con discapacidad diagnosticada.',
                'opcion_b': 'A toda la comunidad educativa: estudiantes con y sin discapacidad, docentes y familias aprenden a valorar la diversidad.',
                'opcion_c': 'Solo a las instituciones que reciben financiación especial del MEN.',
                'opcion_d': 'Únicamente a los estudiantes de estratos socioeconómicos bajos.',
                'respuesta_correcta': 'B',
                'justificacion': 'La investigación en educación inclusiva muestra que los ambientes diversos benefician a todos: los estudiantes sin discapacidad desarrollan empatía, tolerancia y habilidades colaborativas. El docente desarrolla competencias pedagógicas más versátiles. La diversidad enriquece el aprendizaje.',
                'fuente_normativa': 'Decreto 1421/2017 - UNESCO - Educación para todos',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'alta',
                'enunciado': 'El Decreto 1278 de 2002 y la educación inclusiva se relacionan porque el docente vinculado por este estatuto:',
                'opcion_a': 'No tiene obligaciones frente a la inclusión por no ser docente de apoyo.',
                'opcion_b': 'Tiene como función implementar estrategias pedagógicas inclusivas en el aula, construir el PIAR y garantizar la participación de todos los estudiantes.',
                'opcion_c': 'Solo debe reportar a coordinación los casos de estudiantes con discapacidad.',
                'opcion_d': 'Puede negarse a atender estudiantes con discapacidad si no recibió formación específica.',
                'respuesta_correcta': 'B',
                'justificacion': 'El Decreto 1278/2002 y la Resolución 3842/2022 establecen que las funciones del docente incluyen atender la diversidad del aula. El Decreto 1421/2017 refuerza que el docente de aula es el responsable principal de la inclusión, con el apoyo del docente de apoyo pedagógico.',
                'fuente_normativa': 'Decreto 1278/2002 - Decreto 1421/2017 - Resolución 3842/2022',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'media',
                'enunciado': 'Las Necesidades Educativas Especiales (NEE) se clasifican en:',
                'opcion_a': 'Solo permanentes (discapacidades de por vida).',
                'opcion_b': 'Transitorias (situaciones temporales que afectan el aprendizaje) y permanentes (discapacidades o talentos excepcionales).',
                'opcion_c': 'Solo cognitivas y físicas.',
                'opcion_d': 'Diagnosticadas por médico y no diagnosticadas.',
                'respuesta_correcta': 'B',
                'justificacion': 'Las NEE pueden ser transitorias (dificultades de aprendizaje temporales por factores emocionales, sociales o pedagógicos) o permanentes (discapacidades sensoriales, motoras, cognitivas, múltiples o talentos excepcionales). Ambas requieren atención educativa diferenciada.',
                'fuente_normativa': 'MEN Colombia - NEE / Decreto 1421/2017',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'alta',
                'enunciado': 'Según el Decreto 1421 de 2017, la valoración pedagógica que da origen al PIAR debe realizarla:',
                'opcion_a': 'Un psicólogo clínico externo a la institución.',
                'opcion_b': 'El docente de aula con el apoyo del docente de apoyo pedagógico, basándose en la observación del desempeño en el contexto educativo.',
                'opcion_c': 'El médico pediatra o neurólogo del estudiante.',
                'opcion_d': 'El coordinador académico mediante pruebas estandarizadas.',
                'respuesta_correcta': 'B',
                'justificacion': 'La valoración pedagógica es un proceso educativo, no clínico. El docente de aula y el docente de apoyo observan al estudiante en el contexto escolar, identifican sus fortalezas, necesidades y las barreras del entorno. No requiere diagnóstico médico previo.',
                'fuente_normativa': 'Decreto 1421/2017 - Valoración pedagógica',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'media',
                'enunciado': 'El enfoque diferencial en educación inclusiva implica:',
                'opcion_a': 'Tratar a todos los estudiantes exactamente igual sin distinción.',
                'opcion_b': 'Reconocer que ciertos grupos (mujeres, personas con discapacidad, grupos étnicos, víctimas del conflicto) enfrentan barreras adicionales que requieren respuestas específicas.',
                'opcion_c': 'Crear currículos completamente diferentes para cada grupo poblacional.',
                'opcion_d': 'Asignar a estudiantes vulnerables a instituciones especializadas.',
                'respuesta_correcta': 'B',
                'justificacion': 'El enfoque diferencial reconoce que la igualdad formal (tratar a todos igual) puede reproducir desigualdad cuando algunos grupos enfrentan obstáculos adicionales. Requiere acciones afirmativas y respuestas específicas que garanticen equidad real, no solo igualdad formal.',
                'fuente_normativa': 'MEN - Enfoque diferencial / Decreto 1421/2017',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'alta',
                'enunciado': 'La Convención sobre los Derechos de las Personas con Discapacidad (ONU, 2006), ratificada por Colombia mediante la Ley 1346 de 2009, establece en su Art. 24 que los Estados deben garantizar:',
                'opcion_a': 'Educación especial segregada de alta calidad para personas con discapacidad.',
                'opcion_b': 'Un sistema de educación inclusiva en todos los niveles, con ajustes razonables y apoyos necesarios para facilitar la formación efectiva.',
                'opcion_c': 'Educación optativa para personas con discapacidad según sus capacidades.',
                'opcion_d': 'Financiamiento privado para instituciones especializadas en discapacidad.',
                'respuesta_correcta': 'B',
                'justificacion': 'El Art. 24 de la Convención ONU es el fundamento internacional del Decreto 1421/2017. Colombia asumió la obligación de garantizar educación inclusiva en todos los niveles, con ajustes razonables y apoyos individualizados para que las personas con discapacidad no sean excluidas del sistema general.',
                'fuente_normativa': 'Ley 1346 de 2009 - Convención ONU Discapacidad Art. 24',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'media',
                'enunciado': 'En el marco de la educación inclusiva, la sobreprotección del estudiante con discapacidad por parte del docente es una barrera porque:',
                'opcion_a': 'Implica mayor trabajo para el docente.',
                'opcion_b': 'Limita el desarrollo de la autonomía, las habilidades y la autoconfianza del estudiante al no permitirle enfrentar desafíos apropiados.',
                'opcion_c': 'Genera conflictos con los padres de familia.',
                'opcion_d': 'Viola la normatividad del Decreto 1421/2017 sobre horarios.',
                'respuesta_correcta': 'B',
                'justificacion': 'La sobreprotección es una barrera actitudinal que parte de bajas expectativas hacia el estudiante con discapacidad. Limitar los desafíos por "protegerlo" impide el desarrollo de competencias, autonomía y autoestima. El enfoque inclusivo parte de reconocer las capacidades, no solo las limitaciones.',
                'fuente_normativa': 'Decreto 1421/2017 - Barreras actitudinales',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'alta',
                'enunciado': 'Un docente de básica primaria tiene en su aula una estudiante con síndrome de Down. Al planear una clase de matemáticas sobre fracciones, la mejor estrategia inclusiva es:',
                'opcion_a': 'Asignarle una tarea diferente y más fácil sin relación con el tema de la clase.',
                'opcion_b': 'Aplicar DUA: presentar fracciones con materiales concretos, representaciones gráficas y contexto cotidiano, ajustando el nivel de complejidad según el PIAR.',
                'opcion_c': 'Pedir al docente de apoyo que la saque del aula durante matemáticas.',
                'opcion_d': 'Esperar a que termine la primaria para iniciar los procesos de inclusión.',
                'respuesta_correcta': 'B',
                'justificacion': 'El DUA con materiales concretos y contextos cotidianos facilita la comprensión para estudiantes con síndrome de Down y enriquece el aprendizaje de todos. El PIAR define el nivel de complejidad esperado. La exclusión del aula viola el Decreto 1421/2017.',
                'fuente_normativa': 'Decreto 1421/2017 - DUA - PIAR',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'media',
                'enunciado': 'La política de educación inclusiva en Colombia busca transitar de un modelo de:',
                'opcion_a': 'Educación especial a educación integrada.',
                'opcion_b': 'Exclusión a inclusión, eliminando barreras para que todos participen en el sistema educativo regular.',
                'opcion_c': 'Educación pública a educación privada especializada.',
                'opcion_d': 'Educación presencial a educación virtual para estudiantes con discapacidad.',
                'respuesta_correcta': 'B',
                'justificacion': 'El Decreto 1421/2017 y el documento CONPES 166 de 2013 marcan la transición de un modelo de educación especial segregada hacia un sistema educativo inclusivo donde todos participan con apoyos y ajustes necesarios. Es un cambio de paradigma, no solo de metodología.',
                'fuente_normativa': 'Decreto 1421/2017 - CONPES 166/2013',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'alta',
                'enunciado': 'Cuando un estudiante con discapacidad motora requiere acceder al segundo piso de la institución donde está su salón, y no hay ascensor, el docente debe:',
                'opcion_a': 'Decirle al estudiante que no puede asistir a esas clases.',
                'opcion_b': 'Reportar la barrera física a la institución, gestionar el cambio de salón al primer piso como ajuste razonable inmediato y documentarlo en el PIAR.',
                'opcion_c': 'Esperar a que la institución construya el ascensor antes de actuar.',
                'opcion_d': 'Contratar un acompañante para cargar al estudiante.',
                'respuesta_correcta': 'B',
                'justificacion': 'La barrera física debe eliminarse. El ajuste razonable inmediato es cambiar el salón al primer piso. El docente debe reportar la barrera a la institución para que se gestione su eliminación permanente y documentarlo en el PIAR como parte de los ajustes del entorno.',
                'fuente_normativa': 'Decreto 1421/2017 - Ajustes razonables - Barreras físicas',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'media',
                'enunciado': 'La atención educativa a población víctima del conflicto armado en Colombia se rige principalmente por:',
                'opcion_a': 'El Decreto 1421 de 2017 exclusivamente.',
                'opcion_b': 'La Ley 1448 de 2011 (Ley de Víctimas) y el Decreto 4800 de 2011, que garantizan el derecho preferente a la educación con enfoque psicosocial.',
                'opcion_c': 'Solo el SIEE de cada institución según su contexto.',
                'opcion_d': 'La Ley 1620 de 2013 sobre convivencia escolar.',
                'respuesta_correcta': 'B',
                'justificacion': 'La Ley 1448/2011 establece medidas de atención, asistencia y reparación a víctimas del conflicto. En educación, garantiza acceso y permanencia con enfoque psicosocial. Los docentes deben reconocer el impacto del conflicto en el aprendizaje y la convivencia.',
                'fuente_normativa': 'Ley 1448 de 2011 - Atención a víctimas en educación',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'alta',
                'enunciado': 'Desde la perspectiva del concurso docente CNSC, un docente demuestra competencia en inclusión cuando en su práctica:',
                'opcion_a': 'Remite todos los casos de diversidad al docente de apoyo sin intervención propia.',
                'opcion_b': 'Implementa el DUA en su planeación regular, construye el PIAR con el equipo de apoyo, elimina barreras del aula y garantiza participación de todos los estudiantes.',
                'opcion_c': 'Aprueba automáticamente a todos los estudiantes con discapacidad para garantizar su permanencia.',
                'opcion_d': 'Solicita la reducción del grupo cuando hay estudiantes con NEE.',
                'respuesta_correcta': 'B',
                'justificacion': 'El concurso CNSC evalúa la comprensión integral de la inclusión: no es segregar ni aprobar automáticamente, sino transformar la práctica pedagógica. Implementar DUA, construir PIAR, eliminar barreras y garantizar participación son las evidencias de un docente inclusivo competente.',
                'fuente_normativa': 'Resolución 3842/2022 - CNSC - Decreto 1421/2017',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'media',
                'enunciado': 'El plazo establecido por el Decreto 1421 de 2017 para que las instituciones implementen los ajustes y apoyos definidos en el PIAR es:',
                'opcion_a': 'Tres años desde la matrícula del estudiante.',
                'opcion_b': 'Inmediato: los ajustes deben implementarse desde el inicio de la matrícula y actualizarse continuamente.',
                'opcion_c': 'Un año lectivo completo antes de hacer ajustes.',
                'opcion_d': 'Solo cuando la institución reciba financiación adicional del MEN.',
                'respuesta_correcta': 'B',
                'justificacion': 'El PIAR no tiene plazos de espera para su implementación. Los ajustes razonables deben aplicarse desde que el estudiante ingresa a la institución. La demora en implementar ajustes constituye una barrera institucional que viola los derechos del estudiante.',
                'fuente_normativa': 'Decreto 1421/2017 - Implementación del PIAR',
            },
        ]

    def _preguntas_sesion7(self):
        return [
            {
                'componente': 'pedagogico', 'dificultad': 'media',
                'enunciado': 'La Ley 1620 de 2013 crea el Sistema Nacional de Convivencia Escolar con el objetivo principal de:',
                'opcion_a': 'Sancionar a los estudiantes que cometan faltas disciplinarias graves.',
                'opcion_b': 'Fomentar, fortalecer y articular acciones para la promoción de la convivencia, la prevención de la violencia escolar, la atención al embarazo adolescente y el ejercicio de los DDHH.',
                'opcion_c': 'Crear tribunales escolares para juzgar conflictos entre estudiantes.',
                'opcion_d': 'Obligar a las instituciones a contratar psicólogos como requisito de funcionamiento.',
                'respuesta_correcta': 'B',
                'justificacion': 'El Art. 1 de la Ley 1620/2013 establece que el sistema busca promover y fortalecer la convivencia escolar, la formación ciudadana, el ejercicio de DDHH y la prevención de situaciones que afectan la convivencia. Tiene enfoque preventivo y formativo, no punitivo.',
                'fuente_normativa': 'Ley 1620 de 2013 - Art. 1',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'alta',
                'enunciado': 'Las tres rutas de atención integral establecidas en la Ley 1620 de 2013 para situaciones que afectan la convivencia son:',
                'opcion_a': 'Prevención, sanción y reparación.',
                'opcion_b': 'Promoción, prevención, atención y seguimiento.',
                'opcion_c': 'Denuncia, investigación y sanción.',
                'opcion_d': 'Detección, remisión y seguimiento exclusivamente.',
                'respuesta_correcta': 'B',
                'justificacion': 'La Ley 1620/2013 y el Decreto 1965/2013 establecen cuatro componentes de la ruta: promoción (cultura de convivencia), prevención (factores de riesgo), atención (situaciones presentadas) y seguimiento (monitoreo de casos). No es una ruta punitiva sino formativa.',
                'fuente_normativa': 'Ley 1620/2013 - Decreto 1965/2013 - Ruta de atención',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'media',
                'enunciado': 'Según la Ley 1620 de 2013, las situaciones que afectan la convivencia escolar se clasifican en:',
                'opcion_a': 'Leves, graves y gravísimas.',
                'opcion_b': 'Tipo I (conflictos manejables desde el aula), Tipo II (situaciones que no son delito pero causan daño) y Tipo III (situaciones que pueden ser delito).',
                'opcion_c': 'Verbales, físicas y cibernéticas.',
                'opcion_d': 'Internas y externas a la institución.',
                'respuesta_correcta': 'B',
                'justificacion': 'El Decreto 1965/2013 clasifica las situaciones en Tipo I (conflictos cotidianos, manejados por docentes), Tipo II (agresiones que no constituyen delito pero requieren protocolos formales) y Tipo III (posibles delitos que requieren activar autoridades externas como policía o ICBF).',
                'fuente_normativa': 'Decreto 1965 de 2013 - Art. 40, 41, 42',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'alta',
                'enunciado': 'Un estudiante de grado 8° insulta repetidamente a un compañero en redes sociales publicando comentarios humillantes. Según la Ley 1620 de 2013, esta situación es:',
                'opcion_a': 'Tipo I porque ocurre fuera de la institución.',
                'opcion_b': 'Ciberacoso (Tipo II o III según la gravedad), que debe atenderse mediante la ruta de atención institucional aunque ocurra fuera del aula.',
                'opcion_c': 'Un asunto privado que la institución no debe atender.',
                'opcion_d': 'Solo sancionable si ocurre dentro de la institución durante el horario escolar.',
                'respuesta_correcta': 'B',
                'justificacion': 'La Ley 1620/2013 incluye el ciberacoso como situación de convivencia escolar que debe atenderse aunque ocurra fuera del horario escolar si involucra a miembros de la comunidad educativa. El impacto en el aprendizaje y bienestar del estudiante es responsabilidad de la institución.',
                'fuente_normativa': 'Ley 1620/2013 - Ciberacoso - Decreto 1965/2013',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'media',
                'enunciado': 'El Comité Escolar de Convivencia establecido por la Ley 1620 de 2013 está presidido por:',
                'opcion_a': 'El docente con más años de experiencia.',
                'opcion_b': 'El rector o director de la institución educativa.',
                'opcion_c': 'El personero estudiantil.',
                'opcion_d': 'Un representante de la Secretaría de Educación.',
                'respuesta_correcta': 'B',
                'justificacion': 'El Art. 12 de la Ley 1620/2013 establece que el Comité Escolar de Convivencia está presidido por el rector e integrado por el coordinador, el personero, el docente con función de orientación, un docente líder de iniciativas de convivencia, dos padres y dos estudiantes.',
                'fuente_normativa': 'Ley 1620 de 2013 - Art. 12 - Comité de Convivencia',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'alta',
                'enunciado': 'Un docente identifica en el recreo que un estudiante de grado 6° está siendo agredido físicamente por compañeros de grado 9°. La acción inmediata correcta según la Ley 1620 es:',
                'opcion_a': 'Esperar a que termine el recreo y reportar en el siguiente consejo de docentes.',
                'opcion_b': 'Intervenir para detener la agresión, garantizar la seguridad del afectado, reportar al coordinador e iniciar el protocolo de atención Tipo II o III según la gravedad.',
                'opcion_c': 'Llamar a los padres de ambas partes para que resuelvan el conflicto entre ellos.',
                'opcion_d': 'Escribir un acta y archivarla sin tomar medidas inmediatas.',
                'respuesta_correcta': 'B',
                'justificacion': 'Ante una agresión física en curso, la intervención inmediata es obligatoria. El docente debe proteger al afectado, reportar a coordinación e iniciar la ruta de atención. Si hay lesiones o la situación puede ser delito, es Tipo III y debe activarse la ruta con autoridades.',
                'fuente_normativa': 'Ley 1620/2013 - Decreto 1965/2013 - Ruta de atención Tipo II/III',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'media',
                'enunciado': 'El manual de convivencia según la Ley 1620 de 2013 debe:',
                'opcion_a': 'Ser elaborado exclusivamente por el Consejo Directivo sin participación estudiantil.',
                'opcion_b': 'Construirse con participación de toda la comunidad educativa y contener las pautas para convivencia, los protocolos de atención y las estrategias pedagógicas para el manejo de conflictos.',
                'opcion_c': 'Limitarse a listar las sanciones disciplinarias aplicables.',
                'opcion_d': 'Ser idéntico para todas las instituciones del país.',
                'respuesta_correcta': 'B',
                'justificacion': 'La Ley 1620/2013 exige que el manual de convivencia se construya participativamente e incluya: pautas de convivencia, protocolos de atención para cada tipo de situación, mecanismos de participación, estrategias pedagógicas y rutas de atención. Es un instrumento formativo, no solo punitivo.',
                'fuente_normativa': 'Ley 1620/2013 - Manual de Convivencia',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'alta',
                'enunciado': 'La Guía 49 del MEN describe los estilos docentes relacionados con la convivencia. El estilo "asertivo/democrático" se caracteriza por:',
                'opcion_a': 'Alto nivel de estructura y bajo nivel de cuidado.',
                'opcion_b': 'Alto nivel de cuidado y bajo nivel de estructura.',
                'opcion_c': 'Alto nivel de cuidado y alto nivel de estructura, con normas construidas colectivamente.',
                'opcion_d': 'Bajo nivel de cuidado y bajo nivel de estructura.',
                'respuesta_correcta': 'C',
                'justificacion': 'La Guía 49 (MEN) describe cuatro estilos docentes según las dimensiones de cuidado y estructura. El estilo asertivo/democrático combina alto cuidado (preocupación por el bienestar del estudiante) con alta estructura (normas claras y consistentes), favoreciendo el desarrollo de competencias ciudadanas.',
                'fuente_normativa': 'Guía 49 MEN - Estilos docentes / Chaux 2012',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'media',
                'enunciado': 'Las competencias ciudadanas según el MEN colombiano se clasifican en:',
                'opcion_a': 'Solo cognitivas y emocionales.',
                'opcion_b': 'Cognitivas, emocionales, comunicativas e integradoras.',
                'opcion_c': 'Académicas, deportivas y artísticas.',
                'opcion_d': 'Individuales y colectivas exclusivamente.',
                'respuesta_correcta': 'B',
                'justificacion': 'Los EBC de Competencias Ciudadanas (MEN 2004) clasifican las competencias en: cognitivas (toma de perspectiva, pensamiento crítico), emocionales (manejo de emociones, empatía), comunicativas (escucha activa, asertividad) e integradoras (que articulan las anteriores en acción ciudadana).',
                'fuente_normativa': 'MEN - EBC Competencias Ciudadanas 2004',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'alta',
                'enunciado': 'Un docente de ciencias sociales nota que en su grupo hay exclusión sistemática hacia un estudiante por su origen étnico. Desde la Ley 1620 y las competencias ciudadanas, la acción más pertinente es:',
                'opcion_a': 'Ignorar la situación porque ocurre entre estudiantes y no es responsabilidad del docente.',
                'opcion_b': 'Implementar estrategias pedagógicas para el desarrollo de empatía y perspectiva, activar la ruta de atención Tipo I y trabajar la valoración de la diversidad como proyecto transversal.',
                'opcion_c': 'Sancionar a los estudiantes que excluyen con nota deficiente en convivencia.',
                'opcion_d': 'Cambiar al estudiante excluido de grupo para evitar el conflicto.',
                'respuesta_correcta': 'B',
                'justificacion': 'La exclusión por origen étnico es una Situación Tipo I que el docente debe atender pedagógicamente. Las estrategias de desarrollo de empatía, perspectiva y valoración de la diversidad son la respuesta formativa. La Ley 1620 prioriza el enfoque preventivo y formativo sobre el punitivo.',
                'fuente_normativa': 'Ley 1620/2013 - MEN EBC Competencias Ciudadanas',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'media',
                'enunciado': 'El matoneo o bullying según la Ley 1620 de 2013 se define como:',
                'opcion_a': 'Cualquier conflicto entre estudiantes dentro de la institución.',
                'opcion_b': 'Conducta negativa, intencional, metódica y sistemática de agresión, intimidación o exclusión hacia un estudiante por parte de uno o más compañeros.',
                'opcion_c': 'Una sola agresión física grave que requiere expulsión.',
                'opcion_d': 'Los conflictos verbales ocasionales entre compañeros.',
                'respuesta_correcta': 'B',
                'justificacion': 'La Ley 1620/2013 distingue el bullying del conflicto ordinario por sus características: es intencional, sistemático (se repite en el tiempo), hay desequilibrio de poder, y busca intimidar, aislar o agredir. Un solo incidente no constituye bullying.',
                'fuente_normativa': 'Ley 1620 de 2013 - Definición de bullying',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'alta',
                'enunciado': 'El Decreto 1965 de 2013 que reglamenta la Ley 1620 establece que ante una situación Tipo III (posible delito), el docente debe:',
                'opcion_a': 'Resolver el caso internamente para proteger la imagen institucional.',
                'opcion_b': 'Activar la ruta de atención, reportar al Comité de Convivencia, garantizar atención en salud si hay lesiones, y poner en conocimiento de las autoridades competentes (Policía, ICBF, Fiscalía).',
                'opcion_c': 'Esperar la decisión del rector antes de tomar cualquier medida.',
                'opcion_d': 'Mediar directamente entre las partes para evitar escalar el conflicto.',
                'respuesta_correcta': 'B',
                'justificacion': 'Las situaciones Tipo III (violencia sexual, lesiones graves, porte de armas, tráfico de sustancias) son posibles delitos que deben reportarse a autoridades externas. El docente o directivo que oculte estas situaciones puede incurrir en responsabilidad legal.',
                'fuente_normativa': 'Decreto 1965/2013 - Art. 42 - Situaciones Tipo III',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'media',
                'enunciado': 'El aprendizaje "haciendo" como principio pedagógico para el desarrollo de competencias ciudadanas significa:',
                'opcion_a': 'Que los estudiantes aprenden ciudadanía mediante discursos morales del docente.',
                'opcion_b': 'Que las competencias ciudadanas se desarrollan practicándolas en situaciones reales o simuladas dentro del aula y la institución.',
                'opcion_c': 'Que la educación ciudadana solo ocurre en las salidas pedagógicas.',
                'opcion_d': 'Que la teoría es suficiente para desarrollar competencias ciudadanas.',
                'respuesta_correcta': 'B',
                'justificacion': 'La Guía 49 del MEN retoma a Chaux (2012): las competencias ciudadanas se desarrollan practicándolas, no escuchando discursos. El aula es el laboratorio de ciudadanía: resolver conflictos reales, tomar decisiones colectivas, ejercer el gobierno escolar son prácticas ciudadanas auténticas.',
                'fuente_normativa': 'Guía 49 MEN - Chaux 2012 - Aprender haciendo',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'alta',
                'enunciado': 'El gobierno escolar establecido en la Ley 115 de 1994 incluye el Consejo Estudiantil como espacio de participación democrática. En relación con la convivencia, su función es:',
                'opcion_a': 'Solo elegir al personero y al representante al Consejo Directivo.',
                'opcion_b': 'Participar activamente en la construcción del manual de convivencia, representar los intereses estudiantiles y proponer iniciativas para mejorar la convivencia institucional.',
                'opcion_c': 'Sancionar a los estudiantes que violen el manual de convivencia.',
                'opcion_d': 'Supervisar el cumplimiento del horario por parte de los docentes.',
                'respuesta_correcta': 'B',
                'justificacion': 'El Consejo Estudiantil (Ley 115/1994 Art. 94) y la Ley 1620/2013 reconocen a los estudiantes como actores clave de la convivencia. Su participación en la construcción del manual y en la propuesta de iniciativas de convivencia desarrolla competencias ciudadanas y genera apropiación de las normas.',
                'fuente_normativa': 'Ley 115/1994 Art. 94 - Ley 1620/2013',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'media',
                'enunciado': 'La mediación escolar como estrategia de resolución de conflictos se caracteriza por:',
                'opcion_a': 'La imposición de una solución por parte de una autoridad.',
                'opcion_b': 'La intervención de un tercero neutral que facilita el diálogo entre las partes para que lleguen a un acuerdo voluntario.',
                'opcion_c': 'La aplicación de sanciones disciplinarias a ambas partes en conflicto.',
                'opcion_d': 'La separación permanente de las partes en conflicto.',
                'respuesta_correcta': 'B',
                'justificacion': 'La mediación es un proceso voluntario, confidencial y neutral donde un mediador facilita la comunicación entre las partes para que ellas construyan su propio acuerdo. A diferencia del arbitraje o la sanción, empodera a las partes y desarrolla habilidades de resolución pacífica de conflictos.',
                'fuente_normativa': 'Guía 49 MEN - Mediación escolar / Ley 1620/2013',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'alta',
                'enunciado': 'Según la Ley 1620 de 2013, las instituciones educativas deben incluir en el currículo:',
                'opcion_a': 'Una asignatura obligatoria llamada "Convivencia Escolar" de al menos 2 horas semanales.',
                'opcion_b': 'Educación para el ejercicio de los derechos humanos, sexuales y reproductivos de manera transversal en todas las áreas.',
                'opcion_c': 'Un programa extracurricular de convivencia certificado por el MEN.',
                'opcion_d': 'Solo el área de ética y valores para abordar la convivencia.',
                'respuesta_correcta': 'B',
                'justificacion': 'La Ley 1620/2013 establece que la educación para el ejercicio de DDHH, sexuales y reproductivos debe incluirse de manera transversal en el currículo, no como una asignatura aislada. Esto significa que todos los docentes, independientemente del área, tienen responsabilidad en esta formación.',
                'fuente_normativa': 'Ley 1620 de 2013 - Educación en DDHH transversal',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'media',
                'enunciado': 'El clima escolar positivo se relaciona directamente con:',
                'opcion_a': 'La infraestructura física de la institución exclusivamente.',
                'opcion_b': 'Las relaciones de respeto, confianza y participación entre todos los miembros de la comunidad, que favorecen el aprendizaje y el bienestar.',
                'opcion_c': 'El nivel socioeconómico de los estudiantes.',
                'opcion_d': 'La rigurosidad de las sanciones disciplinarias aplicadas.',
                'respuesta_correcta': 'B',
                'justificacion': 'La investigación (Hattie, Chaux) muestra que el clima escolar es uno de los factores con mayor efecto en el aprendizaje. Un clima de respeto, confianza y participación democrática reduce la violencia, aumenta la motivación y mejora los resultados académicos.',
                'fuente_normativa': 'Guía 49 MEN - Hattie - Clima escolar',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'alta',
                'enunciado': 'Un docente del Decreto 1278 que ante una situación de conflicto en el aula actúa de manera autoritaria (impone la solución sin escuchar) demuestra desde la Guía 31:',
                'opcion_a': 'Alta competencia en gestión de aula por resolver rápido el conflicto.',
                'opcion_b': 'Limitación en la competencia comportamental de negociación y mediación, y en la competencia funcional de comunicación institucional.',
                'opcion_c': 'Cumplimiento del Decreto 1278 que exige disciplina en el aula.',
                'opcion_d': 'Eficiencia pedagógica al optimizar el tiempo de clase.',
                'respuesta_correcta': 'B',
                'justificacion': 'La Guía 31 evalúa competencias comportamentales como negociación y mediación (resolver conflictos de forma colaborativa) y competencias funcionales como comunicación institucional. El docente autoritario que impone soluciones no desarrolla estas competencias ni en sí mismo ni en sus estudiantes.',
                'fuente_normativa': 'Guía 31 MEN - Decreto 1278/2002 - Competencias comportamentales',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'media',
                'enunciado': 'La Ley 1620 de 2013 establece que la ruta de atención integral debe activarse:',
                'opcion_a': 'Solo cuando hay lesiones físicas visibles.',
                'opcion_b': 'Ante cualquier situación que afecte la convivencia escolar o el ejercicio de los derechos humanos, sexuales y reproductivos.',
                'opcion_c': 'Solo cuando el rector lo autorice previamente.',
                'opcion_d': 'Únicamente en situaciones Tipo III que constituyan posibles delitos.',
                'respuesta_correcta': 'B',
                'justificacion': 'La ruta de atención integral aplica para todos los tipos de situación (I, II y III). Incluso las situaciones Tipo I (conflictos cotidianos) tienen su protocolo de atención. La diferencia está en quién la activa y qué instancias participan según la gravedad.',
                'fuente_normativa': 'Ley 1620/2013 - Decreto 1965/2013 - Ruta integral',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'alta',
                'enunciado': 'El enfoque de derechos humanos en la convivencia escolar implica que las normas del manual de convivencia deben:',
                'opcion_a': 'Priorizar el cumplimiento de obligaciones sobre el reconocimiento de derechos.',
                'opcion_b': 'Fundamentarse en los DDHH, garantizar el debido proceso, ser construidas participativamente y orientarse a la formación integral más que a la sanción.',
                'opcion_c': 'Ser diseñadas exclusivamente por los directivos docentes.',
                'opcion_d': 'Prohibir toda forma de conflicto en la institución.',
                'respuesta_correcta': 'B',
                'justificacion': 'La Ley 1620/2013 adopta el enfoque de derechos: las normas escolares deben fundamentarse en DDHH, respetar el debido proceso en las sanciones, ser construidas con participación de todos y orientarse a la formación ciudadana. El conflicto no se prohíbe sino que se gestiona pedagógicamente.',
                'fuente_normativa': 'Ley 1620/2013 - Guía 49 MEN - Enfoque de DDHH',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'media',
                'enunciado': 'El proyecto de Educación para la Sexualidad y Construcción de Ciudadanía (PESCC) en Colombia se implementa porque:',
                'opcion_a': 'Es una materia obligatoria del currículo nacional.',
                'opcion_b': 'La educación sexual es un derecho que debe abordarse de forma integral, transversal y participativa para el desarrollo de competencias ciudadanas y la prevención de violencias.',
                'opcion_c': 'Solo aplica para grados 9°, 10° y 11°.',
                'opcion_d': 'Es un programa externo al PEI que implementan las EPS.',
                'respuesta_correcta': 'B',
                'justificacion': 'El PESCC (MEN) aborda la sexualidad como dimensión fundamental del desarrollo humano y la ciudadanía. Se implementa de forma transversal en todos los grados y áreas, articulado con el PEI, y busca desarrollar competencias para el ejercicio responsable de los derechos sexuales y reproductivos.',
                'fuente_normativa': 'Ley 1620/2013 - PESCC MEN',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'alta',
                'enunciado': 'La Guía 49 del MEN señala que el principal indicador de un buen clima escolar en el aula es:',
                'opcion_a': 'La ausencia total de conflictos entre estudiantes.',
                'opcion_b': 'La capacidad de la comunidad para gestionar constructivamente los conflictos, mantener relaciones de respeto y garantizar participación de todos.',
                'opcion_c': 'El número de sanciones disciplinarias aplicadas durante el año.',
                'opcion_d': 'Los resultados en pruebas Saber de convivencia.',
                'respuesta_correcta': 'B',
                'justificacion': 'La Guía 49 plantea que el conflicto es inherente a la vida social y no debe eliminarse sino gestionarse constructivamente. Un buen clima escolar no se mide por ausencia de conflictos sino por la capacidad de la comunidad de resolverlos pacíficamente y aprender de ellos.',
                'fuente_normativa': 'Guía 49 MEN - Clima escolar',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'media',
                'enunciado': 'El papel del personero estudiantil en el marco de la Ley 1620 de 2013 es:',
                'opcion_a': 'Aplicar sanciones a los estudiantes que violen el manual de convivencia.',
                'opcion_b': 'Promover el ejercicio de los derechos y deberes de los estudiantes, participar en el Comité de Convivencia y ser vocero de las necesidades estudiantiles.',
                'opcion_c': 'Supervisar el trabajo de los docentes en el aula.',
                'opcion_d': 'Elaborar el manual de convivencia sin participación de otros estamentos.',
                'respuesta_correcta': 'B',
                'justificacion': 'El personero estudiantil (Ley 115/1994 Art. 94 y Ley 1620/2013) es el representante de los derechos estudiantiles. Forma parte del Comité de Convivencia, promueve el ejercicio de derechos y deberes y es un agente de cultura democrática en la institución.',
                'fuente_normativa': 'Ley 115/1994 Art. 94 - Ley 1620/2013',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'alta',
                'enunciado': 'Cuando un docente observa que un estudiante presenta señales de posible abuso sexual (cambios de comportamiento, lesiones inexplicables, expresiones en dibujos), la acción correcta según la Ley 1620 y la Ley 1098 (Código de Infancia) es:',
                'opcion_a': 'Investigar personalmente la situación antes de reportar.',
                'opcion_b': 'Reportar inmediatamente al orientador y al rector para activar la ruta de atención Tipo III, que incluye notificación al ICBF y a las autoridades competentes.',
                'opcion_c': 'Hablar con los padres para que resuelvan la situación en casa.',
                'opcion_d': 'Esperar más señales antes de actuar para no hacer una denuncia equivocada.',
                'respuesta_correcta': 'B',
                'justificacion': 'El Código de Infancia (Ley 1098/2006) y la Ley 1620/2013 establecen que todo docente es agente del sistema de protección. Ante sospecha de abuso, el docente no investiga sino que reporta inmediatamente. La demora puede agravar el daño al menor.',
                'fuente_normativa': 'Ley 1620/2013 - Ley 1098/2006 - Ruta Tipo III',
            },
            {
                'componente': 'pedagogico', 'dificultad': 'media',
                'enunciado': 'La corresponsabilidad en la convivencia escolar según la Ley 1620 de 2013 implica que:',
                'opcion_a': 'Solo los docentes son responsables de la convivencia escolar.',
                'opcion_b': 'La familia, la sociedad, el Estado y la institución comparten la responsabilidad de formar en convivencia y proteger los derechos de los estudiantes.',
                'opcion_c': 'Los estudiantes son los únicos responsables de la convivencia en el aula.',
                'opcion_d': 'La responsabilidad es exclusiva del orientador escolar.',
                'respuesta_correcta': 'B',
                'justificacion': 'La Ley 1620/2013 adopta el principio de corresponsabilidad: la familia, la sociedad, el Estado (en todos sus niveles) y la institución educativa comparten la responsabilidad de garantizar la convivencia escolar y el pleno ejercicio de derechos.',
                'fuente_normativa': 'Ley 1620 de 2013 - Principio de corresponsabilidad',
            },
        ]

    def _preguntas_sesion8(self):
        return [
            {
                'componente': 'normativo', 'dificultad': 'media',
                'enunciado': 'La Ley 115 de 1994 (Ley General de Educación) se fundamenta en el artículo constitucional que establece:',
                'opcion_a': 'El derecho al trabajo como base del desarrollo económico.',
                'opcion_b': 'El derecho a la educación como derecho fundamental de la persona y un servicio público con función social.',
                'opcion_c': 'La obligatoriedad de la educación religiosa en todas las instituciones.',
                'opcion_d': 'La privatización del servicio educativo como política de calidad.',
                'respuesta_correcta': 'B',
                'justificacion': 'La Ley 115/1994 se fundamenta en el Art. 67 de la Constitución Política de Colombia, que establece la educación como derecho fundamental y servicio público con función social. Este artículo es la base constitucional de toda la política educativa colombiana.',
                'fuente_normativa': 'Ley 115 de 1994 - Art. 1 / Constitución Art. 67',
            },
            {
                'componente': 'normativo', 'dificultad': 'alta',
                'enunciado': 'El Art. 5 de la Ley 115 de 1994 establece los fines de la educación colombiana. ¿Cuál de los siguientes corresponde a uno de esos fines?',
                'opcion_a': 'La formación exclusivamente técnica y laboral para el mercado productivo.',
                'opcion_b': 'El pleno desarrollo de la personalidad sin más limitaciones que las que le imponen los derechos de los demás.',
                'opcion_c': 'La transmisión de la cultura nacional sin modificaciones.',
                'opcion_d': 'La preparación exclusiva para el acceso a la educación superior.',
                'respuesta_correcta': 'B',
                'justificacion': 'El Art. 5 Numeral 1 establece como fin el "pleno desarrollo de la personalidad sin más limitaciones que las que le imponen los derechos de los demás". Los 13 fines abarcan desarrollo personal, formación ciudadana, cultura, ciencia, trabajo, salud y democracia.',
                'fuente_normativa': 'Ley 115 de 1994 - Art. 5 Numeral 1',
            },
            {
                'componente': 'normativo', 'dificultad': 'media',
                'enunciado': 'Según la Ley 115 de 1994, la educación formal en Colombia se organiza en:',
                'opcion_a': 'Preescolar, básica, media y universitaria.',
                'opcion_b': 'Preescolar (3 grados), educación básica (9 grados: primaria y secundaria) y educación media (2 grados).',
                'opcion_c': 'Primaria (5 grados), bachillerato (6 grados) y técnico (2 grados).',
                'opcion_d': 'Inicial, básica y superior.',
                'respuesta_correcta': 'B',
                'justificacion': 'La Ley 115/1994 organiza la educación formal en: preescolar (3 grados: prejardín, jardín, transición), básica primaria (grados 1-5), básica secundaria (grados 6-9) y media (grados 10-11). La educación superior la regula la Ley 30 de 1992.',
                'fuente_normativa': 'Ley 115 de 1994 - Art. 11',
            },
            {
                'componente': 'normativo', 'dificultad': 'alta',
                'enunciado': 'El Art. 92 de la Ley 115 de 1994 establece que la formación del educando debe favorecer:',
                'opcion_a': 'La memorización de contenidos académicos como base del desarrollo.',
                'opcion_b': 'El pleno desarrollo de la personalidad, la formación para la participación ciudadana, la autonomía y la capacidad de decisión.',
                'opcion_c': 'La obediencia a las normas institucionales sin cuestionamiento.',
                'opcion_d': 'Exclusivamente el desarrollo de competencias laborales.',
                'respuesta_correcta': 'B',
                'justificacion': 'El Art. 92 establece que la educación debe favorecer el pleno desarrollo de la personalidad del educando, dar acceso a la cultura, al logro del conocimiento científico y técnico, y a la formación de valores éticos, estéticos, morales, ciudadanos y religiosos.',
                'fuente_normativa': 'Ley 115 de 1994 - Art. 92',
            },
            {
                'componente': 'normativo', 'dificultad': 'media',
                'enunciado': 'La autonomía escolar consagrada en el Art. 77 de la Ley 115 de 1994 permite a las instituciones:',
                'opcion_a': 'Desconocer los lineamientos nacionales del MEN.',
                'opcion_b': 'Organizar las áreas del conocimiento, adoptar métodos de enseñanza y administrar su labor dentro del marco de la ley.',
                'opcion_c': 'Definir sus propios fines de la educación independientes del Art. 5.',
                'opcion_d': 'Contratar docentes sin cumplir el Decreto 1278.',
                'respuesta_correcta': 'B',
                'justificacion': 'La autonomía escolar (Art. 77) permite a las IE organizar áreas, adoptar métodos, seleccionar textos, adaptar el currículo al contexto. Es autonomía regulada: dentro de los fines nacionales, los EBC y la normatividad vigente. No es autonomía absoluta.',
                'fuente_normativa': 'Ley 115 de 1994 - Art. 77',
            },
            {
                'componente': 'normativo', 'dificultad': 'alta',
                'enunciado': 'El currículo, según la Ley 115 de 1994 y el Decreto 1860 de 1994, se entiende como:',
                'opcion_a': 'El listado de materias y sus contenidos para cada grado.',
                'opcion_b': 'El conjunto de criterios, planes de estudio, programas, metodologías y procesos que contribuyen a la formación integral y a la identidad cultural.',
                'opcion_c': 'Solo el plan de estudios oficial aprobado por el MEN.',
                'opcion_d': 'Los libros de texto autorizados para cada área.',
                'respuesta_correcta': 'B',
                'justificacion': 'El Art. 76 de la Ley 115/1994 define currículo como el conjunto de criterios, planes de estudio, programas, metodologías y procesos para la formación integral. Es mucho más amplio que un listado de contenidos: incluye la cultura institucional y el proyecto formativo.',
                'fuente_normativa': 'Ley 115 de 1994 - Art. 76',
            },
            {
                'componente': 'normativo', 'dificultad': 'media',
                'enunciado': 'La jornada escolar obligatoria mínima en Colombia para educación básica y media, según la normatividad vigente, es de:',
                'opcion_a': '4 horas diarias.',
                'opcion_b': '6 horas diarias (jornada única como meta progresiva del MEN).',
                'opcion_c': '8 horas diarias incluyendo almuerzo.',
                'opcion_d': '3 horas diarias para básica primaria.',
                'respuesta_correcta': 'B',
                'justificacion': 'La Ley 1753 de 2015 (Plan Nacional de Desarrollo) estableció la Jornada Única como meta progresiva para mejorar la calidad educativa. El Decreto 501 de 2016 reglamenta la implementación progresiva hacia las 6-7 horas diarias de trabajo académico.',
                'fuente_normativa': 'Ley 1753/2015 - Decreto 501/2016 - Jornada Única',
            },
            {
                'componente': 'normativo', 'dificultad': 'alta',
                'enunciado': 'El gobierno escolar establecido en la Ley 115 de 1994 debe ser conformado por:',
                'opcion_a': 'Solo el rector y los coordinadores.',
                'opcion_b': 'El Consejo Directivo, el Consejo Académico y el rector, con participación de representantes de estudiantes, padres, docentes y egresados.',
                'opcion_c': 'La Secretaría de Educación y los directivos docentes.',
                'opcion_d': 'El MEN y los rectores de cada institución.',
                'respuesta_correcta': 'B',
                'justificacion': 'El Art. 142 de la Ley 115/1994 establece que el gobierno escolar está conformado por el rector (representante legal), el Consejo Directivo (directivos, docentes, padres, estudiantes, ex-alumnos, sector productivo) y el Consejo Académico (rector y jefes de área).',
                'fuente_normativa': 'Ley 115 de 1994 - Art. 142, 143, 144',
            },
            {
                'componente': 'normativo', 'dificultad': 'media',
                'enunciado': 'Según la Ley 115 de 1994, la educación no formal (hoy denominada educación para el trabajo y el desarrollo humano) tiene como objetivo:',
                'opcion_a': 'Reemplazar la educación básica para personas que no pueden asistir a la escuela.',
                'opcion_b': 'Complementar, actualizar, suplir y formar en aspectos académicos o laborales sin sujeción al sistema de niveles y grados de la educación formal.',
                'opcion_c': 'Otorgar títulos de bachiller a adultos mayores de 18 años.',
                'opcion_d': 'Preparar exclusivamente para el trabajo artesanal.',
                'respuesta_correcta': 'B',
                'justificacion': 'La Ley 115/1994 (Art. 36) define la educación no formal como aquella que se ofrece con el objeto de complementar, actualizar, suplir conocimientos y formar en aspectos académicos o laborales, sin sujeción a los niveles y grados del sistema educativo formal.',
                'fuente_normativa': 'Ley 115 de 1994 - Art. 36',
            },
            {
                'componente': 'normativo', 'dificultad': 'alta',
                'enunciado': 'El Art. 104 de la Ley 115 de 1994 define al educador como:',
                'opcion_a': 'Un funcionario público con obligación de cumplir horarios.',
                'opcion_b': 'El orientador en los procesos de formación, enseñanza y aprendizaje, contribuyendo al desarrollo integral del educando.',
                'opcion_c': 'Un transmisor de conocimientos disciplinares acumulados.',
                'opcion_d': 'Un evaluador de competencias según los estándares del MEN.',
                'respuesta_correcta': 'B',
                'justificacion': 'El Art. 104 define al educador como el orientador en los procesos de formación, enseñanza y aprendizaje de los educandos, contribuyendo a su desarrollo humano, integral, cultural y comunitario. Esta definición trasciende la transmisión de contenidos.',
                'fuente_normativa': 'Ley 115 de 1994 - Art. 104',
            },
            {
                'componente': 'normativo', 'dificultad': 'media',
                'enunciado': 'La educación básica en Colombia según la Ley 115 es obligatoria para:',
                'opcion_a': 'Solo los niños entre 5 y 10 años.',
                'opcion_b': 'Los niños de 6 a 15 años (9 grados de educación básica).',
                'opcion_c': 'Todos los menores de 18 años sin excepción.',
                'opcion_d': 'Solo quienes vivan a menos de 2 km de una institución educativa.',
                'respuesta_correcta': 'B',
                'justificacion': 'La Ley 115/1994 establece que la educación básica (9 grados: primaria y secundaria) es obligatoria para las personas entre 6 y 15 años. El Estado debe garantizar condiciones para que toda la población en edad escolar acceda a la educación básica gratuita.',
                'fuente_normativa': 'Ley 115 de 1994 - Art. 17 y 18',
            },
            {
                'componente': 'normativo', 'dificultad': 'alta',
                'enunciado': 'El plan de estudios según la Ley 115 de 1994 debe incluir:',
                'opcion_a': 'Solo el listado de áreas y sus intensidades horarias.',
                'opcion_b': 'La estructura de las áreas obligatorias y optativas, la distribución del tiempo, los logros, los indicadores de logros, los lineamientos pedagógicos y los procesos de evaluación.',
                'opcion_c': 'Exclusivamente lo que dicte el MEN sin adaptaciones institucionales.',
                'opcion_d': 'Solo los objetivos generales por área sin especificaciones por grado.',
                'respuesta_correcta': 'B',
                'justificacion': 'El Art. 79 de la Ley 115/1994 define el plan de estudios como el esquema estructurado de áreas obligatorias y optativas con sus respectivas asignaturas, que forma parte del currículo. Debe incluir la forma de evaluación, los métodos pedagógicos y los logros esperados.',
                'fuente_normativa': 'Ley 115 de 1994 - Art. 79',
            },
            {
                'componente': 'normativo', 'dificultad': 'media',
                'enunciado': 'La Ley 115 de 1994 establece que los padres de familia tienen derecho a:',
                'opcion_a': 'Diseñar el currículo de la institución sin consultar a los docentes.',
                'opcion_b': 'Escoger el tipo de educación para sus hijos, participar en el gobierno escolar y ser informados sobre el rendimiento académico y convivencia de sus hijos.',
                'opcion_c': 'Determinar qué áreas deben suprimirse del plan de estudios.',
                'opcion_d': 'Contratar y despedir docentes de la institución donde estudian sus hijos.',
                'respuesta_correcta': 'B',
                'justificacion': 'La Ley 115/1994 (Art. 7) establece que la familia tiene derecho a escoger el tipo de educación para sus hijos, a participar en el gobierno escolar y a ser informada del proceso educativo. También tiene deberes: matricularlos, apoyar el proceso formativo y cumplir las normas.',
                'fuente_normativa': 'Ley 115 de 1994 - Art. 7',
            },
            {
                'componente': 'normativo', 'dificultad': 'alta',
                'enunciado': 'La educación media técnica, según la Ley 115 de 1994, se orienta a:',
                'opcion_a': 'Reemplazar la educación superior para quienes no pueden acceder a la universidad.',
                'opcion_b': 'La preparación para el trabajo mediante la profundización en un área técnica o vocacional, sin cerrar el acceso a la educación superior.',
                'opcion_c': 'La formación exclusiva de operarios para la industria sin componente académico.',
                'opcion_d': 'Reducir el currículo a solo las áreas técnicas eliminando las humanidades.',
                'respuesta_correcta': 'B',
                'justificacion': 'Los Art. 27 y 32 de la Ley 115/1994 definen la educación media técnica como la que prepara para el trabajo en sectores de la producción y los servicios, con formación en competencias básicas, ciudadanas y laborales. El título de bachiller técnico permite acceso a la educación superior.',
                'fuente_normativa': 'Ley 115 de 1994 - Art. 27, 32',
            },
            {
                'componente': 'normativo', 'dificultad': 'media',
                'enunciado': 'El Decreto 1075 de 2015, conocido como Decreto Único Reglamentario del Sector Educación, tiene como propósito:',
                'opcion_a': 'Crear nuevas normas educativas para reemplazar la Ley 115.',
                'opcion_b': 'Compilar y racionalizar las normas reglamentarias del sector educativo en un solo decreto para facilitar su consulta y aplicación.',
                'opcion_c': 'Establecer el estatuto docente de los educadores vinculados antes de 2002.',
                'opcion_d': 'Regular exclusivamente la educación superior en Colombia.',
                'respuesta_correcta': 'B',
                'justificacion': 'El Decreto 1075/2015 es un decreto compilatorio que reúne las normas reglamentarias del sector educación en un único instrumento. No crea nuevas normas sino que organiza las existentes. Facilita la consulta de la regulación educativa sin tener que revisar decenas de decretos separados.',
                'fuente_normativa': 'Decreto 1075 de 2015',
            },
            {
                'componente': 'normativo', 'dificultad': 'alta',
                'enunciado': 'Según la Ley 115 de 1994, los proyectos pedagógicos transversales obligatorios incluyen:',
                'opcion_a': 'Solo el proyecto de lectoescritura y matemáticas.',
                'opcion_b': 'Educación sexual, uso del tiempo libre, aprovechamiento del medio ambiente, educación para la democracia y prevención de desastres.',
                'opcion_c': 'Exclusivamente los proyectos que defina cada institución en su PEI.',
                'opcion_d': 'Solo los proyectos financiados por el MEN.',
                'respuesta_correcta': 'B',
                'justificacion': 'El Art. 14 de la Ley 115/1994 establece como obligatoria la enseñanza transversal de: estudio y comprensión de la Constitución, educación sexual, uso del tiempo libre, protección del ambiente y educación para la justicia y la democracia. Estos temas no son asignaturas sino ejes transversales.',
                'fuente_normativa': 'Ley 115 de 1994 - Art. 14',
            },
            {
                'componente': 'normativo', 'dificultad': 'media',
                'enunciado': 'La evaluación institucional anual de la institución educativa, diferente a la evaluación de los estudiantes, tiene como propósito:',
                'opcion_a': 'Evaluar el desempeño individual de cada docente.',
                'opcion_b': 'Reflexionar colectivamente sobre los logros y dificultades de la gestión institucional para mejorar el PEI y el plan de mejoramiento.',
                'opcion_c': 'Determinar si la institución puede seguir funcionando.',
                'opcion_d': 'Comparar la institución con otras para establecer un ranking.',
                'respuesta_correcta': 'B',
                'justificacion': 'La evaluación institucional (Ley 115/1994 Art. 84 y Decreto 1860/1994) es un proceso de autoevaluación anual donde la comunidad educativa reflexiona sobre los resultados de la gestión para mejorar. Es el insumo para el Plan de Mejoramiento Institucional (PMI).',
                'fuente_normativa': 'Ley 115/1994 Art. 84 - MEN Guía 34',
            },
            {
                'componente': 'normativo', 'dificultad': 'alta',
                'enunciado': 'Según la Ley 115 de 1994, la educación de adultos tiene como objetivo:',
                'opcion_a': 'Ofrecer exactamente el mismo currículo de la educación regular comprimido en menos tiempo.',
                'opcion_b': 'Suplir y complementar la educación de personas que por razones de edad no han podido cursarla en los niveles y grados establecidos, reconociendo su experiencia de vida.',
                'opcion_c': 'Preparar exclusivamente para el trabajo técnico sin formación ciudadana.',
                'opcion_d': 'Solo certificar saberes informales mediante pruebas del ICFES.',
                'respuesta_correcta': 'B',
                'justificacion': 'Los Art. 50-57 de la Ley 115/1994 regulan la educación de adultos como aquella que suple y complementa la educación de quienes no pudieron cursarla en edad escolar. Debe reconocer la experiencia de vida como aprendizaje significativo y ofrecer metodologías flexibles.',
                'fuente_normativa': 'Ley 115 de 1994 - Art. 50-57',
            },
            {
                'componente': 'normativo', 'dificultad': 'media',
                'enunciado': 'El rector de una institución educativa oficial tiene como función principal según la Ley 115 de 1994:',
                'opcion_a': 'Impartir clases en las áreas donde hay déficit de docentes.',
                'opcion_b': 'Dirigir y administrar la institución, representarla legalmente, coordinar los diferentes estamentos del gobierno escolar y garantizar el cumplimiento del PEI.',
                'opcion_c': 'Diseñar el currículo sin consultar al Consejo Académico.',
                'opcion_d': 'Contratar y despedir docentes de manera autónoma.',
                'respuesta_correcta': 'B',
                'justificacion': 'Los Art. 25 y 126 del Decreto 1860/1994 definen las funciones del rector: representar legalmente la institución, dirigirla, coordinar el gobierno escolar, administrar los recursos y velar por el cumplimiento del PEI. Es el responsable máximo del proyecto educativo.',
                'fuente_normativa': 'Ley 115/1994 - Decreto 1860/1994 - Art. 25',
            },
            {
                'componente': 'normativo', 'dificultad': 'alta',
                'enunciado': 'La relación entre la Ley 115 de 1994 y el Decreto 1278 de 2002 es que:',
                'opcion_a': 'El Decreto 1278 reemplaza la Ley 115 en todo lo relacionado con docentes.',
                'opcion_b': 'La Ley 115 define los fines y la estructura del sistema educativo; el Decreto 1278 regula el estatuto de los docentes vinculados desde 2002 como parte del sistema.',
                'opcion_c': 'Son normas independientes sin relación entre sí.',
                'opcion_d': 'El Decreto 1278 solo aplica a los docentes de educación media.',
                'respuesta_correcta': 'B',
                'justificacion': 'La Ley 115/1994 es la norma macro del sistema educativo colombiano (fines, estructura, gobierno). El Decreto 1278/2002 es una norma específica que regula el estatuto de profesionalización de los docentes vinculados después de 2002, subordinado a los fines de la Ley 115.',
                'fuente_normativa': 'Ley 115/1994 - Decreto 1278 de 2002',
            },
            {
                'componente': 'normativo', 'dificultad': 'media',
                'enunciado': 'El área de educación religiosa en las instituciones educativas colombianas según la Ley 115 es:',
                'opcion_a': 'Obligatoria para todos los estudiantes sin excepción.',
                'opcion_b': 'Obligatoria en el currículo pero con reserva de conciencia: ningún estudiante puede ser obligado a recibirla en contra de su voluntad o la de sus padres.',
                'opcion_c': 'Optativa y puede suprimirse si el Consejo Directivo lo decide.',
                'opcion_d': 'Solo permitida en instituciones de carácter confesional.',
                'respuesta_correcta': 'B',
                'justificacion': 'El Art. 24 de la Ley 115/1994 establece la educación religiosa como parte de las áreas obligatorias pero garantiza el derecho a la libertad de conciencia y culto. Ningún estudiante puede ser obligado a recibirla en contra de su voluntad y la de sus padres.',
                'fuente_normativa': 'Ley 115 de 1994 - Art. 24',
            },
            {
                'componente': 'normativo', 'dificultad': 'alta',
                'enunciado': 'El Decreto 1290 de 2009 modifica la evaluación de los aprendizajes establecida en el Decreto 230 de 2002, principalmente porque:',
                'opcion_a': 'Vuelve a las calificaciones numéricas del 1 al 10.',
                'opcion_b': 'Elimina la promoción automática y devuelve autonomía a las instituciones para definir su SIEE y sus criterios de promoción.',
                'opcion_c': 'Unifica la escala de valoración nacional como único sistema posible.',
                'opcion_d': 'Elimina la evaluación formativa para fortalecer la sumativa.',
                'respuesta_correcta': 'B',
                'justificacion': 'El Decreto 230/2002 obligaba a promover al 95% de los estudiantes automáticamente, lo que fue muy criticado. El Decreto 1290/2009 deroga esa obligación y devuelve autonomía a las IE para definir sus criterios de evaluación y promoción en el SIEE, manteniendo la escala nacional como referente.',
                'fuente_normativa': 'Decreto 1290/2009 - Deroga Decreto 230/2002',
            },
            {
                'componente': 'normativo', 'dificultad': 'media',
                'enunciado': 'La Resolución 3842 de 2022 del MEN establece el Manual de Funciones para los cargos docentes y directivos docentes. Su importancia para el concurso docente radica en que:',
                'opcion_a': 'Determina el salario base de los docentes según el grado del escalafón.',
                'opcion_b': 'Define las funciones, requisitos y competencias requeridas para cada cargo, siendo la base para la evaluación en el concurso de méritos.',
                'opcion_c': 'Establece el horario laboral obligatorio de docentes y directivos.',
                'opcion_d': 'Determina el número máximo de estudiantes por aula en cada municipio.',
                'respuesta_correcta': 'B',
                'justificacion': 'La Resolución 3842/2022 es fundamental para el concurso porque define las competencias funcionales y comportamentales evaluadas en la entrevista (5% del puntaje). Los concursantes deben conocer las funciones específicas del cargo al que aspiran.',
                'fuente_normativa': 'Resolución 3842 de 2022 - Manual de Funciones',
            },
            {
                'componente': 'normativo', 'dificultad': 'alta',
                'enunciado': 'Según la Ley 115 de 1994, el concepto de calidad educativa implica:',
                'opcion_a': 'Que todas las instituciones obtengan los mismos resultados en pruebas estandarizadas.',
                'opcion_b': 'La formación integral del educando que desarrolla competencias para la vida, la ciudadanía y el trabajo en un marco de equidad y pertinencia cultural.',
                'opcion_c': 'La adquisición de tecnología de última generación por parte de las instituciones.',
                'opcion_d': 'El cumplimiento estricto de los horarios y el calendario escolar.',
                'respuesta_correcta': 'B',
                'justificacion': 'La calidad educativa en Colombia (Ley 115/1994, Plan Decenal) se entiende como formación integral: desarrollo de competencias básicas, ciudadanas y laborales con equidad, pertinencia cultural y contextual. No se reduce a resultados en pruebas estandarizadas.',
                'fuente_normativa': 'Ley 115/1994 - MEN - Plan Decenal de Educación',
            },
            {
                'componente': 'normativo', 'dificultad': 'media',
                'enunciado': 'El concepto de "servicio educativo" en la Ley 115 de 1994 incluye:',
                'opcion_a': 'Solo la educación formal en instituciones oficiales.',
                'opcion_b': 'La educación formal, no formal e informal, prestada por el Estado, los particulares y la comunidad.',
                'opcion_c': 'Únicamente la educación privada con ánimo de lucro.',
                'opcion_d': 'Solo los niveles de básica y media.',
                'respuesta_correcta': 'B',
                'justificacion': 'El Art. 2 de la Ley 115/1994 establece que el servicio educativo comprende la educación formal (instituciones educativas), no formal (educación para el trabajo) e informal (familia, medios, comunidad). Es prestado por el Estado, por particulares y por las comunidades.',
                'fuente_normativa': 'Ley 115 de 1994 - Art. 2',
            },
            {
                'componente': 'normativo', 'dificultad': 'alta',
                'enunciado': 'Desde la perspectiva del concurso docente CNSC, demostrar conocimiento de la Ley 115 de 1994 es fundamental porque:',
                'opcion_a': 'Es la única ley que el docente necesita conocer para ejercer su profesión.',
                'opcion_b': 'Es el marco normativo general que orienta todos los procesos educativos y pedagógicos en los que el docente participa cotidianamente.',
                'opcion_c': 'El concurso evalúa exclusivamente la memorización de artículos de la ley.',
                'opcion_d': 'Su desconocimiento implica descalificación automática del concurso.',
                'respuesta_correcta': 'B',
                'justificacion': 'El concurso CNSC evalúa la comprensión y aplicación de la normatividad educativa en situaciones pedagógicas reales. La Ley 115/1994 es el marco rector de la educación colombiana que fundamenta las decisiones pedagógicas, curriculares y de gestión del docente en ejercicio.',
                'fuente_normativa': 'CNSC - Competencias pedagógicas y normativas',
            },
        ]
