# Generated by Django 6.0.5 on 2026-07-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='auth_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='estado_pago',
            field=models.CharField(choices=[('sin_pago', 'Sin pago'), ('pendiente', 'Pendiente'), ('activo', 'Activo'), ('expirado', 'Expirado'), ('rechazado', 'Rechazado')], default='sin_pago', max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_expiracion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='modulo_adquirido',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='usuario',
            name='oauth_provider',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='usuario',
            name='uid',
            field=models.CharField(blank=True, db_index=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='area_concurso',
            field=models.CharField(choices=[('matematicas', 'Matematicas'), ('lenguaje', 'Lenguaje'), ('ciencias_naturales', 'Ciencias Naturales'), ('ciencias_sociales', 'Ciencias Sociales'), ('ingles', 'Ingles'), ('preescolar', 'Preescolar'), ('primaria', 'Primaria'), ('educacion_fisica', 'Educacion Fisica'), ('artistica', 'Educacion Artistica'), ('tecnologia', 'Tecnologia e Informatica'), ('otro', 'Otro')], default='otro', max_length=30, verbose_name='Area del concurso'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='entidad_territorial',
            field=models.CharField(blank=True, max_length=100, verbose_name='Entidad territorial'),
        ),
    ]
