# Generated by Django 6.0.5 on 2026-07-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_auth_email_verified_usuario_estado_pago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='area_concurso',
            field=models.CharField(choices=[('matematicas', 'Matemáticas'), ('lenguaje', 'Lenguaje'), ('ciencias_naturales', 'Ciencias Naturales'), ('ciencias_sociales', 'Ciencias Sociales'), ('ingles', 'Inglés'), ('preescolar', 'Preescolar'), ('primaria', 'Primaria'), ('educacion_fisica', 'Educacion Fisica'), ('artistica', 'Educacion Artistica'), ('tecnologia', 'Tecnología e Informática'), ('otro', 'Otro')], default='otro', max_length=30, verbose_name='Area del concurso'),
        ),
    ]
