# Generated by Django 6.0.5 on 2026-05-18 03:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('single_purchase', 'Compra individual'), ('combo', 'Combo'), ('subscription', 'Suscripción'), ('admin_granted', 'Asignado manualmente')], default='single_purchase', max_length=30)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('expired', 'Expirado'), ('revoked', 'Revocado')], default='active', max_length=20)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to='academics.module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acceso usuario',
                'verbose_name_plural': 'Accesos usuarios',
                'unique_together': {('user', 'module')},
            },
        ),
    ]
