# Generated by Django 6.0.5 on 2026-07-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccess',
            name='access_type',
            field=models.CharField(choices=[('combo', 'Acceso completo'), ('admin_granted', 'Asignado manualmente')], default='combo', max_length=30),
        ),
    ]
