# Generated by Django 6.0.5 on 2026-07-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulo',
            name='tipo',
            field=models.CharField(choices=[('lectura_tjs', 'Lectura Crítica (legacy)'), ('perfil_docente', 'Rol Docente (legacy)'), ('pedagogico', 'Competencias Pedagógicas (legacy)'), ('psicotecnico', 'Análisis de Casos (legacy)'), ('diagnostico_inicial', 'Diagnóstico Inicial'), ('lectura_critica_aplicada', 'Lectura Crítica'), ('normativa_contexto', 'Normatividad Educativa'), ('inclusion_educativa', 'Inclusión Educativa'), ('competencias_pedagogicas', 'Competencias Pedagógicas'), ('competencias_tjs', 'Análisis de Casos'), ('gestion_escolar', 'Gestión Escolar'), ('simulacros_area', 'Competencias Disciplinares'), ('simulacro_final', 'Simulacro Integral'), ('analisis_desempeno', 'Análisis del Desempeño'), ('plan_fortalecimiento', 'Plan de Fortalecimiento')], max_length=30, unique=True),
        ),
    ]
