# Generated by Django 6.0.4 on 2026-05-19 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banco', '0001_initial'),
        ('contenidos', '0001_initial'),
        ('simulacros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Intento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('puntaje_obtenido', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total_correctas', models.PositiveIntegerField(default=0)),
                ('total_incorrectas', models.PositiveIntegerField(default=0)),
                ('simulacro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulacros.simulacro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimiento_intentos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProgresoModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.PositiveIntegerField(default=0)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenidos.modulo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaIntento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta_seleccionada', models.CharField(blank=True, max_length=1, null=True)),
                ('es_correcta', models.BooleanField(default=False)),
                ('intento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='seguimiento.intento')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimiento_respuestas', to='banco.bancopregunta')),
            ],
        ),
    ]
