# Generated by Django 6.0.5 on 2026-07-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intento',
            name='estado',
            field=models.CharField(choices=[('en_curso', 'En curso'), ('completado', 'Completado'), ('abandonado', 'Abandonado')], default='en_curso', max_length=20),
        ),
        migrations.AddField(
            model_name='intento',
            name='reporte_enviado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='intento',
            name='tiempo_usado_segundos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='intento',
            name='total_sin_responder',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='respuestaintento',
            name='respondida_en_tiempo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='respuestaintento',
            name='tiempo_usado_segundos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
