# -*- coding: utf-8 -*-
"""Banco Oficial de Preguntas - Modulo: Analisis de Casos | Tema: Comunicacion
asertiva (Lote 1). Bajo la regla permanente desde Modulo 5: 10 preguntas por
tema (aplica tambien a Modulo 6). Primer lote del modulo con calificacion por
IDONEIDAD GRADUADA (0-4), formato TJS ("MAS/MENOS adecuada"), segun el
esquema documentado en banco/models.py (tipo_item, idoneidad_a..d) y el
Modelo Oro (_resources/banco_oficial/MODELO_ORO_v2.md, Item 5). Contenido
enteramente nuevo, sin reutilizar casos de otros modulos. Dificultad
unicamente Alta y Muy Alta. Proceso cognitivo nivel 3-4 (analisis y juicio
situacional). Mezcla balanceada de tipo_item mas_adecuada/menos_adecuada
(5/5). Contexto de 150-300 palabras por item segun el estandar del Modelo
Oro. Cada item tiene un espectro completo de idoneidad entre sus cuatro
opciones (incluye siempre un 4 y un 0, sin empates entre opciones salvo que
la justificacion explique la equivalencia). respuesta_correcta se fija segun
la regla del Cap. 8.5 del documento maestro: en mas_adecuada, la opcion con
idoneidad 4; en menos_adecuada, la opcion con idoneidad 0. Letra objetivo
planificada por adelantado (A2/B3/C3/D2) y escrita directamente en la
posicion correspondiente desde el primer borrador para evitar sesgo de
distribucion.
"""

CATEGORIA = "Análisis de Casos"
SUBCATEGORIA = "Análisis de Casos - Comunicación asertiva"
COMPETENCIA = "Análisis de casos y competencias comportamentales"
AREA = "psicotecnico"

ITEMS = [
 {
  'codigo': 'MOD06-CA-001',
  'contexto': 'En una institución de Sahagún, la docente Bibiana Salas coordina el área de ciencias sociales desde hace dos años. Durante la reunión mensual de área, un colega con mayor antigüedad en la institución cuestionó en tono elevado, frente al resto del equipo de diez docentes, la forma en que ella había distribuido las horas de acompañamiento a estudiantes con dificultades académicas para el periodo. Calificó la decisión de "improvisada" sin haber revisado antes los criterios técnicos que ella había enviado por escrito una semana atrás junto con la propuesta completa, incluyendo un cuadro comparativo con los históricos de cada grupo. Bibiana notó que el tono del colega generó incomodidad visible en el resto del equipo, y que dos docentes más jóvenes evitaron intervenir en la discusión, bajando la mirada hacia sus documentos. La reunión debía continuar con otros puntos importantes del orden del día, y aún faltaba definir el cronograma de evaluaciones del periodo, un tema que no admitía más demoras porque debía reportarse a coordinación académica esa misma tarde, antes de las cuatro.',
  'enunciado': '¿Cuál es la respuesta MÁS adecuada que puede dar Bibiana ante este cuestionamiento público?',
  'opcion_a': 'Responder con calma, reconociendo el desacuerdo sin igualar el tono elevado, señalar que los criterios fueron enviados por escrito con antelación, y proponer revisarlos en un espacio posterior a la reunión.',
  'opcion_b': 'Ceder de inmediato ante el reclamo y ofrecerse a rehacer la distribución de horas en ese mismo momento de la reunión, para evitar que la discusión con el colega continúe escalando frente al resto del equipo.',
  'opcion_c': 'Pedirle al colega, en el mismo tono elevado, que explique frente a todo el equipo por qué no revisó los criterios técnicos que ella había enviado por escrito antes de calificar la decisión de improvisada.',
  'opcion_d': 'No responder en ese momento al cuestionamiento y continuar de inmediato con el siguiente punto del orden del día, sin aclarar ante el equipo si los criterios técnicos existían o no.',
  'tipo_item': 'mas_adecuada',
  'idoneidad': {'a': 4, 'b': 1, 'c': 2, 'd': 0},
  'respuesta_correcta': 'A',
  'nivel_dificultad': 'alto',
  'proceso_cognitivo': 'evaluacion_juicio',
  'justificacion': 'A obtiene la idoneidad máxima porque responde con firmeza y respeto simultáneos: no iguala el tono elevado del colega, aporta el dato objetivo que desmonta la acusación de improvisación (los criterios ya fueron enviados por escrito), y protege el tiempo de la reunión al proponer un espacio posterior para revisar el desacuerdo de fondo, sin dejar pendientes ni el cronograma de evaluaciones ni la aclaración necesaria frente al equipo.\n\nC (idoneidad 2) es la opción más tentadora porque señala algo cierto (el colega no revisó los criterios antes de opinar), pero lo hace igualando el tono elevado, lo que escala el conflicto en lugar de resolverlo con asertividad.\n\nB (idoneidad 1) cede el criterio técnico bajo presión pública, sin necesidad real de hacerlo, y premia el reclamo hecho en tono inadecuado en lugar de sostener una decisión ya sustentada.\n\nD (idoneidad 0) deja al equipo sin ninguna aclaración sobre si la decisión fue o no técnica, un daño directo a la credibilidad de Bibiana y a la claridad del equipo, aunque evitar el conflicto en el momento sea una reacción comprensible.\n\nError frecuente del aspirante: Confundir asertividad con pasividad (opción D) o con imponer razón en el mismo tono del reclamo (opción C), sin reconocer que la asertividad combina firmeza en el contenido con calma en la forma.\n\nEstrategia mental recomendada: Ante un reclamo público en tono inadecuado, evaluar cuál opción sostiene el criterio técnico con datos objetivos sin igualar el tono agresivo ni evadir la respuesta.\n\nSubcompetencia: Comunicación asertiva bajo presión pública frente a un cuestionamiento de un par con mayor antigüedad',
  'fuente_normativa': 'Ley 1620 de 2013 sobre convivencia escolar, en lo relativo al manejo respetuoso de desacuerdos entre miembros de la comunidad educativa.',
 },
 {
  'codigo': 'MOD06-CA-002',
  'contexto': 'En una institución de Chiquinquirá, el docente Nelson Rico atiende la reunión de entrega de informes académicos con los acudientes de grado noveno, un proceso que se extiende durante toda la tarde con citas cada quince minutos. Un acudiente, visiblemente molesto por la nota de su hijo en el segundo periodo, alza la voz y le dice frente a otros padres presentes en la fila que "los profesores solo buscan rajar a los estudiantes para no tener que explicar bien los temas". Nelson tiene sobre el escritorio la carpeta completa del estudiante con los seguimientos del periodo, las notas de las tres actividades de refuerzo entregadas oportunamente por Nelson pero no realizadas por el estudiante, y el registro de dos citaciones previas a las que el acudiente no había asistido, ambas notificadas por escrito con acuse de recibo firmado. Varios padres en la fila, que aún esperan su turno para ser atendidos, escuchan con atención la conversación que se está dando en voz alta frente a todos.',
  'enunciado': '¿Cuál es la respuesta MENOS adecuada que podría dar Nelson ante este reclamo del acudiente?',
  'opcion_a': 'Responder con calma que entiende la preocupación por la nota, mostrarle el seguimiento del estudiante con las actividades de refuerzo pendientes, y proponer una cita breve más adelante para revisar juntos un plan de apoyo.',
  'opcion_b': 'Reconocer la molestia del acudiente sin aceptar la acusación general sobre los profesores, y mencionar de forma respetuosa que existen citaciones previas a las que no había podido asistir, ofreciendo agendar una nueva.',
  'opcion_c': 'Levantar también la voz frente a los demás padres presentes para decirle al acudiente que su hijo no entrega las actividades de refuerzo y que la responsabilidad de la nota es enteramente suya como padre.',
  'opcion_d': 'Pedirle al acudiente, en tono calmado, que baje un poco la voz porque hay otros padres esperando, y proponerle continuar la conversación sobre la nota en un espacio con más privacidad.',
  'tipo_item': 'menos_adecuada',
  'idoneidad': {'a': 4, 'b': 3, 'c': 0, 'd': 2},
  'respuesta_correcta': 'C',
  'nivel_dificultad': 'muy_alto',
  'proceso_cognitivo': 'evaluacion_juicio',
  'justificacion': 'C tiene la idoneidad más baja porque iguala y supera el tono agresivo del acudiente, expone públicamente ante otros padres una responsabilidad que corresponde tratar en privado, y convierte una queja puntual en un enfrentamiento personal que daña la relación institución-familia sin resolver el problema de fondo de la nota del estudiante.\n\nA (idoneidad 4) es la respuesta más adecuada: reconoce la preocupación, aporta evidencia objetiva sin exponer al acudiente frente a otros padres, y propone un espacio constructivo posterior.\n\nB (idoneidad 3) también es una respuesta sólida y respetuosa, cercana a la ideal, aunque menciona las citaciones previas de forma algo más directa que A, sin llegar a ser inadecuada.\n\nD (idoneidad 2) es razonable en cuanto busca privacidad, pero no aporta ningún dato objetivo sobre el seguimiento del estudiante en el momento, dejando la conversación sin resolver el fondo del reclamo.\n\nError frecuente del aspirante: Subestimar el daño relacional de igualar un tono agresivo frente a terceros, asumiendo que "defender los hechos" justifica cualquier forma de hacerlo, incluso una que escala el conflicto en un espacio público.\n\nEstrategia mental recomendada: Ante una pregunta de tipo MENOS adecuada, buscar la opción que combine mayor exposición pública innecesaria con mayor escalamiento del tono, no solo la que suene "más dura".\n\nSubcompetencia: Comunicación asertiva bajo presión ante un reclamo público de un acudiente',
  'fuente_normativa': 'Ley 1620 de 2013 sobre convivencia escolar y manejo respetuoso de la relación entre la institución educativa y las familias.',
 },
 {
  'codigo': 'MOD06-CA-003',
  'contexto': 'En una institución de Puerto Asís, la docente Marlene Ortega recibe un mensaje por el grupo institucional de WhatsApp de padres de familia de grado quinto, enviado por un acudiente, en el que se queja de que "nunca le responden a tiempo" y que "parece que a los profesores no les importa la comunicación con las familias". Marlene revisa el hilo completo del grupo, que tiene más de treinta integrantes, y encuentra que sí había respondido a una inquietud anterior de ese mismo acudiente dos días antes, aunque con cierta demora debido a que esa semana la institución estuvo en jornada de evaluaciones institucionales que ocupó buena parte de las tardes disponibles para atender mensajes. El mensaje quedó visible para todos los acudientes que integran el grupo, y algunos ya empezaron a reaccionar con emojis al comentario mientras Marlene aún estaba revisando el hilo completo para entender exactamente qué había ocurrido antes de decidir cómo responder frente a un grupo tan numeroso.',
  'enunciado': '¿Cuál es la respuesta MÁS adecuada que puede dar Marlene ante este mensaje en el grupo?',
  'opcion_a': 'Escribir en privado únicamente al acudiente para reclamarle por haber hecho el comentario en el grupo general, en lugar de escribirle directamente a ella primero antes de publicarlo frente a todos.',
  'opcion_b': 'Responder en el grupo con un tono calmado, reconociendo la demora puntual de esa semana por la jornada de evaluaciones, aclarando que sí se había atendido la inquietud anterior, y ofreciendo un canal directo para consultas urgentes.',
  'opcion_c': 'Ignorar el mensaje por completo dentro del grupo y esperar a que la conversación se diluya con otros temas, sin aclarar en ningún momento la situación frente a los demás acudientes que ya vieron el comentario.',
  'opcion_d': 'Responder en el grupo señalando que el acudiente no está siendo justo porque sí se le respondió antes, y sugerirle revisar bien el hilo de mensajes antes de hacer ese tipo de comentarios frente a todos.',
  'tipo_item': 'mas_adecuada',
  'idoneidad': {'a': 0, 'b': 4, 'c': 1, 'd': 2},
  'respuesta_correcta': 'B',
  'nivel_dificultad': 'alto',
  'proceso_cognitivo': 'evaluacion_juicio',
  'justificacion': 'B logra la idoneidad máxima porque atiende la percepción del acudiente sin negarla de plano, aporta el contexto real de la demora (jornada de evaluaciones), corrige con datos la afirmación de que "nunca" responde, y ofrece una solución concreta hacia adelante (canal directo), todo en un tono que preserva la confianza del resto del grupo que también observa la interacción.\n\nD (idoneidad 2) corrige el dato pero en un tono que reprende públicamente al acudiente, lo que puede generar una escalada innecesaria en un canal donde participan muchas otras familias.\n\nC (idoneidad 1) deja sin aclarar una afirmación pública inexacta frente a más de treinta acudientes, lo que puede reforzar una percepción errónea sobre la comunicación institucional.\n\nA (idoneidad 0) es la opción más problemática: reclama en privado por la forma del mensaje sin resolver el malentendido público, dejando la afirmación errónea sin aclarar frente a todo el grupo que la vio.\n\nError frecuente del aspirante: Asumir que la opción "más discreta" (A) es automáticamente la más profesional, sin considerar que dejar una afirmación pública inexacta sin aclarar frente al mismo público que la vio también tiene un costo institucional.\n\nEstrategia mental recomendada: Ante un reclamo público con una afirmación parcialmente inexacta, identificar la opción que corrige el dato con evidencia y tono calmado en el mismo canal donde ocurrió el malentendido.\n\nSubcompetencia: Comunicación asertiva en canales digitales institucionales frente a un reclamo público de un acudiente',
  'fuente_normativa': 'Lineamientos del MEN sobre comunicación efectiva entre la escuela y las familias como parte de la corresponsabilidad educativa.',
 },
 {
  'codigo': 'MOD06-CA-004',
  'contexto': 'En una institución de Aguachica, el docente Freddy Barbosa participa en un comité de convivencia donde debe presentar el caso de un estudiante de grado octavo con reportes reiterados de conflictos con compañeros durante las últimas semanas. Durante la reunión, la psicóloga escolar plantea una interpretación del caso distinta a la que Freddy había preparado con base en su observación directa en el aula durante varias semanas consecutivas. La psicóloga expone su punto con seguridad y cita literatura académica general sobre dinámicas de grupo en adolescentes, mientras que la observación de Freddy es más situacional pero incluye detalles muy concretos de las últimas cuatro semanas que ella no había podido presenciar directamente por no estar presente en el aula regularmente, solo en las citas individuales programadas con el estudiante. El comité debe definir una ruta de acompañamiento antes de que termine la sesión, ya programada para durar solo cuarenta minutos más.',
  'enunciado': '¿Cuál es la respuesta MENOS adecuada que podría dar Freddy en ese momento del comité?',
  'opcion_a': 'Reconocer el aporte teórico de la psicóloga y complementarlo con la observación directa y reciente del aula, proponiendo integrar ambas miradas antes de definir una ruta de acompañamiento para el estudiante.',
  'opcion_b': 'Guardar silencio ante el planteamiento de la psicóloga, asumiendo que su formación académica en el tema pesa más que la observación directa que él ha hecho durante varias semanas en el aula.',
  'opcion_c': 'Compartir con respeto los detalles concretos observados en las últimas semanas, señalando que pueden aportar información complementaria útil para la ruta de acompañamiento que se defina en el comité.',
  'opcion_d': 'Interrumpir a la psicóloga para decirle que su interpretación no tiene sentido porque ella no ha estado presente en el aula y por tanto no puede conocer realmente al estudiante.',
  'tipo_item': 'menos_adecuada',
  'idoneidad': {'a': 4, 'b': 2, 'c': 3, 'd': 0},
  'respuesta_correcta': 'D',
  'nivel_dificultad': 'muy_alto',
  'proceso_cognitivo': 'evaluacion_juicio',
  'justificacion': 'D tiene la idoneidad más baja porque interrumpe de forma irrespetuosa a una colega, descalifica por completo su aporte técnico sin reconocer ningún valor en él, y convierte una diferencia de interpretación legítima en un conflicto interpersonal dentro de un espacio institucional que exige colaboración entre distintos roles.\n\nA (idoneidad 4) es la respuesta más adecuada: integra ambas miradas, valora el aporte de la psicóloga y aporta la observación directa como información complementaria, no como contradicción.\n\nC (idoneidad 3) también es una intervención asertiva y respetuosa, cercana a la ideal, aunque se limita a compartir la información sin proponer explícitamente integrarla con la mirada de la psicóloga.\n\nB (idoneidad 2) evita el conflicto pero deja fuera información relevante y reciente que podría ser valiosa para el comité, lo que no beneficia plenamente la decisión sobre la ruta de acompañamiento del estudiante.\n\nError frecuente del aspirante: Considerar que descalificar abiertamente el aporte de un colega en un comité técnico es una forma "directa" de comunicación asertiva, cuando en realidad es una falta de respeto que daña la colaboración interdisciplinar.\n\nEstrategia mental recomendada: Ante una pregunta de tipo MENOS adecuada en un contexto de trabajo interdisciplinar, identificar la opción que descalifica o interrumpe a un colega en lugar de aportar información de forma respetuosa.\n\nSubcompetencia: Comunicación asertiva en espacios interdisciplinares de comité escolar',
  'fuente_normativa': 'Ley 1620 de 2013 y Decreto 1075 de 2015 sobre el funcionamiento de los comités escolares de convivencia.',
 },
 {
  'codigo': 'MOD06-CA-005',
  'contexto': 'En una institución de La Dorada, la docente Carolina Rendón coordina el proceso de admisiones de nuevos estudiantes para el siguiente año escolar, un proceso que involucra revisar decenas de solicitudes con plazos estrictos definidos por coordinación general. Un colega de otra sede de la misma institución le escribe un mensaje bastante cortante pidiéndole que agilice la revisión de un caso particular, "como si no tuviera nada más que hacer", según las palabras textuales del mensaje enviado a las siete de la noche de un domingo. Carolina en efecto tiene una carga alta de casos pendientes esa semana, todos con plazos definidos por la coordinación general y organizados en una lista de prioridad según la fecha de radicación, y el caso que menciona el colega no tiene ninguna prioridad especial frente a los demás que ya estaban en cola desde antes, varios de ellos radicados con más de diez días de anticipación.',
  'enunciado': '¿Cuál es la respuesta MÁS adecuada que puede dar Carolina ante este mensaje cortante del colega?',
  'opcion_a': 'Acceder de inmediato a adelantar ese caso particular por encima de todos los demás que ya estaban en cola, solo para evitar una posible tensión adicional con el colega.',
  'opcion_b': 'Responder con el mismo tono cortante, señalándole al colega que ella también tiene una carga alta de trabajo y que no puede atender solicitudes con ese nivel de exigencia.',
  'opcion_c': 'No responder al mensaje durante varios días, dejando al colega sin ninguna información sobre el estado real del caso que solicitó revisar con cierta urgencia.',
  'opcion_d': 'Responder con un tono profesional, explicando el orden de prioridad de los casos pendientes y el plazo estimado real para revisar el caso mencionado, sin reaccionar al tono cortante del mensaje.',
  'tipo_item': 'mas_adecuada',
  'idoneidad': {'a': 0, 'b': 1, 'c': 2, 'd': 4},
  'respuesta_correcta': 'D',
  'nivel_dificultad': 'alto',
  'proceso_cognitivo': 'evaluacion_juicio',
  'justificacion': 'D logra la idoneidad máxima porque no responde al tono cortante con otro tono defensivo, aporta información objetiva y verificable sobre el orden de prioridad de los casos, y mantiene el trato profesional necesario para sostener la relación de trabajo entre sedes sin ceder a una presión injustificada.\n\nC (idoneidad 2) evita el conflicto directo, pero deja al colega sin ninguna información, lo que puede generar más frustración y una percepción de indiferencia frente a una solicitud legítima aunque mal formulada.\n\nB (idoneidad 1) iguala el tono inadecuado del mensaje original, lo que puede escalar una tensión que aún era manejable con una respuesta profesional.\n\nA (idoneidad 0) es la opción más problemática: cede la prioridad del trabajo bajo presión de un tono inadecuado, afectando injustamente a los demás casos que ya estaban en cola con plazos definidos.\n\nError frecuente del aspirante: Confundir "no ceder ante la presión" con responder de forma igualmente cortante, sin reconocer que la asertividad exige sostener el criterio técnico con un tono profesional constante.\n\nEstrategia mental recomendada: Ante un mensaje con tono inadecuado pero una solicitud de fondo legítima, separar el tono del contenido y responder al contenido con información objetiva, sin igualar el tono recibido.\n\nSubcompetencia: Comunicación asertiva entre colegas de distintas sedes bajo presión de tiempo',
  'fuente_normativa': 'Lineamientos institucionales de gestión académica sobre priorización equitativa de procesos y trato profesional entre colegas.',
 },
 {
  'codigo': 'MOD06-CA-006',
  'contexto': 'En una institución de Fusagasugá, el docente Iván Cepeda participa en una capacitación institucional obligatoria de dos días, dictada por un asesor externo contratado por la secretaría de educación para todo el cuerpo docente del municipio. Durante la sesión de la mañana, el asesor hace un comentario genérico y algo despectivo sobre "los docentes que llevan muchos años sin actualizarse", sin dirigirse a nadie en particular, pero varios colegas de mayor experiencia en la sala, presentes en primera fila, se muestran visiblemente incómodos con el comentario, cruzando miradas entre ellos. Iván, más joven que la mayoría del grupo y con apenas tres años de experiencia, nota el silencio incómodo que se genera en la sala tras el comentario del asesor, mientras la presentación continúa como si nada hubiera pasado y aún quedan dos horas de sesión antes del receso para el almuerzo. Al final de la jornada se diligenciará una encuesta de satisfacción sobre la capacitación, que la secretaría de educación usa como insumo para decidir si renueva el contrato con este mismo asesor para las próximas jornadas del año.',
  'enunciado': '¿Cuál es la respuesta MENOS adecuada que podría tener Iván ante esta situación durante la capacitación?',
  'opcion_a': 'Interrumpir de inmediato al asesor en voz alta frente a todo el grupo para decirle que su comentario es una falta de respeto y que no debería seguir dictando la capacitación.',
  'opcion_b': 'No decir nada durante la sesión y comentar el malestar generado únicamente en privado, después, con algunos colegas cercanos que también notaron el comentario del asesor externo.',
  'opcion_c': 'Escribirle en privado al asesor, al finalizar la sesión, para comentarle con respeto que el comentario generó incomodidad en varios colegas presentes en la sala.',
  'opcion_d': 'Esperar un espacio adecuado dentro de la sesión (como la ronda de preguntas) para señalar, con respeto, que ese tipo de generalizaciones no reflejan la diversidad real de trayectorias y actualizaciones del cuerpo docente presente.',
  'tipo_item': 'menos_adecuada',
  'idoneidad': {'a': 0, 'b': 1, 'c': 3, 'd': 4},
  'respuesta_correcta': 'A',
  'nivel_dificultad': 'alto',
  'proceso_cognitivo': 'evaluacion_juicio',
  'justificacion': 'A tiene la idoneidad más baja porque interrumpe de forma agresiva y descalifica públicamente al asesor sin necesidad, generando un conflicto abierto frente a todo el grupo que puede resultar desproporcionado frente a un comentario genérico, aunque desafortunado, que no estaba dirigido a nadie en particular.\n\nD (idoneidad 4) es la respuesta más adecuada: usa el espacio institucional previsto (la ronda de preguntas) para expresar el desacuerdo con respeto, sin escalar el conflicto ni guardar silencio ante algo que generó malestar visible en el grupo.\n\nC (idoneidad 3) también es una forma válida y respetuosa de plantear el desacuerdo, aunque al hacerlo en privado después de la sesión pierde la oportunidad de que el comentario quede aclarado frente a todo el grupo que lo escuchó.\n\nB (idoneidad 1) evita cualquier tipo de intervención directa, dejando que el malestar quede sin canalizar de forma constructiva, lo que no aporta a mejorar futuras sesiones de capacitación.\n\nError frecuente del aspirante: Confundir la firmeza necesaria ante un comentario desafortunado con una reacción pública desproporcionada, sin considerar los espacios institucionales adecuados para expresar el desacuerdo.\n\nEstrategia mental recomendada: Ante una pregunta de tipo MENOS adecuada sobre una reacción a un comentario incómodo, identificar la opción que interrumpe de forma agresiva y descalifica en público, frente a otras que canalizan el desacuerdo de forma respetuosa.\n\nSubcompetencia: Comunicación asertiva ante comentarios institucionales incómodos en espacios de formación',
  'fuente_normativa': 'Ley 1620 de 2013 sobre convivencia escolar, aplicada por extensión al trato respetuoso entre actores del sistema educativo en espacios de formación docente.',
 },
 {
  'codigo': 'MOD06-CA-007',
  'contexto': 'En una institución de Chaparral, la docente Yésica Roldán es citada por la rectoría para explicar por qué el promedio de su grupo de grado sexto en matemáticas quedó por debajo del promedio institucional en el último periodo, una diferencia que la coordinación académica considera significativa frente al resto de los grupos del mismo grado. En la reunión, el rector le pregunta directamente, con cierto tono de preocupación pero sin agresividad, qué está pasando con el grupo. Yésica sabe que una parte importante de la explicación tiene que ver con que ese grupo concentra un número alto de estudiantes con procesos de nivelación pendientes de años anteriores, siete en total, una situación que ya había reportado por escrito a coordinación académica al inicio del año, adjuntando el listado completo de esos estudiantes, sin recibir aún una respuesta formal sobre el apoyo adicional solicitado para ese grupo en particular. El rector aclara que no busca señalar una falla exclusiva de Yésica, sino entender el panorama completo antes de la reunión de consejo académico programada para la semana siguiente, en la que deberá presentar un balance de resultados por grado.',
  'enunciado': '¿Cuál es la respuesta MÁS adecuada que puede dar Yésica en esa reunión con el rector?',
  'opcion_a': 'Aceptar la responsabilidad completa por el resultado del grupo sin mencionar la composición particular del curso ni el reporte enviado previamente a coordinación académica.',
  'opcion_b': 'Pedirle al rector que hable directamente con los estudiantes del grupo para que le expliquen a él por qué no han mejorado sus resultados en el periodo.',
  'opcion_c': 'Explicar con datos concretos la composición particular del grupo y recordar el reporte enviado a coordinación académica al inicio del año, proponiendo hacer seguimiento conjunto a la solicitud de apoyo pendiente.',
  'opcion_d': 'Señalar que el resultado es responsabilidad exclusiva de coordinación académica por no haber respondido a tiempo el reporte enviado al inicio del año, sin aportar ninguna explicación adicional sobre el grupo.',
  'tipo_item': 'mas_adecuada',
  'idoneidad': {'a': 2, 'b': 0, 'c': 4, 'd': 1},
  'respuesta_correcta': 'C',
  'nivel_dificultad': 'alto',
  'proceso_cognitivo': 'evaluacion_juicio',
  'justificacion': 'C logra la idoneidad máxima porque responde con información objetiva y verificable (la composición del grupo y el reporte ya enviado), sin evadir su propia responsabilidad ni trasladarla por completo a otra instancia, y propone una acción concreta hacia adelante (seguimiento conjunto) que beneficia tanto al grupo como a la relación con la rectoría.\n\nA (idoneidad 2) es una respuesta honesta en cuanto a la disposición de Yésica, pero omite información relevante que el rector necesita para entender el contexto real del resultado del grupo.\n\nD (idoneidad 1) traslada toda la responsabilidad a otra instancia sin aportar ningún elemento propio de análisis sobre el grupo, lo que puede leerse como evasivo frente a una pregunta hecha sin agresividad.\n\nB (idoneidad 0) es la opción más problemática: delega en los propios estudiantes una responsabilidad que corresponde explicar a la docente frente a la rectoría, y no aporta ninguna información útil para la reunión.\n\nError frecuente del aspirante: Asumir que aceptar toda la responsabilidad sin contexto (opción A) es la actitud "más profesional", sin reconocer que la comunicación asertiva incluye aportar información objetiva relevante, no solo mostrar disposición.\n\nEstrategia mental recomendada: Ante una pregunta directa de un superior sobre un resultado bajo, identificar la opción que combina datos objetivos, corresponsabilidad y una propuesta concreta hacia adelante.\n\nSubcompetencia: Comunicación asertiva ante una autoridad institucional frente a resultados académicos bajo revisión',
  'fuente_normativa': 'Decreto 1290 de 2009 sobre evaluación y seguimiento institucional de los procesos de aprendizaje.',
 },
 {
  'codigo': 'MOD06-CA-008',
  'contexto': 'En una institución de El Banco, el docente Alexánder Julio recibe una llamada de un acudiente exaltado porque su hija, estudiante de grado séptimo, fue registrada en el observador con una anotación por usar el celular durante una evaluación, algo prohibido explícitamente en el reglamento institucional que la familia firmó al inicio del año escolar junto con el resto de compromisos de convivencia. El acudiente insiste, en tono elevado, en que la anotación es "una exageración" y exige que se elimine del observador en ese mismo momento, antes de escuchar la versión completa de los hechos que Alexánder había registrado, incluyendo el testimonio de otro estudiante que estaba sentado cerca durante la evaluación y confirmó lo ocurrido por escrito ante el coordinador de convivencia esa misma tarde. La llamada se está dando a mitad de la jornada, entre dos clases seguidas que Alexánder tiene programadas, y el acudiente le advierte que si no resuelve el tema de inmediato escalará el reclamo directamente a la rectoría.',
  'enunciado': '¿Cuál es la respuesta MENOS adecuada que podría dar Alexánder durante esta llamada?',
  'opcion_a': 'Escuchar la molestia del acudiente sin interrumpir, y luego explicar con calma el procedimiento seguido y el reglamento firmado, ofreciendo revisar el caso completo en una reunión presencial posterior.',
  'opcion_b': 'Aceptar eliminar la anotación del observador en ese mismo momento de la llamada, solo para que el acudiente deje de insistir en tono elevado, sin revisar antes el reglamento ni el testimonio registrado.',
  'opcion_c': 'Explicar con calma que la anotación sigue un procedimiento reglamentario ya firmado por la familia, y proponer revisar juntos, en una reunión presencial, toda la información disponible del caso.',
  'opcion_d': 'Mantener un tono calmado durante toda la llamada, pero ser claro en que la anotación no puede eliminarse de forma unilateral por una llamada telefónica sin revisar el procedimiento completo.',
  'tipo_item': 'menos_adecuada',
  'idoneidad': {'a': 3, 'b': 0, 'c': 4, 'd': 2},
  'respuesta_correcta': 'B',
  'nivel_dificultad': 'muy_alto',
  'proceso_cognitivo': 'evaluacion_juicio',
  'justificacion': 'B tiene la idoneidad más baja porque cede a una exigencia bajo presión sin ningún respaldo procedimental, elimina un registro válido sin haber revisado el reglamento firmado ni el testimonio disponible, y sienta un precedente institucional problemático al modificar decisiones documentadas solo por insistencia en tono elevado.\n\nC (idoneidad 4) es la respuesta más adecuada: sostiene el procedimiento reglamentario con calma, sin ceder a la presión, y propone un espacio adecuado para revisar el caso con toda la información disponible.\n\nA (idoneidad 3) también es una respuesta sólida y respetuosa, muy cercana a la ideal, aunque prioriza escuchar antes de explicar el procedimiento, un orden razonable pero levemente menos directo que C frente a una exigencia inmediata.\n\nD (idoneidad 2) mantiene el tono calmado y no cede, pero es menos constructiva porque no ofrece de forma explícita un espacio posterior para revisar el caso completo con el acudiente.\n\nError frecuente del aspirante: Asumir que "resolver rápido" una llamada tensa mediante una concesión inmediata es la opción más profesional, sin considerar el daño que genera modificar un registro válido bajo presión sin revisión procedimental.\n\nEstrategia mental recomendada: Ante una pregunta de tipo MENOS adecuada sobre el manejo de una exigencia bajo presión, identificar la opción que cede sin ningún respaldo procedimental, frente a otras que sostienen el proceso con distintos grados de firmeza.\n\nSubcompetencia: Comunicación asertiva ante exigencias de un acudiente bajo presión telefónica',
  'fuente_normativa': 'Ley 1620 de 2013 y el reglamento o manual de convivencia institucional sobre el debido proceso en los registros del observador del estudiante.',
 },
 {
  'codigo': 'MOD06-CA-009',
  'contexto': 'En una institución de Yopal, la docente Estefanía Bohórquez lidera un proyecto de lectura institucional que requiere la colaboración de varios docentes de distintas áreas y que ya lleva tres meses en desarrollo con buenos resultados iniciales. Uno de los colegas invitados al proyecto ha dejado de responder los mensajes del grupo de coordinación desde hace más de una semana, y no ha entregado el material que se había comprometido a preparar para la siguiente fase, que ya tiene una fecha de presentación acordada con la coordinación académica y comunicada a los padres de familia mediante circular. Estefanía necesita tomar una decisión pronto porque el cronograma del proyecto no admite más demoras sin afectar la fecha ya comprometida institucionalmente, y hasta ahora el colega siempre había cumplido puntualmente con sus entregas anteriores durante los primeros dos meses del proyecto. Estefanía no tiene ninguna información sobre lo que puede estar ocurriendo con su colega, y sabe que otros miembros del equipo también han notado su ausencia reciente en los espacios habituales de la institución durante los descansos.',
  'enunciado': '¿Cuál es la respuesta MÁS adecuada que puede tomar Estefanía frente a esta situación con el colega?',
  'opcion_a': 'Redistribuir de inmediato, sin conversar antes con el colega, la parte del material comprometida entre los demás docentes del proyecto, asumiendo que el colega ya no participará.',
  'opcion_b': 'Esperar sin comunicarse con el colega hasta la fecha límite acordada con coordinación académica, asumiendo que el material aparecerá a tiempo sin necesidad de ninguna gestión adicional de su parte.',
  'opcion_c': 'Escribirle directamente al colega, en privado, para preguntar con respeto si está teniendo alguna dificultad con el material comprometido, y ofrecer ajustar el plazo o redistribuir esa parte del trabajo si es necesario.',
  'opcion_d': 'Escribir en el grupo general de coordinación del proyecto, visible para todos los demás docentes participantes, señalando directamente que el colega no ha cumplido con su parte del compromiso.',
  'tipo_item': 'mas_adecuada',
  'idoneidad': {'a': 2, 'b': 1, 'c': 4, 'd': 0},
  'respuesta_correcta': 'C',
  'nivel_dificultad': 'alto',
  'proceso_cognitivo': 'evaluacion_juicio',
  'justificacion': 'C logra la idoneidad máxima porque indaga primero las causas del silencio del colega antes de asumir una intención negativa, ofrece flexibilidad razonable ante el cronograma, y protege tanto la relación de trabajo como el avance del proyecto sin exponer al colega frente al resto del equipo.\n\nA (idoneidad 2) es una acción práctica frente al riesgo de cronograma, pero toma una decisión unilateral sobre el trabajo del colega sin haber indagado primero las razones de su silencio, lo que puede generar un conflicto evitable, especialmente considerando su buen historial de cumplimiento previo.\n\nB (idoneidad 1) asume pasivamente que el problema se resolverá solo, sin ninguna gestión activa frente a un riesgo real para una fecha ya comprometida institucionalmente.\n\nD (idoneidad 0) es la opción más problemática: expone públicamente el incumplimiento de un colega frente a todo el equipo del proyecto, sin haber indagado antes en privado, lo que puede dañar innecesariamente la relación de trabajo y la disposición futura del colega a colaborar.\n\nError frecuente del aspirante: Confundir "actuar rápido ante un riesgo de cronograma" con exponer o reemplazar unilateralmente a un colega sin antes indagar la causa de su falta de respuesta.\n\nEstrategia mental recomendada: Ante una pregunta de tipo MÁS adecuada sobre el manejo de un incumplimiento de un colega en un proyecto colaborativo, priorizar la opción que indaga en privado antes de exponer, redistribuir o asumir pasivamente.\n\nSubcompetencia: Comunicación asertiva en la coordinación de proyectos colaborativos entre docentes',
  'fuente_normativa': 'Lineamientos institucionales sobre trabajo colaborativo docente y manejo respetuoso de la corresponsabilidad en proyectos transversales.',
 },
 {
  'codigo': 'MOD06-CA-010',
  'contexto': 'En una institución de Ipiales, el docente Wílmar Guerrero recibe una evaluación de desempeño de su coordinador en la que se señala, entre otros aspectos, que debe mejorar la puntualidad en la entrega de planeaciones durante el periodo evaluado. Wílmar considera que la observación es en parte injusta, porque en dos de las cuatro ocasiones señaladas la demora se debió a que el coordinador no le había entregado a tiempo el formato actualizado que la institución exige usar para las planeaciones de ese año, un hecho que sí puede documentar con los correos institucionales correspondientes, con fecha y hora de envío. La reunión de retroalimentación se realiza de forma individual, sin más personas presentes en la oficina, y el coordinador mantiene un tono profesional y abierto a la conversación durante todo el encuentro, incluso preguntándole directamente si tiene algo que agregar antes de cerrar el punto. Esta es la primera evaluación de desempeño formal que Wílmar recibe en la institución, y sabe que el documento final quedará archivado como parte de su historial laboral para efectos del siguiente periodo de evaluación.',
  'enunciado': '¿Cuál es la respuesta MENOS adecuada que podría dar Wílmar durante esta reunión de retroalimentación?',
  'opcion_a': 'Reconocer la observación sobre puntualidad, y aclarar con respeto, apoyado en los correos institucionales, las dos ocasiones en que la demora se debió a la entrega tardía del formato por parte de coordinación.',
  'opcion_b': 'Guardar silencio durante toda la reunión, sin aceptar ni aclarar la observación del coordinador, esperando simplemente a que la conversación termine lo antes posible.',
  'opcion_c': 'Aceptar la observación sin ninguna aclaración, evitando mencionar la entrega tardía del formato por parte de coordinación, para no generar ninguna tensión durante la reunión individual.',
  'opcion_d': 'Rechazar por completo la observación del coordinador, argumentando que toda la responsabilidad de las demoras es exclusivamente de coordinación académica y no suya en ningún caso.',
  'tipo_item': 'menos_adecuada',
  'idoneidad': {'a': 4, 'b': 0, 'c': 2, 'd': 1},
  'respuesta_correcta': 'B',
  'nivel_dificultad': 'alto',
  'proceso_cognitivo': 'evaluacion_juicio',
  'justificacion': 'B tiene la idoneidad más baja porque no aporta ninguna aclaración ni reconocimiento, desaprovechando por completo un espacio de retroalimentación abierto y respetuoso en el que el propio coordinador invitó explícitamente a agregar información.\n\nA (idoneidad 4) es la respuesta más adecuada: reconoce la observación general sin negarla de plano, y aporta evidencia objetiva y verificable (los correos institucionales) para aclarar las dos ocasiones específicas en que la demora tuvo una causa distinta, en un tono respetuoso adecuado para una reunión individual abierta al diálogo.\n\nC (idoneidad 2) evita la tensión, pero deja sin corregir una percepción parcialmente inexacta sobre su desempeño, perdiendo una oportunidad legítima de aclaración en un espacio diseñado justamente para ello.\n\nD (idoneidad 1) traslada toda la responsabilidad a otra instancia sin reconocer ningún matiz en la observación general, lo que puede leerse como una actitud defensiva desproporcionada frente a un coordinador que mantiene un tono profesional.\n\nError frecuente del aspirante: Asumir que aceptar sin matices cualquier observación de un superior (opción C) es la actitud más adecuada, sin reconocer que la comunicación asertiva permite aclarar con evidencia objetiva sin faltar al respeto ni rechazar la retroalimentación de fondo.\n\nEstrategia mental recomendada: Ante una pregunta de tipo MENOS adecuada sobre el manejo de una observación de desempeño parcialmente injusta, identificar la opción que no aporta ninguna reacción ni aclaración, desaprovechando el espacio de diálogo ofrecido.\n\nSubcompetencia: Comunicación asertiva en reuniones individuales de retroalimentación de desempeño',
  'fuente_normativa': 'Decreto 1075 de 2015 sobre evaluación de desempeño docente y el derecho a la contradicción documentada dentro del proceso.',
 },
]
