# -*- coding: utf-8 -*-
"""Banco Oficial de Preguntas - Modulo 6: Analisis de Casos
TEMA 4 de 4: Orientacion al logro (Lote 1) - 10 preguntas.
Nombre alineado exactamente con el catalogo oficial de la plataforma
(dashboard/question_generator.py, MODULES['analisis-de-casos']['topics']).
Los 4 temas del Modulo 6, cada uno con 10 preguntas (40 en total):
1. Comunicacion asertiva (AC_comunicacion_asertiva_lote01.py)
2. Liderazgo pedagogico (AC_liderazgo_lote01.py)
3. Trabajo colaborativo (AC_trabajo_equipo_lote01.py)
4. Orientacion al logro (este archivo)
Ultimo tema del Modulo 6, bajo la regla permanente desde Modulo 5: 10
preguntas por tema. Formato TJS con idoneidad
graduada 0-4, igual a los lotes de Comunicacion asertiva, Liderazgo y
Trabajo en equipo ya aprobados. Contenido enteramente nuevo. Dificultad
unicamente Alta y Muy Alta. Proceso cognitivo nivel 3-4. Mezcla balanceada
de tipo_item mas_adecuada/menos_adecuada (5/5). Contexto de 150-300 palabras
por item. Letra objetivo planificada por adelantado (A3/B2/C2/D3) y escrita
directamente en la posicion correspondiente desde el primer borrador para
evitar el sesgo de distribucion detectado y corregido en lotes anteriores.
"""

CATEGORIA = "Análisis de Casos"
SUBCATEGORIA = "Análisis de Casos - Orientación al logro"
COMPETENCIA = "Análisis de casos y competencias comportamentales"
AREA = "psicotecnico"

ITEMS = [
 {
  'codigo': 'MOD06-OL-001',
  'contexto': 'En una institución de Yumbo, la docente Marcela Idárraga lidera desde el inicio del año un plan de mejoramiento en comprensión lectora para todo el grado séptimo, con una meta institucional clara: reducir en un veinte por ciento el número de estudiantes con desempeño bajo en esa competencia para el cierre del año escolar. Al llegar al tercer periodo, Marcela revisa los resultados parciales y encuentra que, aunque hay avances reales en dos de los cuatro grupos de séptimo, los otros dos grupos no muestran ninguna mejora significativa frente a la línea base del diagnóstico inicial, a pesar de haber aplicado exactamente la misma estrategia de trabajo en los cuatro grupos durante todo el semestre. Coordinación académica le pide un informe de ajuste antes de iniciar el último periodo del año, con solo diez semanas restantes antes del cierre, y Marcela sabe que mantener la misma estrategia sin ningún cambio podría significar no alcanzar la meta institucional acordada para los grupos que aún no muestran avance real.',
  'enunciado': '¿Cuál es la respuesta MENOS adecuada que podría dar Marcela al preparar este informe de ajuste para el último periodo?',
  'opcion_a': 'Analizar con detalle qué diferencia a los dos grupos sin avance de los dos que sí mejoraron, e identificar ajustes específicos a la estrategia para esos dos grupos en las diez semanas restantes.',
  'opcion_b': 'Consultar con los propios estudiantes de los dos grupos sin avance qué dificultades concretas han tenido con la estrategia aplicada, para incorporar esa información al ajuste propuesto.',
  'opcion_c': 'Proponer un ajuste de estrategia diferenciado para los dos grupos sin avance, mientras sostiene la estrategia actual en los dos grupos que ya muestran una mejora consistente.',
  'opcion_d': 'Mantener exactamente la misma estrategia en los cuatro grupos durante el último periodo, confiando en que los resultados de los dos grupos sin avance mejorarán solos con más tiempo.',
  'tipo_item': 'menos_adecuada',
  'idoneidad': {'a': 3, 'b': 3, 'c': 4, 'd': 0},
  'respuesta_correcta': 'D',
  'nivel_dificultad': 'muy_alto',
  'proceso_cognitivo': 'evaluacion_juicio',
  'justificacion': 'D tiene la idoneidad más baja porque, ante evidencia clara de que la estrategia no está funcionando en dos de los cuatro grupos, mantenerla sin ningún ajuste no está fundamentado en ningún dato real, solo en la esperanza de que el tiempo por sí solo resuelva el estancamiento, arriesgando directamente el cumplimiento de la meta institucional en esas diez semanas restantes.\n\nC (idoneidad 4) es la respuesta más adecuada porque usa la evidencia disponible para diferenciar la estrategia exactamente donde se necesita el ajuste, sin desmontar innecesariamente lo que ya funciona en los otros dos grupos.\n\nA (idoneidad 3) y B (idoneidad 3) son también respuestas sólidas y basadas en evidencia, cercanas a la ideal: A compara los grupos para identificar diferencias explicativas, y B indaga directamente con los estudiantes afectados; ambas aportan información valiosa para el ajuste, aunque ninguna llega a proponer todavía la acción diferenciada concreta que sí plantea C.\n\nError frecuente del aspirante: Confundir "dar más tiempo" con una estrategia válida de mejora, cuando en realidad la persistencia sin ajuste ante evidencia de estancamiento no es orientación al logro, sino inercia.\n\nEstrategia mental recomendada: Ante una pregunta de tipo MENOS adecuada sobre el ajuste de una estrategia con resultados desiguales, identificar la opción que sostiene la misma estrategia sin ningún cambio basado en evidencia, confiando únicamente en el paso del tiempo.\n\nSubcompetencia: Orientación al logro mediante el ajuste de estrategia basado en evidencia de resultados parciales',
  'fuente_normativa': 'Decreto 1290 de 2009 sobre seguimiento y evaluación continua del proceso de aprendizaje y ajuste de estrategias pedagógicas.',
 },
 {
  'codigo': 'MOD06-OL-002',
  'contexto': 'En una institución de Facatativá, el docente Norbey Casallas se propuso, desde comienzo de año, que todos los estudiantes de su grado once presentaran las pruebas de estado con al menos una simulación completa realizada bajo condiciones reales de tiempo, algo que en años anteriores solo lograban hacer los estudiantes con mejor rendimiento académico del curso. A mitad de año, Norbey revisa su avance y encuentra que ha logrado aplicar la simulación completa a poco más de la mitad del curso, principalmente porque coordinar los tiempos y espacios necesarios para una simulación bajo condiciones reales ha sido más complejo de lo previsto, y varios estudiantes con más dificultades académicas aún no han tenido su primera simulación completa, precisamente el grupo que más se beneficiaría de esa práctica según el diagnóstico inicial de Norbey al comienzo del año escolar. Coordinación académica ha manifestado interés en usar esta experiencia como referencia para otros grados del bachillerato en los años siguientes.',
  'enunciado': '¿Cuál es la respuesta MÁS adecuada que puede tomar Norbey frente a este avance parcial de su meta, a mitad de año?',
  'opcion_a': 'Priorizar de forma intencionada, en lo que resta del año, a los estudiantes con más dificultades académicas que aún no han tenido su primera simulación completa, ajustando la logística que ha dificultado el proceso hasta ahora.',
  'opcion_b': 'Reducir la meta original a solo los estudiantes que ya lograron su simulación completa, dando por hecho que el resto del curso no alcanzará a cumplir con esa práctica este año.',
  'opcion_c': 'Continuar aplicando las simulaciones en el mismo orden en que se han venido dando hasta ahora, sin ningún criterio adicional de priorización para lo que resta del año escolar.',
  'opcion_d': 'Suspender por completo las simulaciones completas restantes del año, y dedicar todo el tiempo disponible únicamente a repasar contenidos teóricos con el curso completo, sin ningún criterio de priorización.',
  'tipo_item': 'mas_adecuada',
  'idoneidad': {'a': 4, 'b': 1, 'c': 2, 'd': 0},
  'respuesta_correcta': 'A',
  'nivel_dificultad': 'alto',
  'proceso_cognitivo': 'evaluacion_juicio',
  'justificacion': 'A logra la idoneidad máxima porque, ante un avance parcial de la meta y un obstáculo logístico identificado, prioriza intencionadamente al grupo que más necesita la práctica según el diagnóstico inicial, y ajusta directamente la causa concreta que ha dificultado el proceso, maximizando el impacto real de la meta en el tiempo restante.\n\nC (idoneidad 2) mantiene el esfuerzo sin cambios, pero al no priorizar conscientemente corre el riesgo de que el grupo que más necesita la práctica siga sin acceder a ella por el mismo obstáculo logístico no resuelto.\n\nB (idoneidad 1) renuncia a la meta original justo para el grupo que más se beneficiaría de ella, conformándose con el avance ya logrado en lugar de buscar alcanzar el propósito inicial.\n\nD (idoneidad 0) es la opción más problemática: abandona por completo una práctica que el propio diagnóstico inicial de Norbey identificó como valiosa, sin intentar antes resolver el obstáculo logístico que ha limitado el avance.\n\nError frecuente del aspirante: Confundir "mantener el mismo ritmo" con perseverancia genuina, sin reconocer que la orientación al logro exige priorizar de forma intencionada cuando el tiempo y los recursos son limitados.\n\nEstrategia mental recomendada: Ante una pregunta de tipo MÁS adecuada sobre el avance parcial de una meta con un obstáculo identificado, identificar la opción que prioriza intencionadamente a quienes más necesitan el logro y ajusta la causa concreta del obstáculo.\n\nSubcompetencia: Orientación al logro mediante la priorización intencionada de metas parciales bajo restricciones de tiempo y recursos',
  'fuente_normativa': 'Lineamientos del MEN sobre preparación para pruebas de Estado y equidad en el acceso a estrategias de preparación entre estudiantes de distinto desempeño.',
 },
 {
  'codigo': 'MOD06-OL-003',
  'contexto': 'En una institución de Chía, la docente Vanessa Riaño coordina un proyecto institucional de escritura creativa que culminará con la publicación de una revista literaria elaborada íntegramente por los estudiantes de bachillerato, una meta que se propuso desde el inicio del año con el respaldo del rector. Faltando dos meses para la fecha de publicación ya anunciada a toda la comunidad educativa, Vanessa recibe la noticia de que la editorial local con la que había acordado la impresión física de la revista, sin costo para la institución, canceló el compromiso por una reestructuración interna de la empresa que no tiene relación alguna con el proyecto. Vanessa cuenta con todos los textos de los estudiantes ya revisados y editados, y sabe que buscar una alternativa de impresión con costo implicaría gestionar un presupuesto que la institución no tiene actualmente disponible para este proyecto en particular. La revista ha sido promocionada activamente por el rector como uno de los proyectos insignia del año ante toda la comunidad de padres de familia.',
  'enunciado': '¿Cuál es la respuesta MÁS adecuada que puede tomar Vanessa frente a este imprevisto, a dos meses de la fecha de publicación ya anunciada?',
  'opcion_a': 'Cancelar por completo la publicación de la revista, comunicando a la comunidad educativa que el proyecto no podrá concretarse este año debido al imprevisto con la editorial.',
  'opcion_b': 'Explorar activamente alternativas concretas para sostener la meta (una publicación digital de acceso gratuito, otra editorial local, o una gestión de recursos institucionales), manteniendo informada a la comunidad educativa sobre el ajuste necesario.',
  'opcion_c': 'Esperar sin ninguna gestión adicional a que surja una solución espontánea antes de la fecha ya anunciada, sin explorar activamente ninguna alternativa de impresión o de formato.',
  'opcion_d': 'Reducir la revista a solo un fragmento simbólico de los textos ya revisados, sin buscar ninguna alternativa que permita publicar el trabajo completo de los estudiantes.',
  'tipo_item': 'mas_adecuada',
  'idoneidad': {'a': 0, 'b': 4, 'c': 1, 'd': 2},
  'respuesta_correcta': 'B',
  'nivel_dificultad': 'muy_alto',
  'proceso_cognitivo': 'evaluacion_juicio',
  'justificacion': 'B logra la idoneidad máxima porque, ante un obstáculo externo real que no depende de su gestión, explora activamente alternativas concretas para sostener el propósito central del proyecto (que el trabajo completo de los estudiantes llegue a publicarse), sin dejar a la comunidad educativa sin información sobre el ajuste necesario.\n\nD (idoneidad 2) mantiene algo del propósito original, pero reducir la publicación a un fragmento simbólico sacrifica innecesariamente el trabajo completo de los estudiantes sin haber agotado antes las alternativas disponibles.\n\nC (idoneidad 1) no gestiona activamente ninguna solución, dejando la meta librada al azar en un momento en que aún hay tiempo real para explorar alternativas concretas.\n\nA (idoneidad 0) es la opción más problemática: abandona por completo una meta ya anunciada y con el trabajo de los estudiantes ya listo, sin haber intentado ninguna alternativa viable ante un obstáculo que, aunque real, no es insuperable.\n\nError frecuente del aspirante: Asumir que un obstáculo externo fuera del control directo de la persona justifica abandonar por completo una meta, sin explorar primero alternativas concretas que permitan sostenerla de otra forma.\n\nEstrategia mental recomendada: Ante una pregunta de tipo MÁS adecuada sobre un obstáculo externo que amenaza una meta ya avanzada, identificar la opción que explora alternativas concretas para sostener el propósito central, en lugar de cancelar, esperar pasivamente o reducir el alcance sin necesidad real.\n\nSubcompetencia: Orientación al logro ante obstáculos externos imprevistos en proyectos con fecha comprometida',
  'fuente_normativa': 'Lineamientos institucionales sobre proyectos pedagógicos transversales de lectura y escritura dentro del PEI.',
 },
 {
  'codigo': 'MOD06-OL-004',
  'contexto': 'En una institución de Guaduas, el docente Ferney Aponte se propuso a comienzo de año, junto con el equipo de matemáticas, mejorar el desempeño de grado noveno en resolución de problemas contextualizados, con una meta concreta acordada con coordinación: que al menos el setenta por ciento del curso alcanzara el nivel esperado en la prueba institucional del tercer periodo. Al revisar los resultados de esa prueba, Ferney encuentra que solo el cuarenta y cinco por ciento del curso alcanzó el nivel esperado, un resultado considerablemente por debajo de la meta acordada, aunque también nota que la mayoría de los estudiantes que no alcanzaron el nivel esperado tuvieron dificultades específicas con un solo tipo de problema (los que involucran proporcionalidad), mientras que en los demás tipos de problema el desempeño general del curso fue mucho más cercano a lo esperado según el análisis detallado que Ferney hizo pregunta por pregunta, comparando cada respuesta con el estándar esperado para el grado.',
  'enunciado': '¿Cuál es la respuesta MENOS adecuada que podría dar Ferney frente a este resultado, considerablemente por debajo de la meta acordada?',
  'opcion_a': 'Compartir el análisis detallado con los propios estudiantes, para que entiendan con claridad en qué tipo de problema necesitan concentrar su esfuerzo de estudio durante el siguiente periodo.',
  'opcion_b': 'Presentar a coordinación el resultado general junto con el análisis detallado que identifica la dificultad específica en proporcionalidad, y proponer una estrategia de refuerzo focalizada en ese tipo de problema para el siguiente periodo.',
  'opcion_c': 'Diseñar, junto con el equipo de matemáticas, una secuencia didáctica específica sobre proporcionalidad para reforzar esa dificultad puntual antes de la siguiente evaluación institucional del área.',
  'opcion_d': 'Reportar el resultado general a coordinación sin haber revisado el detalle pregunta por pregunta, y proponer repetir exactamente la misma estrategia general de todo el periodo en el siguiente.',
  'tipo_item': 'menos_adecuada',
  'idoneidad': {'a': 3, 'b': 4, 'c': 3, 'd': 0},
  'respuesta_correcta': 'D',
  'nivel_dificultad': 'muy_alto',
  'proceso_cognitivo': 'evaluacion_juicio',
  'justificacion': 'D tiene la idoneidad más baja porque, a pesar de contar con un análisis detallado que identifica con precisión la causa específica del resultado bajo (la proporcionalidad), reporta solo el dato general y repite la misma estrategia sin ningún ajuste, desaprovechando la información más valiosa que él mismo generó para mejorar el resultado del siguiente periodo.\n\nB (idoneidad 4) es la respuesta más adecuada porque usa el análisis detallado como base para una propuesta de ajuste concreto y focalizado, comunicando con transparencia tanto el resultado como la causa identificada.\n\nC (idoneidad 3) y A (idoneidad 3) son también respuestas orientadas al logro y basadas en la evidencia detallada, cercanas a la ideal: C traduce el hallazgo en una acción pedagógica concreta con el equipo, y A involucra directamente a los estudiantes en el diagnóstico; ambas son valiosas, aunque ninguna incluye el paso adicional de informar formalmente a coordinación como sí hace B.\n\nError frecuente del aspirante: Reportar únicamente el resultado general de una evaluación sin aprovechar un análisis detallado ya disponible que podría orientar de forma mucho más precisa el ajuste necesario para el siguiente periodo.\n\nEstrategia mental recomendada: Ante una pregunta de tipo MENOS adecuada sobre el manejo de un resultado bajo con una causa específica ya identificada, identificar la opción que ignora esa información detallada y repite la misma estrategia sin ningún ajuste.\n\nSubcompetencia: Orientación al logro mediante el uso de análisis detallado de resultados para focalizar el ajuste de estrategia',
  'fuente_normativa': 'Decreto 1290 de 2009 sobre análisis técnico de resultados de evaluación institucional y su uso para el mejoramiento continuo.',
 },
 {
  'codigo': 'MOD06-OL-005',
  'contexto': 'En una institución de Piedecuesta, la docente Angie Ropero se propuso, desde el inicio del año, consolidar un club de ciencias con participación constante de al menos quince estudiantes de bachillerato, una meta que ella misma definió tras notar poco interés institucional previo en actividades científicas extracurriculares. Durante el primer semestre, el club llegó a tener hasta dieciocho estudiantes participando de forma regular, un resultado que superó la meta inicial. Sin embargo, al iniciar el segundo semestre, la participación bajó de forma sostenida hasta solo seis estudiantes en las últimas tres sesiones, una caída que Angie no esperaba después del buen resultado del primer semestre, y que coincide con el cambio de horario del club a un bloque después de la jornada escolar regular, decidido por necesidades de disponibilidad de espacio institucional que no dependían de ella. El rector ha destacado públicamente este club como un ejemplo del interés creciente de la institución por las actividades científicas extracurriculares.',
  'enunciado': '¿Cuál es la respuesta MÁS adecuada que puede tomar Angie frente a esta caída sostenida de participación en el segundo semestre?',
  'opcion_a': 'Indagar directamente con los estudiantes, tanto los que se mantienen como los que dejaron de asistir, las razones concretas de la caída, para identificar si el cambio de horario es la causa principal antes de definir cualquier ajuste.',
  'opcion_b': 'Aceptar la caída de participación como algo normal en este tipo de actividades extracurriculares, sin indagar ninguna causa concreta ni proponer ningún ajuste para el resto del año.',
  'opcion_c': 'Cerrar por completo el club de ciencias, considerando que el resultado del segundo semestre demuestra que la meta inicial no era sostenible a largo plazo en la institución.',
  'opcion_d': 'Exigir a los estudiantes que dejaron de asistir una justificación formal por escrito de su inasistencia, como condición para poder reincorporarse al club más adelante en el año.',
  'tipo_item': 'mas_adecuada',
  'idoneidad': {'a': 4, 'b': 1, 'c': 0, 'd': 2},
  'respuesta_correcta': 'A',
  'nivel_dificultad': 'alto',
  'proceso_cognitivo': 'evaluacion_juicio',
  'justificacion': 'A logra la idoneidad máxima porque indaga directamente las causas concretas de la caída antes de asumir ninguna explicación ni proponer ningún ajuste, permitiendo identificar con evidencia real si el cambio de horario (un factor fuera de su control directo) es efectivamente la causa principal, y a partir de ahí definir una respuesta pertinente.\n\nD (idoneidad 2) es una medida de control que no resuelve la causa real de la caída y puede incluso desincentivar aún más el regreso de los estudiantes que dejaron de asistir.\n\nB (idoneidad 1) renuncia a cualquier gestión activa frente a una caída sostenida y significativa, normalizándola sin ninguna indagación que permita entender qué está ocurriendo realmente.\n\nC (idoneidad 0) es la opción más problemática: cierra por completo una iniciativa que había superado su meta inicial en el primer semestre, sin haber indagado antes si la causa de la caída es un factor externo y potencialmente ajustable como el cambio de horario.\n\nError frecuente del aspirante: Interpretar una caída de participación como una señal automática de que la meta original no era viable, sin indagar primero si existe una causa externa concreta y potencialmente ajustable detrás del cambio.\n\nEstrategia mental recomendada: Ante una pregunta de tipo MÁS adecuada sobre una caída sostenida en el avance de una meta ya alcanzada previamente, identificar la opción que indaga las causas concretas antes de aceptar, cerrar o sancionar sin evidencia.\n\nSubcompetencia: Orientación al logro mediante la indagación de causas ante una caída de resultados previamente alcanzados',
  'fuente_normativa': 'Lineamientos institucionales sobre proyectos extracurriculares y su sostenibilidad dentro de la jornada escolar.',
 },
 {
  'codigo': 'MOD06-OL-006',
  'contexto': 'En una institución de San Vicente del Caguán, el docente Deiby Perdomo lidera desde hace dos años un proyecto de huerta escolar con enfoque en seguridad alimentaria, que se propuso ampliar este año a un nuevo objetivo: que los estudiantes de grado noveno documenten científicamente el proceso completo de cultivo de al menos tres especies distintas, como insumo para un proyecto de feria de ciencias departamental programada para dentro de cuatro meses. A la mitad del plazo disponible, Deiby revisa el avance y encuentra que la documentación de dos de las tres especies va según lo planeado, pero la tercera especie, más sensible a las condiciones climáticas de la región, ha tenido un desarrollo mucho más lento de lo esperado debido a una temporada de lluvias inusualmente prolongada ese año, lo que compromete seriamente la posibilidad de completar su documentación a tiempo para la feria departamental. Esta sería la primera vez que la institución participa en la feria departamental de ciencias, y el rector ha expresado su expectativa de que la experiencia se convierta en un proyecto anual permanente.',
  'enunciado': '¿Cuál es la respuesta MENOS adecuada que podría dar Deiby frente a este atraso en una de las tres especies documentadas?',
  'opcion_a': 'Consultar con un ingeniero agrónomo o experto local disponible sobre alternativas viables para acelerar de forma responsable el desarrollo de la tercera especie dentro del tiempo restante.',
  'opcion_b': 'No hacer ningún ajuste al plan original y esperar a que la tercera especie complete su ciclo natural, aunque eso signifique no tener la documentación lista para la fecha de la feria departamental.',
  'opcion_c': 'Evaluar junto con los estudiantes si conviene sustituir la tercera especie por otra con un ciclo de desarrollo más corto y compatible con el tiempo restante antes de la feria.',
  'opcion_d': 'Documentar de forma completa las dos especies que sí van según lo planeado, y presentar el caso de la tercera como un análisis de las limitaciones climáticas reales, un hallazgo también valioso.',
  'tipo_item': 'menos_adecuada',
  'idoneidad': {'a': 3, 'b': 0, 'c': 3, 'd': 4},
  'respuesta_correcta': 'B',
  'nivel_dificultad': 'muy_alto',
  'proceso_cognitivo': 'evaluacion_juicio',
  'justificacion': 'B tiene la idoneidad más baja porque, ante un atraso real que compromete directamente el plazo de la feria departamental, no gestiona ningún ajuste ni alternativa, dejando el resultado librado por completo a un factor climático que ya se sabe que está afectando negativamente el desarrollo de la tercera especie.\n\nD (idoneidad 4) es la respuesta más adecuada porque convierte una limitación real en un hallazgo científico legítimo y presentable, sosteniendo el propósito educativo del proyecto sin forzar un resultado que las condiciones climáticas no permiten.\n\nA (idoneidad 3) y C (idoneidad 3) son también respuestas activas y razonables ante el atraso, cercanas a la ideal: A busca asesoría experta para intentar acelerar el proceso de forma responsable, y C explora sustituir la especie por una más viable en el tiempo restante; ambas son gestiones válidas, aunque D aprovecha mejor la situación real sin depender de una intervención externa incierta.\n\nError frecuente del aspirante: Asumir que "no intervenir" ante un obstáculo real y esperar el desenlace natural es una forma prudente de manejar un atraso, cuando en realidad la orientación al logro exige explorar activamente alternativas viables dentro del tiempo disponible.\n\nEstrategia mental recomendada: Ante una pregunta de tipo MENOS adecuada sobre un atraso causado por un factor externo real, identificar la opción que no gestiona ningún ajuste ni alternativa, dejando el resultado completamente librado al factor externo.\n\nSubcompetencia: Orientación al logro ante atrasos generados por factores externos no controlables dentro de un plazo fijo',
  'fuente_normativa': 'Lineamientos del MEN sobre proyectos pedagógicos productivos y su articulación con ferias de ciencia y tecnología departamentales.',
 },
 {
  'codigo': 'MOD06-OL-007',
  'contexto': 'En una institución de Villa del Rosario, la docente Katherine Zambrano se propuso, junto con el equipo de convivencia, reducir en un tercio el número de casos de conflictos entre estudiantes reportados en el observador durante el año, una meta ambiciosa acordada con el rector a comienzo del año escolar. Al llegar al segundo periodo, Katherine revisa las cifras y encuentra que el número de casos reportados apenas ha bajado en un cinco por ciento frente al año anterior, un avance mucho menor al esperado según el ritmo necesario para alcanzar la meta del tercio al final del año. Al revisar el detalle de los casos, Katherine identifica que la mayoría de los reportes recientes provienen de un mismo grupo de estudiantes de grado octavo, mientras que en el resto de grados el número de casos sí muestra una tendencia más cercana a la meta acordada con el rector. El rector le ha pedido a Katherine un informe de seguimiento antes del cierre del segundo periodo, con una explicación clara de por qué el avance general ha sido tan limitado hasta ahora.',
  'enunciado': '¿Cuál es la respuesta MÁS adecuada que puede tomar Katherine frente a este avance insuficiente, concentrado principalmente en un solo grupo?',
  'opcion_a': 'Reportar al rector que la meta acordada no es alcanzable este año, sin proponer ningún ajuste de estrategia diferenciado para el grupo donde se concentran los casos.',
  'opcion_b': 'Mantener la misma estrategia general de convivencia para todos los grupos por igual, confiando en que el grupo de grado octavo mejorará junto con el resto sin ninguna intervención adicional.',
  'opcion_c': 'Reducir la meta original solo para el grupo de grado octavo, dejando que ese grupo tenga un estándar distinto al resto de la institución durante lo que queda del año.',
  'opcion_d': 'Diseñar, junto con el equipo de convivencia, una intervención específica y focalizada para el grupo de grado octavo, manteniendo la estrategia general para el resto de grados que ya muestra una tendencia positiva.',
  'tipo_item': 'mas_adecuada',
  'idoneidad': {'a': 0, 'b': 2, 'c': 1, 'd': 4},
  'respuesta_correcta': 'D',
  'nivel_dificultad': 'alto',
  'proceso_cognitivo': 'evaluacion_juicio',
  'justificacion': 'D logra la idoneidad máxima porque usa el análisis detallado (la concentración de casos en un solo grupo) para diseñar una intervención focalizada exactamente donde se necesita, sin desmontar la estrategia general que ya funciona bien en el resto de la institución.\n\nB (idoneidad 2) mantiene el esfuerzo general, pero al no focalizar la intervención en el grupo donde se concentra el problema, arriesga seguir sin avance suficiente en ese grupo específico durante el resto del año.\n\nC (idoneidad 1) ajusta la meta hacia abajo justo para el grupo que más necesita la intervención, en lugar de intensificar el esfuerzo donde realmente se requiere.\n\nA (idoneidad 0) es la opción más problemática: declara la meta inalcanzable sin haber propuesto ningún ajuste de estrategia, a pesar de contar con información precisa sobre dónde se concentra el problema.\n\nError frecuente del aspirante: Asumir que un avance insuficiente en una meta institucional exige necesariamente reducir la ambición de la meta, sin explorar antes si una intervención focalizada en la causa identificada puede acercar al cumplimiento original.\n\nEstrategia mental recomendada: Ante una pregunta de tipo MÁS adecuada sobre un avance insuficiente concentrado en una causa específica identificada, identificar la opción que diseña una intervención focalizada en esa causa, sin renunciar a la meta general ni desmontar lo que ya funciona.\n\nSubcompetencia: Orientación al logro mediante la focalización de estrategias en la causa específica de un avance insuficiente',
  'fuente_normativa': 'Ley 1620 de 2013 sobre el Sistema Nacional de Convivencia Escolar y el seguimiento de metas institucionales de convivencia.',
 },
 {
  'codigo': 'MOD06-OL-008',
  'contexto': 'En una institución de Ocaña, el docente Jhon Contreras se propuso, junto con el área de tecnología, que todos los estudiantes de grado décimo desarrollaran y presentaran un proyecto funcional de robótica básica antes del cierre del año, una meta ambiciosa considerando que la institución solo cuenta con un kit compartido de materiales para todo el grado. Faltando seis semanas para la fecha límite ya acordada con coordinación académica, Jhon revisa el avance y encuentra que, debido a la limitación del único kit compartido, varios grupos de estudiantes apenas han podido empezar la construcción física de su proyecto, mientras que el diseño teórico y la programación ya están prácticamente terminados en la mayoría de los grupos, un desfase que pone en riesgo real que todos los proyectos lleguen completos y funcionales a la fecha de presentación final ya comprometida con coordinación. Este es el primer año en que el área de tecnología incluye un componente práctico de esta magnitud en el plan de estudios de grado décimo.',
  'enunciado': '¿Cuál es la respuesta MENOS adecuada que podría dar Jhon frente a esta limitación de materiales, a seis semanas del cierre del proyecto?',
  'opcion_a': 'Gestionar con coordinación académica un horario rotativo más intensivo del kit compartido para las seis semanas restantes, priorizando a los grupos con mayor atraso en la construcción física.',
  'opcion_b': 'Explorar con los estudiantes alternativas de materiales caseros o reciclados que permitan avanzar en paralelo con la construcción física, sin depender exclusivamente del kit compartido disponible.',
  'opcion_c': 'Mantener el mismo horario de uso del kit compartido que se ha usado durante todo el año, sin ninguna gestión adicional frente al riesgo real de no completar los proyectos a tiempo.',
  'opcion_d': 'Ajustar el criterio de evaluación final para valorar también el diseño teórico y la programación ya completados, en caso de que algunos grupos no logren terminar la construcción física completa.',
  'tipo_item': 'menos_adecuada',
  'idoneidad': {'a': 4, 'b': 4, 'c': 0, 'd': 2},
  'respuesta_correcta': 'C',
  'nivel_dificultad': 'muy_alto',
  'proceso_cognitivo': 'evaluacion_juicio',
  'justificacion': 'C tiene la idoneidad más baja porque, a pesar de identificar con claridad un riesgo real de incumplimiento de la meta por una limitación de recursos conocida, no gestiona ningún cambio frente a esa limitación, dejando el resultado final librado al mismo ritmo que ya se sabe insuficiente para las seis semanas restantes.\n\nA y B (ambas con la idoneidad más alta, 4) representan las dos formas más efectivas de responder: A gestiona directamente el recurso limitante mediante un uso más intensivo y priorizado, mientras que B crea alternativas de materiales que reducen la dependencia del kit compartido; ambas atacan la causa raíz del atraso desde ángulos distintos y complementarios.\n\nD (idoneidad 2) es una medida razonable de contingencia en la evaluación, pero no resuelve la causa del atraso en la construcción física, solo amortigua su consecuencia final si el problema no se resuelve.\n\nError frecuente del aspirante: Asumir que "seguir con el mismo plan" ante una limitación de recursos ya identificada es una postura neutral o prudente, sin reconocer que la orientación al logro exige gestionar activamente los recursos limitantes cuando el tiempo apremia.\n\nEstrategia mental recomendada: Ante una pregunta de tipo MENOS adecuada sobre una limitación de recursos que amenaza una meta con fecha fija, identificar la opción que no gestiona ningún cambio frente a esa limitación ya conocida.\n\nSubcompetencia: Orientación al logro mediante la gestión activa de recursos limitantes bajo plazos fijos',
  'fuente_normativa': 'Lineamientos del MEN sobre proyectos de tecnología e informática y gestión de recursos educativos compartidos.',
 },
 {
  'codigo': 'MOD06-OL-009',
  'contexto': 'En una institución de Puerto Boyacá, la docente Leidy Salamanca lidera desde hace tres años un proyecto de fortalecimiento en habilidades socioemocionales para grado sexto, un proyecto que este año se propuso extender por primera vez a un componente de seguimiento individual con los diez estudiantes identificados con mayores dificultades de adaptación escolar, una meta más ambiciosa que en años anteriores. A dos meses de finalizar el año, Leidy revisa el avance de este componente nuevo y encuentra que ha logrado hacer seguimiento consistente a solo cuatro de los diez estudiantes priorizados, principalmente porque el tiempo disponible para las sesiones individuales resultó ser mucho menor de lo que había calculado al planear el proyecto a comienzo de año, un cálculo que ahora reconoce que fue demasiado optimista frente a su carga real de trabajo en la institución. El proyecto ha sido reconocido por la secretaría de educación municipal como una experiencia significativa en bienestar escolar durante los últimos dos años consecutivos.',
  'enunciado': '¿Cuál es la respuesta MÁS adecuada que puede tomar Leidy frente a este avance parcial, reconociendo que el cálculo inicial fue poco realista?',
  'opcion_a': 'Reconocer el cálculo inicial poco realista, ajustar las sesiones planeadas para lo que resta del año según el tiempo disponible, y priorizar a los seis estudiantes sin seguimiento aún.',
  'opcion_b': 'Insistir en cumplir la meta original de los diez estudiantes en los dos meses restantes, aunque eso implique reducir drásticamente la calidad de cada sesión individual para poder atender a todos.',
  'opcion_c': 'Mantener el seguimiento únicamente con los cuatro estudiantes ya atendidos, sin ningún plan concreto para los seis restantes antes de que termine el año escolar.',
  'opcion_d': 'Suspender por completo el componente de seguimiento individual para lo que resta del año, dejándolo para el siguiente año escolar sin ningún ajuste intermedio.',
  'tipo_item': 'mas_adecuada',
  'idoneidad': {'a': 4, 'b': 1, 'c': 2, 'd': 0},
  'respuesta_correcta': 'A',
  'nivel_dificultad': 'alto',
  'proceso_cognitivo': 'evaluacion_juicio',
  'justificacion': 'A logra la idoneidad máxima porque reconoce con honestidad el cálculo inicial poco realista, ajusta el plan a partir del tiempo real disponible en lugar de negar la limitación, y prioriza de forma intencionada a los estudiantes que aún no han recibido el seguimiento, maximizando el impacto real de lo que queda del año.\n\nC (idoneidad 2) sostiene lo ya logrado, pero sin ningún plan concreto para los seis estudiantes restantes, dejando sin atender justamente al grupo que motivó la ampliación del proyecto este año.\n\nB (idoneidad 1) prioriza cumplir la cifra original por encima de la calidad real del acompañamiento, lo que puede terminar siendo contraproducente para estudiantes que necesitan un seguimiento genuino, no solo nominal.\n\nD (idoneidad 0) es la opción más problemática: abandona por completo el componente más ambicioso del proyecto de este año, sin intentar ningún ajuste intermedio que permita sostener parte del propósito original.\n\nError frecuente del aspirante: Asumir que reconocer un cálculo inicial poco realista implica renunciar completamente a la meta, en lugar de ajustarla con base en el tiempo real disponible y priorizar el impacto donde más se necesita.\n\nEstrategia mental recomendada: Ante una pregunta de tipo MÁS adecuada sobre el ajuste de una meta con un cálculo inicial poco realista, identificar la opción que reconoce la limitación, ajusta el plan con evidencia y prioriza intencionadamente el impacto restante.\n\nSubcompetencia: Orientación al logro mediante el ajuste realista de metas ante cálculos iniciales poco precisos',
  'fuente_normativa': 'Ley 1620 de 2013 y lineamientos del MEN sobre acompañamiento socioemocional y bienestar escolar.',
 },
 {
  'codigo': 'MOD06-OL-010',
  'contexto': 'En una institución de Líbano, Tolima, el docente Duván Trujillo se propuso, junto con el equipo de bachillerato, que la institución participara por primera vez en una feria departamental de emprendimiento escolar, presentando al menos tres proyectos de estudiantes de grado once, una meta acordada con rectoría a comienzo del año considerando que la institución nunca había participado antes en un evento de este tipo. A un mes de la fecha límite de inscripción, Duván revisa el avance y encuentra que uno de los tres proyectos planeados va muy bien encaminado, otro tiene un avance moderado pero razonable, y el tercero prácticamente no ha tenido ningún desarrollo real porque el grupo de estudiantes responsable ha mostrado poco compromiso constante con las reuniones de trabajo acordadas desde hace dos meses, a pesar de los recordatorios que Duván les ha hecho en varias ocasiones durante ese tiempo. La participación en la feria departamental requiere confirmar los proyectos definitivos con al menos tres semanas de anticipación a la fecha límite de inscripción, según las bases publicadas por la organización del evento.',
  'enunciado': '¿Cuál es la respuesta MÁS adecuada que puede tomar Duván frente a este tercer proyecto sin avance real, a un mes de la fecha límite de inscripción?',
  'opcion_a': 'Reunirse con el grupo del tercer proyecto para entender las causas del bajo compromiso, y definir junto con ellos si conviene retomarlo con alcance ajustado o redirigir el esfuerzo a los otros dos proyectos.',
  'opcion_b': 'Presentar solo los dos proyectos con avance real ante la feria departamental, sin conversar antes con el grupo del tercer proyecto sobre las razones de su bajo compromiso.',
  'opcion_c': 'Insistir en presentar los tres proyectos originalmente planeados, incluido el que no tiene ningún avance real, confiando en que el grupo lo completará a tiempo en el último mes disponible.',
  'opcion_d': 'Asumir personalmente buena parte del trabajo pendiente del tercer proyecto, para garantizar que los tres proyectos lleguen completos a la fecha límite de inscripción sin conversar con el grupo responsable.',
  'tipo_item': 'menos_adecuada',
  'idoneidad': {'a': 4, 'b': 2, 'c': 0, 'd': 1},
  'respuesta_correcta': 'C',
  'nivel_dificultad': 'muy_alto',
  'proceso_cognitivo': 'evaluacion_juicio',
  'justificacion': 'C tiene la idoneidad más baja porque, a pesar de que el grupo ha mostrado un patrón sostenido de bajo compromiso durante dos meses a pesar de varios recordatorios, sostener la expectativa original sin ninguna conversación ni ajuste no está fundamentado en ninguna evidencia real de cambio, arriesgando innecesariamente la meta general de la participación institucional en la feria.\n\nA (idoneidad 4) es la respuesta más adecuada porque indaga las causas concretas del bajo compromiso antes de decidir, y define junto con el grupo una salida realista que puede sostener parte del propósito original sin forzar un resultado poco probable.\n\nB (idoneidad 2) protege la meta general de participación institucional, pero renuncia a conversar con el grupo responsable, perdiendo la oportunidad de entender la causa del bajo compromiso y de ofrecer una salida constructiva.\n\nD (idoneidad 1) resuelve el síntoma asumiendo personalmente el trabajo pendiente, pero sin conversar con el grupo, lo que no aborda la causa real del bajo compromiso y sobrecarga innecesariamente a Duván en el último mes disponible.\n\nError frecuente del aspirante: Sostener una expectativa original sin ajuste alguno frente a un patrón sostenido de bajo desempeño, confundiendo la persistencia ciega con la orientación genuina al logro.\n\nEstrategia mental recomendada: Ante una pregunta de tipo MENOS adecuada sobre un proyecto sin avance real pese a un patrón sostenido de bajo compromiso, identificar la opción que sostiene la expectativa original sin ninguna indagación ni ajuste basado en evidencia.\n\nSubcompetencia: Orientación al logro ante un patrón sostenido de bajo compromiso en un equipo de trabajo con plazo fijo',
  'fuente_normativa': 'Lineamientos del MEN sobre proyectos de emprendimiento escolar y articulación con la media técnica.',
 },
]
