# -*- coding: utf-8 -*-
"""Lote 01 - Modulo: Lectura Critica | Subtema: Inferencia textual.
Construido siguiendo la Constitucion Academica (Cap. 8-11) y el Blueprint
del Banco de Items (Sprint 1). Version 3: posiciones de respuesta correcta
rotadas (ya no todas en A) y referencias de justificacion remapeadas.
"""

ITEMS = [
    {
        'codigo': 'LC-INF-001',
        'contexto': 'En una institución oficial de zona rural, el equipo directivo revisó los registros de asistencia de los últimos dos periodos y encontró que trece estudiantes de básica secundaria acumulaban más de veinte inasistencias no justificadas. Al citar a las familias, la mayoría explicó que sus hijos apoyaban labores agrícolas en las épocas de cosecha, coincidiendo con las fechas de mayor ausentismo. Antes de tomar cualquier decisión, la coordinación consultó el calendario agrícola de la vereda con los presidentes de junta comunal y cruzó esas fechas con el calendario académico institucional. Con esa información, decidió ajustar el calendario de evaluaciones para evitar las semanas de mayor demanda de trabajo en el campo y ofrecer guías de trabajo autónomo que los estudiantes pudieran desarrollar en casa durante los periodos de cosecha, sin perder continuidad en los contenidos del área. La medida se socializó con las familias en la siguiente reunión de escuela de padres.',
        'enunciado': '¿Qué se puede inferir de la decisión tomada por la coordinación?',
        'opcion_a': 'Que reconoció una causa estructural del ausentismo y ajustó su propia planeación institucional en lugar de sancionar únicamente a las familias afectadas.',
        'opcion_b': 'Que consideró injustificadas las inasistencias reportadas y buscó una forma de registrar la falta sin afectar el promedio de asistencia general.',
        'opcion_c': 'Que decidió eliminar por completo la exigencia académica durante la temporada de cosecha para no generar conflictos con las familias.',
        'opcion_d': 'Que trasladó toda la responsabilidad del aprendizaje a las familias mientras dure la temporada agrícola en la vereda.',
        'respuesta_correcta': 'A',
        'nivel_dificultad': 'medio',
        'proceso_cognitivo': 'comprension_aplicada',
        'justificacion': 'El texto indica que la institución investigó la causa (consultó el calendario agrícola con la comunidad) y respondió con dos acciones concretas: ajustar el calendario y ofrecer guías de trabajo autónomo — ambas evidencian un ajuste institucional deliberado, no una tolerancia pasiva ni una sanción. La opción B invierte el sentido del texto: no hay mención de registro de faltas ni de proteger un indicador. La opción C exagera: el texto dice que se mantiene la continuidad de contenidos mediante guías, no que se elimina la exigencia. La opción D contradice el texto explícitamente, ya que la institución sigue acompañando el proceso con material de trabajo.',
    },
    {
        'codigo': 'LC-INF-002',
        'contexto': 'Un colegio urbano implementó una huerta escolar como proyecto transversal entre las áreas de ciencias naturales y ética. Durante el primer semestre, los estudiantes de grado sexto se encargaron de sembrar y llevar un registro fotográfico semanal del crecimiento de las plantas, mientras que los de grado once asumieron la coordinación de turnos de riego, el control de plagas y la elaboración de informes de avance que debían entregar cada quince días al docente líder del proyecto. Al finalizar el periodo, ese docente organizó una puesta en común con los profesores de otras asignaturas y allí surgieron dos observaciones coincidentes: los estudiantes de sexto mostraban mayor participación espontánea en las discusiones de clase sobre ecosistemas, mientras que los de once habían mejorado de forma notoria la puntualidad en la entrega de informes de otras asignaturas distintas al proyecto de huerta. Ninguna de las dos mejoras había sido un objetivo explícito al diseñar el proyecto.',
        'enunciado': '¿Qué puede inferirse razonablemente de las observaciones compartidas por los docentes?',
        'opcion_a': 'Que el proyecto de huerta escolar debería reemplazar por completo la enseñanza tradicional de ciencias naturales en toda la institución.',
        'opcion_b': 'Que el proyecto generó efectos formativos adicionales a los inicialmente planeados, distintos según el rol y el nivel de responsabilidad asumido por cada grupo de edad.',
        'opcion_c': 'Que los estudiantes de grado once tenían previamente un desempeño académico deficiente y generalizado en todas sus asignaturas.',
        'opcion_d': 'Que la mejora en la participación de sexto se debe exclusivamente a la novedad de trabajar fuera del salón de clase habitual.',
        'respuesta_correcta': 'B',
        'nivel_dificultad': 'alto',
        'proceso_cognitivo': 'analisis_situacional',
        'justificacion': 'El texto muestra dos efectos distintos y no planeados, cada uno asociado al tipo de responsabilidad asumida (sembrar y observar vs. coordinar, controlar y reportar), lo que sustenta que el proyecto tuvo un efecto formativo diferenciado según el rol. La opción A es una generalización indebida que el texto no sustenta en absoluto. La opción C afirma algo no dicho: el texto no menciona el desempeño previo de once en otras áreas, solo la puntualidad de entregas después del proyecto. La opción D atribuye la mejora a una causa única (la novedad del espacio) que el texto nunca menciona como explicación.',
    },
    {
        'codigo': 'LC-INF-003',
        'contexto': 'Una docente de matemáticas de grado octavo notó, revisando los tiempos de entrega de tres evaluaciones consecutivas, que un grupo de estudiantes con buen desempeño terminaba muy rápido y esperaba en silencio el resto de la clase, mientras otro grupo con dificultades apenas alcanzaba a resolver la mitad de los ejercicios en el tiempo disponible. Decidió entonces implementar un sistema de tutorías entre pares: los estudiantes que terminaban primero debían explicar en voz alta a un compañero con dificultades un ejercicio ya resuelto, señalando paso a paso su razonamiento, antes de que ambos revisaran juntos un ejercicio nuevo del mismo tema. Tras un mes de aplicar esta rutina en cada clase, la docente notó que las calificaciones del grupo con dificultades subieron de forma moderada pero sostenida, y además comenzó a recibir, de parte de los estudiantes que antes terminaban rápido y guardaban silencio, más preguntas de aclaración durante el desarrollo de la clase.',
        'enunciado': '¿Qué inferencia sobre los estudiantes que antes terminaban rápido está mejor sustentada por el texto?',
        'opcion_a': 'Que su desempeño académico bajó de forma directa como consecuencia de dedicar tiempo de clase a explicarle a sus compañeros con dificultades.',
        'opcion_b': 'Que estaban en franco desacuerdo con el nuevo sistema de tutorías entre pares implementado por la docente de matemáticas.',
        'opcion_c': 'Que el ejercicio de explicar a otros los llevó a cuestionar aspectos de su propia comprensión que antes no verbalizaban durante la clase.',
        'opcion_d': 'Que preferían trabajar en silencio y que el cambio metodológico afectó negativamente su motivación hacia la asignatura.',
        'respuesta_correcta': 'C',
        'nivel_dificultad': 'alto',
        'proceso_cognitivo': 'analisis_situacional',
        'justificacion': 'El texto conecta el nuevo rol de explicar (que exige verbalizar el propio razonamiento paso a paso) con el aumento posterior de preguntas de aclaración de ese mismo grupo — un patrón consistente con que el acto de enseñar a otros expuso vacíos de comprensión que antes no se manifestaban en el silencio. La opción A afirma una baja de desempeño que el texto no menciona en absoluto. Las opciones B y D interpretan las nuevas preguntas como señal de desacuerdo o desmotivación, cuando el texto no ofrece ninguna evidencia de actitud negativa hacia el cambio metodológico.',
    },
    {
        'codigo': 'LC-INF-004',
        'contexto': 'La biblioteca de una institución educativa de jornada única registró que el préstamo de libros de ficción aumentó de forma considerable después de que el equipo de docentes de lenguaje comenzó a dedicar los primeros diez minutos de cada clase a que los estudiantes comentaran en parejas qué estaban leyendo por gusto propio, sin que esa lectura tuviera ninguna calificación asociada ni fuera parte del plan de área formal. El bibliotecario llevó un conteo mensual de préstamos por categoría durante todo el semestre y confirmó que el aumento se concentraba específicamente en literatura juvenil, no en otros géneros de la colección, y que la mayoría de los préstamos correspondía a estudiantes que antes no figuraban entre los usuarios frecuentes de la biblioteca. Al mismo tiempo, el coordinador académico revisó el promedio de calificaciones en las pruebas formales de comprensión lectora del área, aplicadas al final de cada periodo, y encontró que ese promedio se mantuvo prácticamente igual al del periodo anterior, sin cambios significativos en ningún grado de la institución.',
        'enunciado': '¿Qué conclusión es más coherente con la información presentada en el texto?',
        'opcion_a': 'La estrategia de los diez minutos fracasó por completo, ya que no logró ningún efecto observable en los estudiantes de la institución.',
        'opcion_b': 'Las pruebas formales de comprensión lectora dejaron de ser, a partir de ese momento, un indicador válido para medir el aprendizaje del área.',
        'opcion_c': 'El aumento en el préstamo de libros se debe a que los docentes comenzaron a calificar la lectura por gusto propio de los estudiantes.',
        'opcion_d': 'El hábito de lectura por gusto propio aumentó de forma medible, sin que ese cambio se haya reflejado todavía en los resultados de las pruebas formales del área.',
        'respuesta_correcta': 'D',
        'nivel_dificultad': 'medio',
        'proceso_cognitivo': 'comprension_aplicada',
        'justificacion': 'El texto reporta dos datos verificados por separado (conteo del bibliotecario y revisión del coordinador) sin relacionarlos causalmente entre sí: aumento de préstamos concentrado en ficción juvenil, y estabilidad en las pruebas formales — la lectura más precisa es que un efecto ya se observa mientras el otro aún no, no que uno anule al otro. La opción A ignora el dato real y verificado del aumento de préstamos. La opción B es una generalización indebida sobre la validez de las pruebas que el texto no sustenta. La opción C contradice el texto, que dice explícitamente que la lectura no tenía calificación asociada.',
    },
    {
        'codigo': 'LC-INF-005',
        'contexto': 'Durante una jornada de capacitación institucional en herramientas digitales, un grupo de docentes con más de quince años de experiencia mostró resistencia inicial a usar una nueva plataforma para registrar calificaciones, argumentando en la sesión que el sistema anterior en papel les permitía revisar el progreso de cada estudiante con mayor rapidez durante las reuniones de comisión de evaluación. La coordinación académica decidió, de todas formas, hacer obligatorio su uso a partir del siguiente periodo, y ofreció una mesa de ayuda presencial durante las dos primeras semanas para resolver dudas puntuales sobre el registro básico de notas. Pasado ese tiempo, varios de esos mismos docentes comenzaron a usar por iniciativa propia una función de la plataforma que no había sido explicada ni en la capacitación inicial ni en la mesa de ayuda: generar gráficas de progreso individual para compartir con los acudientes en las reuniones de entrega de informes del periodo.',
        'enunciado': '¿Qué puede inferirse sobre estos docentes a partir del uso de la nueva función?',
        'opcion_a': 'Su resistencia inicial no impidió que, una vez familiarizados con la herramienta, identificaran por su cuenta una utilidad práctica que superó su objeción original sobre la rapidez.',
        'opcion_b': 'La capacitación institucional recibida fue insuficiente, ya que estos docentes tuvieron que aprender a usar la plataforma completamente solos y sin ningún apoyo.',
        'opcion_c': 'Los docentes cambiaron de opinión sobre la plataforma únicamente porque la coordinación los obligó a usarla durante dos semanas seguidas.',
        'opcion_d': 'El sistema en papel que usaban antes era, en todos los aspectos posibles, claramente inferior a la nueva plataforma digital institucional.',
        'respuesta_correcta': 'A',
        'nivel_dificultad': 'alto',
        'proceso_cognitivo': 'analisis_situacional',
        'justificacion': 'El texto muestra una progresión clara: resistencia inicial fundamentada → uso obligatorio con apoyo básico → adopción voluntaria de una función no enseñada por nadie, lo que sustenta que encontraron un valor práctico propio, más allá de la obligación. La opción B interpreta el autoaprendizaje de una función adicional como fracaso de la capacitación, cuando el texto aclara que sí hubo mesa de ayuda para lo básico. La opción C reduce el cambio únicamente a la obligatoriedad, ignorando que la función usada ni siquiera fue parte de lo enseñado. La opción D es una generalización que el texto no permite: solo se menciona una ventaja puntual del sistema en papel, no una comparación completa entre ambos sistemas.',
    },
    {
        'codigo': 'LC-INF-006',
        'contexto': 'En un colegio con antecedentes de conflictos frecuentes entre estudiantes de grado noveno, documentados en el observador durante los dos años anteriores, el equipo de convivencia implementó círculos de diálogo semanales en lugar del procedimiento disciplinario habitual para faltas leves relacionadas con conflictos entre compañeros. En los círculos, coordinados por el orientador escolar, los estudiantes involucrados en un conflicto exponían su versión frente al grupo, escuchaban la versión de la otra parte y proponían en conjunto una forma concreta de reparación, que quedaba registrada en un acta breve. Después de un semestre completo de aplicar esta estrategia, el coordinador de convivencia presentó un informe al consejo directivo comparando las cifras con las del semestre anterior, y encontró que el número de remisiones a coordinación por faltas leves bajó de forma notoria, mientras que el número de remisiones por faltas graves, que seguían gestionándose con el procedimiento disciplinario tradicional sin ningún cambio, se mantuvo prácticamente estable, sin variaciones relevantes respecto al periodo anterior.',
        'enunciado': '¿Qué inferencia es más precisa a partir de estos resultados comparados por el coordinador?',
        'opcion_a': 'Los círculos de diálogo demostraron ser una estrategia ineficaz, ya que no lograron reducir ningún tipo de conflicto grave dentro de la institución.',
        'opcion_b': 'Los círculos de diálogo parecen haber sido efectivos específicamente para las situaciones antes gestionadas como faltas leves, sin que el texto permita concluir nada sobre su efecto en las faltas graves.',
        'opcion_c': 'El número de faltas graves se mantuvo igual porque los estudiantes dejaron de reportar voluntariamente los conflictos más serios que vivían.',
        'opcion_d': 'La estrategia de círculos de diálogo debe eliminarse ya porque no logró un impacto medible sobre la totalidad de los conflictos institucionales.',
        'respuesta_correcta': 'B',
        'nivel_dificultad': 'muy_alto',
        'proceso_cognitivo': 'evaluacion_juicio',
        'justificacion': 'El texto reporta un cambio medible en un tipo de falta (leve, gestionada con la nueva estrategia) y ausencia de cambio en otro (grave, gestionado con el procedimiento tradicional sin modificar); la inferencia correcta reconoce el alcance real del dato sin extrapolar más allá de lo que el texto permite. La opción A ignora la reducción real y documentada en faltas leves. La opción C inventa una causa (subregistro voluntario) que el texto no menciona en absoluto. La opción D concluye una eliminación de la estrategia con base en un resultado parcial, sin que el texto sustente esa conclusión tan amplia.',
    },
    {
        'codigo': 'LC-INF-007',
        'contexto': 'Una institución con preescolar y primaria en la misma sede decidió que, durante el último mes del año escolar, los estudiantes de transición compartieran dos sesiones semanales en el aula de primero, acompañados por su propia docente titular y observados de cerca por la docente titular de primero, quien tomaba notas breves sobre la actitud y el comportamiento de cada niño durante las sesiones compartidas, sin que esas notas formaran parte de ningún informe oficial de evaluación. Al iniciar el año siguiente, con un grupo nuevo ya asignado formalmente a su aula, la docente de primero reportó en la primera reunión de área que el grupo de estudiantes que había participado en esas sesiones de transición se ubicaba de forma notoriamente más rápida en la rutina diaria del aula —organización de materiales, filas, tiempos de trabajo— comparado con lo que ella recordaba, sin registros escritos, de grupos anteriores que no habían tenido ese acompañamiento previo.',
        'enunciado': '¿Qué puede inferirse con mayor precisión de esta observación reportada por la docente?',
        'opcion_a': 'La estrategia de transición garantiza, para cualquier institución que la implemente, un excelente desempeño académico posterior de todos los estudiantes en primero.',
        'opcion_b': 'Los estudiantes de años anteriores que no tuvieron el acompañamiento previo presentaron, según se puede asumir, problemas graves y generalizados de adaptación escolar.',
        'opcion_c': 'La estrategia parece asociada a una adaptación más rápida a la rutina del aula, aunque la comparación se basa en el recuerdo de la docente, no en un registro sistemático previo.',
        'opcion_d': 'La percepción de la docente confirma de manera objetiva y definitiva que la estrategia funciona igual para cualquier institución educativa del país.',
        'respuesta_correcta': 'C',
        'nivel_dificultad': 'muy_alto',
        'proceso_cognitivo': 'evaluacion_juicio',
        'justificacion': "La inferencia más precisa reconoce tanto el hallazgo (adaptación más rápida a rutinas concretas) como su limitación metodológica explícita en el texto (comparación basada en el recuerdo de la docente, no en un registro sistemático). La opción A generaliza a 'excelente desempeño académico' y a 'cualquier institución', algo que el texto no menciona ni permite afirmar. La opción B exagera la situación de los grupos anteriores, de los que el texto solo dice que no tuvieron el acompañamiento, sin mencionar 'problemas graves'. La opción D trata una percepción individual como si fuera una confirmación objetiva y generalizable a otras instituciones, lo que el texto no permite afirmar.",
    },
    {
        'codigo': 'LC-INF-008',
        'contexto': 'Un área de ciencias sociales decidió reemplazar los exámenes escritos tradicionales de fin de periodo por portafolios de evidencia, donde cada estudiante reunía a lo largo del periodo trabajos individuales, mapas conceptuales elaborados en clase y reflexiones escritas sobre su propio proceso de aprendizaje, con una rúbrica común acordada por todo el equipo de docentes del área y socializada con los estudiantes antes de iniciar el periodo. Al calificar los primeros portafolios entregados, los docentes se reunieron en jornada pedagógica para comparar resultados y notaron que varios estudiantes con calificaciones históricamente bajas en los exámenes escritos de periodos anteriores presentaban ahora portafolios completos y bien argumentados según la rúbrica acordada por el equipo docente, mientras que algunos estudiantes con buen historial en exámenes escritos entregaron portafolios incompletos, con trabajos faltantes y muy poca reflexión personal escrita sobre su propio proceso de aprendizaje a lo largo del periodo evaluado por el área.',
        'enunciado': '¿Qué inferencia se sustenta mejor en lo observado por los docentes del área?',
        'opcion_a': 'Los estudiantes con buen historial en exámenes escritos dejaron de esforzarse académicamente por completo durante ese periodo específico del año.',
        'opcion_b': 'El portafolio de evidencia es, en términos generales y para cualquier grupo de estudiantes, una forma de evaluación más fácil que el examen escrito.',
        'opcion_c': 'Los estudiantes con calificaciones históricamente bajas mejoraron de forma generalizada su comprensión conceptual de toda el área de ciencias sociales.',
        'opcion_d': 'El nuevo formato de evaluación puede estar midiendo habilidades distintas a las que evaluaba el examen escrito tradicional, explicando el cambio en el patrón de desempeño de algunos estudiantes.',
        'respuesta_correcta': 'D',
        'nivel_dificultad': 'alto',
        'proceso_cognitivo': 'analisis_situacional',
        'justificacion': 'El texto muestra un cambio de patrón asociado directamente al cambio de formato de evaluación (mismo grupo de estudiantes, misma área, rúbrica nueva), lo que sustenta que el nuevo instrumento capta algo distinto —como organización sostenida o capacidad de reflexión— que el examen escrito no capturaba igual. La opción A atribuye el cambio a falta total de esfuerzo, una causa que el texto no menciona ni sustenta. La opción B hace una generalización sobre la dificultad relativa de los formatos que el texto no permite (solo describe un cambio de patrón puntual, no una comparación general de dificultad). La opción C extiende el hallazgo del portafolio a una mejora general de comprensión de toda el área, algo que el texto no afirma.',
    },
    {
        'codigo': 'LC-INF-009',
        'contexto': 'Al pasar de jornada mixta a jornada única, una institución educativa amplió el tiempo de permanencia diaria de los estudiantes en dos horas adicionales, que el consejo académico decidió destinar a clubes extracurriculares de deporte, arte y robótica, organizados por inscripción voluntaria de cada estudiante al inicio del año escolar, con un profesor encargado de acompañar cada club durante las dos horas adicionales. Un año después de implementado el cambio, el coordinador de convivencia presentó ante el consejo directivo un informe con una disminución sostenida en los reportes de conflicto registrados durante los descansos, comparando cifra por cifra con el año anterior a la jornada única. En la misma sesión, el coordinador académico señaló, a partir de los registros de la secretaría académica, que el número de estudiantes que solicitaron formalmente cambio de colegio durante ese año fue el más bajo de los últimos cinco años registrados en la institución.',
        'enunciado': '¿Qué inferencia es razonable a partir de los dos datos presentados ante el consejo?',
        'opcion_a': 'Ambos indicadores son coherentes con una mayor vinculación de los estudiantes con la institución, aunque el texto no establece una relación causal exclusiva entre la jornada única y esos resultados.',
        'opcion_b': 'La jornada única es la única causa comprobada y demostrada de la disminución en los conflictos y en las solicitudes de cambio de colegio.',
        'opcion_c': 'Los clubes extracurriculares de deporte, arte y robótica eliminaron por completo cualquier tipo de conflicto entre estudiantes durante los descansos.',
        'opcion_d': 'El coordinador académico y el coordinador de convivencia diseñaron en conjunto, desde el inicio, los nuevos clubes extracurriculares de la institución.',
        'respuesta_correcta': 'A',
        'nivel_dificultad': 'muy_alto',
        'proceso_cognitivo': 'evaluacion_juicio',
        'justificacion': "La inferencia más cuidadosa reconoce que ambos datos son coherentes con una mayor vinculación institucional de los estudiantes, sin afirmar una relación causal exclusiva que el texto no establece explícitamente (podría haber otros factores concurrentes). La opción B afirma una causalidad única y comprobada con un nivel de certeza que el texto no sustenta. La opción C exagera a 'eliminaron por completo', cuando el texto solo habla de una disminución sostenida. La opción D introduce información sobre un diseño conjunto desde el inicio que el texto nunca menciona.",
    },
    {
        'codigo': 'LC-INF-010',
        'contexto': 'Un docente de tecnología e informática notó, revisando los registros de tres evaluaciones prácticas consecutivas, que en las actividades de manejo de hojas de cálculo los estudiantes que primero explicaban en voz alta a un compañero los pasos que iban a seguir cometían de forma consistente menos errores que quienes trabajaban en completo silencio desde el inicio del ejercicio. Decidió entonces pedir a todo el grupo que, antes de comenzar cualquier ejercicio práctico nuevo, describieran en parejas y en voz alta el procedimiento completo que planeaban usar, antes de tocar el computador. Tras aplicar esta rutina durante un mes en todas las clases prácticas, el docente comparó los registros de tiempo y encontró que el tiempo promedio que el grupo tardaba en completar los ejercicios disminuyó de forma clara, aunque, al mismo tiempo, la cantidad de preguntas dirigidas directamente al docente durante el desarrollo de la actividad aumentó respecto al mes anterior.',
        'enunciado': '¿Qué inferencia explica mejor el conjunto de los dos cambios observados tras la nueva rutina?',
        'opcion_a': 'El aumento de preguntas indica que la nueva rutina confundió a los estudiantes y los volvió más dependientes del docente que antes de aplicarla.',
        'opcion_b': 'Verbalizar el procedimiento antes de ejecutarlo parece ayudar a planear con más claridad, lo cual explicaría la mayor eficiencia y las preguntas más específicas que antes no se formulaban.',
        'opcion_c': 'La disminución en el tiempo de ejecución se debe únicamente a que los ejercicios de ese mes eran más sencillos que los del mes anterior.',
        'opcion_d': 'Los estudiantes que trabajaban en silencio desde el inicio tenían, en general, un nivel de manejo de la herramienta más bajo que el resto del grupo.',
        'respuesta_correcta': 'B',
        'nivel_dificultad': 'alto',
        'proceso_cognitivo': 'analisis_situacional',
        'justificacion': 'El texto conecta ambos cambios (menos tiempo, más preguntas) con la misma causa plausible: planear en voz alta hace visibles dudas específicas que antes quedaban sin resolver en silencio, mejorando a la vez la eficiencia general del grupo. La opción A interpreta el aumento de preguntas como confusión, sentido opuesto al que sugiere el texto (preguntas más específicas, no señales de desorientación generalizada). La opción C atribuye la mejora a una causa externa (ejercicios más fáciles) que el texto no menciona en ningún momento. La opción D generaliza sobre el nivel previo de los estudiantes que trabajaban en silencio, algo que el texto no afirma.',
    },
]
