# -*- coding: utf-8 -*-
"""Piloto v2 - Modulo: Lectura Critica | Subtema: Inferencia textual.
Construido bajo la nueva etapa "Validacion Cognitiva del Item" (Constitucion
Academica, Cap. 11.0), tras el rechazo del Lote 01 por insuficiencia
cognitiva. NO IMPORTAR A LA BASE DE DATOS todavia: pendiente de aprobacion
explicita del usuario. Estos 5 items son de revision, no un lote de
construccion masiva.

Cada item integra lectura critica con un segundo proceso (juicio
profesional, analisis pedagogico o interpretacion normativa), evita el
patron de distractor invertir/exagerar/contradecir, y exige comparar al
menos dos opciones genuinamente plausibles antes de decidir cual es la
mejor decision, no solo la unica compatible con el texto.
"""

ITEMS = [
    {
        'codigo': 'LC-INF-P01',
        'contexto': 'La comisión de evaluación y promoción de una institución educativa se reunió para revisar el caso de una estudiante de grado noveno que, según el consolidado de calificaciones del primer periodo, obtuvo un promedio de 2.6 en el área de ciencias naturales, por debajo del mínimo aprobatorio establecido en el Sistema Institucional de Evaluación de los Estudiantes (SIEE). Al revisar el expediente, la comisión encontró que la estudiante estuvo incapacitada durante cuatro semanas por una cirugía programada, ausencia reportada oportunamente por la familia y registrada por la secretaría académica. El SIEE de la institución contempla, para casos de ausencia justificada y prolongada, la aplicación de un plan de apoyo con actividades de nivelación y una evaluación de recuperación al reintegro del estudiante. La docente del área diseñó e implementó ese plan: la estudiante presentó las actividades de nivelación y la evaluación de recuperación, obteniendo un desempeño alto en ambas. Sin embargo, al calcular la nota definitiva del periodo, el sistema de calificaciones promedió automáticamente esos resultados con la nota de 0.0 que había quedado registrada durante las semanas de incapacidad, arrojando un promedio final insuficiente pese al desempeño demostrado tras el reintegro.',
        'enunciado': '¿Cuál es la decisión que mejor concilia lo dispuesto en el SIEE institucional con los principios del Decreto 1290 de 2009 frente a este caso?',
        'opcion_a': 'Valorar el desempeño final de la estudiante con base en el plan de apoyo y la evaluación de recuperación ya aplicados, sin promediarlos con la nota de 0.0 registrada durante la incapacidad, dado que el Decreto 1290 exige una evaluación continua e integral y el propio SIEE previó ese plan precisamente para casos como este.',
        'opcion_b': 'Mantener el promedio simple que arrojó el sistema de calificaciones, porque ese es el procedimiento formalmente adoptado por la institución y modificarlo sin una reforma previa del SIEE aprobada por el consejo directivo alteraría un criterio ya vigente.',
        'opcion_c': 'Promover automáticamente a la estudiante sin exigir ningún tipo de evaluación adicional, en reconocimiento de que una incapacidad médica prolongada y debidamente justificada no puede tener ningún efecto sobre la valoración del periodo.',
        'opcion_d': 'Remitir el caso directamente a la Secretaría de Educación para que sea esa entidad, y no la institución, quien determine la valoración final del periodo, dado que se trata de una situación médica que excede la competencia de la comisión.',
        'respuesta_correcta': 'A',
        'nivel_dificultad': 'muy_alto',
        'proceso_cognitivo': 'evaluacion_juicio',
        'fuente_normativa': 'Decreto 1290 de 2009, arts. 3 y 4',
        'justificacion': 'El texto documenta que el SIEE ya contempla un plan de apoyo con evaluación de recuperación para ausencias justificadas y prolongadas, que ese plan se aplicó, y que arrojó un desempeño alto: promediarlo con la nota de 0.0 previa contradice el propósito del propio mecanismo institucional y el principio de evaluación continua e integral del Decreto 1290, que exige valorar el proceso, no un promedio aritmético mecánico. La opción B es tentadora porque apela al respeto por lo formalmente adoptado, pero pasa por alto que el SIEE mismo previó una ruta distinta para este caso, así que aplicar el promedio simple ignora una disposición ya vigente, no la respeta. La opción C confunde justificar una ausencia con eximir de evaluación: el Decreto 1290 no exige promoción automática, exige valorar evidencia, y esa evidencia ya existe y es favorable. La opción D traslada a la Secretaría de Educación una competencia que el Decreto 1290 asigna expresamente a la comisión de evaluación y promoción de la institución.',
    },
    {
        'codigo': 'LC-INF-P02',
        'contexto': 'Una estudiante de grado séptimo cuenta con un Plan Individual de Ajustes Razonables (PIAR) vigente, elaborado por el equipo interdisciplinario de la institución con base en un diagnóstico de dislexia. Entre los ajustes registrados en el documento se establece que, en las evaluaciones escritas de cualquier asignatura, la estudiante debe contar con la posibilidad de complementar su respuesta de forma oral cuando el docente lo considere necesario para verificar el aprendizaje evaluado. Un docente nuevo en la institución, que reemplazó a la titular de matemáticas durante una licencia, no fue informado con suficiente antelación del contenido del PIAR y aplicó la prueba escrita de fin de periodo de la misma manera para todo el curso. La estudiante entregó la prueba incompleta y obtuvo una calificación reprobatoria, pese a que, según las anotaciones del observador del estudiante, había participado activamente y con claridad conceptual en las discusiones orales de clase durante todo el periodo. Al conocer la situación, la coordinación académica revisó el caso y el docente argumentó que aplicar un procedimiento distinto para una sola estudiante sería injusto frente al resto del curso, que presentó la misma prueba en las mismas condiciones.',
        'enunciado': '¿Cuál es la interpretación más ajustada a lo establecido en el Decreto 1421 de 2017 frente a la objeción del docente sobre un trato desigual?',
        'opcion_a': 'Aplicar el ajuste previsto en el PIAR no vulnera la igualdad entre estudiantes, porque los ajustes razonables buscan garantizar equidad en el acceso a la evaluación de un aprendizaje ya alcanzado, no otorgar una ventaja sobre un aprendizaje no logrado, y el desempeño oral registrado en el observador es evidencia consistente de ese aprendizaje.',
        'opcion_b': 'Mantener la misma prueba escrita para todo el grupo, porque cualquier variación en el instrumento de evaluación entre estudiantes de un mismo curso compromete la validez comparativa de los resultados frente al resto de la institución.',
        'opcion_c': 'Eximir a la estudiante de toda evaluación escrita en las demás asignaturas de forma permanente, dado que su diagnóstico de dislexia representa una condición que impide de manera generalizada el desarrollo de pruebas escritas.',
        'opcion_d': 'Citar nuevamente al equipo interdisciplinario para reformular desde cero el PIAR antes de modificar la calificación ya obtenida, dado que el docente que aplicó la prueba desconocía el contenido del documento vigente.',
        'respuesta_correcta': 'A',
        'nivel_dificultad': 'muy_alto',
        'proceso_cognitivo': 'evaluacion_juicio',
        'fuente_normativa': 'Decreto 1421 de 2017, art. 2.3.3.5.2.3.5',
        'justificacion': 'El PIAR ya establece el ajuste y el observador ya documenta el aprendizaje oral logrado por la estudiante durante el periodo: la decisión correcta es aplicar lo ya vigente, distinguiendo entre igualdad de instrumento y equidad de acceso. La opción B es la más tentadora porque suena rigurosa desde la lógica de la comparabilidad psicométrica, pero esa lógica solo es válida cuando no existe una barrera documentada de acceso; aplicarla aquí ignora que el instrumento igual produce, para esta estudiante, una medición distinta del aprendizaje real. La opción C toma un ajuste puntual y documentado (complementar por vía oral en evaluaciones escritas) y lo generaliza a una exención total no prevista en el PIAR, sobrepasando lo que el propio documento establece. La opción D es tentadora porque parece una ruta procedimental cuidadosa, pero desconoce que el PIAR ya es un documento vigente y vinculante: el problema no es su contenido sino que no se aplicó, así que reabrir el proceso completo retrasa innecesariamente una corrección que ya tiene sustento documental.',
    },
    {
        'codigo': 'LC-INF-P03',
        'contexto': 'Durante el descanso, dos estudiantes de grado décimo protagonizaron una pelea que dejó golpes visibles en ambos y que fue registrada por varios compañeros con sus teléfonos. El rector, al conocer los hechos esa misma tarde, propuso aplicar de inmediato la sanción máxima prevista en el manual de convivencia para agresión física, por igual, a los dos estudiantes involucrados, argumentando que ambos se agredieron mutuamente y que actuar de otra manera sería injusto frente al resto de la comunidad educativa. Al revisar los antecedentes en la coordinación de convivencia, sin embargo, apareció que uno de los dos estudiantes había presentado, en los tres meses anteriores, al menos cuatro reportes escritos por presunto acoso reiterado por parte del otro estudiante —burlas constantes frente al grupo, publicaciones ofensivas en una red social y aislamiento deliberado en actividades grupales—, reportes que quedaron registrados en el observador pero que nunca fueron remitidos al comité escolar de convivencia ni derivaron en ninguna actuación institucional. El día de los hechos, según los testigos, el estudiante que había reportado el acoso reaccionó físicamente después de una burla adicional del otro estudiante frente al curso.',
        'enunciado': '¿Cuál es la actuación institucional más ajustada a la ruta de atención integral prevista en la Ley 1620 de 2013, considerando los antecedentes del caso?',
        'opcion_a': 'El comité de convivencia debe activar la ruta de atención integral, documentar los antecedentes de acoso previamente reportados y no atendidos, y definir medidas diferenciadas según la responsabilidad y el contexto de cada estudiante, en lugar de aplicar automáticamente la misma sanción a ambos por el solo hecho de haberse agredido mutuamente.',
        'opcion_b': 'Sancionar a ambos estudiantes de forma idéntica, dado que la agresión física fue mutua y visible, y otorgar un tratamiento diferenciado en este momento podría interpretarse como una decisión arbitraria del comité frente a hechos objetivamente equivalentes.',
        'opcion_c': 'Remitir el caso directamente a la Comisaría de Familia y a la Policía de Infancia y Adolescencia sin agotar primero la ruta interna de atención integral, dado que hubo lesiones físicas visibles entre los dos estudiantes.',
        'opcion_d': 'Sancionar únicamente al estudiante que reaccionó físicamente en el momento de los hechos y cerrar el caso una vez aplicada esa sanción individual, sin necesidad de revisar los reportes previos de acoso que no fueron atendidos.',
        'respuesta_correcta': 'A',
        'nivel_dificultad': 'muy_alto',
        'proceso_cognitivo': 'analisis_situacional',
        'fuente_normativa': 'Ley 1620 de 2013 y Decreto 1965 de 2013, ruta de atención integral',
        'justificacion': 'El texto documenta una agresión física puntual y, a la vez, un historial no atendido de acoso previo contra uno de los dos estudiantes: la Ley 1620 exige que el comité de convivencia examine el contexto y los antecedentes antes de definir la actuación, no que sancione el hecho aislado del momento. La opción B es la más tentadora porque apela a un principio de simetría que suena justo ante hechos "objetivamente equivalentes", pero ignora que la ruta de atención integral exige precisamente valorar el contexto y la responsabilidad diferenciada, no tratar como equivalente lo que el propio expediente muestra que no lo es. La opción C confunde la gravedad de las lesiones con el orden del procedimiento: la ruta interna de documentación y activación del comité debe agotarse y puede coexistir con la remisión externa cuando corresponda, pero omitirla no es lo que exige la norma. La opción D identifica al agresor visible del momento y cierra el caso con eficiencia aparente, pero desatiende la obligación institucional de revisar y actuar sobre los reportes previos de acoso que nunca fueron procesados, una omisión que la propia institución debe subsanar.',
    },
    {
        'codigo': 'LC-INF-P04',
        'contexto': 'Una docente de matemáticas de grado octavo aplicó una evaluación formativa sobre ecuaciones lineales a sus tres cursos y, como parte de su práctica habitual, registró en una rúbrica no solo el puntaje de cada estudiante sino también el tipo de error cometido en las preguntas falladas. Al revisar los dieciocho estudiantes que obtuvieron un puntaje inferior a sesenta sobre cien, encontró tres patrones distintos en sus propias anotaciones: seis estudiantes aplicaron correctamente el procedimiento para despejar la incógnita pero cometieron errores aritméticos simples en operaciones básicas; siete estudiantes utilizaron un procedimiento distinto al de una ecuación lineal, tratándola como si fuera una expresión de simplificación directa, lo que sugiere que no habían comprendido el concepto de igualdad entre ambos lados de la ecuación; y cinco estudiantes dejaron más de la mitad de los ejercicios sin desarrollar, con anotaciones al margen que indicaban haber empezado tarde por dificultades para copiar el enunciado del tablero. Antes de planear la siguiente clase, la docente debía decidir cómo diseñar la actividad de refuerzo para este grupo de dieciocho estudiantes con puntajes similares pero, según su propio registro, con causas de error visiblemente distintas.',
        'enunciado': 'A partir de la información que la propia docente registró en su rúbrica, ¿cuál es la decisión pedagógica más adecuada para diseñar el refuerzo?',
        'opcion_a': 'Diseñar tres rutas de refuerzo distintas: ejercicios de precisión de cálculo para quienes cometieron errores aritméticos con procedimiento correcto, actividades de re-enseñanza del concepto de igualdad para quienes aplicaron un método incorrecto, y ejercicios con tiempo extendido para quienes no alcanzaron a finalizar, dado que su propio registro evidencia causas distintas detrás de un mismo puntaje bajo.',
        'opcion_b': 'Asignar el mismo taller de ejercicios adicionales a los dieciocho estudiantes con puntaje inferior a sesenta, ya que estandarizar el refuerzo facilita el seguimiento del progreso del grupo y evita señalar a estudiantes específicos por su tipo de error.',
        'opcion_c': 'Concentrar el refuerzo únicamente en los siete estudiantes con errores conceptuales, dado que ese tipo de error representa el riesgo más alto para el aprendizaje futuro, y asumir que los errores de precisión de cálculo se corregirán de forma espontánea con la práctica regular de clase.',
        'opcion_d': 'Repetir la misma evaluación una semana después con los dieciocho estudiantes, sin modificar la estrategia de enseñanza previa, dado que un segundo intento permitirá confirmar si el bajo desempeño se debió a un mal momento puntual.',
        'respuesta_correcta': 'A',
        'nivel_dificultad': 'alto',
        'proceso_cognitivo': 'evaluacion_juicio',
        'fuente_normativa': '',
        'justificacion': 'La propia rúbrica de la docente distingue tres causas de error cualitativamente distintas detrás de puntajes similares: la decisión pedagógicamente coherente es usar esa evidencia ya recolectada para diferenciar el refuerzo, no tratarlo como un problema homogéneo. La opción B es tentadora porque apela a la eficiencia operativa y a evitar estigmatización, pero desaprovecha un diagnóstico ya hecho y probablemente sea inefectiva para al menos dos de los tres subgrupos. La opción C acierta en identificar que el error conceptual es más grave, pero comete el error de convertir una priorización razonable en una exclusión total de los otros dos grupos, cuyas causas de error —incluida la dificultad de tiempo, que no se resuelve "espontáneamente"— también están documentadas y requieren intervención. La opción D suena rigurosa por apelar a una segunda medición, pero repetir la evaluación sin cambiar la enseñanza previa no atiende ninguna de las causas ya identificadas y solo aplaza la intervención necesaria.',
    },
    {
        'codigo': 'LC-INF-P05',
        'contexto': 'Una institución educativa modificó la hora de inicio de la jornada, pasándola de las 6:30 a.m. a las 7:00 a.m., como respuesta a las quejas reiteradas de las familias por las llegadas tarde de los estudiantes de los grados de básica primaria. En el mismo mes en que entró en vigencia el nuevo horario, la institución también inauguró una ruta de transporte escolar adicional que por primera vez cubría un sector periférico del barrio donde vivía un número importante de estudiantes que antes debían caminar más de cuarenta minutos para llegar a pie, y el consejo estudiantil lanzó una rifa mensual de útiles escolares entre los estudiantes con asistencia perfecta durante el mes. Al finalizar el periodo, el rector comparó los registros de tardanzas del mes anterior al cambio con los del mes posterior y encontró una reducción del 40% en el número de estudiantes reportados como impuntuales. Con esa cifra en mano, se preparó para incluirla en el informe mensual dirigido a la Secretaría de Educación como sustento para solicitar la aprobación definitiva del nuevo horario en el calendario académico del año siguiente.',
        'enunciado': '¿Cuál es la lectura más rigurosa que el rector debería adoptar antes de reportar esta cifra como evidencia del efecto de la nueva hora de inicio?',
        'opcion_a': 'Reconocer que la disminución del 40% coincide con al menos otras dos intervenciones simultáneas —la nueva ruta de transporte y el incentivo de asistencia—, por lo que el efecto no puede atribuirse de forma exclusiva al cambio de horario sin un análisis que aísle o controle esas variables.',
        'opcion_b': 'Reportar la cifra como evidencia directa de que el cambio de horario fue la causa principal de la mejora, dado que fue la intervención más visible y la que generó mayor discusión entre los docentes al momento de implementarse.',
        'opcion_c': 'Descartar por completo la cifra del 40% como dato útil para la toma de decisiones, dado que la coincidencia de tres intervenciones en el mismo periodo invalida cualquier uso posterior de esa información.',
        'opcion_d': 'Concluir que la reducción se debe principalmente a la nueva ruta de transporte, ya que resolver una barrera de acceso físico suele tener un impacto mayor sobre la asistencia que un ajuste de veinte minutos en el horario de inicio.',
        'respuesta_correcta': 'A',
        'nivel_dificultad': 'muy_alto',
        'proceso_cognitivo': 'evaluacion_juicio',
        'fuente_normativa': '',
        'justificacion': 'El texto describe tres intervenciones simultáneas en el mismo mes: atribuir la mejora a una sola de ellas sin control de las otras es una inferencia causal que los datos disponibles no sustentan; la lectura rigurosa es reconocer la coincidencia y la imposibilidad de aislar el efecto, no elegir una causa. La opción B es tentadora porque sigue la narrativa más visible y discutida institucionalmente, pero la saliencia de una intervención en la conversación docente no es evidencia de que sea la causa estadísticamente dominante: es un sesgo de disponibilidad, no un análisis de los datos. La opción C suena metodológicamente cauta, pero comete el error opuesto: pasar de "no puedo aislar la causa" a "el dato no sirve para nada" descarta información direccional real (la tardanza sí bajó) que puede ser útil si se reporta con las salvedades correctas. La opción D comete exactamente el mismo error de atribución causal que la opción B, solo que apunta a una variable distinta con un argumento intuitivamente plausible (una barrera de acceso físico resuelta), pero sigue sin contar con evidencia que aísle esa variable de las otras dos.',
    },
]
