# -*- coding: utf-8 -*-
"""Banco Oficial de Preguntas - Modulo: Normatividad Educativa | Tema:
Convivencia Escolar (Lote 1). Contenido enteramente nuevo, sin reutilizar nada
del borrador descartado del Modulo 3. Dificultad unicamente Muy Alta. Codigos
MOD03-CE-. Clave planificada de antemano (C,D,A,B,C,A,D,C,B,A,D,C,A,D,B) para
lograr distribucion balanceada A/B/C/D dentro del tema. Longitud de opciones
equilibrada por diseno para evitar sesgo de longitud.
"""

CATEGORIA = "Normatividad Educativa"
SUBCATEGORIA = "Normatividad Educativa - Convivencia Escolar"
COMPETENCIA = "Normativa educativa aplicada"
AREA = "general"

ITEMS = [
 {'codigo': 'MOD03-CE-001',
  'contexto': 'Dos estudiantes de séptimo grado de la Institución Educativa "Ciudad de Popayán" '
              'sostuvieron una discusión verbal durante el descanso por un desacuerdo sobre un '
              'préstamo de material escolar, que subió de tono e incluyó insultos mutuos frente '
              'a otros compañeros, sin que en ningún momento se produjera contacto físico ni '
              'ningún tipo de daño al cuerpo o a la salud de ninguno de los dos. El docente que '
              'se encontraba de turno de acompañamiento intervino de inmediato, separó a los '
              'estudiantes y los citó a su oficina para conversar individualmente con cada uno '
              'antes de reunirlos en un espacio de diálogo conjunto. Un padre de familia, al '
              'enterarse del incidente, exigió que el caso fuera remitido de inmediato al Comité '
              'Escolar de Convivencia para activar el protocolo más riguroso previsto en la '
              'normativa, argumentando que cualquier conflicto entre estudiantes debía tratarse '
              'con el mismo nivel de formalidad. La coordinación de convivencia le explicó que, '
              'conforme a la clasificación de situaciones que afectan la convivencia escolar, '
              'este incidente correspondía a una situación tipo I, es decir, un conflicto '
              'manejado inadecuadamente y de carácter esporádico que no generó daño al cuerpo ni '
              'a la salud de los involucrados, por lo que su manejo correspondía directamente al '
              'docente presente mediante estrategias de mediación pedagógica, sin que fuera '
              'necesario activar el protocolo formal ante el Comité Escolar de Convivencia '
              'previsto para situaciones de mayor gravedad.',
  'enunciado': '¿Qué opción resuelve correctamente la exigencia del padre de familia de activar '
               'el protocolo más riguroso ante el Comité Escolar de Convivencia?',
  'opcion_a': 'El incidente debía remitirse obligatoriamente al Comité Escolar de Convivencia, '
              'dado que toda discusión verbal entre estudiantes activa automáticamente el '
              'protocolo más riguroso previsto en la normativa vigente.',
  'opcion_b': 'El incidente no ameritaba ninguna intervención institucional, dado que las '
              'discusiones verbales esporádicas entre estudiantes de la misma edad no son '
              'competencia de ningún docente ni directivo del establecimiento.',
  'opcion_c': 'El incidente correspondía a una situación tipo I, cuyo manejo directo por el '
              'docente mediante mediación pedagógica es procedente, sin que sea necesario activar '
              'el protocolo formal del Comité Escolar de Convivencia.',
  'opcion_d': 'El incidente debía resolverse exclusivamente mediante un proceso disciplinario '
              'formal con apertura de expediente, dado que todo conflicto que involucre insultos '
              'mutuos entre estudiantes exige ese trámite.',
  'respuesta_correcta': 'C',
  'nivel_dificultad': 'muy_alto',
  'proceso_cognitivo': 'identificacion',
  'justificacion': 'Las situaciones tipo I corresponden a conflictos manejados inadecuadamente y '
                   'situaciones esporádicas que inciden negativamente en el clima escolar, sin '
                   'generar daño al cuerpo o a la salud de los involucrados; su manejo '
                   'corresponde directamente al docente presente mediante mecanismos de '
                   'mediación pedagógica, sin necesidad de activar el protocolo formal del '
                   'Comité Escolar de Convivencia.\n'
                   '\n'
                   'Distractores:\n'
                   '- A) Es plausible porque busca dar formalidad institucional a cualquier '
                   'conflicto; pero la clasificación de situaciones tipo I reserva precisamente '
                   'estos casos esporádicos y sin daño al manejo directo del docente presente.\n'
                   '- B) Es plausible porque minimiza el conflicto por tratarse de una discusión '
                   'verbal; pero todo conflicto que afecte el clima escolar amerita alguna '
                   'intervención pedagógica, aunque no active el protocolo formal.\n'
                   '- D) Es plausible porque asocia los insultos a una falta disciplinaria '
                   'formal; pero la situación tipo I se gestiona mediante mediación pedagógica, '
                   'no mediante apertura de un expediente disciplinario formal.\n'
                   '\n'
                   'Error frecuente del aspirante: Confundir las situaciones tipo I, de manejo '
                   'directo y pedagógico, con situaciones de mayor gravedad que sí requieren '
                   'activar el protocolo formal del Comité Escolar de Convivencia.\n'
                   '\n'
                   'Estrategia mental recomendada: Verificar si la situación generó daño al '
                   'cuerpo o a la salud y si es esporádica o sistemática, antes de determinar el '
                   'nivel de formalidad del manejo institucional requerido.\n'
                   '\n'
                   'Subcompetencia: Aplicación contextual de la clasificación de situaciones tipo '
                   'I dentro del Sistema Nacional de Convivencia Escolar',
  'fuente_normativa': 'Ley 1620 de 2013, artículo 40, y Decreto 1965 de 2013, artículo 40, sobre '
                      'la clasificación de las situaciones que afectan la convivencia escolar.'},
 {'codigo': 'MOD03-CE-002',
  'contexto': 'Un estudiante de noveno grado de la Institución Educativa "Marco Fidel Suárez" '
              'reportó ante la coordinación de convivencia que, desde hacía varias semanas, '
              'venía siendo objeto de burlas repetidas y sistemáticas por parte de un grupo de '
              'compañeros, quienes además habían creado un grupo de mensajería instantánea fuera '
              'del horario escolar para compartir imágenes editadas y comentarios despectivos '
              'sobre su apariencia física. El estudiante llevó a la reunión capturas de pantalla '
              'de varias de las publicaciones, junto con los nombres de los cuatro compañeros que '
              'participaban activamente en el grupo de mensajería, y explicó que había intentado '
              'primero resolver la situación directamente con ellos sin ningún resultado positivo. '
              'Ninguna de las agresiones había generado lesión física '
              'ni incapacidad médica para el estudiante afectado, pero sí un impacto emocional '
              'significativo reportado por la familia. La coordinación de convivencia, al '
              'analizar el caso, concluyó que la situación no podía tratarse como un conflicto '
              'esporádico de manejo directo por el docente, dado que se trataba de agresiones '
              'repetidas y sistemáticas que configuraban acoso escolar, incluyendo su modalidad '
              'de ciberacoso desarrollada fuera de la jornada escolar, y que, precisamente por su '
              'carácter reiterado y sistemático, sin generar incapacidad médica, correspondía '
              'clasificarla como una situación tipo II, lo que exigía activar formalmente el '
              'protocolo previsto ante el Comité Escolar de Convivencia, incluyendo la remisión '
              'del caso al área de orientación escolar y el correspondiente seguimiento '
              'periódico de la situación.',
  'enunciado': 'De acuerdo con el Decreto 1965 de 2013, ¿cómo debía clasificarse jurídicamente la '
               'situación reportada por el estudiante?',
  'opcion_a': 'Como una situación tipo I, dado que ninguna de las agresiones generó lesión '
              'física ni incapacidad médica para el estudiante afectado por las burlas '
              'reportadas.',
  'opcion_b': 'Como un asunto ajeno a la competencia institucional, dado que buena parte de las '
              'agresiones ocurrieron a través de un grupo de mensajería instantánea fuera del '
              'horario escolar.',
  'opcion_c': 'Como una situación tipo III, dado que toda forma de ciberacoso constituye '
              'automáticamente un presunto delito que debe remitirse directamente a la Fiscalía '
              'sin intervención previa del colegio.',
  'opcion_d': 'Como una situación tipo II, dado que se trata de agresiones repetidas y '
              'sistemáticas que configuran acoso escolar y ciberacoso, sin generar incapacidad '
              'médica para el estudiante afectado.',
  'respuesta_correcta': 'D',
  'nivel_dificultad': 'muy_alto',
  'proceso_cognitivo': 'analisis_situacional',
  'justificacion': 'Las situaciones tipo II incluyen la agresión escolar, el acoso escolar y el '
                   'ciberacoso que se presenten de manera repetida o sistemática, sin que '
                   'necesariamente generen incapacidad médica para las personas involucradas; el '
                   'caso descrito, por su carácter reiterado y sistemático, encuadra precisamente '
                   'en esta clasificación y exige activar el protocolo formal del Comité.\n'
                   '\n'
                   'Distractores:\n'
                   '- A) Es plausible porque se apoya en la ausencia de lesión física; pero la '
                   'repetición y sistematicidad de las agresiones excluye la clasificación como '
                   'situación tipo I, de carácter esporádico.\n'
                   '- B) Es plausible porque las agresiones ocurrieron parcialmente fuera del '
                   'horario escolar; pero la institución sí tiene competencia cuando el hecho '
                   'afecta la convivencia escolar de sus estudiantes, sin importar el lugar u '
                   'horario exacto.\n'
                   '- C) Es plausible porque el ciberacoso puede alcanzar niveles muy graves; '
                   'pero solo se clasifica como situación tipo III cuando constituye presunto '
                   'delito o genera incapacidad médica, lo que no ocurrió en este caso.\n'
                   '\n'
                   'Error frecuente del aspirante: Asumir que el ciberacoso queda fuera de la '
                   'competencia institucional por ocurrir fuera del horario escolar, o '
                   'confundir su gravedad con la clasificación automática como situación tipo '
                   'III.\n'
                   '\n'
                   'Estrategia mental recomendada: Evaluar si la agresión es repetida o '
                   'sistemática y si genera incapacidad médica o configura presunto delito, para '
                   'distinguir correctamente entre situaciones tipo II y tipo III.\n'
                   '\n'
                   'Subcompetencia: Aplicación contextual de la clasificación de situaciones tipo '
                   'II, incluido el ciberacoso, dentro del Sistema Nacional de Convivencia '
                   'Escolar',
  'fuente_normativa': 'Ley 1620 de 2013, artículo 40, y Decreto 1965 de 2013, artículo 40, sobre '
                      'situaciones tipo II, incluido el acoso escolar y el ciberacoso.'},
 {'codigo': 'MOD03-CE-003',
  'contexto': 'Durante un descanso escolar, un estudiante de grado octavo agredió físicamente a '
              'un compañero de curso, causándole una lesión que requirió atención médica de '
              'urgencia y que derivó en una incapacidad médica certificada de cinco días. Varios '
              'compañeros que presenciaron los hechos fueron entrevistados brevemente por el '
              'docente de turno mientras se esperaba la llegada de los padres del estudiante '
              'lesionado, quienes llegaron a la institución menos de media hora después de haber '
              'sido contactados telefónicamente. El '
              'rector de la institución, al conocer los hechos de manera inmediata a través del '
              'docente de turno, activó sin demora la ruta de atención integral correspondiente, '
              'ordenando que el estudiante lesionado recibiera atención médica de urgencia, '
              'informando de inmediato a los padres de familia de ambos estudiantes involucrados, '
              'y reportando el caso a la Policía Nacional y a la Comisaría de Familia del '
              'municipio como autoridades competentes, dado que los hechos, por la gravedad de la '
              'lesión y la incapacidad médica generada, configuraban una situación tipo III '
              'conforme a la clasificación legal vigente. El rector explicó posteriormente al '
              'Comité Escolar de Convivencia que, en este tipo de situaciones, el reporte a las '
              'autoridades competentes debe realizarse de manera inmediata y no está condicionado '
              'a que primero se agote un trámite interno de mediación pedagógica dentro de la '
              'institución educativa, dado que la gravedad de los hechos exige la intervención '
              'oportuna de las autoridades externas competentes.',
  'enunciado': '¿Cuál es la actuación jurídicamente correcta que debía adoptar el rector frente a '
               'los hechos descritos?',
  'opcion_a': 'Reportar de inmediato el caso a la Policía Nacional y a la Comisaría de Familia '
              'como autoridades competentes, sin condicionar ese reporte al agotamiento previo de '
              'un trámite interno de mediación pedagógica.',
  'opcion_b': 'Agotar primero un proceso interno completo de mediación pedagógica entre los dos '
              'estudiantes involucrados, y solo reportar el caso a las autoridades externas si '
              'esa mediación resultaba infructuosa.',
  'opcion_c': 'Abstenerse de reportar el caso a cualquier autoridad externa, dado que los hechos '
              'ocurrieron dentro de las instalaciones de la institución educativa y bajo su plena '
              'competencia disciplinaria interna.',
  'opcion_d': 'Remitir el caso únicamente a la Secretaría de Educación municipal, entidad '
              'competente de manera exclusiva y excluyente para conocer de las situaciones tipo '
              'III que ocurran dentro de instituciones educativas oficiales.',
  'respuesta_correcta': 'A',
  'nivel_dificultad': 'muy_alto',
  'proceso_cognitivo': 'evaluacion_juicio',
  'justificacion': 'Las situaciones tipo III, que generan incapacidad médica o configuran '
                   'presunto delito, exigen el reporte inmediato a las autoridades competentes, '
                   'como la Policía Nacional y la Comisaría de Familia, sin que ese reporte esté '
                   'condicionado al agotamiento previo de un trámite interno de mediación '
                   'pedagógica dentro de la institución educativa.\n'
                   '\n'
                   'Distractores:\n'
                   '- B) Es plausible porque privilegia la mediación pedagógica como primera '
                   'instancia; pero en situaciones tipo III el reporte a las autoridades '
                   'competentes debe ser inmediato, no condicionado a un trámite interno previo.\n'
                   '- C) Es plausible porque invoca la competencia disciplinaria interna de la '
                   'institución; pero esa competencia no excluye el deber legal de reportar a las '
                   'autoridades externas competentes en casos de esta gravedad.\n'
                   '- D) Es plausible porque menciona una entidad real del sector educativo; pero '
                   'la Secretaría de Educación no es la autoridad competente exclusiva para '
                   'situaciones tipo III, que exigen reporte directo a Policía y Comisaría.\n'
                   '\n'
                   'Error frecuente del aspirante: Asumir que el reporte a las autoridades '
                   'externas competentes debe esperar el agotamiento de instancias internas de '
                   'mediación, cuando la gravedad del caso exige actuación inmediata.\n'
                   '\n'
                   'Estrategia mental recomendada: Ante situaciones tipo III, priorizar el '
                   'reporte inmediato a las autoridades externas competentes, sin subordinarlo a '
                   'trámites internos previos de mediación pedagógica.\n'
                   '\n'
                   'Subcompetencia: Aplicación contextual de la ruta de atención integral y el '
                   'reporte inmediato en situaciones tipo III',
  'fuente_normativa': 'Ley 1620 de 2013, artículos 29 y 40, y Decreto 1965 de 2013, artículo 44, '
                      'sobre la ruta de atención integral y el reporte de situaciones tipo III a '
                      'las autoridades competentes.'},
 {'codigo': 'MOD03-CE-004',
  'contexto': 'Un estudiante de grado décimo fue citado por la coordinación de convivencia para '
              'responder por una presunta falta grave relacionada con el manual de convivencia '
              'institucional, luego de que un docente reportara que lo había visto alterar una '
              'calificación en su cuaderno de notas. El docente reportante no presenció '
              'directamente el hecho, sino que se basó en el comentario de otro estudiante que '
              'aseguraba haberlo visto, sin que se recopilara ninguna otra evidencia adicional '
              'antes de la reunión. Al iniciar la reunión, la coordinación le '
              'informó verbalmente que ya había sido sancionado con la suspensión de tres días, '
              'sin haberle permitido previamente presentar su versión de los hechos ni aportar '
              'pruebas en su defensa, y sin haberlo notificado formalmente de los cargos '
              'específicos que se le atribuían. El estudiante, acompañado posteriormente por su '
              'acudiente, presentó una reclamación formal ante el Consejo Directivo, alegando que '
              'la sanción había sido impuesta sin respetar su derecho de defensa ni el '
              'procedimiento previsto en el manual de convivencia. El Consejo Directivo, al '
              'revisar el caso, concluyó que la sanción impuesta era nula, dado que toda '
              'aplicación del manual de convivencia debe garantizar el debido proceso, incluyendo '
              'la notificación formal de los cargos, la oportunidad real de presentar descargos y '
              'pruebas, y la posibilidad de conocer la decisión antes de que esta se ejecute, '
              'ninguno de los cuales había sido respetado en este caso.',
  'enunciado': '¿Qué determinación es la ajustada a derecho respecto a la validez de la '
               'suspensión impuesta antes de escuchar al estudiante?',
  'opcion_a': 'La sanción es válida, dado que la coordinación de convivencia tiene competencia '
              'exclusiva para imponer suspensiones de hasta tres días sin necesidad de agotar '
              'ningún procedimiento previo formal.',
  'opcion_b': 'La sanción es nula, dado que su imposición desconoció el debido proceso al no '
              'notificar formalmente los cargos ni permitir al estudiante presentar sus descargos '
              'y pruebas antes de decidir.',
  'opcion_c': 'La sanción es válida siempre que sea ratificada posteriormente por el Consejo '
              'Directivo, sin que sea necesario que el estudiante haya sido escuchado previamente '
              'por la coordinación de convivencia.',
  'opcion_d': 'La sanción es nula, pero únicamente porque la suspensión impuesta excedió el '
              'número máximo de días que el manual de convivencia permite para faltas de esa '
              'naturaleza específica.',
  'respuesta_correcta': 'B',
  'nivel_dificultad': 'muy_alto',
  'proceso_cognitivo': 'evaluacion_juicio',
  'justificacion': 'Toda aplicación del manual de convivencia debe garantizar el debido proceso, '
                   'incluyendo la notificación formal de los cargos, la oportunidad real de '
                   'presentar descargos y pruebas, y la posibilidad de conocer la decisión antes '
                   'de su ejecución; la ausencia de estas garantías vicia de nulidad la sanción '
                   'impuesta, como ocurrió en este caso.\n'
                   '\n'
                   'Distractores:\n'
                   '- A) Es plausible porque atribuye competencia sancionatoria directa a la '
                   'coordinación; pero ninguna competencia sancionatoria exime del cumplimiento '
                   'del debido proceso frente al estudiante afectado.\n'
                   '- C) Es plausible porque involucra a un órgano superior en la ratificación; '
                   'pero la ratificación posterior no subsana la ausencia del debido proceso en '
                   'la etapa inicial de imposición de la sanción.\n'
                   '- D) Es plausible porque introduce un límite objetivo de días de suspensión; '
                   'pero el vicio central de la sanción no es su duración, sino la ausencia total '
                   'de debido proceso en su imposición.\n'
                   '\n'
                   'Error frecuente del aspirante: Centrar el análisis en la proporcionalidad o '
                   'duración de la sanción, sin advertir que el vicio principal es la ausencia '
                   'del debido proceso en su imposición.\n'
                   '\n'
                   'Estrategia mental recomendada: Verificar siempre si se garantizaron '
                   'notificación, defensa y oportunidad probatoria antes de evaluar la '
                   'proporcionalidad específica de una sanción escolar.\n'
                   '\n'
                   'Subcompetencia: Aplicación contextual del debido proceso en la imposición de '
                   'sanciones derivadas del manual de convivencia',
  'fuente_normativa': 'Constitución Política, artículo 29, y Ley 1620 de 2013, artículo 21, sobre '
                      'el debido proceso en la aplicación del manual de convivencia escolar.'},
 {'codigo': 'MOD03-CE-005',
  'contexto': 'El manual de convivencia de una institución educativa oficial establecía, para '
              'las faltas consideradas graves, la obligación del rector de exponer públicamente '
              'en la cartelera institucional el nombre del estudiante sancionado junto con una '
              'descripción de la falta cometida, "como medida ejemplarizante para toda la '
              'comunidad educativa". Esa disposición había sido incluida en el manual de '
              'convivencia varios años atrás, sin que ningún directivo posterior hubiera '
              'cuestionado su compatibilidad con los principios que rigen el régimen '
              'disciplinario escolar vigente. Tras la aplicación de esa disposición a un '
              'estudiante de '
              'grado noveno sancionado por una falta relacionada con el porte de un elemento '
              'prohibido, la familia presentó una queja ante la Secretaría de Educación, '
              'alegando que esa práctica vulneraba la dignidad del estudiante. La Secretaría de '
              'Educación, tras revisar el caso, le ordenó a la institución modificar de inmediato '
              'esa disposición del manual de convivencia, explicando que ninguna sanción escolar '
              'puede implicar tratos crueles, humillantes o degradantes para el estudiante '
              'sancionado, y que la exposición pública de su nombre y de los detalles de la falta '
              'cometida configuraba precisamente ese tipo de trato prohibido, con independencia '
              'del propósito ejemplarizante que la institución pretendiera atribuirle a esa '
              'práctica dentro de su régimen disciplinario interno.',
  'enunciado': '¿Qué determinación es la ajustada a derecho respecto a la disposición del manual '
               'de convivencia cuestionada por la familia?',
  'opcion_a': 'La disposición es válida, dado que las instituciones educativas tienen plena '
              'autonomía para definir el contenido de su manual de convivencia sin ningún límite '
              'externo aplicable.',
  'opcion_b': 'La disposición es válida siempre que el propósito ejemplarizante sea aprobado '
              'previamente por el Consejo Directivo mediante acta institucional debidamente '
              'motivada.',
  'opcion_c': 'La disposición debe modificarse, dado que ninguna sanción escolar puede implicar '
              'tratos crueles, humillantes o degradantes, y la exposición pública del estudiante '
              'sancionado configura ese tipo de trato prohibido.',
  'opcion_d': 'La disposición debe eliminarse por completo del manual de convivencia, pero solo '
              'mediante un trámite de reforma que exige la aprobación previa y expresa de la '
              'Secretaría de Educación departamental.',
  'respuesta_correcta': 'C',
  'nivel_dificultad': 'muy_alto',
  'proceso_cognitivo': 'evaluacion_juicio',
  'justificacion': 'Ninguna sanción escolar puede implicar tratos crueles, humillantes o '
                   'degradantes para el estudiante sancionado; la exposición pública de su '
                   'nombre y de los detalles de la falta cometida configura precisamente ese tipo '
                   'de trato prohibido, con independencia del propósito ejemplarizante que la '
                   'institución pretenda atribuirle.\n'
                   '\n'
                   'Distractores:\n'
                   '- A) Es plausible porque invoca la autonomía institucional en materia de '
                   'convivencia; pero esa autonomía tiene como límite infranqueable la prohibición '
                   'de tratos crueles, humillantes o degradantes.\n'
                   '- B) Es plausible porque exige un aval institucional adicional aparentemente '
                   'riguroso; pero ningún aval del Consejo Directivo puede legitimar una práctica '
                   'que vulnera la dignidad del estudiante sancionado.\n'
                   '- D) Es plausible porque condiciona la corrección a un trámite adicional de '
                   'aprobación; pero la disposición debe eliminarse por vulnerar la dignidad del '
                   'estudiante, sin que ello dependa de un aval previo de la Secretaría.\n'
                   '\n'
                   'Error frecuente del aspirante: Centrar el análisis en defectos procedimentales '
                   'secundarios, sin identificar que el vicio de fondo es la vulneración a la '
                   'dignidad humana del estudiante sancionado.\n'
                   '\n'
                   'Estrategia mental recomendada: Ante disposiciones del manual de convivencia, '
                   'verificar primero si respetan la dignidad del estudiante antes de evaluar '
                   'otros aspectos procedimentales de su aplicación.\n'
                   '\n'
                   'Subcompetencia: Aplicación contextual de la prohibición de tratos crueles, '
                   'humillantes o degradantes en el régimen disciplinario escolar',
  'fuente_normativa': 'Constitución Política, artículo 12, y Ley 1620 de 2013, artículo 21, sobre '
                      'la prohibición de sanciones que vulneren la dignidad del estudiante.'},
 {'codigo': 'MOD03-CE-006',
  'contexto': 'La orientadora escolar de una institución educativa recibió el reporte '
              'confidencial de una estudiante de grado once que manifestó estar siendo víctima '
              'de acoso escolar por parte de dos compañeras de su mismo curso. Antes de activar '
              'cualquier protocolo, la orientadora le preguntó a la estudiante si autorizaba que '
              'su identidad fuera revelada abiertamente en la próxima reunión del Comité Escolar '
              'de Convivencia, ante lo cual la estudiante se negó rotundamente, manifestando '
              'temor a represalias si su nombre se hacía público entre sus compañeras. La '
              'estudiante añadió que estaba dispuesta a colaborar con cualquier medida que se '
              'adoptara, incluyendo entrevistas individuales con las presuntas responsables, '
              'siempre que su identidad no fuera divulgada abiertamente ante el resto del curso. '
              'La '
              'orientadora le explicó que el manejo de este tipo de situaciones exige garantizar '
              'la confidencialidad de la identidad de las personas involucradas y la reserva de '
              'la información conocida, de manera que el Comité Escolar de Convivencia podía '
              'activar el protocolo correspondiente y adoptar las medidas de protección '
              'necesarias sin necesidad de exponer públicamente la identidad de la estudiante '
              'afectada ante el resto de sus integrantes o de la comunidad educativa, dado que el '
              'deber de reserva es un principio rector expresamente reconocido en el manejo de '
              'este tipo de situaciones de convivencia escolar.',
  'enunciado': '¿Qué opción resuelve correctamente la inquietud de la estudiante sobre el manejo '
               'confidencial de su identidad frente al Comité Escolar de Convivencia?',
  'opcion_a': 'El Comité Escolar de Convivencia puede activar el protocolo y adoptar medidas de '
              'protección garantizando la confidencialidad de la identidad de la estudiante, sin '
              'necesidad de exponerla públicamente ante el Comité o la comunidad.',
  'opcion_b': 'El Comité Escolar de Convivencia no puede activar ningún protocolo sin que la '
              'estudiante autorice expresamente que su identidad sea revelada ante todos los '
              'integrantes del Comité durante la sesión.',
  'opcion_c': 'El Comité Escolar de Convivencia debe revelar la identidad de la estudiante '
              'afectada como requisito de validez de cualquier medida de protección que '
              'pretenda adoptarse a su favor.',
  'opcion_d': 'El Comité Escolar de Convivencia solo puede conocer el caso si la estudiante '
              'presenta la denuncia directamente ante la Policía Nacional antes de acudir a la '
              'orientación escolar de la institución.',
  'respuesta_correcta': 'A',
  'nivel_dificultad': 'muy_alto',
  'proceso_cognitivo': 'comprension_aplicada',
  'justificacion': 'El manejo de las situaciones de convivencia escolar exige garantizar la '
                   'confidencialidad de la identidad de las personas involucradas y la reserva de '
                   'la información conocida; el Comité Escolar de Convivencia puede activar el '
                   'protocolo y adoptar medidas de protección sin necesidad de exponer '
                   'públicamente la identidad de la persona afectada.\n'
                   '\n'
                   'Distractores:\n'
                   '- B) Es plausible porque parece respetar la voluntad de la estudiante; pero '
                   'la reserva de identidad no impide que el Comité active el protocolo, sino que '
                   'exige que lo haga de manera confidencial.\n'
                   '- C) Es plausible porque asume que la identificación es requisito de eficacia '
                   'de las medidas; pero la normativa exige precisamente lo contrario: proteger '
                   'la identidad mientras se adoptan las medidas necesarias.\n'
                   '- D) Es plausible porque introduce un requisito procesal externo '
                   'aparentemente riguroso; pero la denuncia ante la Policía no es un requisito '
                   'previo para que la orientación escolar conozca y gestione el caso.\n'
                   '\n'
                   'Error frecuente del aspirante: Asumir que la confidencialidad de la identidad '
                   'impide la activación del protocolo institucional, en lugar de entenderla como '
                   'una garantía que debe acompañar su aplicación.\n'
                   '\n'
                   'Estrategia mental recomendada: Distinguir entre la obligación de proteger la '
                   'identidad de las personas involucradas y la obligación de activar el '
                   'protocolo correspondiente, que no son excluyentes entre sí.\n'
                   '\n'
                   'Subcompetencia: Aplicación contextual del deber de confidencialidad en el '
                   'manejo de situaciones de convivencia escolar',
  'fuente_normativa': 'Ley 1620 de 2013, artículo 21, numeral 8, sobre la reserva de la '
                      'información y la confidencialidad en el manejo de situaciones de '
                      'convivencia escolar.'},
 {'codigo': 'MOD03-CE-007',
  'contexto': 'Un grupo de diez estudiantes de un mismo curso fue sancionado colectivamente por '
              'el coordinador de convivencia con la pérdida de un espacio de recreación durante '
              'una semana completa, luego de que se reportara daño a un mural pintado en el '
              'patio central de la institución, sin que se hubiera identificado individualmente a '
              'los responsables directos del daño ni se hubiera dado oportunidad a cada '
              'estudiante del curso de presentar su propia versión de los hechos. La medida se '
              'comunicó verbalmente durante la formación general del lunes siguiente, sin '
              'entregar constancia escrita individual a ninguna de las familias afectadas por la '
              'sanción impuesta. Varios padres '
              'de familia reclamaron ante la rectoría, argumentando que sus hijos no habían '
              'participado en absoluto en el daño causado y que la sanción colectiva los '
              'afectaba injustamente sin ninguna prueba individual en su contra. La rectoría, '
              'tras revisar el caso con apoyo jurídico de la Secretaría de Educación, concluyó '
              'que la sanción colectiva impuesta era improcedente, dado que el régimen '
              'disciplinario escolar exige la individualización de responsabilidades y respeta la '
              'presunción de inocencia de cada estudiante, de manera que ningún curso completo '
              'puede sancionarse colectivamente por hechos atribuibles únicamente a algunos de '
              'sus integrantes, mientras no se identifique individualmente a los responsables '
              'directos mediante el respectivo procedimiento.',
  'enunciado': '¿Qué solución es la jurídicamente viable frente a la sanción colectiva impuesta '
               'al curso completo?',
  'opcion_a': 'La sanción colectiva es válida, dado que el coordinador de convivencia tiene '
              'plena discrecionalidad para sancionar a todo un curso cuando no se logra '
              'identificar individualmente a los responsables directos del daño.',
  'opcion_b': 'La sanción colectiva es válida únicamente si es ratificada posteriormente por el '
              'Consejo de Padres, órgano competente para avalar sanciones grupales impuestas a '
              'cursos completos.',
  'opcion_c': 'La sanción colectiva es válida siempre que se aplique de manera temporal y no '
              'exceda una semana de duración, conforme a los límites generales de las sanciones '
              'escolares.',
  'opcion_d': 'La sanción colectiva es improcedente, dado que el régimen disciplinario escolar '
              'exige individualizar responsabilidades y respetar la presunción de inocencia de '
              'cada estudiante del curso.',
  'respuesta_correcta': 'D',
  'nivel_dificultad': 'muy_alto',
  'proceso_cognitivo': 'evaluacion_juicio',
  'justificacion': 'El régimen disciplinario escolar exige la individualización de '
                   'responsabilidades y respeta la presunción de inocencia de cada estudiante; '
                   'ningún curso completo puede sancionarse colectivamente por hechos atribuibles '
                   'únicamente a algunos de sus integrantes, mientras no se identifique '
                   'individualmente a los responsables mediante el procedimiento correspondiente.\n'
                   '\n'
                   'Distractores:\n'
                   '- A) Es plausible porque reconoce la dificultad práctica de identificar '
                   'responsables individuales; pero esa dificultad no habilita sancionar '
                   'colectivamente a estudiantes sin prueba individual en su contra.\n'
                   '- B) Es plausible porque involucra a un órgano de participación real de '
                   'padres; pero ninguna ratificación posterior del Consejo de Padres puede '
                   'subsanar la ausencia de individualización de responsabilidades.\n'
                   '- C) Es plausible porque introduce un límite temporal aparentemente '
                   'razonable; pero el vicio de la sanción colectiva no es su duración, sino la '
                   'ausencia de individualización de responsabilidades entre los estudiantes.\n'
                   '\n'
                   'Error frecuente del aspirante: Centrar el análisis en la duración o '
                   'proporcionalidad de la sanción colectiva, sin advertir que su vicio de fondo '
                   'es la ausencia de individualización de responsabilidades.\n'
                   '\n'
                   'Estrategia mental recomendada: Ante sanciones grupales, verificar siempre si '
                   'se individualizó la responsabilidad de cada estudiante antes de evaluar otros '
                   'aspectos de la sanción impuesta.\n'
                   '\n'
                   'Subcompetencia: Aplicación contextual de la prohibición de sanciones '
                   'colectivas y la presunción de inocencia en el régimen disciplinario escolar',
  'fuente_normativa': 'Constitución Política, artículo 29, y Ley 1620 de 2013, artículo 21, sobre '
                      'la individualización de responsabilidades en el régimen disciplinario '
                      'escolar.'},
 {'codigo': 'MOD03-CE-008',
  'contexto': 'El Comité Escolar de Convivencia de una institución educativa oficial no se había '
              'reunido en los últimos ocho meses del año lectivo, a pesar de que durante ese '
              'periodo se habían presentado varias situaciones de convivencia reportadas por '
              'docentes y estudiantes. Un docente que lideraba estrategias de convivencia '
              'escolar dentro de la institución solicitó formalmente al rector que se convocara '
              'de inmediato una sesión, señalando que la inactividad prolongada del Comité '
              'incumplía la periodicidad mínima de reuniones exigida por la normativa aplicable, y '
              'advirtió que dos de las situaciones reportadas en ese periodo ya llevaban más de '
              'cuatro meses sin recibir ningún tipo de seguimiento formal por parte del Comité, lo '
              'que había generado inquietud entre los docentes que habían presentado esos '
              'reportes iniciales sin recibir respuesta institucional alguna. '
              'El rector, tras verificar la situación, reconoció el incumplimiento y convocó de '
              'inmediato una sesión extraordinaria, explicando ante los demás integrantes del '
              'Comité que la normativa exige que este órgano se reúna como mínimo una vez cada '
              'dos meses, sin perjuicio de que pueda convocarse de manera extraordinaria cuantas '
              'veces sea necesario ante situaciones que lo ameriten, y que la inactividad '
              'prolongada del Comité, más allá de ese término mínimo legal, constituye un '
              'incumplimiento de sus deberes como rector y presidente de dicho órgano '
              'institucional.',
  'enunciado': '¿Cuál es la periodicidad mínima de reunión del Comité Escolar de Convivencia '
               'conforme a la normativa aplicable?',
  'opcion_a': 'El Comité Escolar de Convivencia debe reunirse como mínimo una vez por semana '
              'durante todo el año lectivo, sin excepción alguna prevista en la normativa '
              'vigente.',
  'opcion_b': 'El Comité Escolar de Convivencia solo debe reunirse cuando se presente una '
              'situación tipo III, sin que exista ninguna periodicidad mínima obligatoria fuera '
              'de esos casos excepcionales.',
  'opcion_c': 'El Comité Escolar de Convivencia debe reunirse como mínimo una vez cada dos meses, '
              'sin perjuicio de que pueda convocarse extraordinariamente cuantas veces sea '
              'necesario ante situaciones que lo ameriten.',
  'opcion_d': 'El Comité Escolar de Convivencia debe reunirse como mínimo una vez al año, al '
              'inicio del calendario escolar, para la planeación general de las estrategias de '
              'convivencia institucional.',
  'respuesta_correcta': 'C',
  'nivel_dificultad': 'muy_alto',
  'proceso_cognitivo': 'identificacion',
  'justificacion': 'La normativa exige que el Comité Escolar de Convivencia se reúna como mínimo '
                   'una vez cada dos meses, sin perjuicio de que pueda convocarse de manera '
                   'extraordinaria cuantas veces sea necesario ante situaciones que lo ameriten; '
                   'su inactividad prolongada más allá de ese término constituye un incumplimiento '
                   'de los deberes del rector como presidente de dicho órgano.\n'
                   '\n'
                   'Distractores:\n'
                   '- A) Es plausible porque exige una periodicidad estricta y frecuente; pero la '
                   'normativa fija el mínimo en dos meses, no en una periodicidad semanal '
                   'permanente.\n'
                   '- B) Es plausible porque vincula la reunión solo a situaciones extremas; pero '
                   'la normativa exige una periodicidad mínima ordinaria, independiente de la '
                   'ocurrencia de situaciones tipo III específicas.\n'
                   '- D) Es plausible porque menciona una reunión de planeación real y necesaria; '
                   'pero la periodicidad mínima legal exige reuniones bimestrales, no una única '
                   'reunión anual de planeación.\n'
                   '\n'
                   'Error frecuente del aspirante: Confundir la posibilidad de convocar sesiones '
                   'extraordinarias con la inexistencia de una periodicidad mínima ordinaria '
                   'exigida por la normativa.\n'
                   '\n'
                   'Estrategia mental recomendada: Diferenciar la periodicidad mínima ordinaria '
                   'exigida por la ley de la facultad de convocar sesiones extraordinarias '
                   'adicionales ante situaciones específicas.\n'
                   '\n'
                   'Subcompetencia: Aplicación contextual de la periodicidad mínima de reunión '
                   'del Comité Escolar de Convivencia',
  'fuente_normativa': 'Decreto 1965 de 2013, artículo 22, sobre la periodicidad de las sesiones '
                      'del Comité Escolar de Convivencia.'},
 {'codigo': 'MOD03-CE-009',
  'contexto': 'Tras una situación tipo II reportada entre dos estudiantes de grado séptimo, la '
              'coordinación de convivencia definió unilateralmente un conjunto de compromisos '
              'pedagógicos para ambos estudiantes, sin haberlos citado previamente junto con sus '
              'respectivos acudientes para discutir el contenido de dichos compromisos, '
              'limitándose a entregarles un documento ya elaborado para que lo firmaran como '
              'constancia de aceptación. Uno de los acudientes se negó a firmar el documento, '
              'señalando que ni él ni su hijo habían sido escuchados antes de que se definieran '
              'esos compromisos, y que varios de ellos le parecían desproporcionados frente a lo '
              'realmente ocurrido entre los estudiantes, entre ellos la exigencia de asistir a '
              'talleres los fines de semana durante todo un semestre, condición que ni el '
              'estudiante ni su acudiente habían tenido oportunidad de discutir ni matizar antes '
              'de la entrega del documento. La coordinación de '
              'convivencia, tras '
              'consultar con la orientadora escolar, reconoció que el procedimiento aplicado no '
              'había sido el correcto, explicando que los compromisos pedagógicos derivados de '
              'una situación de convivencia escolar deben definirse con la participación activa '
              'del estudiante involucrado y de su acudiente, y no de manera unilateral por parte '
              'de la coordinación, por lo que se hacía necesario repetir el proceso citando '
              'formalmente a ambas partes para su construcción conjunta.',
  'enunciado': '¿Cuál es el vicio jurídicamente relevante en el procedimiento aplicado por la '
               'coordinación de convivencia?',
  'opcion_a': 'Ningún vicio relevante, dado que la coordinación de convivencia tiene plena '
              'facultad para definir unilateralmente los compromisos pedagógicos derivados de '
              'cualquier situación de convivencia escolar.',
  'opcion_b': 'Haber definido los compromisos pedagógicos de manera unilateral, sin la '
              'participación activa del estudiante involucrado y de su acudiente en su '
              'construcción conjunta.',
  'opcion_c': 'Haber tardado más de veinticuatro horas en definir los compromisos pedagógicos '
              'tras la ocurrencia de la situación tipo II reportada entre los dos estudiantes.',
  'opcion_d': 'Haber consultado únicamente a la orientadora escolar sobre el procedimiento, sin '
              'involucrar directamente al Comité Escolar de Convivencia en la revisión del '
              'trámite realizado.',
  'respuesta_correcta': 'B',
  'nivel_dificultad': 'muy_alto',
  'proceso_cognitivo': 'analisis_situacional',
  'justificacion': 'Los compromisos pedagógicos derivados de una situación de convivencia '
                   'escolar deben definirse con la participación activa del estudiante '
                   'involucrado y de su acudiente, y no de manera unilateral por parte de la '
                   'coordinación de convivencia, que es precisamente el vicio identificado en el '
                   'procedimiento aplicado en este caso.\n'
                   '\n'
                   'Distractores:\n'
                   '- A) Es plausible porque atribuye amplia facultad a la coordinación; pero la '
                   'normativa exige expresamente la participación del estudiante y su acudiente '
                   'en la construcción de estos compromisos.\n'
                   '- C) Es plausible porque introduce un término aparentemente objetivo; pero la '
                   'normativa no fija un plazo específico de veinticuatro horas para definir '
                   'compromisos pedagógicos tras una situación tipo II.\n'
                   '- D) Es plausible porque menciona un órgano institucional real; pero el vicio '
                   'central no es la falta de consulta al Comité, sino la ausencia de '
                   'participación del estudiante y su acudiente en la construcción conjunta.\n'
                   '\n'
                   'Error frecuente del aspirante: Buscar vicios procedimentales secundarios '
                   '(plazos, consultas a otros órganos) sin identificar que el vicio central es '
                   'la ausencia de participación de las partes directamente involucradas.\n'
                   '\n'
                   'Estrategia mental recomendada: Verificar siempre si el estudiante y su '
                   'acudiente participaron activamente en la definición de compromisos '
                   'pedagógicos, antes de evaluar otros aspectos procedimentales del caso.\n'
                   '\n'
                   'Subcompetencia: Aplicación contextual de la participación del estudiante y su '
                   'acudiente en la definición de compromisos pedagógicos',
  'fuente_normativa': 'Ley 1620 de 2013, artículo 22, y Decreto 1965 de 2013, artículo 43, sobre '
                      'la construcción participativa de los compromisos pedagógicos derivados de '
                      'situaciones de convivencia escolar.'},
 {'codigo': 'MOD03-CE-010',
  'contexto': 'Un estudiante de grado sexto fue sorprendido por segunda vez en el mismo periodo '
              'académico incumpliendo una norma leve del manual de convivencia relacionada con el '
              'uso del uniforme institucional, tras haber recibido ya un llamado de atención '
              'verbal por el mismo motivo semanas atrás, llamado que quedó registrado únicamente '
              'de manera informal en el cuaderno personal del docente de turno de ese día, sin '
              'que se hubiera dejado constancia formal en el observador del estudiante en esa '
              'primera ocasión. El '
              'coordinador de convivencia, al '
              'analizar el caso, decidió aplicar una sanción más severa que la impuesta la '
              'primera vez, consistente en una anotación formal en el observador del estudiante, '
              'explicando a los padres de familia que el manual de convivencia contempla el '
              'principio de gradualidad, según el cual las sanciones deben incrementar su nivel '
              'de severidad de manera proporcional cuando exista reincidencia del estudiante en '
              'una misma falta, sin que ello implique aplicar directamente la sanción más grave '
              'prevista para faltas de mayor entidad, sino avanzar de manera razonable dentro de '
              'la escala progresiva de medidas pedagógicas y correctivas contempladas '
              'específicamente en el manual de convivencia institucional para este tipo de faltas '
              'leves reiteradas.',
  'enunciado': '¿Qué curso de acción resulta procedente conforme al principio de gradualidad '
               'invocado por el coordinador de convivencia frente a la reincidencia del '
               'estudiante?',
  'opcion_a': 'El manual de convivencia contempla el principio de gradualidad, según el cual la '
              'reincidencia incrementa proporcionalmente la severidad de la sanción, sin saltar '
              'directamente a la más grave prevista para faltas de mayor entidad.',
  'opcion_b': 'El manual de convivencia exige aplicar exactamente la misma sanción en cada '
              'reincidencia, sin que el número de veces que se repita la falta module en modo '
              'alguno la severidad de la medida correctiva impuesta.',
  'opcion_c': 'El manual de convivencia obliga a aplicar automáticamente la sanción más grave '
              'prevista en la escala institucional desde la segunda vez que se comete cualquier '
              'falta, sin excepción alguna.',
  'opcion_d': 'El manual de convivencia prohíbe expresamente que se tenga en cuenta la '
              'reincidencia del estudiante como criterio para determinar la severidad de las '
              'sanciones aplicables dentro de la institución.',
  'respuesta_correcta': 'A',
  'nivel_dificultad': 'muy_alto',
  'proceso_cognitivo': 'comprension_aplicada',
  'justificacion': 'El principio de gradualidad, propio del régimen disciplinario escolar, '
                   'implica que las sanciones deben incrementar su nivel de severidad de manera '
                   'proporcional cuando exista reincidencia, sin que ello implique aplicar '
                   'directamente la sanción más grave prevista para faltas de mayor entidad, sino '
                   'avanzar razonablemente dentro de la escala progresiva del manual de '
                   'convivencia.\n'
                   '\n'
                   'Distractores:\n'
                   '- B) Es plausible porque propone uniformidad en el trato disciplinario; pero '
                   'el principio de gradualidad exige precisamente que la reincidencia module la '
                   'severidad de la sanción impuesta.\n'
                   '- C) Es plausible porque exagera el efecto de la gradualidad; pero esta no '
                   'implica saltar directamente a la sanción más grave, sino avanzar de manera '
                   'razonable y progresiva en la escala prevista.\n'
                   '- D) Es plausible porque niega por completo la relevancia de la reincidencia; '
                   'pero precisamente el principio de gradualidad reconoce la reincidencia como '
                   'criterio relevante para la severidad de las sanciones.\n'
                   '\n'
                   'Error frecuente del aspirante: Confundir la gradualidad proporcional de las '
                   'sanciones con la aplicación automática de la sanción más grave ante cualquier '
                   'reincidencia del estudiante.\n'
                   '\n'
                   'Estrategia mental recomendada: Entender la gradualidad como un avance '
                   'progresivo y proporcional dentro de la escala de sanciones, no como un salto '
                   'directo a la medida más severa disponible.\n'
                   '\n'
                   'Subcompetencia: Aplicación contextual del principio de gradualidad y '
                   'proporcionalidad de las sanciones ante la reincidencia del estudiante',
  'fuente_normativa': 'Ley 1620 de 2013, artículo 21, sobre los principios de proporcionalidad y '
                      'gradualidad en la aplicación del manual de convivencia escolar.'},
 {'codigo': 'MOD03-CE-011',
  'contexto': 'Un estudiante de grado once fue citado por el coordinador de convivencia luego de '
              'que otro estudiante lo señalara, sin ninguna prueba adicional, como presunto autor '
              'de un comentario ofensivo publicado en una red social sobre un docente de la '
              'institución. El estudiante que hizo el señalamiento no presentó ninguna captura de '
              'pantalla ni prueba adicional que respaldara su afirmación, limitándose a comentar '
              'el hecho de manera informal en la sala de profesores. El coordinador, antes de '
              'adelantar cualquier verificación adicional, '
              'le informó al estudiante señalado que ya había sido calificado como responsable de '
              'los hechos y que debía presentarse al día siguiente con sus padres para "recibir '
              'la sanción correspondiente", sin haberle dado la oportunidad de aportar pruebas '
              'que desvirtuaran la acusación ni de controvertir la versión del estudiante que lo '
              'había señalado. El rector, al conocer posteriormente el caso por una queja de la '
              'familia, le indicó al coordinador que su actuación había desconocido la presunción '
              'de inocencia que debe garantizarse a todo estudiante frente a una acusación no '
              'probada, y que el procedimiento correcto exigía verificar los hechos y permitir el '
              'ejercicio del derecho de defensa antes de calificar a alguien como responsable y '
              'anunciarle una sanción ya definida de antemano.',
  'enunciado': '¿Cuál es el principio jurídico que el coordinador de convivencia desconoció en su '
               'actuación frente al estudiante señalado?',
  'opcion_a': 'El principio de confidencialidad de la identidad de las personas involucradas en '
              'situaciones de convivencia escolar reportadas formalmente ante el Comité '
              'correspondiente para su trámite.',
  'opcion_b': 'El principio de gradualidad y proporcionalidad de las sanciones escolares frente '
              'a faltas reincidentes cometidas por un mismo estudiante dentro de la institución '
              'educativa respectiva.',
  'opcion_c': 'El principio de participación de los padres de familia en la construcción de '
              'compromisos pedagógicos derivados de situaciones de convivencia escolar '
              'previamente reportadas ante el Comité.',
  'opcion_d': 'El principio de presunción de inocencia, que exige verificar los hechos y '
              'permitir el ejercicio del derecho de defensa antes de calificar a un estudiante '
              'como responsable de una falta.',
  'respuesta_correcta': 'D',
  'nivel_dificultad': 'muy_alto',
  'proceso_cognitivo': 'identificacion',
  'justificacion': 'El coordinador de convivencia desconoció el principio de presunción de '
                   'inocencia, que exige verificar los hechos y permitir el ejercicio del derecho '
                   'de defensa antes de calificar a un estudiante como responsable de una falta y '
                   'anunciarle una sanción ya definida de antemano sin ese trámite previo.\n'
                   '\n'
                   'Distractores:\n'
                   '- A) Es plausible porque menciona un principio real del sistema de '
                   'convivencia escolar; pero el problema del caso no es la confidencialidad de '
                   'identidades, sino la ausencia de verificación y defensa antes de sancionar.\n'
                   '- B) Es plausible porque introduce otro principio real aplicable a otros '
                   'casos; pero aquí no se trataba de graduar una sanción por reincidencia, sino '
                   'de calificar responsabilidad sin verificación previa.\n'
                   '- C) Es plausible porque menciona otro elemento real del sistema; pero el '
                   'vicio identificado en el caso no se relaciona con la construcción de '
                   'compromisos pedagógicos, sino con la presunción de inocencia.\n'
                   '\n'
                   'Error frecuente del aspirante: Confundir entre sí los distintos principios '
                   'que rigen el sistema de convivencia escolar, aplicando el más genérico en '
                   'lugar de identificar el específicamente vulnerado en el caso concreto.\n'
                   '\n'
                   'Estrategia mental recomendada: Identificar con precisión cuál elemento del '
                   'debido proceso fue omitido en el caso (verificación, defensa, '
                   'confidencialidad, gradualidad) antes de seleccionar el principio aplicable.\n'
                   '\n'
                   'Subcompetencia: Aplicación contextual del principio de presunción de '
                   'inocencia en el manejo de situaciones de convivencia escolar',
  'fuente_normativa': 'Constitución Política, artículo 29, y Ley 1620 de 2013, artículo 21, sobre '
                      'la presunción de inocencia en el régimen disciplinario escolar.'},
 {'codigo': 'MOD03-CE-012',
  'contexto': 'Una institución educativa oficial conformó su Comité Escolar de Convivencia '
              'incluyendo únicamente al rector, dos docentes designados directamente por él y un '
              'representante de los padres de familia también escogido por la rectoría, sin '
              'incluir al presidente del consejo de estudiantes ni a un representante elegido por '
              'el consejo estudiantil, integrantes que, según el acta de constitución revisada, '
              'nunca habían sido convocados desde la creación del Comité tres años atrás, situación '
              'que ningún miembro del Comité había reportado previamente ante la Secretaría de '
              'Educación. Al '
              'revisar la conformación del Comité durante una visita '
              'de inspección y vigilancia, un funcionario de la Secretaría de Educación señaló '
              'que esa integración no cumplía con los requisitos legales, dado que la normativa '
              'exige que el Comité Escolar de Convivencia incluya, entre otros integrantes, al '
              'presidente del consejo de estudiantes y a un representante de los estudiantes '
              'elegido por el consejo estudiantil, precisamente para garantizar la participación '
              'directa de este estamento en un órgano que conoce y decide sobre situaciones que '
              'los afectan de manera central, por lo que ordenó a la institución reconformar el '
              'Comité incluyendo a los representantes estudiantiles legalmente exigidos antes de '
              'que este pudiera sesionar válidamente.',
  'enunciado': '¿Cuál es la irregularidad jurídicamente relevante identificada por el funcionario '
               'de la Secretaría de Educación en la conformación del Comité?',
  'opcion_a': 'Ninguna irregularidad relevante, dado que el rector tiene plena facultad para '
              'conformar el Comité Escolar de Convivencia según su propio criterio institucional, '
              'sin sujeción a integrantes específicos.',
  'opcion_b': 'La ausencia de un docente que lidere estrategias de convivencia escolar dentro del '
              'Comité, integrante que la normativa exige de manera obligatoria e insustituible '
              'para su válida conformación.',
  'opcion_c': 'La exclusión del presidente del consejo de estudiantes y de un representante '
              'estudiantil elegido por el consejo, integrantes exigidos por la normativa para '
              'garantizar la participación de ese estamento.',
  'opcion_d': 'La ausencia del personero estudiantil como integrante obligatorio del Comité '
              'Escolar de Convivencia, cargo cuya participación en dicho órgano es exigida de '
              'manera expresa por la normativa vigente.',
  'respuesta_correcta': 'C',
  'nivel_dificultad': 'muy_alto',
  'proceso_cognitivo': 'identificacion',
  'justificacion': 'La normativa exige que el Comité Escolar de Convivencia incluya, entre otros '
                   'integrantes, al presidente del consejo de estudiantes y a un representante de '
                   'los estudiantes elegido por el consejo estudiantil, para garantizar la '
                   'participación directa de ese estamento en un órgano que decide sobre '
                   'situaciones que los afectan de manera central.\n'
                   '\n'
                   'Distractores:\n'
                   '- A) Es plausible porque atribuye amplia discrecionalidad al rector; pero la '
                   'conformación del Comité está reglada por la normativa, que exige integrantes '
                   'específicos, entre ellos los representantes estudiantiles.\n'
                   '- B) Es plausible porque menciona un integrante real del Comité; pero el caso '
                   'describe específicamente la exclusión de los representantes estudiantiles, no '
                   'del docente líder de convivencia.\n'
                   '- D) Es plausible porque el personero es un cargo real de representación '
                   'estudiantil; pero la irregularidad descrita en el caso se refiere '
                   'específicamente a la exclusión del presidente y representante del consejo '
                   'estudiantil, no del personero.\n'
                   '\n'
                   'Error frecuente del aspirante: Confundir entre sí los distintos cargos de '
                   'representación estudiantil (personero, presidente del consejo estudiantil, '
                   'representante ante el Comité) y sus respectivas exigencias normativas.\n'
                   '\n'
                   'Estrategia mental recomendada: Verificar con precisión cuál integrante '
                   'específico fue excluido de un órgano colegiado antes de identificar la '
                   'irregularidad concreta en su conformación.\n'
                   '\n'
                   'Subcompetencia: Aplicación contextual de la conformación legal del Comité '
                   'Escolar de Convivencia y la participación estudiantil',
  'fuente_normativa': 'Decreto 1965 de 2013, artículo 22, sobre la conformación del Comité '
                      'Escolar de Convivencia y sus integrantes obligatorios.'},
 {'codigo': 'MOD03-CE-013',
  'contexto': 'Un estudiante de grado octavo fue sancionado con la cancelación definitiva de su '
              'matrícula para el año siguiente, tras acumular varias anotaciones en el '
              'observador por faltas leves relacionadas con el incumplimiento de tareas y '
              'algunos llamados de atención por comportamiento en clase, ninguna de las cuales '
              'había sido clasificada como falta grave ni había generado daño a otras personas, '
              'siendo la última de ellas un llamado de atención por olvidar en dos ocasiones el '
              'carné estudiantil dentro del plazo fijado por el manual de convivencia, situación '
              'que el propio coordinador de convivencia había calificado como "reiterativa pero '
              'menor" en su momento, sin recomendar entonces ninguna medida adicional al llamado '
              'de atención inicial. '
              'La familia impugnó la decisión ante el Consejo Directivo, argumentando que la '
              'sanción resultaba manifiestamente desproporcionada frente a la naturaleza leve de '
              'las faltas acumuladas. El Consejo Directivo, al revisar el caso, revocó la '
              'cancelación de matrícula, explicando que toda sanción escolar debe guardar '
              'proporcionalidad entre la gravedad de la falta cometida y la severidad de la '
              'medida impuesta, de manera que una consecuencia tan grave como la cancelación '
              'definitiva de la matrícula, que afecta de manera significativa el derecho a la '
              'educación del estudiante, no resulta procedente frente a la acumulación de faltas '
              'leves que, individualmente consideradas, no alcanzan la entidad suficiente para '
              'justificar una medida de esa magnitud.',
  'enunciado': '¿Cuál es el principio jurídico que fundamentó la revocatoria de la cancelación de '
               'matrícula por parte del Consejo Directivo?',
  'opcion_a': 'El principio de proporcionalidad, según el cual la severidad de la sanción debe '
              'guardar relación con la gravedad real de la falta cometida por el estudiante '
              'sancionado.',
  'opcion_b': 'El principio de confidencialidad, según el cual la identidad del estudiante '
              'sancionado debe mantenerse en reserva frente a los demás integrantes de la '
              'comunidad educativa.',
  'opcion_c': 'El principio de gradualidad estricta, que exige agotar previamente todas las '
              'sanciones intermedias antes de poder imponer la cancelación definitiva de la '
              'matrícula a cualquier estudiante.',
  'opcion_d': 'El principio de participación estudiantil, según el cual ninguna sanción puede '
              'imponerse sin la aprobación previa del consejo de estudiantes de la institución '
              'educativa correspondiente.',
  'respuesta_correcta': 'A',
  'nivel_dificultad': 'muy_alto',
  'proceso_cognitivo': 'evaluacion_juicio',
  'justificacion': 'Toda sanción escolar debe guardar proporcionalidad entre la gravedad de la '
                   'falta cometida y la severidad de la medida impuesta; una consecuencia tan '
                   'grave como la cancelación definitiva de la matrícula no resulta procedente '
                   'frente a la acumulación de faltas leves que, individualmente consideradas, no '
                   'alcanzan la entidad suficiente para justificarla.\n'
                   '\n'
                   'Distractores:\n'
                   '- B) Es plausible porque menciona un principio real del sistema de '
                   'convivencia; pero el fundamento de la revocatoria en este caso no se '
                   'relaciona con la reserva de identidad, sino con la proporcionalidad de la '
                   'sanción.\n'
                   '- C) Es plausible porque introduce una exigencia de agotamiento previo '
                   'aparentemente rigurosa; pero el fundamento central de la revocatoria fue la '
                   'proporcionalidad, no una regla estricta de agotamiento secuencial de '
                   'sanciones.\n'
                   '- D) Es plausible porque menciona la participación estudiantil, elemento real '
                   'del sistema; pero la revocatoria no se fundamentó en la falta de aprobación '
                   'del consejo de estudiantes, sino en la desproporción de la sanción impuesta.\n'
                   '\n'
                   'Error frecuente del aspirante: Confundir el principio de proporcionalidad con '
                   'otros principios del sistema de convivencia escolar que, aunque reales, no '
                   'son los aplicables al fundamento específico de este caso.\n'
                   '\n'
                   'Estrategia mental recomendada: Identificar la relación entre la gravedad de '
                   'la falta y la severidad de la sanción impuesta como criterio central para '
                   'evaluar la proporcionalidad de una medida disciplinaria escolar.\n'
                   '\n'
                   'Subcompetencia: Aplicación contextual del principio de proporcionalidad entre '
                   'la falta cometida y la sanción escolar impuesta',
  'fuente_normativa': 'Ley 1620 de 2013, artículo 21, sobre el principio de proporcionalidad en '
                      'la aplicación de sanciones derivadas del manual de convivencia escolar.'},
 {'codigo': 'MOD03-CE-014',
  'contexto': 'Durante la investigación de una situación tipo II reportada entre varios '
              'estudiantes de grado noveno, el orientador escolar identificó indicios de que uno '
              'de los estudiantes involucrados podría estar siendo víctima adicional de una '
              'situación de violencia intrafamiliar, ajena por completo a los hechos ocurridos '
              'dentro de la institución educativa. El indicio surgió de un comentario espontáneo '
              'del estudiante durante una de las entrevistas individuales realizadas como parte '
              'de la investigación, sin que existiera hasta ese momento ningún reporte previo '
              'sobre su situación familiar. El orientador consultó al rector si esa '
              'información debía manejarse únicamente dentro del expediente interno de '
              'convivencia escolar del estudiante, sin ningún reporte adicional, dado que no '
              'guardaba relación directa con la situación tipo II que se estaba investigando '
              'dentro del colegio. El rector le indicó que, independientemente de que esa '
              'información hubiera surgido en el contexto de una investigación escolar distinta, '
              'existía un deber legal de reportar de inmediato cualquier indicio de violencia '
              'intrafamiliar o vulneración de derechos de un menor de edad ante las autoridades '
              'competentes de protección, como la Comisaría de Familia o el Instituto Colombiano '
              'de Bienestar Familiar, sin que ese reporte pudiera omitirse o postergarse '
              'simplemente por no formar parte del objeto original de la investigación escolar en '
              'curso.',
  'enunciado': '¿Qué solución es la jurídicamente viable frente al indicio de violencia '
               'intrafamiliar identificado por el orientador escolar?',
  'opcion_a': 'Consignar la información únicamente en el expediente interno de convivencia '
              'escolar del estudiante, sin realizar ningún reporte adicional ante autoridades '
              'externas de protección de menores.',
  'opcion_b': 'Esperar a que concluya formalmente la investigación de la situación tipo II '
              'original antes de considerar la posibilidad de reportar el indicio de violencia '
              'intrafamiliar identificado.',
  'opcion_c': 'Solicitar autorización expresa y previa de los padres del estudiante antes de '
              'poder reportar el indicio de violencia intrafamiliar ante cualquier autoridad de '
              'protección de menores.',
  'opcion_d': 'Reportar de inmediato el indicio identificado ante las autoridades competentes de '
              'protección de menores, dado el deber legal de reporte independiente del objeto '
              'original de la investigación escolar en curso.',
  'respuesta_correcta': 'D',
  'nivel_dificultad': 'muy_alto',
  'proceso_cognitivo': 'evaluacion_juicio',
  'justificacion': 'Existe un deber legal de reportar de inmediato cualquier indicio de violencia '
                   'intrafamiliar o vulneración de derechos de un menor de edad ante las '
                   'autoridades competentes de protección, como la Comisaría de Familia o el '
                   'ICBF, sin que ese reporte pueda omitirse o postergarse por no formar parte del '
                   'objeto original de la investigación escolar en curso.\n'
                   '\n'
                   'Distractores:\n'
                   '- A) Es plausible porque limita la actuación al ámbito escolar interno; pero '
                   'el deber de reporte de indicios de violencia intrafamiliar trasciende el '
                   'expediente interno de convivencia escolar del estudiante.\n'
                   '- B) Es plausible porque busca no interferir con la investigación en curso; '
                   'pero el deber de reporte de indicios de violencia intrafamiliar no puede '
                   'postergarse hasta la conclusión de un trámite escolar distinto.\n'
                   '- C) Es plausible porque exige un consentimiento previo aparentemente '
                   'respetuoso de la familia; pero el reporte ante autoridades de protección de '
                   'menores no está condicionado a la autorización previa de los padres.\n'
                   '\n'
                   'Error frecuente del aspirante: Asumir que el deber de reporte de indicios de '
                   'vulneración de derechos de un menor se limita al objeto específico de la '
                   'investigación escolar en la que dicho indicio fue identificado.\n'
                   '\n'
                   'Estrategia mental recomendada: Reconocer que el deber de reporte ante '
                   'autoridades de protección de menores opera de manera autónoma frente a '
                   'cualquier indicio identificado, sin condicionarlo al trámite escolar en curso.\n'
                   '\n'
                   'Subcompetencia: Aplicación contextual del deber de reporte de indicios de '
                   'vulneración de derechos de menores ante autoridades de protección',
  'fuente_normativa': 'Ley 1098 de 2006 (Código de la Infancia y la Adolescencia), artículo 44, y '
                      'Ley 1620 de 2013, sobre el deber de reporte ante autoridades de protección '
                      'de menores.'},
 {'codigo': 'MOD03-CE-015',
  'contexto': 'Un docente de la Institución Educativa "Simón Rodríguez" solicitó al Comité '
              'Escolar de Convivencia que definiera de manera unilateral, en cabeza exclusiva de '
              'los docentes y directivos, cualquier estrategia de resolución de conflictos entre '
              'estudiantes, argumentando que "los estudiantes involucrados en un conflicto no '
              'están en condiciones de aportar soluciones objetivas a su propia situación", y '
              'propuso que, de aprobarse su solicitud, se incorporara esa regla como protocolo '
              'permanente dentro del manual de convivencia institucional, citando como respaldo '
              'una experiencia similar aplicada años atrás en otra institución donde había '
              'trabajado previamente. El '
              'Comité, tras estudiar la propuesta, le explicó al docente que uno de los '
              'principios rectores del Sistema Nacional de Convivencia Escolar es precisamente la '
              'promoción de la mediación y otras estrategias de resolución pacífica de conflictos '
              'con participación activa de los propios estudiantes involucrados, en la medida en '
              'que ello fortalece su formación en competencias ciudadanas y su capacidad de '
              'autorregulación, sin que esto excluya el acompañamiento y la orientación de los '
              'docentes y directivos durante el proceso, de manera que la propuesta de excluir '
              'por completo la participación estudiantil de la resolución de sus propios '
              'conflictos resultaba contraria al enfoque formativo que orienta el sistema de '
              'convivencia escolar vigente.',
  'enunciado': '¿Qué determinación es la ajustada a derecho frente a la propuesta de excluir a '
               'los estudiantes de la resolución de sus propios conflictos?',
  'opcion_a': 'La propuesta es correcta, dado que los estudiantes involucrados en un conflicto '
              'nunca deben participar en la definición de las estrategias para resolverlo, por '
              'carecer de la objetividad necesaria.',
  'opcion_b': 'La propuesta es contraria al enfoque formativo del sistema, dado que uno de sus '
              'principios rectores es la mediación con participación activa de los estudiantes, '
              'sin excluir el acompañamiento docente.',
  'opcion_c': 'La propuesta debe someterse a votación directa de todos los padres de familia de '
              'la institución, siendo su resultado mayoritario el que determine si los '
              'estudiantes participan o no en la resolución de conflictos.',
  'opcion_d': 'La propuesta es parcialmente correcta, pero solo debe aplicarse a los estudiantes '
              'de los grados de básica primaria, dado que los de básica secundaria sí pueden '
              'participar en su resolución.',
  'respuesta_correcta': 'B',
  'nivel_dificultad': 'muy_alto',
  'proceso_cognitivo': 'evaluacion_juicio',
  'justificacion': 'Uno de los principios rectores del Sistema Nacional de Convivencia Escolar es '
                   'la promoción de la mediación y otras estrategias de resolución pacífica de '
                   'conflictos con participación activa de los estudiantes involucrados, sin '
                   'excluir el acompañamiento y la orientación de los docentes y directivos '
                   'durante el proceso.\n'
                   '\n'
                   'Distractores:\n'
                   '- A) Es plausible porque cuestiona la objetividad de los estudiantes '
                   'involucrados; pero el sistema reconoce precisamente el valor formativo de su '
                   'participación activa en la resolución de sus propios conflictos.\n'
                   '- C) Es plausible porque apela a una decisión colectiva de los padres de '
                   'familia; pero la aplicación del principio de mediación no depende de una '
                   'votación mayoritaria externa a los órganos del gobierno escolar.\n'
                   '- D) Es plausible porque distingue por nivel educativo de forma aparentemente '
                   'razonable; pero el principio de mediación con participación estudiantil no '
                   'distingue entre básica primaria y secundaria para su aplicación.\n'
                   '\n'
                   'Error frecuente del aspirante: Subestimar la capacidad formativa de la '
                   'participación estudiantil en la resolución de conflictos, asumiendo que debe '
                   'quedar reservada exclusivamente a docentes y directivos.\n'
                   '\n'
                   'Estrategia mental recomendada: Reconocer la mediación con participación '
                   'estudiantil como un principio formativo central del sistema de convivencia, '
                   'no como una concesión excepcional condicionada a aprobaciones externas.\n'
                   '\n'
                   'Subcompetencia: Aplicación contextual del principio de mediación y '
                   'participación estudiantil en la resolución de conflictos escolares',
  'fuente_normativa': 'Ley 1620 de 2013, artículo 6, sobre los principios del Sistema Nacional de '
                      'Convivencia Escolar, incluida la promoción de la mediación.'},
]
