# -*- coding: utf-8 -*-
"""Banco Oficial de Preguntas - Modulo: Normatividad Educativa | Tema: Ley
General de Educacion (Lote 1). Contenido enteramente nuevo, sin reutilizar
nada del borrador descartado del Modulo 3. Dificultad unicamente Muy Alta.
Codigos MOD03-LGE-. Clave planificada de antemano (D,B,A,C,B,D,A,C,B,D,A,C,B,
D,A) para lograr distribucion balanceada A/B/C/D dentro del tema. Longitud de
opciones equilibrada por diseno para evitar sesgo de longitud.
"""

CATEGORIA = "Normatividad Educativa"
SUBCATEGORIA = "Normatividad Educativa - Ley General de Educación"
COMPETENCIA = "Normativa educativa aplicada"
AREA = "general"

ITEMS = [
 {'codigo': 'MOD03-LGE-001',
  'contexto': 'La Institución Educativa "Simón Bolívar" atraviesa una discusión interna sobre la '
              'reforma de su Proyecto Educativo Institucional, luego de que un grupo de padres '
              'de familia propusiera que el énfasis institucional se orientara exclusivamente '
              'hacia la formación técnica y el desarrollo de competencias laborales específicas, '
              'argumentando que "eso es lo único que realmente le sirve a los estudiantes para '
              'conseguir empleo". El rector, al presentar la propuesta al Consejo Directivo para '
              'su análisis, recordó que los fines de la educación consagrados en la Ley General '
              'de Educación no se limitan a la formación laboral, sino que comprenden un '
              'conjunto amplio de propósitos que incluyen el pleno desarrollo de la '
              'personalidad, la formación en el respeto a la vida y los demás derechos humanos, '
              'la formación para facilitar la participación democrática, el desarrollo de la '
              'capacidad crítica, reflexiva y analítica, y el acceso al conocimiento científico y '
              'técnico, entre otros propósitos igualmente relevantes para la formación integral '
              'del estudiante. El rector explicó que, si bien el PEI puede legítimamente '
              'incorporar un énfasis técnico o vocacional como parte de su identidad '
              'institucional, ese énfasis no puede convertirse en el propósito exclusivo y '
              'excluyente de la institución, en la medida en que ello implicaría desconocer el '
              'carácter integral y plural que la ley atribuye a los fines de la educación, los '
              'cuales deben orientar de manera conjunta y armónica la totalidad del proyecto '
              'educativo, sin que ninguno de ellos pueda eliminar o subordinar completamente a '
              'los demás dentro de la propuesta curricular institucional. Uno de los padres '
              'insistió en que, si el énfasis técnico no podía ser exclusivo, entonces la '
              'institución debía al menos garantizar por escrito que el cien por ciento de los '
              'egresados obtendría empleo formal inmediato, como condición para aprobar '
              'cualquier reforma del PEI en ese sentido. El rector le aclaró que ni la Ley '
              'General de Educación ni ningún Proyecto Educativo Institucional pueden '
              'condicionarse a resultados de empleabilidad garantizados, pues la función de la '
              'institución es formativa y no puede comprometerse jurídicamente a un resultado '
              'laboral específico para cada egresado, sin que ello desvirtúe la validez de '
              'incorporar el énfasis técnico como parte legítima del proyecto educativo '
              'institucional.',
  'enunciado': '¿Cuál es la explicación jurídicamente correcta que el rector presentó al '
               'Consejo Directivo sobre la propuesta de los padres de familia?',
  'opcion_a': 'La propuesta es procedente en su totalidad, dado que la formación laboral y '
              'técnica es, conforme a la Ley General de Educación, el único fin legítimo que '
              'debe orientar de manera exclusiva el Proyecto Educativo Institucional.',
  'opcion_b': 'La propuesta debe rechazarse de plano, dado que la Ley General de Educación '
              'prohíbe expresamente que cualquier institución educativa oficial incorpore un '
              'énfasis técnico o vocacional dentro de su Proyecto Educativo Institucional.',
  'opcion_c': 'La propuesta es parcialmente viable, pero solo si es aprobada directamente por la '
              'Secretaría de Educación, dado que el Consejo Directivo carece de competencia para '
              'decidir sobre el énfasis institucional del establecimiento.',
  'opcion_d': 'El énfasis técnico puede incorporarse legítimamente al PEI, pero no puede '
              'convertirse en el propósito exclusivo de la institución, pues los fines de la '
              'educación son plurales e integrales y deben orientarse de manera conjunta y '
              'armónica.',
  'respuesta_correcta': 'D',
  'nivel_dificultad': 'muy_alto',
  'proceso_cognitivo': 'evaluacion_juicio',
  'justificacion': 'Los fines de la educación establecidos en la Ley General de Educación '
                   'conforman un conjunto plural e integral de propósitos formativos, ninguno de '
                   'los cuales puede eliminar o subordinar completamente a los demás; por tanto, '
                   'un énfasis técnico o vocacional puede incorporarse legítimamente al PEI como '
                   'parte de su identidad institucional, pero no puede convertirse en el '
                   'propósito exclusivo y excluyente de la formación impartida.\n'
                   '\n'
                   'Distractores:\n'
                   '- A) Es plausible porque responde a una preocupación real de empleabilidad '
                   'de los egresados; pero la ley no reconoce la formación laboral como fin '
                   'único y excluyente, sino como uno entre varios propósitos formativos '
                   'igualmente relevantes.\n'
                   '- B) Es plausible porque plantea una prohibición aparentemente protectora de '
                   'la formación integral; pero la ley sí permite incorporar énfasis técnicos o '
                   'vocacionales al PEI, siempre que no excluyan los demás fines educativos.\n'
                   '- C) Es plausible porque involucra a la autoridad educativa territorial en '
                   'la decisión; pero la definición del énfasis institucional dentro del PEI es '
                   'una competencia propia del gobierno escolar, no una aprobación previa y '
                   'directa de la Secretaría.\n'
                   '\n'
                   'Error frecuente del aspirante: Asumir que los fines de la educación admiten '
                   'jerarquización absoluta o exclusión mutua, en lugar de entenderlos como un '
                   'conjunto plural que debe orientarse de manera conjunta y armónica.\n'
                   '\n'
                   'Estrategia mental recomendada: Ante propuestas que buscan privilegiar un '
                   'único fin educativo de manera excluyente, verificar si la norma concibe los '
                   'fines como plurales e integrales antes de aceptar esa exclusividad.\n'
                   '\n'
                   'Subcompetencia: Aplicación contextual de los fines de la educación y su '
                   'carácter plural e integral en la definición del Proyecto Educativo '
                   'Institucional',
  'fuente_normativa': 'Ley 115 de 1994, artículo 5 (fines de la educación) y artículo 73 '
                      '(Proyecto Educativo Institucional).'},
 {'codigo': 'MOD03-LGE-002',
  'contexto': 'Una familia solicitó el cupo para su hija de cuatro años en el grado de '
              'preescolar de una institución educativa oficial, pero la coordinadora académica '
              'les informó verbalmente que el establecimiento "solo tenía disponibilidad de cupo '
              'garantizada por ley para el grado de transición, correspondiente a los cinco '
              'años, y no para los grados anteriores del nivel preescolar", por lo que la niña '
              'quedaría en lista de espera sujeta a disponibilidad. Los padres, inconformes con '
              'esa respuesta verbal, solicitaron primero una certificación escrita de la '
              'coordinación, la cual reiteró por oficio la misma posición, citando además la '
              'disponibilidad de cupos como criterio adicional para prejardín y jardín dentro de '
              'esa institución en particular. Ante esa respuesta, los padres presentaron un '
              'derecho de petición ante la Secretaría de Educación, argumentando que el nivel '
              'preescolar completo, compuesto por los grados de prejardín, jardín y transición, '
              'debía garantizarse con cupo obligatorio en cualquier institución oficial del '
              'sector, sin distinción entre esos tres grados. La Secretaría de Educación '
              'respondió, mediante oficio motivado, que la obligatoriedad y gratuidad '
              'constitucional y legal del nivel preescolar se predica específicamente del grado '
              'de transición, por ser este el único grado de preescolar cuya prestación es '
              'obligatoria a cargo del Estado dentro del sistema educativo oficial, mientras que '
              'los grados de prejardín y jardín, aunque hacen parte del nivel preescolar y las '
              'instituciones pueden ofrecerlos según su disponibilidad, no gozan de esa misma '
              'garantía de obligatoriedad y cupo asegurado, por lo que la respuesta inicial de la '
              'coordinadora académica se ajustaba al régimen legal vigente sobre la materia.',
  'enunciado': '¿Cómo debe resolver la Secretaría de Educación el derecho de petición sobre el '
               'cupo solicitado en los grados de prejardín y jardín?',
  'opcion_a': 'Los tres grados del nivel preescolar, sin distinción alguna entre ellos, gozan '
              'por igual de obligatoriedad y cupo garantizado en cualquier institución educativa '
              'oficial del sistema.',
  'opcion_b': 'Únicamente el grado de transición del nivel preescolar goza de obligatoriedad y '
              'cupo garantizado en las instituciones oficiales, mientras prejardín y jardín no '
              'tienen esa misma garantía legal.',
  'opcion_c': 'Ningún grado del nivel preescolar es obligatorio en las instituciones educativas '
              'oficiales, dado que la obligatoriedad constitucional solo cobija los niveles de '
              'básica y media del sistema.',
  'opcion_d': 'La obligatoriedad del nivel preescolar completo depende exclusivamente de la '
              'disponibilidad presupuestal que cada Secretaría de Educación certificada defina '
              'anualmente para su territorio.',
  'respuesta_correcta': 'B',
  'nivel_dificultad': 'muy_alto',
  'proceso_cognitivo': 'comprension_aplicada',
  'justificacion': 'La obligatoriedad y gratuidad constitucional del nivel preescolar se predica '
                   'específicamente del grado de transición, que es el único grado de ese nivel '
                   'cuya prestación es obligatoria a cargo del Estado; prejardín y jardín hacen '
                   'parte del nivel preescolar pero no gozan de esa misma garantía de cupo '
                   'asegurado en toda institución oficial.\n'
                   '\n'
                   'Distractores:\n'
                   '- A) Es plausible porque asume que todo el nivel preescolar debería tratarse '
                   'de manera uniforme; pero la garantía constitucional de obligatoriedad recae '
                   'específicamente sobre el grado de transición.\n'
                   '- C) Es plausible porque introduce una restricción aparentemente coherente '
                   'con otros niveles; pero desconoce que el grado de transición sí es '
                   'obligatorio por mandato constitucional expreso.\n'
                   '- D) Es plausible porque menciona un factor real de la planeación educativa '
                   'territorial; pero la obligatoriedad del grado de transición no depende de la '
                   'disponibilidad presupuestal discrecional de la Secretaría.\n'
                   '\n'
                   'Error frecuente del aspirante: Asumir que todo el nivel preescolar (prejardín, '
                   'jardín y transición) tiene el mismo estatus de obligatoriedad legal, sin '
                   'distinguir cuál grado específico goza de esa garantía constitucional.\n'
                   '\n'
                   'Estrategia mental recomendada: Ante preguntas sobre obligatoriedad de niveles '
                   'educativos, identificar el grado específico al que la Constitución o la ley '
                   'atribuyen esa garantía, en lugar de generalizarla a todo el nivel.\n'
                   '\n'
                   'Subcompetencia: Aplicación contextual de la obligatoriedad del grado de '
                   'transición dentro del nivel preescolar',
  'fuente_normativa': 'Constitución Política, artículo 67, y Ley 115 de 1994, artículos 15 y 18, '
                      'sobre el nivel preescolar y la obligatoriedad del grado de transición.'},
 {'codigo': 'MOD03-LGE-003',
  'contexto': 'Un estudiante de octavo grado, diagnosticado con una discapacidad cognitiva leve '
              'certificada por un equipo interdisciplinario de salud, fue matriculado en la '
              'Institución Educativa "La Esperanza" dentro del aula regular correspondiente a su '
              'edad y grado. Al finalizar el primer periodo académico, el docente titular del '
              'aula solicitó a la coordinación que el estudiante fuera trasladado de manera '
              'permanente a un aula separada exclusiva para estudiantes con discapacidad, '
              'argumentando que "no contaba con el tiempo suficiente para atender de manera '
              'individual sus necesidades sin afectar el ritmo del resto del grupo". El docente '
              'insistió en su solicitud mediante un memorando formal dirigido a la coordinación, '
              'anexando un registro de incidentes de manejo de aula ocurridos durante el periodo '
              'y solicitando que la decisión se adoptara antes del inicio del segundo periodo '
              'académico. La coordinación académica, antes de resolver, consultó a la Secretaría '
              'de Educación, '
              'la cual conceptuó que el principio de integración educativa que rige el sistema '
              'obliga a las instituciones a adoptar los ajustes razonables y las estrategias '
              'pedagógicas flexibles necesarias para que los estudiantes con discapacidad '
              'permanezcan y participen en el aula regular junto con sus demás compañeros, y que '
              'la separación permanente a un aula exclusiva solo procede en circunstancias '
              'excepcionales debidamente justificadas por un concepto técnico especializado que '
              'determine que esa es la alternativa más favorable para el desarrollo del '
              'estudiante, y no como respuesta ordinaria a las dificultades de manejo de aula '
              'que enfrenta un docente en particular.',
  'enunciado': '¿Cuál es la actuación correcta que debía adoptar la coordinación académica frente '
               'a la solicitud del docente titular?',
  'opcion_a': 'Trasladar de inmediato al estudiante al aula exclusiva solicitada por el docente, '
              'dado que la carga de trabajo del profesor titular es motivo suficiente para '
              'justificar la separación permanente del grupo regular.',
  'opcion_b': 'No acceder al traslado permanente y, en su lugar, adoptar los ajustes razonables '
              'y las estrategias pedagógicas flexibles que permitan la permanencia del '
              'estudiante en el aula regular junto con sus compañeros de grado.',
  'opcion_c': 'Remitir la decisión directamente a los padres de familia del estudiante, para que '
              'sean ellos quienes determinen unilateralmente si su hijo continúa en el aula '
              'regular o se traslada al aula exclusiva propuesta.',
  'opcion_d': 'Suspender temporalmente la asistencia del estudiante a clases mientras se resuelve '
              'de fondo la solicitud del docente titular sobre su ubicación definitiva dentro de '
              'la institución.',
  'respuesta_correcta': 'B',
  'nivel_dificultad': 'muy_alto',
  'proceso_cognitivo': 'analisis_situacional',
  'justificacion': 'El principio de integración educativa obliga a las instituciones a adoptar '
                   'ajustes razonables y estrategias pedagógicas flexibles para que los '
                   'estudiantes con discapacidad permanezcan en el aula regular; la separación '
                   'permanente a un aula exclusiva solo procede excepcionalmente, con concepto '
                   'técnico especializado que la justifique, no como respuesta ordinaria a las '
                   'dificultades de manejo de un docente en particular.\n'
                   '\n'
                   'Distractores:\n'
                   '- A) Es plausible porque reconoce una dificultad real de carga docente; pero '
                   'esa dificultad no constituye, por sí sola, justificación técnica suficiente '
                   'para la separación permanente del estudiante del aula regular.\n'
                   '- C) Es plausible porque involucra a la familia en una decisión que le '
                   'afecta directamente; pero la determinación pedagógica sobre la ubicación del '
                   'estudiante corresponde a la institución con base en criterios técnicos, no a '
                   'una decisión unilateral y aislada de los padres.\n'
                   '- D) Es plausible porque busca ganar tiempo mientras se resuelve el caso; '
                   'pero suspender la asistencia del estudiante vulnera su derecho a la '
                   'educación y no es una medida prevista para este tipo de situaciones.\n'
                   '\n'
                   'Error frecuente del aspirante: Asumir que las dificultades de manejo de aula '
                   'que enfrenta un docente son justificación suficiente, por sí solas, para '
                   'separar permanentemente a un estudiante con discapacidad del aula regular.\n'
                   '\n'
                   'Estrategia mental recomendada: Ante solicitudes de separación de un '
                   'estudiante con discapacidad del aula regular, verificar si existe un '
                   'concepto técnico especializado que la justifique excepcionalmente, en lugar '
                   'de aceptar razones puramente organizativas del docente.\n'
                   '\n'
                   'Subcompetencia: Aplicación contextual del principio de integración educativa '
                   'de estudiantes con discapacidad al aula regular',
  'fuente_normativa': 'Ley 115 de 1994, artículos 46 a 48, y Decreto 1421 de 2017, sobre '
                      'atención educativa a población con discapacidad e integración al aula '
                      'regular.'},
 {'codigo': 'MOD03-LGE-004',
  'contexto': 'Durante el proceso de conformación del gobierno escolar de la Institución '
              'Educativa "Antonio Nariño" para el nuevo año lectivo, un grupo de estudiantes de '
              'grado décimo propuso que fuera uno de ellos quien asumiera el cargo de personero '
              'estudiantil, argumentando que "los estudiantes de once ya tienen suficiente carga '
              'académica con las pruebas de Estado y no deberían asumir responsabilidades '
              'adicionales". Los estudiantes de grado décimo llevaron su propuesta a una reunión '
              'informal con el coordinador de convivencia y solicitaron que, al menos para ese '
              'año lectivo, se permitiera una candidatura mixta entre grados décimo y once, '
              'argumentando que así se repartiría mejor la carga de responsabilidades entre los '
              'dos grupos. La coordinación de convivencia, encargada de organizar el proceso '
              'electoral, les explicó que, conforme a la normativa que regula el gobierno '
              'escolar, el personero de los estudiantes debe ser un alumno que curse el último '
              'grado que ofrezca el establecimiento educativo, de manera que, en una institución '
              'que ofrece hasta el grado once, únicamente los estudiantes matriculados en ese '
              'grado son elegibles para el cargo, sin que la carga académica adicional derivada '
              'de las pruebas de Estado constituya una razón jurídicamente válida para extender '
              'esa elegibilidad a estudiantes de grados inferiores, precisando además que el '
              'personero es elegido por votación secreta y universal de todos los estudiantes '
              'matriculados, dentro de los primeros treinta días calendario siguientes al inicio '
              'de clases.',
  'enunciado': '¿Cuál es la explicación jurídicamente correcta que la coordinación de convivencia '
               'dio a los estudiantes de grado décimo?',
  'opcion_a': 'Cualquier estudiante de la institución, sin importar el grado que curse, puede ser '
              'elegido personero estudiantil, siempre que cuente con el respaldo mayoritario de '
              'sus compañeros de curso.',
  'opcion_b': 'La elegibilidad para el cargo de personero depende exclusivamente del promedio '
              'académico del estudiante, sin relación alguna con el grado específico que se '
              'encuentre cursando dentro de la institución.',
  'opcion_c': 'El personero estudiantil no se elige por votación de los estudiantes, sino que es '
              'designado directamente por el rector entre los candidatos que postulen los '
              'docentes de la institución.',
  'opcion_d': 'Solo los estudiantes que cursan el último grado ofrecido por la institución '
              'pueden ser elegidos personero estudiantil, sin que la carga académica de las '
              'pruebas de Estado modifique esa exigencia legal.',
  'respuesta_correcta': 'D',
  'nivel_dificultad': 'muy_alto',
  'proceso_cognitivo': 'identificacion',
  'justificacion': 'La normativa que regula el gobierno escolar exige que el personero '
                   'estudiantil sea un alumno que curse el último grado ofrecido por el '
                   'establecimiento educativo, elegido por votación secreta y universal de todos '
                   'los estudiantes matriculados; la carga académica adicional de las pruebas de '
                   'Estado no constituye una excepción válida a esa exigencia legal de grado.\n'
                   '\n'
                   'Distractores:\n'
                   '- A) Es plausible porque parece democrático abrir la elección a cualquier '
                   'estudiante; pero la norma exige específicamente que el candidato curse el '
                   'último grado ofrecido por la institución.\n'
                   '- C) Es plausible porque menciona la intervención del rector en otros '
                   'procesos institucionales; pero el personero se elige por votación directa de '
                   'los estudiantes, no por designación del rector ni de los docentes.\n'
                   '- B) Es plausible porque introduce un criterio de mérito académico '
                   'aparentemente razonable; pero la norma no condiciona la elegibilidad al '
                   'promedio académico, sino al grado que curse el estudiante candidato.\n'
                   '\n'
                   'Error frecuente del aspirante: Confundir los requisitos de elegibilidad para '
                   'personero estudiantil con los de otros cargos de representación escolar, o '
                   'asumir que la carga académica exime del cumplimiento del requisito de grado.\n'
                   '\n'
                   'Estrategia mental recomendada: Verificar los requisitos específicos de cada '
                   'cargo de representación escolar (personero, representante estudiantil ante el '
                   'Consejo Directivo) en lugar de asumir que comparten las mismas exigencias.\n'
                   '\n'
                   'Subcompetencia: Aplicación contextual de los requisitos de elegibilidad y '
                   'elección del personero estudiantil dentro del gobierno escolar',
  'fuente_normativa': 'Decreto 1860 de 1994, artículo 28, sobre el personero de los estudiantes y '
                      'su elección dentro del gobierno escolar.'},
 {'codigo': 'MOD03-LGE-005',
  'contexto': 'El Consejo Directivo de la Institución Educativa "Gabriela Mistral" adoptó una '
              'modificación al Proyecto Educativo Institucional para incorporar un nuevo enfoque '
              'pedagógico basado en el aprendizaje por proyectos, sin haber convocado '
              'previamente al Consejo Académico ni a los demás estamentos de la comunidad '
              'educativa para su discusión. Un grupo de docentes reclamó ante la rectoría que la '
              'modificación era nula, argumentando que el PEI solo puede reformarse mediante '
              'consulta directa y vinculante a la totalidad de la comunidad educativa, incluidos '
              'estudiantes y padres de familia, en un proceso asambleario específico previsto '
              'para tal fin. Los docentes solicitaron además que la modificación quedara '
              'suspendida temporalmente mientras se convocaba esa asamblea general, y anexaron a '
              'su reclamo un pliego de firmas de otros compañeros que respaldaban la misma '
              'posición. La rectoría, tras revisar la normativa aplicable con apoyo del '
              'asesor jurídico de la Secretaría de Educación, explicó a los docentes que si bien '
              'el PEI debe construirse y modificarse con la participación de los distintos '
              'estamentos de la comunidad educativa a través de sus órganos de representación '
              'dentro del gobierno escolar, dicha participación se canaliza institucionalmente a '
              'través del Consejo Directivo y el Consejo Académico como órganos competentes, sin '
              'que la norma exija un mecanismo asambleario directo y vinculante de todos los '
              'estamentos como requisito de validez para cada modificación puntual del proyecto '
              'educativo.',
  'enunciado': '¿Qué determinación es la ajustada a derecho respecto a la validez de la '
               'modificación adoptada por el Consejo Directivo?',
  'opcion_a': 'La modificación es nula en su totalidad, dado que toda reforma al Proyecto '
              'Educativo Institucional exige, sin excepción, una consulta asamblearia directa y '
              'vinculante de todos los estamentos de la comunidad educativa.',
  'opcion_b': 'La modificación es válida, dado que la participación de la comunidad se canaliza '
              'a través de los órganos de representación del gobierno escolar, sin exigir un '
              'mecanismo asambleario directo para cada cambio puntual del proyecto.',
  'opcion_c': 'La modificación es válida, pero únicamente de manera provisional, hasta que sea '
              'ratificada mediante un referendo escolar convocado específicamente para ese '
              'efecto por la propia Secretaría de Educación del municipio correspondiente.',
  'opcion_d': 'La modificación es nula, pero solo porque no fue aprobada previamente por el '
              'personero estudiantil, cuya autorización expresa se exige como requisito '
              'indispensable para tramitar válidamente cualquier reforma futura del PEI.',
  'respuesta_correcta': 'B',
  'nivel_dificultad': 'muy_alto',
  'proceso_cognitivo': 'evaluacion_juicio',
  'justificacion': 'La participación de la comunidad educativa en la construcción y reforma del '
                   'PEI se canaliza institucionalmente a través de los órganos de representación '
                   'del gobierno escolar, como el Consejo Directivo y el Consejo Académico, sin '
                   'que la norma exija un mecanismo asambleario directo y vinculante de todos los '
                   'estamentos como requisito de validez para cada modificación puntual.\n'
                   '\n'
                   'Distractores:\n'
                   '- A) Es plausible porque invoca la participación amplia de la comunidad '
                   'educativa; pero la norma no exige un mecanismo asambleario directo, sino la '
                   'participación canalizada a través de los órganos representativos del '
                   'gobierno escolar.\n'
                   '- C) Es plausible porque introduce un mecanismo de ratificación posterior '
                   'aparentemente democrático; pero la normativa no contempla la figura del '
                   'referendo escolar para la validez de las reformas al PEI.\n'
                   '- D) Es plausible porque asigna un rol de veto al personero estudiantil; pero '
                   'la autorización expresa del personero no es requisito de validez para las '
                   'reformas del Proyecto Educativo Institucional.\n'
                   '\n'
                   'Error frecuente del aspirante: Asumir que la participación de la comunidad '
                   'educativa en el PEI exige necesariamente mecanismos asamblearios directos, en '
                   'lugar de reconocer que se canaliza a través de los órganos de representación '
                   'del gobierno escolar.\n'
                   '\n'
                   'Estrategia mental recomendada: Distinguir entre la exigencia general de '
                   'participación de la comunidad educativa y los mecanismos institucionales '
                   'concretos mediante los cuales esa participación efectivamente se canaliza.\n'
                   '\n'
                   'Subcompetencia: Aplicación contextual de los mecanismos de participación de '
                   'la comunidad educativa en la construcción y reforma del PEI',
  'fuente_normativa': 'Ley 115 de 1994, artículo 73, y Decreto 1860 de 1994, artículos 14 y 20, '
                      'sobre la construcción y adopción del Proyecto Educativo Institucional.'},
 {'codigo': 'MOD03-LGE-006',
  'contexto': 'El Consejo Académico de la Institución Educativa "José Acevedo y Gómez" propuso, '
              'en ejercicio de la autonomía escolar reconocida por la ley, eliminar por completo '
              'el área de educación religiosa del plan de estudios institucional para el próximo '
              'año lectivo, destinando esas horas semanales al fortalecimiento del área de '
              'matemáticas, con el argumento de que los resultados institucionales en las '
              'pruebas Saber de esa área venían siendo consistentemente bajos durante los '
              'últimos tres años. Un grupo de padres de familia se opuso a la propuesta ante el '
              'Consejo Directivo, señalando que la autonomía escolar tiene límites que no pueden '
              'desconocerse y solicitando que el punto se sometiera a consulta previa del Consejo '
              'Académico en pleno antes de cualquier decisión definitiva sobre el plan de '
              'estudios del año siguiente. La Secretaría de Educación, consultada por la rectoría '
              'antes de '
              'aprobar el cambio, conceptuó que la autonomía escolar permite a las instituciones '
              'adaptar sus áreas obligatorias a las necesidades particulares del medio, '
              'introducir asignaturas optativas y organizar actividades formativas adicionales, '
              'pero no permite eliminar del plan de estudios ninguna de las áreas fundamentales y '
              'obligatorias expresamente establecidas por la Ley General de Educación, entre las '
              'cuales se encuentra la educación religiosa, de modo que la propuesta del Consejo '
              'Académico, tal como estaba planteada, excedía los límites de la autonomía escolar '
              'reconocida a las instituciones educativas.',
  'enunciado': '¿Cuál es el análisis jurídicamente correcto del concepto emitido por la '
               'Secretaría de Educación?',
  'opcion_a': 'La propuesta del Consejo Académico es plenamente válida, dado que la autonomía '
              'escolar faculta a las instituciones para eliminar cualquier área obligatoria del '
              'plan de estudios cuando existan razones pedagógicas de bajo rendimiento '
              'debidamente justificadas.',
  'opcion_b': 'La propuesta es válida únicamente si es refrendada mediante consulta popular '
              'dirigida a toda la comunidad del municipio donde se ubica la institución '
              'educativa correspondiente.',
  'opcion_c': 'La autonomía escolar permite adaptar y organizar las áreas, pero no eliminar del '
              'plan de estudios ninguna de las áreas fundamentales y obligatorias establecidas '
              'por la ley, entre ellas la educación religiosa.',
  'opcion_d': 'La autonomía escolar no existe en materia curricular, por lo que ninguna '
              'institución educativa puede introducir ni siquiera asignaturas optativas dentro '
              'de su plan de estudios institucional.',
  'respuesta_correcta': 'C',
  'nivel_dificultad': 'muy_alto',
  'proceso_cognitivo': 'analisis_situacional',
  'justificacion': 'La autonomía escolar permite a las instituciones adaptar sus áreas '
                   'obligatorias a las necesidades del medio e introducir asignaturas optativas, '
                   'pero no permite eliminar del plan de estudios ninguna de las áreas '
                   'fundamentales y obligatorias expresamente establecidas por la Ley General de '
                   'Educación, entre las cuales se encuentra la educación religiosa.\n'
                   '\n'
                   'Distractores:\n'
                   '- A) Es plausible porque invoca razones pedagógicas de bajo rendimiento '
                   'aparentemente legítimas; pero ningún argumento de rendimiento académico '
                   'autoriza eliminar un área obligatoria expresamente fijada por la ley.\n'
                   '- B) Es plausible porque propone un mecanismo de legitimación democrática '
                   'amplio; pero la normativa no contempla una consulta popular municipal como '
                   'vía para modificar el plan de estudios de una institución educativa.\n'
                   '- D) Es plausible porque niega la autonomía de forma categórica; pero '
                   'desconoce que la ley sí reconoce un margen real de autonomía escolar para '
                   'adaptar áreas e introducir asignaturas optativas.\n'
                   '\n'
                   'Error frecuente del aspirante: Confundir el margen de adaptación y '
                   'organización curricular que otorga la autonomía escolar con una facultad '
                   'ilimitada para eliminar áreas obligatorias fijadas por la ley.\n'
                   '\n'
                   'Estrategia mental recomendada: Ante el ejercicio de la autonomía escolar, '
                   'distinguir entre lo que la norma permite adaptar u organizar y lo que fija '
                   'como obligatorio e indisponible para las instituciones educativas.\n'
                   '\n'
                   'Subcompetencia: Aplicación contextual de los límites de la autonomía escolar '
                   'frente a las áreas obligatorias y fundamentales del plan de estudios',
  'fuente_normativa': 'Ley 115 de 1994, artículos 23 (áreas obligatorias y fundamentales) y 77 '
                      '(autonomía escolar).'},
 {'codigo': 'MOD03-LGE-007',
  'contexto': 'Un hombre de 42 años, que no completó su educación básica y media en su juventud '
              'por razones económicas, se acercó a un Centro de Educación para Adultos '
              'adscrito a una institución educativa oficial, con el propósito de terminar sus '
              'estudios de bachillerato en el menor tiempo posible, dado que su empleo actual le '
              'exige contar con el título para acceder a un ascenso laboral próximamente '
              'disponible. Antes de matricularse, el hombre preguntó expresamente si existía '
              'alguna modalidad acelerada distinta a cursar cada grado por separado, pues temía '
              'que el proceso completo le tomara varios años y no llegara a tiempo para el '
              'ascenso ofrecido por su empleador. El coordinador del programa le explicó que la '
              'educación para adultos '
              'se organiza mediante Ciclos Lectivos Especiales Integrados, una modalidad que '
              'permite cursar e integrar en un solo ciclo los contenidos correspondientes a dos '
              'o más grados de la educación formal regular, de manera que el estudiante adulto '
              'pueda avanzar en su formación en un tiempo considerablemente menor al que '
              'tomaría cursar cada grado de manera independiente y separada, sin que ello '
              'implique una disminución en la exigencia académica ni en los contenidos '
              'curriculares mínimos que debe acreditar para obtener finalmente su título de '
              'bachiller, precisando que esta modalidad está expresamente reconocida y '
              'reglamentada para la educación de adultos dentro del sistema educativo colombiano.',
  'enunciado': '¿Cuál es la calificación jurídica correcta de la modalidad de educación para '
               'adultos aplicable al aspirante que busca terminar su bachillerato?',
  'opcion_a': 'La educación para adultos se organiza mediante Ciclos Lectivos Especiales '
              'Integrados, que permiten cursar en un tiempo menor los contenidos de dos o más '
              'grados, sin disminuir la exigencia académica mínima exigida.',
  'opcion_b': 'La educación para adultos exige cursar cada grado de manera individual e '
              'independiente, exactamente en las mismas condiciones y tiempos que la educación '
              'formal regular ofrecida a niños y adolescentes.',
  'opcion_c': 'La educación para adultos no existe como modalidad reconocida por el sistema '
              'educativo colombiano, por lo que el aspirante debía necesariamente validar cada '
              'grado mediante examen ante el ICFES.',
  'opcion_d': 'La educación para adultos permite obtener el título de bachiller sin cursar '
              'contenido académico alguno, bastando con acreditar la edad mínima de dieciocho '
              'años cumplidos ante la institución.',
  'respuesta_correcta': 'A',
  'nivel_dificultad': 'muy_alto',
  'proceso_cognitivo': 'identificacion',
  'justificacion': 'La educación para adultos se organiza mediante Ciclos Lectivos Especiales '
                   'Integrados, que permiten cursar e integrar en un solo ciclo los contenidos '
                   'correspondientes a dos o más grados de la educación formal regular, '
                   'reduciendo el tiempo total de formación sin disminuir la exigencia académica '
                   'ni los contenidos curriculares mínimos exigidos.\n'
                   '\n'
                   'Distractores:\n'
                   '- B) Es plausible porque asimila la educación de adultos al régimen regular; '
                   'pero precisamente la particularidad de esta modalidad es permitir integrar '
                   'varios grados en un ciclo, reduciendo el tiempo de formación.\n'
                   '- C) Es plausible porque menciona una entidad real del sistema educativo; '
                   'pero la educación para adultos sí es una modalidad formal reconocida y '
                   'reglamentada, distinta de la validación individual por examen.\n'
                   '- D) Es plausible porque simplifica el proceso a un requisito de edad; pero '
                   'la obtención del título exige siempre acreditar el contenido académico '
                   'correspondiente, no basta con cumplir una edad mínima.\n'
                   '\n'
                   'Error frecuente del aspirante: Confundir la educación para adultos con la '
                   'validación de bachillerato por examen directo, o asumir que reduce las '
                   'exigencias académicas mínimas en lugar de solo integrar el tiempo de '
                   'formación.\n'
                   '\n'
                   'Estrategia mental recomendada: Diferenciar las distintas modalidades de '
                   'culminación de estudios (educación formal regular, educación para adultos '
                   'mediante ciclos integrados, validación por examen) y sus exigencias '
                   'específicas.\n'
                   '\n'
                   'Subcompetencia: Aplicación contextual de la modalidad de educación para '
                   'adultos mediante Ciclos Lectivos Especiales Integrados',
  'fuente_normativa': 'Ley 115 de 1994, artículos 50 a 53, y Decreto 3011 de 1997, sobre '
                      'educación de adultos y Ciclos Lectivos Especiales Integrados.'},
 {'codigo': 'MOD03-LGE-008',
  'contexto': 'Un estudiante de grado once de la Institución Educativa "Francisco de Paula '
              'Santander" solicitó a la coordinación académica que se le exonerara de prestar el '
              'servicio social estudiantil obligatorio, argumentando que ya contaba con las '
              'mejores calificaciones académicas del grado y que, a su juicio, "prestar un '
              'servicio social no remunerado no debería ser condición para obtener un título que '
              'ya se ha ganado con esfuerzo académico". El estudiante propuso además que, en lugar '
              'de las horas de servicio social, se le permitiera acreditar como equivalente su '
              'participación previa en olimpiadas académicas interinstitucionales, en las que '
              'había representado a la institución durante los últimos dos años, aportando '
              'certificados y reconocimientos obtenidos en esas competencias como respaldo de su '
              'solicitud. La coordinación académica le explicó que '
              'el servicio social estudiantil obligatorio es un requisito autónomo e '
              'independiente del rendimiento académico del estudiante, exigido por la Ley '
              'General de Educación como condición necesaria para la obtención del título de '
              'bachiller, cuya finalidad es integrar a la vida comunitaria al educando mediante '
              'la ejecución de proyectos de beneficio social, sin que dicho servicio genere '
              'relación laboral alguna ni derecho a remuneración económica, de modo que el '
              'excelente desempeño académico del estudiante, aunque meritorio, no lo exime de '
              'cumplir con esa exigencia adicional prevista de manera autónoma por la '
              'normativa vigente para todos los estudiantes de la educación media, sin '
              'excepción por rendimiento.',
  'enunciado': '¿Qué solución es la jurídicamente viable frente a la solicitud del estudiante de '
               'grado once?',
  'opcion_a': 'La solicitud debe negarse, dado que el servicio social estudiantil obligatorio es '
              'un requisito autónomo e independiente del rendimiento académico, exigido para la '
              'obtención del título de bachiller sin excepción.',
  'opcion_b': 'La solicitud debe aceptarse, dado que los estudiantes con las mejores '
              'calificaciones académicas del grado están legalmente exonerados de prestar el '
              'servicio social estudiantil obligatorio.',
  'opcion_c': 'La solicitud debe aceptarse parcialmente, reduciendo a la mitad las horas de '
              'servicio social exigidas, en proporción directa al promedio académico obtenido '
              'por el estudiante durante el año lectivo.',
  'opcion_d': 'La solicitud debe remitirse a votación del Consejo Estudiantil, órgano competente '
              'para decidir sobre exoneraciones individuales del servicio social estudiantil '
              'obligatorio dentro de la institución.',
  'respuesta_correcta': 'A',
  'nivel_dificultad': 'muy_alto',
  'proceso_cognitivo': 'comprension_aplicada',
  'justificacion': 'El servicio social estudiantil obligatorio es un requisito autónomo e '
                   'independiente del rendimiento académico, exigido por la Ley General de '
                   'Educación como condición para la obtención del título de bachiller, sin que '
                   'el excelente desempeño académico de un estudiante lo exima de cumplir con '
                   'esa exigencia adicional.\n'
                   '\n'
                   'Distractores:\n'
                   '- B) Es plausible porque premia el mérito académico de forma intuitiva; pero '
                   'la ley no contempla exoneración alguna del servicio social por rendimiento '
                   'académico sobresaliente del estudiante.\n'
                   '- C) Es plausible porque propone una solución proporcional aparentemente '
                   'equitativa; pero el servicio social no admite reducción proporcional al '
                   'promedio académico obtenido por el estudiante.\n'
                   '- D) Es plausible porque involucra a un órgano de representación estudiantil '
                   'real; pero el Consejo Estudiantil no tiene competencia para decidir '
                   'exoneraciones individuales de un requisito legal obligatorio.\n'
                   '\n'
                   'Error frecuente del aspirante: Asumir que el rendimiento académico '
                   'sobresaliente puede sustituir o exonerar el cumplimiento de requisitos '
                   'legales autónomos como el servicio social estudiantil obligatorio.\n'
                   '\n'
                   'Estrategia mental recomendada: Distinguir entre los requisitos académicos '
                   '(evaluados por rendimiento) y los requisitos administrativos autónomos '
                   'exigidos por la ley para la titulación, que no se compensan entre sí.\n'
                   '\n'
                   'Subcompetencia: Aplicación contextual del servicio social estudiantil '
                   'obligatorio como requisito autónomo para la obtención del título de '
                   'bachiller',
  'fuente_normativa': 'Ley 115 de 1994, artículo 97, y Resolución 4210 de 1996, sobre el '
                      'servicio social estudiantil obligatorio.'},
 {'codigo': 'MOD03-LGE-009',
  'contexto': 'La rectoría de una institución educativa oficial informó a los padres de familia, '
              'mediante circular al inicio del año lectivo, que sería necesario realizar un '
              'cobro adicional de "cuota de sostenimiento" para cubrir gastos de mantenimiento de '
              'la planta física, dado que los recursos girados por el Sistema General de '
              'Participaciones resultaban insuficientes para cubrir esas necesidades específicas '
              'del establecimiento. Algunos padres, ante la insistencia de la rectoría, ya habían '
              'realizado el pago parcial de esa cuota durante las primeras semanas del año '
              'lectivo, mientras que otro grupo se negó a cancelarla y presentó una queja ante la '
              'Secretaría de Educación, señalando que ese cobro desconocía el régimen de '
              'gratuidad educativa vigente para las instituciones oficiales del país. La '
              'Secretaría de Educación, '
              'tras verificar los hechos, le ordenó a la rectoría suspender de inmediato el '
              'cobro, explicando que el régimen de gratuidad educativa vigente prohíbe realizar '
              'cobros académicos a los estudiantes matriculados en establecimientos educativos '
              'estatales, independientemente de la destinación específica que la institución '
              'pretenda darle a los recursos recaudados, y que la eventual insuficiencia de los '
              'recursos girados por el Sistema General de Participaciones debe gestionarse por '
              'la institución a través de los canales presupuestales ordinarios ante la entidad '
              'territorial certificada, y no mediante cobros directos trasladados a las familias '
              'de los estudiantes matriculados.',
  'enunciado': '¿Qué curso de acción resulta procedente conforme a la normativa vigente sobre '
               'gratuidad educativa?',
  'opcion_a': 'El cobro de la cuota de sostenimiento es procedente, dado que las instituciones '
              'oficiales pueden trasladar a las familias cualquier déficit presupuestal '
              'relacionado con el mantenimiento de la planta física del establecimiento.',
  'opcion_b': 'El cobro es procedente únicamente si es aprobado previamente por el Consejo de '
              'Padres de Familia, órgano competente para autorizar cobros adicionales en '
              'instituciones educativas oficiales del país.',
  'opcion_c': 'El cobro debe suspenderse, dado que el régimen de gratuidad prohíbe cobros '
              'académicos a estudiantes de establecimientos oficiales, sin importar la '
              'destinación específica que se pretenda dar a los recursos recaudados.',
  'opcion_d': 'El cobro debe suspenderse, pero únicamente respecto de las familias en condición '
              'de vulnerabilidad socioeconómica certificada, pudiendo mantenerse para el resto de '
              'los estudiantes matriculados.',
  'respuesta_correcta': 'C',
  'nivel_dificultad': 'muy_alto',
  'proceso_cognitivo': 'analisis_situacional',
  'justificacion': 'El régimen de gratuidad educativa vigente prohíbe realizar cobros académicos '
                   'a los estudiantes matriculados en establecimientos educativos estatales, '
                   'independientemente de la destinación específica que la institución pretenda '
                   'darle a los recursos recaudados, por lo que la insuficiencia presupuestal '
                   'debe gestionarse por canales ordinarios ante la entidad territorial, no '
                   'mediante cobros directos a las familias.\n'
                   '\n'
                   'Distractores:\n'
                   '- A) Es plausible porque invoca una necesidad institucional real de '
                   'mantenimiento; pero el régimen de gratuidad no admite excepciones basadas en '
                   'la destinación específica de los recursos recaudados.\n'
                   '- B) Es plausible porque involucra a un órgano de participación de padres '
                   'real; pero el Consejo de Padres no tiene competencia para autorizar cobros '
                   'que la ley prohíbe expresamente en instituciones oficiales.\n'
                   '- D) Es plausible porque introduce un criterio de focalización '
                   'socioeconómica usado en otros contextos; pero el régimen de gratuidad en '
                   'instituciones oficiales no distingue por condición socioeconómica para '
                   'prohibir estos cobros académicos.\n'
                   '\n'
                   'Error frecuente del aspirante: Asumir que una necesidad presupuestal '
                   'institucional legítima habilita excepciones al régimen general de gratuidad '
                   'educativa en establecimientos oficiales.\n'
                   '\n'
                   'Estrategia mental recomendada: Ante cobros propuestos en instituciones '
                   'oficiales, verificar si el régimen de gratuidad los prohíbe de manera '
                   'general, sin dejarse persuadir por la finalidad específica alegada para '
                   'justificarlos.\n'
                   '\n'
                   'Subcompetencia: Aplicación contextual del régimen de gratuidad educativa en '
                   'instituciones oficiales y su alcance general',
  'fuente_normativa': 'Ley 115 de 1994, artículo 183, y Decreto 4807 de 2011, sobre gratuidad '
                      'educativa y prohibición de cobros académicos en establecimientos '
                      'oficiales.'},
 {'codigo': 'MOD03-LGE-010',
  'contexto': 'El rector de una institución educativa oficial decidió, por iniciativa propia y '
              'sin consulta previa a ninguna otra instancia, modificar el calendario académico '
              'institucional para adelantar en dos semanas la finalización del año lectivo, con '
              'el propósito de que los docentes contaran con más tiempo para el proceso de '
              'planeación del año siguiente. La decisión fue comunicada mediante una circular '
              'interna fijada en la cartelera principal del establecimiento, sin que mediara '
              'ninguna reunión previa con el Consejo Directivo ni con los representantes de '
              'padres de familia sobre el cambio. Al conocer la decisión, un grupo de padres de '
              'familia reclamó ante la Secretaría de Educación, señalando que esa modificación '
              'afectaba el número mínimo de semanas lectivas legalmente exigido y que había sido '
              'adoptada sin ninguna autorización previa de la autoridad educativa competente. La '
              'Secretaría de Educación, tras verificar los hechos, le informó al rector que el '
              'calendario académico es adoptado y modificado por la propia entidad territorial '
              'certificada dentro de los parámetros mínimos fijados por el Ministerio de '
              'Educación Nacional, entre ellos el número mínimo de semanas lectivas anuales, y '
              'que ningún rector tiene competencia para modificar unilateralmente el calendario '
              'académico de su institución sin la autorización previa y expresa de la Secretaría '
              'de Educación correspondiente, por lo que la decisión adoptada carecía de validez y '
              'debía revertirse de inmediato.',
  'enunciado': '¿Qué decisión se ajusta al régimen normativo aplicable frente a la modificación '
               'del calendario académico adoptada por el rector?',
  'opcion_a': 'La modificación es válida, dado que los rectores de instituciones educativas '
              'oficiales tienen plena competencia para ajustar el calendario académico según las '
              'necesidades de planeación interna del cuerpo docente.',
  'opcion_b': 'La modificación es válida únicamente si es ratificada posteriormente por el '
              'Consejo Directivo, órgano que sustituye a la Secretaría de Educación en la '
              'aprobación de estos cambios de calendario.',
  'opcion_c': 'La modificación es válida siempre que no reduzca el número mínimo de semanas '
              'lectivas, independientemente de si fue o no autorizada previamente por la '
              'Secretaría de Educación competente.',
  'opcion_d': 'La modificación carece de validez, dado que el calendario académico es competencia '
              'de la entidad territorial certificada dentro de los parámetros del Ministerio, sin '
              'que el rector pueda modificarlo unilateralmente sin autorización previa.',
  'respuesta_correcta': 'D',
  'nivel_dificultad': 'muy_alto',
  'proceso_cognitivo': 'analisis_situacional',
  'justificacion': 'El calendario académico es adoptado y modificado por la entidad territorial '
                   'certificada dentro de los parámetros mínimos fijados por el Ministerio de '
                   'Educación Nacional; ningún rector tiene competencia para modificarlo '
                   'unilateralmente sin la autorización previa y expresa de la Secretaría de '
                   'Educación correspondiente.\n'
                   '\n'
                   'Distractores:\n'
                   '- A) Es plausible porque atribuye al rector una autonomía de gestión interna '
                   'aparentemente razonable; pero la competencia sobre el calendario académico '
                   'corresponde a la entidad territorial certificada, no al rector individual.\n'
                   '- B) Es plausible porque menciona un órgano real del gobierno escolar; pero '
                   'el Consejo Directivo no sustituye a la Secretaría de Educación en la '
                   'aprobación del calendario académico institucional.\n'
                   '- C) Es plausible porque introduce un criterio objetivo de semanas mínimas; '
                   'pero la validez de la modificación exige también la autorización previa de '
                   'la autoridad competente, no basta con cumplir el mínimo de semanas.\n'
                   '\n'
                   'Error frecuente del aspirante: Asumir que los rectores tienen autonomía plena '
                   'sobre el calendario académico, sin considerar que esta es una competencia de '
                   'la entidad territorial certificada sujeta a autorización previa.\n'
                   '\n'
                   'Estrategia mental recomendada: Verificar siempre cuál es la autoridad '
                   'competente para cada decisión institucional antes de asumir que el rector '
                   'puede adoptarla unilateralmente por iniciativa propia.\n'
                   '\n'
                   'Subcompetencia: Aplicación contextual de la competencia para adoptar y '
                   'modificar el calendario académico institucional',
  'fuente_normativa': 'Decreto 1075 de 2015, Libro 2, Título 3, sobre calendario académico y '
                      'competencia de las entidades territoriales certificadas.'},
 {'codigo': 'MOD03-LGE-011',
  'contexto': 'Una familia perteneciente a una confesión religiosa distinta a la mayoritaria en '
              'su región solicitó a la institución educativa oficial donde estudiaba su hijo que '
              'lo exonerara de recibir las clases de educación religiosa incluidas en el plan de '
              'estudios, invocando su derecho a la libertad de conciencia y de cultos, y '
              'propuso que, mientras se dictaba esa clase, el estudiante fuera destinado a la '
              'biblioteca para realizar actividades de lectura autónoma bajo la supervisión del '
              'bibliotecario escolar durante ese periodo de tiempo. La solicitud se presentó '
              'por escrito ante la coordinación académica, adjuntando una carta de la familia en '
              'la que explicaban brevemente los fundamentos de su práctica religiosa y '
              'reiteraban que no buscaban cuestionar la oferta curricular general de la '
              'institución, sino únicamente ejercer su derecho individual a la exoneración. La '
              'coordinación '
              'académica accedió a la exoneración solicitada, precisando que el ejercicio de la '
              'libertad de conciencia y de cultos permite a los estudiantes y sus familias '
              'solicitar ser exonerados de recibir la educación religiosa ofrecida por la '
              'institución conforme a su Proyecto Educativo Institucional, sin que ello implique '
              'una vulneración al derecho a la educación del estudiante ni una sanción '
              'disciplinaria de ningún tipo, y que la institución debía disponer una actividad '
              'formativa alternativa razonable durante ese espacio de tiempo, como efectivamente '
              'ocurrió con la actividad de lectura propuesta, en lugar de dejar al estudiante sin '
              'ninguna actividad supervisada durante esas horas de clase.',
  'enunciado': '¿Qué opción resuelve correctamente la solicitud de exoneración de la clase de '
               'educación religiosa presentada por la familia del estudiante?',
  'opcion_a': 'Acceder a la exoneración de la clase de educación religiosa, en ejercicio de la '
              'libertad de conciencia y de cultos, disponiendo una actividad formativa '
              'alternativa razonable durante ese espacio de tiempo escolar.',
  'opcion_b': 'Negar la exoneración solicitada, dado que la educación religiosa incluida en el '
              'plan de estudios institucional es de carácter obligatorio e irrenunciable para '
              'todos los estudiantes matriculados en la institución.',
  'opcion_c': 'Exigir a la familia un cambio de institución educativa, dado que ninguna '
              'institución oficial está obligada legalmente a ofrecer alternativas curriculares '
              'a estudiantes exonerados de la clase de educación religiosa.',
  'opcion_d': 'Condicionar la exoneración a la presentación de una certificación expedida por la '
              'autoridad religiosa correspondiente a la confesión profesada por la familia '
              'solicitante del estudiante.',
  'respuesta_correcta': 'A',
  'nivel_dificultad': 'muy_alto',
  'proceso_cognitivo': 'comprension_aplicada',
  'justificacion': 'El ejercicio de la libertad de conciencia y de cultos permite a los '
                   'estudiantes y sus familias solicitar ser exonerados de recibir la educación '
                   'religiosa, sin que ello implique vulneración al derecho a la educación ni '
                   'sanción disciplinaria alguna; la institución debe disponer, además, una '
                   'actividad formativa alternativa razonable durante ese espacio de tiempo.\n'
                   '\n'
                   'Distractores:\n'
                   '- B) Es plausible porque la educación religiosa forma parte de las áreas '
                   'obligatorias del plan de estudios; pero su carácter obligatorio institucional '
                   'no elimina el derecho individual a la exoneración por libertad de conciencia.\n'
                   '- C) Es plausible porque busca resolver la tensión mediante una salida '
                   'externa; pero la institución sí tiene el deber de disponer alternativas '
                   'razonables para los estudiantes exonerados, sin exigirles cambio de colegio.\n'
                   '- D) Es plausible porque exige un soporte documental aparentemente riguroso; '
                   'pero la normativa no condiciona la exoneración a la certificación de una '
                   'autoridad religiosa específica sobre la confesión profesada.\n'
                   '\n'
                   'Error frecuente del aspirante: Asumir que el carácter de área obligatoria del '
                   'plan de estudios elimina el derecho individual a la exoneración por libertad '
                   'de conciencia y de cultos.\n'
                   '\n'
                   'Estrategia mental recomendada: Distinguir entre la obligatoriedad '
                   'institucional de ofrecer un área en el plan de estudios y el derecho '
                   'individual del estudiante a ser exonerado de recibirla por motivos de '
                   'conciencia.\n'
                   '\n'
                   'Subcompetencia: Aplicación contextual del derecho a la exoneración de la '
                   'educación religiosa por libertad de conciencia y de cultos',
  'fuente_normativa': 'Ley 115 de 1994, artículo 24, y Ley 133 de 1994, sobre libertad religiosa '
                      'y de cultos aplicada al ámbito educativo.'},
 {'codigo': 'MOD03-LGE-012',
  'contexto': 'El Consejo de Padres de Familia de la Institución Educativa "Rafael Uribe Uribe" '
              'adoptó, en sesión ordinaria, una decisión mediante la cual pretendía modificar '
              'directamente el sistema de evaluación institucional vigente, argumentando que, '
              'como representantes legítimos de los estudiantes, tenían la facultad de decidir '
              'sobre cualquier aspecto académico que afectara a sus hijos, incluida la forma en '
              'que estos eran evaluados por los docentes. Un miembro del Consejo de Padres pidió '
              'expresamente que el acta se remitiera a todos los docentes de la institución para '
              'su aplicación inmediata a partir del siguiente periodo académico, sin necesidad de '
              'trámite adicional alguno. El rector, al recibir el acta de esa '
              'sesión, le informó al Consejo de Padres que su decisión carecía de efectos '
              'vinculantes sobre esa materia específica, explicando que el Consejo de Padres de '
              'Familia es un órgano de participación y consulta de los padres dentro de la '
              'institución, cuyas funciones se orientan a apoyar la labor educativa y a '
              'presentar propuestas e inquietudes ante los órganos competentes del gobierno '
              'escolar, pero que no tiene facultad decisoria directa sobre asuntos técnicos y '
              'académicos como el sistema de evaluación institucional, cuya definición '
              'corresponde a otros órganos del gobierno escolar con competencia específica sobre '
              'esa materia, dentro del marco normativo aplicable.',
  'enunciado': '¿Cuál es la naturaleza jurídica correcta de las decisiones adoptadas por el '
               'Consejo de Padres de Familia en materia académica?',
  'opcion_a': 'El Consejo de Padres de Familia tiene facultad decisoria directa y vinculante '
              'sobre cualquier asunto académico de la institución, incluido el sistema de '
              'evaluación institucional vigente.',
  'opcion_b': 'El Consejo de Padres de Familia no puede reunirse ni sesionar válidamente para '
              'discutir asuntos relacionados con el sistema de evaluación institucional de los '
              'estudiantes matriculados.',
  'opcion_c': 'El Consejo de Padres de Familia es un órgano de participación y consulta, sin '
              'facultad decisoria directa sobre asuntos técnicos y académicos como el sistema de '
              'evaluación institucional.',
  'opcion_d': 'El Consejo de Padres de Familia solo puede pronunciarse sobre asuntos académicos '
              'si cuenta con la aprobación previa y expresa del personero estudiantil de la '
              'institución educativa.',
  'respuesta_correcta': 'C',
  'nivel_dificultad': 'muy_alto',
  'proceso_cognitivo': 'identificacion',
  'justificacion': 'El Consejo de Padres de Familia es un órgano de participación y consulta de '
                   'los padres dentro de la institución educativa, orientado a apoyar la labor '
                   'educativa y presentar propuestas ante los órganos competentes del gobierno '
                   'escolar, pero sin facultad decisoria directa sobre asuntos técnicos y '
                   'académicos como el sistema de evaluación institucional.\n'
                   '\n'
                   'Distractores:\n'
                   '- A) Es plausible porque el Consejo de Padres representa legítimamente a las '
                   'familias; pero su naturaleza es consultiva y de apoyo, no decisoria sobre '
                   'asuntos técnicos y académicos como el sistema de evaluación.\n'
                   '- B) Es plausible porque busca limitar la injerencia en asuntos técnicos; '
                   'pero el Consejo de Padres sí puede reunirse y discutir libremente estos temas, '
                   'aunque sus decisiones no tengan efecto vinculante sobre ellos.\n'
                   '- D) Es plausible porque introduce un requisito de coordinación entre '
                   'estamentos; pero la normativa no condiciona los pronunciamientos del Consejo '
                   'de Padres a la aprobación previa del personero estudiantil.\n'
                   '\n'
                   'Error frecuente del aspirante: Asumir que la representación legítima de los '
                   'padres de familia dentro del Consejo de Padres implica automáticamente '
                   'facultad decisoria vinculante sobre asuntos técnicos y académicos.\n'
                   '\n'
                   'Estrategia mental recomendada: Distinguir entre los órganos de participación '
                   'y consulta (como el Consejo de Padres) y los órganos con facultad decisoria '
                   'específica dentro del gobierno escolar antes de atribuir efectos vinculantes.\n'
                   '\n'
                   'Subcompetencia: Aplicación contextual de la naturaleza consultiva del Consejo '
                   'de Padres de Familia frente a decisiones técnicas y académicas',
  'fuente_normativa': 'Decreto 1286 de 2005, sobre la participación de los padres de familia en '
                      'el proceso educativo y la naturaleza del Consejo de Padres.'},
 {'codigo': 'MOD03-LGE-013',
  'contexto': 'Un estudiante de grado once que había aprobado satisfactoriamente todos los '
              'grados de la educación básica y media, y que además había cumplido con el '
              'servicio social estudiantil obligatorio, solicitó a la Secretaría Académica de su '
              'institución que le expidieran de inmediato el título de bachiller, pese a que aún '
              'no había presentado las pruebas de Estado Saber 11, dado que la fecha de '
              'aplicación de dichas pruebas estaba programada para varias semanas después del '
              'cierre del año lectivo. El estudiante necesitaba el título con antelación para '
              'presentarlo como soporte en una convocatoria de una academia técnica que cerraba '
              'sus inscripciones antes de la fecha oficial de las pruebas Saber 11. La Secretaría '
              'Académica le confirmó que procedía la '
              'expedición del título de bachiller, explicando que los requisitos legales para '
              'obtener ese título son la aprobación completa de todos los grados de la educación '
              'básica y media y el cumplimiento del servicio social estudiantil obligatorio, sin '
              'que la presentación de las pruebas de Estado constituya, conforme a la Ley '
              'General de Educación, un requisito adicional para la obtención del título de '
              'bachiller propiamente dicho, aclarando eso sí que dichas pruebas sí son '
              'indispensables como requisito de ingreso a la mayoría de los programas de '
              'educación superior, aunque no para la titulación de bachiller como tal.',
  'enunciado': '¿Cuál es la calificación jurídica correcta de la situación del estudiante frente '
               'a la expedición de su título de bachiller?',
  'opcion_a': 'El título de bachiller procede únicamente de manera condicionada, quedando sujeto '
              'a revocatoria automática si el estudiante no presenta las pruebas de Estado dentro '
              'del año siguiente a su expedición formal.',
  'opcion_b': 'El título de bachiller no procede, dado que la presentación y aprobación de las '
              'pruebas de Estado Saber 11 es, conforme a la ley, un requisito adicional e '
              'indispensable para la obtención de dicho título académico.',
  'opcion_c': 'El título de bachiller procede, dado que sus requisitos legales son la aprobación '
              'completa de la educación básica y media y el servicio social obligatorio, sin '
              'exigir la presentación previa de las pruebas de Estado Saber 11.',
  'opcion_d': 'El título de bachiller no procede, dado que el servicio social estudiantil '
              'obligatorio debe cumplirse simultáneamente con la presentación de las pruebas de '
              'Estado, no en momentos separados del calendario académico.',
  'respuesta_correcta': 'C',
  'nivel_dificultad': 'muy_alto',
  'proceso_cognitivo': 'comprension_aplicada',
  'justificacion': 'Los requisitos legales para obtener el título de bachiller son la aprobación '
                   'completa de todos los grados de la educación básica y media y el cumplimiento '
                   'del servicio social estudiantil obligatorio; la presentación de las pruebas '
                   'de Estado no constituye un requisito adicional para la titulación, aunque sí '
                   'es indispensable para el ingreso a la educación superior.\n'
                   '\n'
                   'Distractores:\n'
                   '- B) Es plausible porque las pruebas de Estado son un trámite ampliamente '
                   'asociado a la finalización del bachillerato; pero la ley no las exige como '
                   'requisito para la expedición del título, sino para el ingreso a la educación '
                   'superior.\n'
                   '- A) Es plausible porque introduce una condición resolutoria aparentemente '
                   'prudente; pero la normativa no contempla la revocatoria del título de '
                   'bachiller por la falta de presentación posterior de las pruebas de Estado.\n'
                   '- D) Es plausible porque vincula dos trámites que suelen coincidir en el '
                   'tiempo; pero la ley no exige que el servicio social y las pruebas de Estado '
                   'se cumplan de manera simultánea dentro del calendario académico.\n'
                   '\n'
                   'Error frecuente del aspirante: Asumir que las pruebas de Estado Saber 11 son '
                   'un requisito legal para la obtención del título de bachiller, confundiéndolas '
                   'con un requisito de ingreso a la educación superior.\n'
                   '\n'
                   'Estrategia mental recomendada: Distinguir claramente entre los requisitos '
                   'legales para la titulación de bachiller y los requisitos para el acceso '
                   'posterior a la educación superior, que son trámites jurídicamente distintos.\n'
                   '\n'
                   'Subcompetencia: Aplicación contextual de los requisitos legales para la '
                   'obtención del título de bachiller',
  'fuente_normativa': 'Ley 115 de 1994, artículo 88, sobre el título de bachiller y sus '
                      'requisitos de expedición.'},
 {'codigo': 'MOD03-LGE-014',
  'contexto': 'Una institución educativa oficial ubicada en zona rural dispersa, con estudiantes '
              'provenientes de veredas alejadas y con alta rotación escolar asociada a las '
              'labores agrícolas de las familias, adoptó el modelo educativo flexible de Escuela '
              'Nueva para la organización de la educación básica primaria, en lugar del modelo '
              'graduado tradicional aplicado en las instituciones urbanas del mismo municipio. '
              'Un funcionario de la Secretaría de Educación, al realizar una visita de '
              'inspección, cuestionó inicialmente la adopción de ese modelo, señalando que "toda '
              'institución oficial del departamento debía aplicar el mismo modelo pedagógico '
              'graduado, sin distinción entre zona urbana y zona rural, para garantizar '
              'uniformidad en el sistema educativo territorial". El funcionario incluso sugirió '
              'consignar la observación como hallazgo en el informe de inspección, con '
              'recomendación de que la institución retornara al modelo graduado tradicional en '
              'un plazo de seis meses. El rector le explicó, con '
              'apoyo de la normativa aplicable, que la flexibilización curricular y la adopción '
              'de modelos educativos flexibles como Escuela Nueva están expresamente reconocidas '
              'y promovidas por el Ministerio de Educación Nacional para las instituciones '
              'rurales, precisamente en atención a las particularidades del medio rural disperso '
              'y a la necesidad de adaptar la prestación del servicio educativo a las condiciones '
              'reales de la población atendida, sin que ello implique un desconocimiento de los '
              'contenidos curriculares mínimos exigidos por la ley.',
  'enunciado': '¿Cuál es el procedimiento correcto que respalda la adopción del modelo educativo '
               'flexible en la institución rural?',
  'opcion_a': 'Los modelos educativos flexibles como Escuela Nueva están expresamente '
              'reconocidos y promovidos para instituciones rurales, en atención a las '
              'particularidades del medio y sin desconocer los contenidos curriculares mínimos.',
  'opcion_b': 'Ninguna institución educativa oficial puede apartarse del modelo pedagógico '
              'graduado tradicional, independientemente de su ubicación geográfica o de las '
              'condiciones particulares de la población que atiende.',
  'opcion_c': 'Los modelos educativos flexibles solo pueden adoptarse mediante autorización '
              'expresa y previa del Ministerio de Educación Nacional para cada institución rural '
              'de manera individual y caso por caso.',
  'opcion_d': 'La adopción de modelos educativos flexibles como Escuela Nueva implica '
              'necesariamente una reducción de los contenidos curriculares mínimos exigidos por '
              'la Ley General de Educación para la educación básica primaria.',
  'respuesta_correcta': 'A',
  'nivel_dificultad': 'muy_alto',
  'proceso_cognitivo': 'comprension_aplicada',
  'justificacion': 'Los modelos educativos flexibles como Escuela Nueva están expresamente '
                   'reconocidos y promovidos por el Ministerio de Educación Nacional para las '
                   'instituciones rurales, en atención a las particularidades del medio rural '
                   'disperso, sin que su adopción implique desconocer los contenidos curriculares '
                   'mínimos exigidos por la ley para la educación básica.\n'
                   '\n'
                   'Distractores:\n'
                   '- B) Es plausible porque invoca la uniformidad del sistema educativo '
                   'territorial; pero la normativa reconoce expresamente la flexibilización '
                   'curricular para instituciones rurales, apartándose del modelo graduado '
                   'tradicional.\n'
                   '- C) Es plausible porque exige un control previo aparentemente riguroso; '
                   'pero los modelos flexibles ya cuentan con reconocimiento general del '
                   'Ministerio, sin requerir autorización individual caso por caso para cada '
                   'institución.\n'
                   '- D) Es plausible porque asocia la flexibilización con una disminución de '
                   'exigencia; pero estos modelos mantienen los contenidos curriculares mínimos, '
                   'solo adaptan la metodología a las condiciones del medio rural.\n'
                   '\n'
                   'Error frecuente del aspirante: Asumir que la flexibilización curricular para '
                   'zonas rurales implica necesariamente una reducción de los contenidos mínimos '
                   'exigidos, en lugar de una simple adaptación metodológica.\n'
                   '\n'
                   'Estrategia mental recomendada: Distinguir entre la adaptación metodológica '
                   'que permiten los modelos educativos flexibles y una eventual reducción de '
                   'contenidos curriculares mínimos, que la norma no autoriza.\n'
                   '\n'
                   'Subcompetencia: Aplicación contextual de los modelos educativos flexibles '
                   'reconocidos para la educación rural',
  'fuente_normativa': 'Ley 115 de 1994, artículos 64 y 65 (educación campesina y rural), y '
                      'lineamientos del Ministerio de Educación Nacional sobre modelos educativos '
                      'flexibles.'},
 {'codigo': 'MOD03-LGE-015',
  'contexto': 'Los docentes del área de tecnología e informática de una institución educativa '
              'oficial propusieron ante el Consejo Académico incorporar, dentro de las horas '
              'asignadas a esa área obligatoria, un componente adicional de robótica educativa, '
              'utilizando material didáctico donado recientemente a la institución por una '
              'fundación privada. Un docente de otra área se opuso a la propuesta, argumentando '
              'que "ninguna institución educativa puede introducir contenidos que no estén '
              'expresamente enumerados en los lineamientos curriculares nacionales para cada '
              'área obligatoria". El debate se extendió a una segunda sesión del Consejo '
              'Académico, en la que se solicitó un concepto escrito al coordinador académico '
              'sobre el alcance real de la autonomía escolar en materia de contenidos '
              'curriculares complementarios. El Consejo Académico, tras estudiar la propuesta con '
              'apoyo del '
              'coordinador académico, concluyó que la autonomía escolar sí permite a las '
              'instituciones adaptar y complementar los contenidos de las áreas obligatorias '
              'conforme a las necesidades y posibilidades reales del entorno institucional, '
              'siempre que se respeten los lineamientos y estándares básicos de competencias '
              'fijados por el Ministerio de Educación Nacional para esa área, de modo que la '
              'incorporación de un componente de robótica dentro del área de tecnología e '
              'informática resultaba plenamente viable, sin que ello requiriera una autorización '
              'previa y específica del Ministerio para cada contenido complementario que se '
              'quisiera incluir dentro del área.',
  'enunciado': '¿Qué opción resuelve correctamente el desacuerdo planteado sobre la '
               'incorporación de robótica dentro del área de tecnología e informática?',
  'opcion_a': 'La objeción es correcta, dado que ninguna institución educativa puede incorporar '
              'contenidos adicionales a los expresamente enumerados en los lineamientos '
              'curriculares nacionales para cada área obligatoria del plan de estudios.',
  'opcion_b': 'La objeción es incorrecta, dado que la autonomía escolar permite adaptar y '
              'complementar los contenidos de las áreas obligatorias conforme al entorno '
              'institucional, respetando los estándares básicos fijados por el Ministerio.',
  'opcion_c': 'La objeción es correcta, pero únicamente porque el material didáctico donado '
              'proviene de una fundación privada y no de recursos propios de la institución '
              'educativa oficial.',
  'opcion_d': 'La objeción es incorrecta, pero solo porque la robótica educativa ya está '
              'expresamente enumerada como contenido obligatorio dentro de los lineamientos '
              'curriculares nacionales vigentes.',
  'respuesta_correcta': 'B',
  'nivel_dificultad': 'muy_alto',
  'proceso_cognitivo': 'evaluacion_juicio',
  'justificacion': 'La autonomía escolar permite a las instituciones adaptar y complementar los '
                   'contenidos de las áreas obligatorias conforme a las necesidades y '
                   'posibilidades del entorno institucional, siempre que se respeten los '
                   'lineamientos y estándares básicos de competencias fijados por el Ministerio '
                   'de Educación Nacional para esa área específica.\n'
                   '\n'
                   'Distractores:\n'
                   '- A) Es plausible porque invoca la uniformidad curricular nacional; pero la '
                   'autonomía escolar sí permite complementar los contenidos de las áreas '
                   'obligatorias, respetando los estándares básicos fijados por el Ministerio.\n'
                   '- C) Es plausible porque introduce el origen del material didáctico como '
                   'factor relevante; pero la procedencia de una donación privada no determina '
                   'la validez de incorporar un contenido complementario al área.\n'
                   '- D) Es plausible porque plantea una razón alternativa aparentemente técnica; '
                   'pero la viabilidad de incorporar robótica no depende de que ya esté '
                   'enumerada expresamente, sino del ejercicio legítimo de la autonomía escolar.\n'
                   '\n'
                   'Error frecuente del aspirante: Asumir que los lineamientos curriculares '
                   'nacionales agotan taxativamente los contenidos posibles de cada área, sin '
                   'reconocer el margen de complementación que otorga la autonomía escolar.\n'
                   '\n'
                   'Estrategia mental recomendada: Ante propuestas de contenidos complementarios '
                   'dentro de áreas obligatorias, verificar si respetan los estándares básicos '
                   'del Ministerio, en lugar de exigir que estén enumerados taxativamente.\n'
                   '\n'
                   'Subcompetencia: Aplicación contextual de la autonomía escolar para '
                   'complementar contenidos dentro de las áreas obligatorias del plan de '
                   'estudios',
  'fuente_normativa': 'Ley 115 de 1994, artículos 23 y 77, sobre áreas obligatorias y autonomía '
                      'escolar para su adaptación y complementación.'},
]
