# -*- coding: utf-8 -*-
"""Banco Oficial de Preguntas - Modulo: Normatividad Educativa | Tema: Decreto
1290 de 2009 y Sistema Institucional de Evaluacion de los Estudiantes -SIEE-
(Lote 1). Contenido enteramente nuevo, sin reutilizar nada del borrador
descartado del Modulo 3. Dificultad unicamente Muy Alta. Codigos MOD03-SIEE-.
Clave planificada de antemano (B,C,D,A,C,B,D,C,A,B,D,C,B,D,A) para lograr
distribucion balanceada A/B/C/D dentro del tema. Longitud de opciones
equilibrada por diseno para evitar sesgo de longitud.
"""

CATEGORIA = "Normatividad Educativa"
SUBCATEGORIA = "Normatividad Educativa - Decreto 1290 y SIEE"
COMPETENCIA = "Normativa educativa aplicada"
AREA = "general"

ITEMS = [
 {'codigo': 'MOD03-SIEE-001',
  'contexto': 'La Institución Educativa "Rafael Pombo" adoptó, mediante acuerdo del Consejo '
              'Directivo, un Sistema Institucional de Evaluación de los Estudiantes que definía '
              'con detalle la escala de valoración institucional y las estrategias de valoración '
              'integral de los desempeños, pero que no incluía ninguna disposición sobre los '
              'procedimientos y mecanismos para atender y resolver las reclamaciones de los '
              'estudiantes o padres de familia frente a las decisiones de evaluación y promoción. '
              'Un grupo de padres, tras intentar sin éxito radicar una reclamación formal sobre '
              'la calificación de un examen, señaló ante la rectoría que el documento '
              'institucional resultaba incompleto frente a lo exigido por la normativa nacional, '
              'aportando como soporte una copia impresa del SIEE vigente descargada del sitio web '
              'de la institución. '
              'La rectoría, tras consultar con la Secretaría de Educación, reconoció el '
              'vacío y convocó al Consejo Académico para ajustar el documento, explicando que el '
              'Decreto 1290 de 2009 exige que todo Sistema Institucional de Evaluación de los '
              'Estudiantes contenga, entre sus componentes obligatorios, las instancias, '
              'procedimientos y mecanismos de atención y resolución de reclamaciones, de manera '
              'que la ausencia de esa regulación específica constituía una omisión que debía '
              'subsanarse mediante la reforma correspondiente del documento institucional antes '
              'de que pudiera considerarse completo y ajustado a la normativa vigente.',
  'enunciado': '¿Cuál es el componente obligatorio del SIEE cuya ausencia fue identificada en el '
               'documento institucional de la institución educativa?',
  'opcion_a': 'Los criterios de evaluación y promoción de los estudiantes, componente que la '
              'institución había omitido definir dentro de su Sistema Institucional de '
              'Evaluación adoptado.',
  'opcion_b': 'Las instancias, procedimientos y mecanismos de atención y resolución de '
              'reclamaciones, componente obligatorio que el Decreto 1290 exige incluir en todo '
              'SIEE institucional.',
  'opcion_c': 'La escala de valoración institucional y su equivalencia con la escala nacional, '
              'componente que la institución tampoco había definido dentro del documento '
              'adoptado por el Consejo Directivo.',
  'opcion_d': 'Los mecanismos de participación de la comunidad educativa en la construcción del '
              'documento, componente que la institución había excluido completamente de su '
              'Sistema Institucional de Evaluación.',
  'respuesta_correcta': 'B',
  'nivel_dificultad': 'muy_alto',
  'proceso_cognitivo': 'identificacion',
  'justificacion': 'El Decreto 1290 de 2009 exige que todo Sistema Institucional de Evaluación de '
                   'los Estudiantes contenga, entre sus componentes obligatorios, las instancias, '
                   'procedimientos y mecanismos de atención y resolución de reclamaciones sobre '
                   'evaluación y promoción, componente que el caso describe expresamente como '
                   'ausente en el documento institucional adoptado.\n'
                   '\n'
                   'Distractores:\n'
                   '- A) Es plausible porque menciona un componente real y obligatorio del SIEE; '
                   'pero el caso indica que la institución sí había definido con detalle sus '
                   'criterios de evaluación, no que los hubiera omitido.\n'
                   '- C) Es plausible porque menciona otro componente real del SIEE; pero el caso '
                   'señala expresamente que la escala de valoración sí había sido definida con '
                   'detalle por la institución.\n'
                   '- D) Es plausible porque menciona un componente adicional exigido por la '
                   'norma; pero el vacío identificado en el caso se refiere específicamente a los '
                   'mecanismos de reclamación, no a los de participación comunitaria.\n'
                   '\n'
                   'Error frecuente del aspirante: Confundir entre sí los distintos componentes '
                   'obligatorios del SIEE listados en el Decreto 1290, sin identificar '
                   'específicamente cuál fue el omitido en el caso descrito.\n'
                   '\n'
                   'Estrategia mental recomendada: Verificar con precisión cuál componente '
                   'específico del SIEE fue objeto de la omisión descrita en el caso, en lugar de '
                   'asumir genéricamente cualquier componente obligatorio de la norma.\n'
                   '\n'
                   'Subcompetencia: Aplicación contextual de los componentes obligatorios del '
                   'Sistema Institucional de Evaluación de los Estudiantes',
  'fuente_normativa': 'Decreto 1290 de 2009, artículo 4, numeral 10, sobre los componentes '
                      'obligatorios del Sistema Institucional de Evaluación de los Estudiantes.'},
 {'codigo': 'MOD03-SIEE-002',
  'contexto': 'Un estudiante de grado cuarto, trasladado desde otra ciudad a mitad del año '
              'escolar, llegó a la Institución Educativa "Antonia Santos" con un informe '
              'académico de su colegio anterior en el que su desempeño en el área de ciencias '
              'naturales aparecía calificado como "Excelente", conforme a la escala de valoración '
              'propia de esa otra institución. La docente del área, al recibir el informe, no '
              'sabía si debía trasladar directamente esa calificación textual a su propio '
              'registro académico o si debía realizar algún procedimiento adicional antes de '
              'incorporarla, y consultó el caso con la coordinación académica antes de registrar '
              'ninguna nota definitiva en el sistema de la institución, adjuntando además una '
              'copia física del informe original del colegio de procedencia para el archivo del '
              'estudiante. La coordinación académica le explicó que, dado que el Decreto 1290 '
              'de 2009 permite que cada institución defina su propia escala de valoración '
              'siempre que sea homologable con la escala nacional de desempeño superior, alto, '
              'básico y bajo, la calificación traída del colegio anterior debía primero '
              'convertirse a la escala de valoración institucional propia de la nueva '
              'institución, mediante la respectiva tabla de equivalencias, y no incorporarse '
              'literalmente con la denominación original utilizada por el establecimiento de '
              'origen, que podía no coincidir exactamente con las categorías adoptadas '
              'internamente por la institución receptora.',
  'enunciado': '¿Cómo debe resolver la coordinación académica el manejo de la calificación traída '
               'por el estudiante trasladado desde otra institución?',
  'opcion_a': 'La calificación "Excelente" debe incorporarse literalmente al registro académico '
              'de la nueva institución, sin ningún procedimiento adicional de conversión o '
              'equivalencia entre escalas de valoración.',
  'opcion_b': 'El estudiante debe repetir por completo el periodo académico ya cursado en su '
              'colegio anterior, dado que ninguna calificación obtenida en otra institución puede '
              'ser reconocida ni homologada bajo ninguna circunstancia.',
  'opcion_c': 'La calificación debe primero convertirse a la escala de valoración institucional '
              'propia de la nueva institución mediante la tabla de equivalencias correspondiente, '
              'sin incorporarse literalmente con la denominación de origen.',
  'opcion_d': 'La calificación solo puede incorporarse si la Secretaría de Educación del '
              'municipio receptor expide previamente una autorización individual y específica '
              'para el caso particular de ese estudiante trasladado.',
  'respuesta_correcta': 'C',
  'nivel_dificultad': 'muy_alto',
  'proceso_cognitivo': 'comprension_aplicada',
  'justificacion': 'El Decreto 1290 de 2009 permite que cada institución defina su propia escala '
                   'de valoración, siempre homologable con la escala nacional; por ello, una '
                   'calificación proveniente de otra institución debe convertirse a la escala '
                   'institucional propia mediante la tabla de equivalencias correspondiente, sin '
                   'incorporarse literalmente con la denominación de origen.\n'
                   '\n'
                   'Distractores:\n'
                   '- A) Es plausible porque simplifica el trámite de traslado; pero cada '
                   'institución tiene su propia escala de valoración, por lo que la denominación '
                   'original no necesariamente coincide con las categorías propias.\n'
                   '- B) Es plausible porque exige una nueva evaluación completa; pero la norma '
                   'no exige repetir el periodo ya cursado, sino homologar la calificación '
                   'obtenida mediante la conversión de escalas correspondiente.\n'
                   '- D) Es plausible porque introduce un trámite administrativo adicional '
                   'aparentemente riguroso; pero la homologación de la calificación es un '
                   'procedimiento interno institucional, no una autorización previa de la '
                   'Secretaría de Educación.\n'
                   '\n'
                   'Error frecuente del aspirante: Asumir que las calificaciones de otras '
                   'instituciones deben incorporarse literalmente o que exigen una nueva '
                   'evaluación completa, sin considerar la homologación mediante tabla de '
                   'equivalencias.\n'
                   '\n'
                   'Estrategia mental recomendada: Ante calificaciones provenientes de otra '
                   'institución, verificar si existe un procedimiento de homologación mediante '
                   'tabla de equivalencias entre escalas de valoración distintas.\n'
                   '\n'
                   'Subcompetencia: Aplicación contextual de la homologación de calificaciones '
                   'entre escalas de valoración institucionales distintas',
  'fuente_normativa': 'Decreto 1290 de 2009, artículo 5, sobre la escala de valoración '
                      'institucional y su equivalencia con la escala de valoración nacional.'},
 {'codigo': 'MOD03-SIEE-003',
  'contexto': 'Un estudiante de grado quinto de la Institución Educativa "Camilo Torres" '
              'presentó, desde el inicio del año escolar, un rendimiento académico '
              'excepcionalmente alto en todas las áreas del plan de estudios correspondiente a su '
              'grado, junto con un desarrollo personal y social igualmente sobresaliente '
              'reconocido por el equipo docente. Los padres del estudiante solicitaron '
              'formalmente a la institución que fuera promovido de manera anticipada al grado '
              'sexto, sin necesidad de culminar la totalidad del año escolar en curso, aportando como '
              'soporte los boletines de los tres primeros periodos y una carta del docente '
              'director de grupo que respaldaba la solicitud. La coordinación académica les '
              'explicó que esa solicitud debía tramitarse conforme al '
              'procedimiento previsto en la normativa, según el cual el Consejo Académico, previo '
              'consentimiento de los padres de familia, debe recomendar ante el Consejo Directivo '
              'la promoción anticipada de grado del estudiante que demuestre un rendimiento '
              'superior en su desarrollo cognitivo, personal y social, y que dicha recomendación '
              'debe formularse dentro de las primeras semanas del año escolar, siendo el Consejo '
              'Directivo quien finalmente decide sobre la promoción anticipada solicitada, '
              'consignando la decisión adoptada en el acta correspondiente y en el registro '
              'escolar del estudiante.',
  'enunciado': '¿Cuál es el procedimiento jurídicamente correcto para tramitar la promoción '
               'anticipada de grado solicitada por los padres del estudiante?',
  'opcion_a': 'El rector puede decidir unilateralmente la promoción anticipada del estudiante, '
              'sin necesidad de recomendación previa del Consejo Académico ni decisión formal del '
              'Consejo Directivo institucional.',
  'opcion_b': 'La promoción anticipada procede automáticamente por la sola solicitud escrita de '
              'los padres de familia, sin que se requiera ninguna recomendación ni decisión de '
              'los órganos del gobierno escolar.',
  'opcion_c': 'La promoción anticipada solo puede tramitarse al finalizar completamente el año '
              'escolar en curso, una vez el estudiante haya aprobado la totalidad de las áreas '
              'del plan de estudios correspondiente a su grado actual.',
  'opcion_d': 'El Consejo Académico, previo consentimiento de los padres, debe recomendar la '
              'promoción anticipada ante el Consejo Directivo, quien decide finalmente y consigna '
              'la decisión en el acta y el registro escolar.',
  'respuesta_correcta': 'D',
  'nivel_dificultad': 'muy_alto',
  'proceso_cognitivo': 'identificacion',
  'justificacion': 'El procedimiento de promoción anticipada de grado exige que el Consejo '
                   'Académico, previo consentimiento de los padres de familia, recomiende ante el '
                   'Consejo Directivo la promoción del estudiante con rendimiento superior, siendo '
                   'este último órgano quien decide finalmente y consigna la decisión en el acta y '
                   'el registro escolar correspondiente.\n'
                   '\n'
                   'Distractores:\n'
                   '- A) Es plausible porque atribuye la decisión a la máxima autoridad '
                   'institucional; pero el procedimiento exige la recomendación previa del '
                   'Consejo Académico y la decisión formal del Consejo Directivo, no una '
                   'decisión unilateral del rector.\n'
                   '- B) Es plausible porque simplifica el trámite a la sola voluntad de los '
                   'padres; pero la norma exige la intervención de los órganos del gobierno '
                   'escolar, no solo la solicitud escrita de la familia.\n'
                   '- C) Es plausible porque asocia la promoción con la culminación del año '
                   'escolar; pero precisamente la promoción anticipada permite avanzar de grado '
                   'sin necesidad de culminar la totalidad del año escolar en curso.\n'
                   '\n'
                   'Error frecuente del aspirante: Confundir la promoción anticipada de grado con '
                   'la promoción ordinaria al finalizar el año escolar, o atribuir la decisión a '
                   'un solo órgano sin reconocer la intervención conjunta del Consejo Académico y '
                   'el Consejo Directivo.\n'
                   '\n'
                   'Estrategia mental recomendada: Identificar los dos momentos del procedimiento '
                   'de promoción anticipada (recomendación del Consejo Académico y decisión del '
                   'Consejo Directivo) antes de calificar cualquier trámite como válido.\n'
                   '\n'
                   'Subcompetencia: Aplicación contextual del procedimiento de promoción '
                   'anticipada de grado previsto en el Decreto 1290',
  'fuente_normativa': 'Decreto 1290 de 2009, artículo 7, sobre la promoción anticipada de grado.'},
 {'codigo': 'MOD03-SIEE-004',
  'contexto': 'Un estudiante de grado octavo de la Institución Educativa "Policarpa Salavarrieta" '
              'no fue promovido al grado siguiente al finalizar el año escolar, tras haber '
              'reprobado tres áreas del plan de estudios correspondiente. El estudiante, con '
              'apoyo de su acudiente, presentó una reclamación formal ante la instancia '
              'institucional prevista en el SIEE, argumentando que dos de las tres áreas '
              'reprobadas habían sido calificadas sin haberle informado previamente, durante el '
              'año escolar, sobre su bajo desempeño ni haberle ofrecido ningún plan de apoyo o '
              'actividades de refuerzo para superar esas dificultades académicas, pese a que los '
              'boletines de los tres primeros periodos ya reflejaban un desempeño bajo sostenido '
              'en esas mismas áreas desde el inicio del año escolar. La comisión de '
              'evaluación y promoción, al estudiar el caso, encontró que efectivamente no existía '
              'evidencia de que se hubieran implementado las estrategias de apoyo y seguimiento '
              'exigidas por el SIEE institucional durante el año escolar, por lo que concluyó que '
              'la decisión de no promoción debía revisarse, dado que el sistema de evaluación '
              'institucional exige, como componente obligatorio, la implementación oportuna de '
              'acciones de seguimiento y estrategias de apoyo para resolver las situaciones '
              'pedagógicas pendientes de los estudiantes durante el año escolar, y no solo al '
              'final del proceso mediante la calificación definitiva.',
  'enunciado': '¿Cuál es el fundamento jurídico correcto que sustentó la revisión de la decisión '
               'de no promoción del estudiante?',
  'opcion_a': 'La omisión de implementar oportunamente las estrategias de apoyo y acciones de '
              'seguimiento exigidas por el SIEE durante el año escolar, y no solo la calificación '
              'final del estudiante.',
  'opcion_b': 'La circunstancia de que el estudiante hubiera reprobado exactamente tres áreas del '
              'plan de estudios, número que la normativa nacional fija como límite máximo '
              'absoluto para la no promoción.',
  'opcion_c': 'La falta de firma del acudiente en el informe final de calificaciones entregado al '
              'estudiante antes de la decisión definitiva de no promoción adoptada por la '
              'institución.',
  'opcion_d': 'La ausencia de aprobación previa de la Secretaría de Educación municipal para '
              'cualquier decisión institucional de no promoción de un estudiante de educación '
              'básica secundaria.',
  'respuesta_correcta': 'A',
  'nivel_dificultad': 'muy_alto',
  'proceso_cognitivo': 'analisis_situacional',
  'justificacion': 'El SIEE institucional exige, como componente obligatorio, la implementación '
                   'oportuna de acciones de seguimiento y estrategias de apoyo para resolver las '
                   'situaciones pedagógicas pendientes de los estudiantes durante el año escolar; '
                   'su omisión constituye un vicio que justifica la revisión de la decisión de no '
                   'promoción adoptada al final del proceso.\n'
                   '\n'
                   'Distractores:\n'
                   '- B) Es plausible porque introduce un límite numérico aparentemente objetivo; '
                   'pero la normativa nacional no fija un número máximo de áreas reprobadas como '
                   'criterio único y automático de no promoción.\n'
                   '- C) Es plausible porque menciona un requisito formal real de los informes; '
                   'pero el vicio central identificado en el caso no es la firma del acudiente, '
                   'sino la ausencia de estrategias de apoyo oportunas.\n'
                   '- D) Es plausible porque involucra a la autoridad educativa territorial; pero '
                   'las decisiones de promoción y no promoción son competencia institucional, sin '
                   'requerir aprobación previa individual de la Secretaría de Educación.\n'
                   '\n'
                   'Error frecuente del aspirante: Centrar el análisis en aspectos formales o '
                   'numéricos de la calificación final, sin advertir que el vicio de fondo es la '
                   'ausencia de estrategias de apoyo durante el año escolar.\n'
                   '\n'
                   'Estrategia mental recomendada: Verificar siempre si se implementaron '
                   'oportunamente las estrategias de apoyo y seguimiento exigidas por el SIEE '
                   'antes de evaluar la validez de una decisión final de no promoción.\n'
                   '\n'
                   'Subcompetencia: Aplicación contextual del deber institucional de implementar '
                   'estrategias de apoyo y seguimiento durante el año escolar',
  'fuente_normativa': 'Decreto 1290 de 2009, artículo 4, numerales 4 y 6, sobre acciones de '
                      'seguimiento y estrategias de apoyo para resolver situaciones pedagógicas '
                      'pendientes.'},
 {'codigo': 'MOD03-SIEE-005',
  'contexto': 'El rector de una institución educativa oficial decidió, por iniciativa propia y '
              'sin someterlo a discusión de ningún otro órgano institucional, modificar '
              'unilateralmente el Sistema Institucional de Evaluación de los Estudiantes para '
              'endurecer los criterios de promoción del grado once, argumentando que esa medida '
              'mejoraría los resultados institucionales en las pruebas de Estado, y comunicó la '
              'decisión mediante una circular interna dirigida únicamente a los docentes de grado '
              'once, sin registrarla en ningún acta institucional. Un grupo de '
              'docentes del área de ciencias naturales cuestionó la validez de esa modificación '
              'ante la Secretaría de Educación, señalando que el rector había actuado sin '
              'competencia para reformar unilateralmente el documento institucional. La '
              'Secretaría de Educación, tras revisar el caso, le confirmó a los docentes que '
              'tenían razón, explicando que la adopción y cualquier modificación posterior del '
              'Sistema Institucional de Evaluación de los Estudiantes debe surtirse mediante el '
              'análisis y discusión previa en el Consejo Académico y la aprobación formal del '
              'Consejo Directivo como órgano competente, sin que el rector, actuando de manera '
              'individual y unilateral, tenga la facultad de modificar por sí solo los criterios '
              'de evaluación y promoción ya adoptados institucionalmente.',
  'enunciado': '¿Cuál es la consecuencia jurídica correcta de la modificación unilateral del SIEE '
               'adoptada por el rector sin discusión previa en el Consejo Académico?',
  'opcion_a': 'La modificación es válida, dado que el rector, como representante legal de la '
              'institución educativa, tiene plena facultad para modificar unilateralmente '
              'cualquier componente del SIEE institucional.',
  'opcion_b': 'La modificación es válida únicamente si es notificada posteriormente al Ministerio '
              'de Educación Nacional dentro de los treinta días siguientes a su adopción por '
              'parte del rector.',
  'opcion_c': 'La modificación carece de validez, dado que la reforma del SIEE exige análisis y '
              'discusión previa en el Consejo Académico y aprobación formal del Consejo '
              'Directivo, no una decisión unilateral del rector.',
  'opcion_d': 'La modificación carece de validez, pero únicamente porque no fue consultada '
              'previamente con los estudiantes de grado once que resultarían directamente '
              'afectados por el endurecimiento de los criterios.',
  'respuesta_correcta': 'C',
  'nivel_dificultad': 'muy_alto',
  'proceso_cognitivo': 'evaluacion_juicio',
  'justificacion': 'La adopción y cualquier modificación posterior del Sistema Institucional de '
                   'Evaluación de los Estudiantes debe surtirse mediante el análisis y discusión '
                   'previa en el Consejo Académico y la aprobación formal del Consejo Directivo, '
                   'sin que el rector tenga la facultad de modificarlo unilateralmente por sí '
                   'solo.\n'
                   '\n'
                   'Distractores:\n'
                   '- A) Es plausible porque atribuye amplia facultad de representación legal al '
                   'rector; pero esa representación no incluye la modificación unilateral de '
                   'componentes institucionales que exigen aprobación colegiada.\n'
                   '- B) Es plausible porque introduce un trámite de notificación externa '
                   'aparentemente riguroso; pero la validez de la modificación depende del '
                   'procedimiento interno de aprobación, no de una notificación posterior al '
                   'Ministerio.\n'
                   '- D) Es plausible porque menciona a los estudiantes como parte interesada '
                   'real; pero el vicio central de la modificación es la ausencia de discusión en '
                   'el Consejo Académico y aprobación del Consejo Directivo, no la falta de '
                   'consulta estudiantil específica.\n'
                   '\n'
                   'Error frecuente del aspirante: Asumir que la representación legal del rector '
                   'incluye la facultad de modificar unilateralmente documentos institucionales '
                   'que exigen aprobación de órganos colegiados específicos.\n'
                   '\n'
                   'Estrategia mental recomendada: Verificar siempre si una modificación '
                   'institucional exige aprobación de órganos colegiados específicos antes de '
                   'aceptar una decisión unilateral del rector como válida.\n'
                   '\n'
                   'Subcompetencia: Aplicación contextual del procedimiento de adopción y reforma '
                   'del Sistema Institucional de Evaluación de los Estudiantes',
  'fuente_normativa': 'Decreto 1290 de 2009, artículo 8, sobre la adopción del Sistema '
                      'Institucional de Evaluación de los Estudiantes por parte del Consejo '
                      'Directivo, previo análisis del Consejo Académico.'},
 {'codigo': 'MOD03-SIEE-006',
  'contexto': 'Al finalizar el segundo periodo académico, la Institución Educativa "Antonio '
              'Ricaurte" entregó a los padres de familia un informe de evaluación que contenía '
              'únicamente una calificación numérica global para cada área del plan de estudios, '
              'sin ninguna descripción cualitativa sobre las fortalezas o dificultades '
              'específicas identificadas en el desempeño de cada estudiante durante el periodo, '
              'formato que la institución venía utilizando sin modificaciones desde hacía varios '
              'años consecutivos. '
              'Varios padres de familia manifestaron su inconformidad ante la rectoría, '
              'señalando que ese formato de informe no les permitía entender concretamente en qué '
              'aspectos debían apoyar a sus hijos en casa. La rectoría, tras consultar con el '
              'Consejo Académico, reconoció la falencia y ordenó ajustar el formato de los '
              'informes para los periodos siguientes, explicando que el Decreto 1290 exige que '
              'los informes periódicos de evaluación contengan, además de la valoración '
              'cuantitativa o cualitativa según la escala institucional adoptada, una explicación '
              'sobre las fortalezas y dificultades que el estudiante presenta en cada una de las '
              'áreas evaluadas, de manera que un informe compuesto únicamente por calificaciones '
              'numéricas globales, sin ninguna descripción cualitativa del desempeño, resultaba '
              'insuficiente frente a lo exigido por la normativa vigente sobre la materia.',
  'enunciado': '¿Qué curso de acción resulta procedente frente a la falencia identificada en el '
               'contenido de los informes periódicos de evaluación entregados a las familias?',
  'opcion_a': 'Los informes periódicos de evaluación deben incluir una explicación de las '
              'fortalezas y dificultades del estudiante en cada área, y no limitarse a una '
              'calificación numérica global sin descripción cualitativa.',
  'opcion_b': 'Los informes periódicos de evaluación solo deben contener la calificación '
              'numérica global de cada área, dado que la normativa prohíbe expresamente incluir '
              'cualquier descripción cualitativa adicional sobre el desempeño.',
  'opcion_c': 'Los informes periódicos de evaluación son un documento opcional que cada '
              'institución puede decidir libremente si entrega o no a los padres de familia '
              'durante el transcurso del año escolar.',
  'opcion_d': 'Los informes periódicos de evaluación deben remitirse directamente al Ministerio '
              'de Educación Nacional antes de ser entregados a los padres de familia, para su '
              'revisión y aprobación previa.',
  'respuesta_correcta': 'A',
  'nivel_dificultad': 'muy_alto',
  'proceso_cognitivo': 'comprension_aplicada',
  'justificacion': 'El Decreto 1290 exige que los informes periódicos de evaluación contengan, '
                   'además de la valoración según la escala institucional, una explicación sobre '
                   'las fortalezas y dificultades que el estudiante presenta en cada área '
                   'evaluada, de manera que un informe compuesto únicamente por calificaciones '
                   'numéricas globales resulta insuficiente.\n'
                   '\n'
                   'Distractores:\n'
                   '- B) Es plausible porque afirma una restricción aparentemente normativa; pero '
                   'la norma exige precisamente lo contrario: incluir descripción cualitativa de '
                   'fortalezas y dificultades, no prohibirla.\n'
                   '- C) Es plausible porque sugiere flexibilidad institucional; pero la entrega '
                   'de informes periódicos con contenido cualitativo es un componente obligatorio '
                   'del SIEE, no una opción discrecional de la institución.\n'
                   '- D) Es plausible porque involucra a la autoridad nacional en un trámite '
                   'aparentemente riguroso; pero los informes periódicos no requieren aprobación '
                   'previa del Ministerio antes de su entrega a las familias.\n'
                   '\n'
                   'Error frecuente del aspirante: Asumir que los informes periódicos de '
                   'evaluación pueden limitarse a la calificación numérica, sin reconocer la '
                   'exigencia normativa de incluir descripción cualitativa de fortalezas y '
                   'dificultades.\n'
                   '\n'
                   'Estrategia mental recomendada: Verificar si un informe de evaluación combina '
                   'valoración cuantitativa o cualitativa con una explicación descriptiva del '
                   'desempeño, conforme a lo exigido por la normativa vigente.\n'
                   '\n'
                   'Subcompetencia: Aplicación contextual del contenido obligatorio de los '
                   'informes periódicos de evaluación',
  'fuente_normativa': 'Decreto 1290 de 2009, artículo 4, numeral 9, y artículo 5, parágrafo, sobre '
                      'la estructura y el contenido de los informes periódicos de evaluación.'},
 {'codigo': 'MOD03-SIEE-007',
  'contexto': 'Una estudiante de grado séptimo de la Institución Educativa "Simón Bolívar" '
              'presentó, durante el tercer periodo académico, un desempeño consistentemente bajo '
              'en el área de matemáticas, a pesar de haber asistido regularmente a las clases y '
              'de no presentar ninguna dificultad de comprensión evidente en otras áreas del plan '
              'de estudios, según confirmaron los demás docentes de la estudiante en la reunión '
              'de seguimiento académico realizada al cierre del periodo. La docente del área, en '
              'lugar de remitir directamente el caso a la '
              'comisión de evaluación y promoción para su análisis, decidió por su cuenta bajar '
              'aún más la calificación final de la estudiante como "medida para que se esforzara '
              'más el siguiente periodo", sin haber implementado previamente ningún plan de '
              'apoyo o actividad de refuerzo específica para la estudiante. La coordinación '
              'académica, al revisar el caso tras la queja de la familia, le explicó a la docente '
              'que ante situaciones de desempeño bajo persistente, el SIEE institucional exige '
              'implementar oportunamente estrategias de apoyo y seguimiento pedagógico, y que '
              'bajar deliberadamente una calificación sin fundamento en el desempeño real de la '
              'estudiante, como medida disciplinaria o de presión, no es un mecanismo válido '
              'previsto dentro del sistema de evaluación institucional adoptado.',
  'enunciado': '¿Cuál es la actuación jurídicamente correcta que la docente debía haber adoptado '
               'frente al desempeño bajo persistente de la estudiante?',
  'opcion_a': 'Bajar deliberadamente la calificación final de la estudiante como medida de '
              'presión disciplinaria, dado que esa es la estrategia expresamente prevista por el '
              'SIEE para estos casos de bajo desempeño persistente.',
  'opcion_b': 'Esperar hasta el cierre del año escolar para determinar si la estudiante sería o '
              'no promovida al grado siguiente, sin implementar ninguna medida adicional durante '
              'el transcurso del periodo académico.',
  'opcion_c': 'Remitir directamente a la familia a un profesional de la salud externo a la '
              'institución, como único mecanismo válido previsto por la normativa frente a un '
              'desempeño académico bajo persistente.',
  'opcion_d': 'Implementar oportunamente estrategias de apoyo y seguimiento pedagógico frente al '
              'desempeño bajo persistente, sin recurrir a la modificación arbitraria de la '
              'calificación como medida de presión.',
  'respuesta_correcta': 'D',
  'nivel_dificultad': 'muy_alto',
  'proceso_cognitivo': 'evaluacion_juicio',
  'justificacion': 'Ante situaciones de desempeño bajo persistente, el SIEE institucional exige '
                   'implementar oportunamente estrategias de apoyo y seguimiento pedagógico; '
                   'modificar deliberadamente una calificación sin fundamento en el desempeño '
                   'real del estudiante, como medida de presión disciplinaria, no es un mecanismo '
                   'válido dentro del sistema de evaluación institucional.\n'
                   '\n'
                   'Distractores:\n'
                   '- A) Es plausible porque plantea una medida de presión aparentemente '
                   'motivadora; pero modificar arbitrariamente una calificación no es una '
                   'estrategia válida ni prevista por el SIEE institucional.\n'
                   '- B) Es plausible porque sugiere prudencia frente a una decisión definitiva; '
                   'pero la pasividad durante el periodo académico contradice el deber de '
                   'implementar oportunamente estrategias de apoyo pedagógico.\n'
                   '- C) Es plausible porque reconoce la necesidad de apoyo adicional; pero la '
                   'remisión a un profesional externo no es el único mecanismo previsto, ni '
                   'sustituye las estrategias de apoyo pedagógico dentro de la institución.\n'
                   '\n'
                   'Error frecuente del aspirante: Asumir que la modificación arbitraria de '
                   'calificaciones es una herramienta pedagógica válida frente a un bajo '
                   'desempeño, en lugar de reconocer el deber de implementar estrategias de apoyo '
                   'reales.\n'
                   '\n'
                   'Estrategia mental recomendada: Verificar si ante un desempeño bajo persistente '
                   'se implementaron estrategias de apoyo genuinas, en lugar de aceptar medidas '
                   'de presión disciplinaria disfrazadas de estrategia pedagógica.\n'
                   '\n'
                   'Subcompetencia: Aplicación contextual del deber de implementar estrategias de '
                   'apoyo pedagógico frente al desempeño bajo persistente',
  'fuente_normativa': 'Decreto 1290 de 2009, artículo 4, numeral 4, sobre las acciones de '
                      'seguimiento para el mejoramiento de los desempeños de los estudiantes '
                      'durante el año escolar.'},
 {'codigo': 'MOD03-SIEE-008',
  'contexto': 'La Institución Educativa "José María Córdoba" incluyó en su Sistema Institucional '
              'de Evaluación de los Estudiantes una disposición según la cual el proceso de '
              'autoevaluación del estudiante era "opcional y a discreción de cada docente", de '
              'manera que algunos docentes lo aplicaban regularmente al final de cada periodo '
              'académico, mientras que otros nunca lo implementaban dentro de sus respectivas '
              'áreas, según pudo constatar la coordinación al revisar los formatos de seguimiento '
              'entregados por cada docente al final del periodo, revisión que se realizó como '
              'parte de la evaluación institucional anual del sistema de evaluación adoptado. Un '
              'estudiante de grado noveno reclamó ante la coordinación académica que en '
              'varias áreas nunca había tenido la oportunidad de autoevaluar su propio desempeño, '
              'a diferencia de sus compañeros de otros cursos con docentes distintos. La '
              'coordinación académica, tras consultar la normativa aplicable, le explicó al '
              'Consejo Académico que la disposición institucional resultaba contraria al Decreto '
              '1290 de 2009, dado que este exige que el proceso de autoevaluación de los '
              'estudiantes sea un componente obligatorio del sistema institucional de evaluación, '
              'y no una decisión discrecional que cada docente pueda aplicar o no según su propio '
              'criterio individual dentro de su área específica.',
  'enunciado': '¿Qué opción resuelve correctamente la validez de la disposición institucional que '
               'dejaba la autoevaluación a discreción de cada docente?',
  'opcion_a': 'La disposición es válida, dado que cada docente tiene plena autonomía pedagógica '
              'para decidir si aplica o no el proceso de autoevaluación dentro de su propia área '
              'específica del conocimiento.',
  'opcion_b': 'La disposición es válida siempre que la decisión de cada docente sea informada '
              'previamente al Consejo Académico mediante un reporte individual y periódico sobre '
              'su aplicación.',
  'opcion_c': 'La disposición es contraria a la normativa, dado que los procesos de '
              'autoevaluación de los estudiantes son un componente obligatorio del SIEE, no una '
              'decisión discrecional de cada docente.',
  'opcion_d': 'La disposición es contraria a la normativa, pero únicamente porque no fue '
              'consultada previamente con el personero estudiantil antes de su inclusión en el '
              'documento institucional adoptado.',
  'respuesta_correcta': 'C',
  'nivel_dificultad': 'muy_alto',
  'proceso_cognitivo': 'identificacion',
  'justificacion': 'El Decreto 1290 de 2009 exige que el proceso de autoevaluación de los '
                   'estudiantes sea un componente obligatorio del Sistema Institucional de '
                   'Evaluación, aplicable de manera uniforme dentro de la institución, y no una '
                   'decisión discrecional que cada docente pueda aplicar o no según su propio '
                   'criterio individual.\n'
                   '\n'
                   'Distractores:\n'
                   '- A) Es plausible porque invoca la autonomía pedagógica del docente; pero esa '
                   'autonomía no incluye la facultad de omitir un componente obligatorio del SIEE '
                   'como la autoevaluación estudiantil.\n'
                   '- B) Es plausible porque introduce un mecanismo de reporte aparentemente '
                   'razonable; pero ningún reporte informativo subsana la naturaleza obligatoria '
                   'del proceso de autoevaluación exigido por la norma.\n'
                   '- D) Es plausible porque introduce un vicio procedimental real; pero el '
                   'problema de fondo de la disposición no es la falta de consulta al personero, '
                   'sino el carácter discrecional que le atribuye a un componente obligatorio.\n'
                   '\n'
                   'Error frecuente del aspirante: Confundir la autonomía pedagógica del docente '
                   'en el aula con la facultad de omitir componentes obligatorios del sistema '
                   'institucional de evaluación exigidos por la norma nacional.\n'
                   '\n'
                   'Estrategia mental recomendada: Distinguir entre los aspectos que admiten '
                   'autonomía pedagógica del docente y los componentes obligatorios del SIEE que '
                   'no pueden quedar sujetos a la discrecionalidad individual.\n'
                   '\n'
                   'Subcompetencia: Aplicación contextual del carácter obligatorio del proceso de '
                   'autoevaluación de los estudiantes dentro del SIEE',
  'fuente_normativa': 'Decreto 1290 de 2009, artículo 4, numeral 5, sobre los procesos de '
                      'autoevaluación de los estudiantes como componente del Sistema '
                      'Institucional de Evaluación.'},
 {'codigo': 'MOD03-SIEE-009',
  'contexto': 'Un estudiante de grado sexto de la Institución Educativa "Francisco José de '
              'Caldas" acumuló, durante los cuatro periodos del año escolar, desempeño bajo de '
              'manera persistente en dos áreas del plan de estudios, a pesar de haber recibido '
              'las actividades de refuerzo ordinarias implementadas por cada docente '
              'individualmente, sin que esas actividades hubieran producido ninguna mejora '
              'apreciable en su desempeño durante los dos últimos periodos del año. Ante esa '
              'situación, el rector decidió, por sí solo y sin remitir '
              'el caso a ninguna otra instancia institucional, definir directamente que el '
              'estudiante no sería promovido al grado siguiente. La familia reclamó ante la '
              'Secretaría de Educación, argumentando que ese tipo de decisiones no correspondía '
              'exclusivamente al rector. La Secretaría de Educación, tras revisar el SIEE '
              'institucional de la entidad, confirmó que, conforme al documento adoptado por la '
              'propia institución, los casos de estudiantes con dificultades persistentes en su '
              'desempeño académico debían ser analizados por la comisión de evaluación y '
              'promoción prevista dentro del sistema institucional, órgano colegiado encargado '
              'de estudiar integralmente el caso antes de que se adoptara cualquier decisión '
              'definitiva sobre la promoción o no promoción del estudiante afectado.',
  'enunciado': '¿Cuál es la irregularidad jurídicamente relevante en la actuación del rector '
               'frente al caso del estudiante de grado sexto?',
  'opcion_a': 'Ninguna irregularidad relevante, dado que el rector tiene competencia exclusiva y '
              'excluyente para decidir sobre la promoción o no promoción de cualquier estudiante '
              'de la institución educativa.',
  'opcion_b': 'Haber decidido unilateralmente la no promoción sin remitir el caso a la comisión '
              'de evaluación y promoción prevista en el SIEE institucional para el análisis '
              'integral de casos con dificultades persistentes.',
  'opcion_c': 'Haber tardado más de un periodo académico completo en identificar el desempeño '
              'bajo persistente del estudiante en las dos áreas correspondientes del plan de '
              'estudios.',
  'opcion_d': 'Haber informado directamente a la Secretaría de Educación sobre la decisión de no '
              'promoción, en lugar de haberla comunicado primero al Consejo Directivo de la '
              'institución educativa.',
  'respuesta_correcta': 'B',
  'nivel_dificultad': 'muy_alto',
  'proceso_cognitivo': 'analisis_situacional',
  'justificacion': 'Conforme al SIEE institucional, los casos de estudiantes con dificultades '
                   'persistentes en su desempeño académico deben ser analizados por la comisión '
                   'de evaluación y promoción, órgano colegiado encargado de estudiar '
                   'integralmente el caso antes de adoptar cualquier decisión definitiva, sin que '
                   'el rector pueda decidir unilateralmente sobre la no promoción.\n'
                   '\n'
                   'Distractores:\n'
                   '- A) Es plausible porque atribuye competencia exclusiva al rector como '
                   'máxima autoridad; pero la decisión sobre casos de dificultades persistentes '
                   'corresponde a la comisión de evaluación y promoción prevista en el SIEE.\n'
                   '- C) Es plausible porque introduce un criterio temporal aparentemente '
                   'relevante; pero el vicio central de la actuación no es el tiempo de '
                   'identificación, sino la omisión del análisis por la comisión competente.\n'
                   '- D) Es plausible porque menciona una instancia real del gobierno escolar; '
                   'pero el vicio identificado no es haber informado a la Secretaría, sino no '
                   'haber remitido el caso a la comisión de evaluación y promoción.\n'
                   '\n'
                   'Error frecuente del aspirante: Asumir que el rector tiene competencia '
                   'exclusiva para decidir sobre la promoción de los estudiantes, sin reconocer '
                   'el papel de la comisión de evaluación y promoción prevista en el SIEE.\n'
                   '\n'
                   'Estrategia mental recomendada: Verificar si el SIEE institucional prevé un '
                   'órgano colegiado específico para el análisis de casos de dificultades '
                   'persistentes antes de aceptar una decisión unilateral como válida.\n'
                   '\n'
                   'Subcompetencia: Aplicación contextual del papel de la comisión de evaluación '
                   'y promoción en el análisis de casos de dificultades persistentes',
  'fuente_normativa': 'Decreto 1290 de 2009, artículo 4, en concordancia con el Sistema '
                      'Institucional de Evaluación adoptado por cada establecimiento, sobre la '
                      'comisión de evaluación y promoción.'},
 {'codigo': 'MOD03-SIEE-010',
  'contexto': 'Durante la construcción del nuevo Sistema Institucional de Evaluación de los '
              'Estudiantes de la Institución Educativa "Alfonso López Pumarejo", el rector '
              'propuso que el documento fuera elaborado exclusivamente por el equipo directivo y '
              'los coordinadores académicos, sin someterlo a ningún espacio de socialización ni '
              'consulta previa con los padres de familia ni con los representantes de los '
              'estudiantes, argumentando razones de tiempo dada la premura del cronograma '
              'institucional para ese año, así como la necesidad de tener el documento listo '
              'antes del inicio de las matrículas del siguiente año lectivo. Un integrante del '
              'Consejo Directivo objetó esa metodología, señalando '
              'que la normativa exige que la comunidad educativa participe en la construcción del '
              'documento. El rector, tras verificar la observación con apoyo de la Secretaría de '
              'Educación, aceptó que la objeción era correcta, explicando que el Decreto 1290 '
              'exige que el Sistema Institucional de Evaluación de los Estudiantes contemple '
              'mecanismos de participación de la comunidad educativa, entre ellos padres de '
              'familia y estudiantes, en su construcción y socialización, de manera que un '
              'proceso que excluyera por completo esos espacios de participación resultaba '
              'contrario a lo exigido por la norma para la válida adopción del documento '
              'institucional.',
  'enunciado': '¿Qué opción resuelve correctamente la objeción presentada sobre la construcción '
               'participativa del SIEE institucional?',
  'opcion_a': 'La objeción es incorrecta, dado que el equipo directivo tiene plena facultad para '
              'construir el SIEE institucional sin ningún espacio de participación de otros '
              'estamentos de la comunidad educativa.',
  'opcion_b': 'La objeción es correcta, dado que el Decreto 1290 exige que el SIEE contemple '
              'mecanismos de participación de la comunidad educativa, incluidos padres de familia '
              'y estudiantes, en su construcción.',
  'opcion_c': 'La objeción es correcta únicamente si es ratificada previamente por el Ministerio '
              'de Educación Nacional mediante concepto técnico específico sobre el proceso de '
              'construcción del documento.',
  'opcion_d': 'La objeción es incorrecta, pero solo porque la participación de la comunidad '
              'educativa se limita exclusivamente a la fase de socialización posterior, no a la '
              'fase de construcción inicial del documento.',
  'respuesta_correcta': 'B',
  'nivel_dificultad': 'muy_alto',
  'proceso_cognitivo': 'comprension_aplicada',
  'justificacion': 'El Decreto 1290 exige que el Sistema Institucional de Evaluación de los '
                   'Estudiantes contemple mecanismos de participación de la comunidad educativa, '
                   'entre ellos padres de familia y estudiantes, en su construcción y '
                   'socialización, de manera que excluir por completo esos espacios resulta '
                   'contrario a lo exigido para la válida adopción del documento.\n'
                   '\n'
                   'Distractores:\n'
                   '- A) Es plausible porque atribuye amplia facultad técnica al equipo '
                   'directivo; pero la norma exige expresamente mecanismos de participación de la '
                   'comunidad educativa en la construcción del documento.\n'
                   '- C) Es plausible porque involucra a la autoridad nacional en un aval '
                   'aparentemente riguroso; pero la validez de la participación comunitaria no '
                   'depende de un concepto previo del Ministerio de Educación.\n'
                   '- D) Es plausible porque distingue entre construcción y socialización '
                   'posterior; pero la norma exige participación desde la construcción misma del '
                   'documento, no solo en una fase posterior de socialización.\n'
                   '\n'
                   'Error frecuente del aspirante: Asumir que la participación de la comunidad '
                   'educativa en el SIEE se limita a una socialización posterior del documento ya '
                   'construido, en lugar de exigirse desde su elaboración.\n'
                   '\n'
                   'Estrategia mental recomendada: Verificar si los mecanismos de participación '
                   'de la comunidad educativa se contemplan desde la construcción del documento, '
                   'no solo como un trámite posterior de socialización.\n'
                   '\n'
                   'Subcompetencia: Aplicación contextual de los mecanismos de participación de '
                   'la comunidad educativa en la construcción del SIEE',
  'fuente_normativa': 'Decreto 1290 de 2009, artículo 4, numeral 11, sobre los mecanismos de '
                      'participación de la comunidad educativa en la construcción del SIEE.'},
 {'codigo': 'MOD03-SIEE-011',
  'contexto': 'Un estudiante de grado décimo de la Institución Educativa "Manuela Beltrán" fue '
              'calificado con desempeño bajo en el área de educación física durante todo el año '
              'escolar, exclusivamente con fundamento en los reportes de comportamiento '
              'disciplinario del estudiante en esa clase, registrados por el mismo docente en el '
              'observador durante los cuatro periodos del año, sin que el docente hubiera evaluado en '
              'ningún momento su desempeño motriz, su participación en las actividades físicas '
              'programadas ni ningún otro criterio propiamente académico del área, según se pudo verificar '
              'revisando el registro de notas parciales entregado por el propio docente durante '
              'el año. La familia '
              'reclamó ante la coordinación académica, señalando que la calificación no reflejaba '
              'el desempeño real del estudiante en el área evaluada. La coordinación, tras '
              'revisar el caso, le indicó al docente que la valoración académica de un área del '
              'plan de estudios debe fundamentarse en criterios propios del desempeño académico '
              'correspondiente a esa área, y que los aspectos relacionados con el comportamiento '
              'o la convivencia del estudiante deben gestionarse a través del manual de '
              'convivencia institucional, sin que puedan utilizarse como fundamento exclusivo '
              'para determinar la calificación académica del estudiante en un área específica del '
              'plan de estudios.',
  'enunciado': '¿Qué respuesta es la técnicamente correcta frente al fundamento utilizado por el '
               'docente para calificar al estudiante en el área evaluada?',
  'opcion_a': 'La calificación es válida, dado que el comportamiento disciplinario del estudiante '
              'es, conforme a la normativa, el criterio principal y suficiente para determinar la '
              'calificación académica de cualquier área del plan de estudios.',
  'opcion_b': 'La calificación es válida siempre que el comportamiento disciplinario sea '
              'reportado formalmente al Comité Escolar de Convivencia antes de ser tenido en '
              'cuenta para la valoración académica del área correspondiente.',
  'opcion_c': 'La calificación es válida, pero únicamente si el estudiante y su familia son '
              'notificados previamente de que el comportamiento disciplinario será tenido en '
              'cuenta como criterio de valoración académica del área.',
  'opcion_d': 'La calificación académica debe fundamentarse en criterios propios del desempeño en '
              'el área evaluada, y los aspectos de comportamiento deben gestionarse a través del '
              'manual de convivencia, no como fundamento exclusivo de la nota.',
  'respuesta_correcta': 'D',
  'nivel_dificultad': 'muy_alto',
  'proceso_cognitivo': 'evaluacion_juicio',
  'justificacion': 'La valoración académica de un área del plan de estudios debe fundamentarse en '
                   'criterios propios del desempeño académico correspondiente a esa área; los '
                   'aspectos relacionados con el comportamiento o la convivencia deben gestionarse '
                   'a través del manual de convivencia institucional, sin que puedan utilizarse '
                   'como fundamento exclusivo de la calificación académica.\n'
                   '\n'
                   'Distractores:\n'
                   '- A) Es plausible porque atribuye relevancia al comportamiento en el aula; '
                   'pero la normativa exige que la calificación académica se base en criterios '
                   'propios del desempeño en el área, no en el comportamiento disciplinario.\n'
                   '- B) Es plausible porque introduce un trámite institucional real; pero el '
                   'reporte al Comité de Convivencia no legitima usar el comportamiento como '
                   'fundamento exclusivo de una calificación académica.\n'
                   '- C) Es plausible porque exige una notificación previa aparentemente '
                   'garantista; pero ninguna notificación previa legitima fundamentar '
                   'exclusivamente la calificación académica en el comportamiento disciplinario.\n'
                   '\n'
                   'Error frecuente del aspirante: Confundir los criterios de valoración '
                   'académica de un área específica con los aspectos de comportamiento y '
                   'convivencia, que se gestionan por vías institucionales distintas.\n'
                   '\n'
                   'Estrategia mental recomendada: Distinguir siempre entre la evaluación '
                   'académica del desempeño en un área y la gestión del comportamiento '
                   'disciplinario, que corresponden a instrumentos institucionales diferentes.\n'
                   '\n'
                   'Subcompetencia: Aplicación contextual de la separación entre criterios de '
                   'valoración académica y aspectos de comportamiento o convivencia',
  'fuente_normativa': 'Decreto 1290 de 2009, artículo 3, sobre los propósitos de la evaluación '
                      'institucional de los estudiantes, en concordancia con la Ley 1620 de 2013 '
                      'sobre el manejo separado de la convivencia escolar.'},
 {'codigo': 'MOD03-SIEE-012',
  'contexto': 'Un estudiante de grado tercero de la Institución Educativa "Débora Arango", '
              'diagnosticado con una discapacidad cognitiva leve certificada, presentaba avances '
              'progresivos y significativos frente a sus propios logros individuales anteriores, '
              'aunque su desempeño, comparado directamente con los criterios generales exigidos '
              'para el resto de estudiantes de su grado, seguiría clasificándose como bajo bajo '
              'los mismos parámetros exactos, situación que generaba preocupación en la familia '
              'ante la proximidad del cierre del año escolar y la definición de su promoción al '
              'siguiente grado, según lo documentaba el equipo de apoyo pedagógico '
              'en su informe de seguimiento trimestral, elaborado conjuntamente con la docente '
              'titular de aula y la profesional de apoyo a la inclusión asignada al caso. La '
              'familia solicitó a la institución que se '
              'flexibilizaran los criterios de evaluación aplicables al estudiante, conforme a su '
              'situación particular. La coordinación académica, con apoyo del equipo de '
              'inclusión, le explicó a la familia que el SIEE institucional sí permite adaptar y '
              'flexibilizar los criterios e instrumentos de evaluación para estudiantes con '
              'necesidades educativas especiales, valorando su progreso individual frente a sus '
              'propias metas particulares, sin que ello implique eliminar por completo la '
              'evaluación del estudiante ni exonerarlo íntegramente del proceso evaluativo '
              'previsto para el resto de sus compañeros de grado.',
  'enunciado': '¿Qué determinación es la ajustada a derecho respecto a la evaluación aplicable '
               'al estudiante con necesidades educativas especiales?',
  'opcion_a': 'El SIEE institucional no admite ninguna flexibilización de los criterios de '
              'evaluación para estudiantes con necesidades educativas especiales, que deben ser '
              'evaluados exactamente bajo los mismos parámetros que el resto de sus compañeros.',
  'opcion_b': 'El SIEE institucional exonera por completo del proceso evaluativo a los '
              'estudiantes con necesidades educativas especiales certificadas, sin que se les '
              'aplique ningún tipo de valoración académica durante el año escolar.',
  'opcion_c': 'El SIEE institucional sí permite flexibilizar los criterios e instrumentos de '
              'evaluación para estudiantes con necesidades educativas especiales, valorando su '
              'progreso individual, sin eliminar por completo el proceso evaluativo.',
  'opcion_d': 'El SIEE institucional exige que la flexibilización de los criterios de evaluación '
              'sea autorizada previamente por el Ministerio de Educación Nacional, caso por caso, '
              'para cada estudiante con necesidades educativas especiales.',
  'respuesta_correcta': 'C',
  'nivel_dificultad': 'muy_alto',
  'proceso_cognitivo': 'comprension_aplicada',
  'justificacion': 'El SIEE institucional permite adaptar y flexibilizar los criterios e '
                   'instrumentos de evaluación para estudiantes con necesidades educativas '
                   'especiales, valorando su progreso individual frente a sus propias metas '
                   'particulares, sin que ello implique eliminar por completo la evaluación ni '
                   'exonerar íntegramente al estudiante del proceso evaluativo.\n'
                   '\n'
                   'Distractores:\n'
                   '- A) Es plausible porque invoca la igualdad de criterios entre estudiantes; '
                   'pero la normativa sí permite flexibilizar los criterios de evaluación para '
                   'estudiantes con necesidades educativas especiales.\n'
                   '- B) Es plausible porque parece proteger al estudiante de una evaluación '
                   'desfavorable; pero la flexibilización no equivale a exoneración total del '
                   'proceso evaluativo, que se mantiene adaptado a su situación particular.\n'
                   '- D) Es plausible porque introduce un trámite de autorización externa '
                   'aparentemente riguroso; pero la flexibilización de criterios es una decisión '
                   'institucional interna, no sujeta a autorización previa individual del '
                   'Ministerio.\n'
                   '\n'
                   'Error frecuente del aspirante: Confundir la flexibilización de criterios de '
                   'evaluación para estudiantes con necesidades educativas especiales con su '
                   'exoneración total del proceso evaluativo institucional.\n'
                   '\n'
                   'Estrategia mental recomendada: Distinguir entre flexibilizar los criterios de '
                   'evaluación (adaptación válida) y eliminar por completo la evaluación '
                   '(exoneración no prevista) para estudiantes con necesidades educativas '
                   'especiales.\n'
                   '\n'
                   'Subcompetencia: Aplicación contextual de la flexibilización de criterios de '
                   'evaluación para estudiantes con necesidades educativas especiales',
  'fuente_normativa': 'Decreto 1290 de 2009, artículo 4, en concordancia con el Decreto 1421 de '
                      '2017, sobre la flexibilización curricular y evaluativa para estudiantes '
                      'con discapacidad.'},
 {'codigo': 'MOD03-SIEE-013',
  'contexto': 'A pocas semanas de finalizar el año escolar, un estudiante de grado once de la '
              'Institución Educativa "Policarpa Salavarrieta" tenía pendiente de resolver una '
              'situación pedagógica en el área de física, correspondiente a un trabajo final que '
              'no había entregado por motivos de salud debidamente certificados durante varias '
              'semanas del último periodo académico, certificación que la familia radicó '
              'oportunamente ante la coordinación académica junto con las incapacidades médicas '
              'correspondientes, expedidas por la EPS a la que se encontraba afiliado el '
              'estudiante durante ese periodo. Ante la proximidad de la fecha prevista para '
              'la ceremonia de graduación, la familia solicitó a la institución que se definiera '
              'con claridad el procedimiento aplicable para resolver esa situación pendiente '
              'antes del cierre definitivo del año escolar. La coordinación académica le explicó '
              'que el SIEE institucional debe prever mecanismos y plazos razonables para que los '
              'estudiantes con situaciones pedagógicas pendientes, debidamente justificadas, '
              'puedan resolverlas antes del cierre del año escolar, de manera que el estudiante '
              'tendría la oportunidad de presentar el trabajo pendiente dentro del plazo '
              'adicional que la institución le otorgara conforme a su propio sistema de '
              'evaluación, antes de definir su situación final de promoción.',
  'enunciado': '¿Cuál es el procedimiento correcto que debía seguirse frente a la situación '
               'pedagógica pendiente del estudiante antes del cierre del año escolar?',
  'opcion_a': 'El estudiante pierde automáticamente el área de física por no haber presentado el '
              'trabajo final en la fecha original, sin que exista ningún mecanismo institucional '
              'para resolver situaciones pedagógicas pendientes justificadas.',
  'opcion_b': 'El SIEE institucional debe prever mecanismos y plazos razonables para resolver '
              'situaciones pedagógicas pendientes debidamente justificadas antes del cierre del '
              'año escolar, como el caso del trabajo final pendiente.',
  'opcion_c': 'La ceremonia de graduación debe aplazarse indefinidamente para todo el curso '
              'completo hasta que el estudiante resuelva la situación pedagógica pendiente en el '
              'área de física correspondiente.',
  'opcion_d': 'El estudiante debe repetir íntegramente el grado once completo, dado que ninguna '
              'situación pedagógica pendiente puede resolverse después de finalizado el último '
              'periodo académico del año escolar.',
  'respuesta_correcta': 'B',
  'nivel_dificultad': 'muy_alto',
  'proceso_cognitivo': 'comprension_aplicada',
  'justificacion': 'El SIEE institucional debe prever mecanismos y plazos razonables para que los '
                   'estudiantes con situaciones pedagógicas pendientes, debidamente justificadas, '
                   'puedan resolverlas antes del cierre del año escolar, en lugar de perder '
                   'automáticamente el área correspondiente.\n'
                   '\n'
                   'Distractores:\n'
                   '- A) Es plausible porque aplica una consecuencia automática aparentemente '
                   'estricta; pero la normativa exige prever mecanismos para resolver situaciones '
                   'pendientes justificadas, no aplicar la pérdida automática del área.\n'
                   '- C) Es plausible porque busca proteger al estudiante mediante un aplazamiento '
                   'colectivo; pero la solución prevista es individual, mediante plazos '
                   'adicionales, no un aplazamiento de la ceremonia para todo el curso.\n'
                   '- D) Es plausible porque plantea una consecuencia grave y proporcional en '
                   'apariencia; pero repetir el año completo no es la consecuencia prevista para '
                   'una situación pedagógica pendiente y justificada de una sola área.\n'
                   '\n'
                   'Error frecuente del aspirante: Asumir que toda situación pedagógica pendiente '
                   'al cierre del año escolar genera automáticamente la pérdida del área o la '
                   'repetición completa del grado, sin considerar los mecanismos institucionales '
                   'previstos.\n'
                   '\n'
                   'Estrategia mental recomendada: Verificar si el SIEE institucional prevé '
                   'mecanismos y plazos razonables para resolver situaciones pendientes '
                   'justificadas antes de asumir consecuencias automáticas y definitivas.\n'
                   '\n'
                   'Subcompetencia: Aplicación contextual de los mecanismos para resolver '
                   'situaciones pedagógicas pendientes antes del cierre del año escolar',
  'fuente_normativa': 'Decreto 1290 de 2009, artículo 4, numeral 4, sobre las estrategias de '
                      'apoyo necesarias para resolver situaciones pedagógicas pendientes de los '
                      'estudiantes.'},
 {'codigo': 'MOD03-SIEE-014',
  'contexto': 'Un padre de familia de un estudiante de grado cuarto de la Institución Educativa '
              '"Gonzalo Jiménez de Quesada" solicitó formalmente, mediante derecho de petición, '
              'que se le explicara con precisión cuáles eran los mecanismos de participación de '
              'los padres de familia previstos en el SIEE institucional, dado que consideraba que '
              'nunca había sido informado de manera clara sobre cómo podía involucrarse en el '
              'proceso de evaluación de su hijo más allá de la simple recepción de los informes '
              'periódicos de calificaciones, y solicitó además una respuesta escrita formal dentro '
              'de los términos legales previstos para los derechos de petición, la cual se '
              'comprometió a entregar dentro de los quince días hábiles siguientes a la radicación '
              'de la solicitud. La institución le respondió, con apoyo del Consejo '
              'Académico, que el SIEE institucional contemplaba, entre otros mecanismos, la '
              'posibilidad de que los padres de familia presentaran observaciones sobre el '
              'proceso evaluativo a través del Consejo de Padres, solicitaran reuniones '
              'individuales con los docentes para conocer el desempeño específico de su hijo, y '
              'participaran en la socialización previa del documento institucional cuando este '
              'fuera objeto de reforma, mecanismos que iban más allá de la simple recepción '
              'pasiva de los informes periódicos de calificaciones entregados al final de cada '
              'periodo académico.',
  'enunciado': '¿Cuál es la explicación jurídicamente correcta que la institución le dio al padre '
               'de familia sobre los mecanismos de participación previstos en el SIEE?',
  'opcion_a': 'El único mecanismo de participación previsto para los padres de familia es la '
              'recepción de los informes periódicos de calificaciones entregados al final de cada '
              'periodo académico, sin ningún otro mecanismo adicional.',
  'opcion_b': 'Los mecanismos de participación de los padres de familia dependen exclusivamente '
              'de que cada docente individual decida abrir o no espacios adicionales de '
              'comunicación con las familias de sus estudiantes.',
  'opcion_c': 'Los mecanismos de participación de los padres de familia solo pueden ejercerse '
              'directamente ante el Ministerio de Educación Nacional, sin que la institución '
              'educativa tenga ningún canal propio de participación interno.',
  'opcion_d': 'Los mecanismos de participación de los padres de familia incluyen presentar '
              'observaciones a través del Consejo de Padres, solicitar reuniones con docentes y '
              'participar en la socialización de reformas al documento institucional.',
  'respuesta_correcta': 'D',
  'nivel_dificultad': 'muy_alto',
  'proceso_cognitivo': 'identificacion',
  'justificacion': 'El SIEE institucional debe prever mecanismos formales y estructurados de '
                   'participación de los padres de familia, como el Consejo de Padres, las '
                   'reuniones con docentes y la socialización de reformas al documento '
                   'institucional, y no limitarse a la recepción pasiva de informes ni depender '
                   'de la discrecionalidad individual de cada docente.\n'
                   '\n'
                   'Distractores:\n'
                   '- A) Es plausible porque describe una práctica institucional frecuente pero '
                   'insuficiente; la norma exige mecanismos adicionales de participación más allá '
                   'de la simple recepción de informes periódicos.\n'
                   '- B) Es plausible porque reconoce la relevancia del vínculo docente-familia; '
                   'pero los mecanismos de participación son formales e institucionales, no '
                   'dependientes de la discrecionalidad individual de cada docente.\n'
                   '- C) Es plausible porque menciona a la autoridad nacional; pero los mecanismos '
                   'de participación operan a nivel institucional interno, no exclusivamente ante '
                   'el Ministerio de Educación.\n'
                   '\n'
                   'Error frecuente del aspirante: Asumir que la participación de los padres de '
                   'familia se limita a la recepción de informes periódicos, sin reconocer los '
                   'demás mecanismos formales previstos institucionalmente.\n'
                   '\n'
                   'Estrategia mental recomendada: Identificar todos los mecanismos formales de '
                   'participación de los padres de familia previstos en el SIEE, más allá de la '
                   'simple recepción de informes periódicos de calificaciones.\n'
                   '\n'
                   'Subcompetencia: Aplicación contextual de los mecanismos de participación de '
                   'los padres de familia en el SIEE institucional',
  'fuente_normativa': 'Decreto 1290 de 2009, artículo 4, numeral 11, sobre los mecanismos de '
                      'participación de la comunidad educativa, incluidos los padres de familia, '
                      'en el Sistema Institucional de Evaluación.'},
 {'codigo': 'MOD03-SIEE-015',
  'contexto': 'Un estudiante de grado once de la Institución Educativa "Antonio Nariño" '
              'consideró que la calificación final que había obtenido en el área de filosofía '
              'no reflejaba adecuadamente su desempeño real durante el año escolar, por lo que '
              'presentó una reclamación formal ante la instancia correspondiente prevista en el '
              'SIEE institucional, aportando evidencias de sus trabajos y evaluaciones parciales '
              'del periodo, así como los criterios de evaluación entregados por el propio docente '
              'al inicio del año escolar, documentos que la coordinación académica revisó '
              'cuidadosamente antes de programar la citación correspondiente. El docente del área, '
              'al ser citado para responder la reclamación, se '
              'negó a presentarse ante la instancia de reclamación, argumentando que "la '
              'calificación de un docente es una decisión pedagógica autónoma que no puede ser '
              'revisada por ningún otro órgano institucional". El rector le explicó al docente '
              'que esa posición desconocía el derecho de reclamación expresamente reconocido a '
              'los estudiantes dentro del SIEE institucional, el cual exige que toda calificación '
              'pueda ser objeto de revisión a través de las instancias, procedimientos y '
              'mecanismos previstos específicamente para ese fin, sin que la autonomía pedagógica '
              'del docente pueda invocarse para sustraerse por completo del proceso de '
              'reclamación previsto en la normativa institucional vigente.',
  'enunciado': '¿Cuál es la explicación jurídicamente correcta que el rector le dio al docente '
               'sobre su negativa a participar en el proceso de reclamación?',
  'opcion_a': 'La negativa del docente es incorrecta, dado que el derecho de reclamación exige '
              'que toda calificación pueda revisarse mediante las instancias y procedimientos '
              'previstos en el SIEE, sin que la autonomía pedagógica excluya ese proceso.',
  'opcion_b': 'La negativa del docente es correcta, dado que la calificación otorgada a un '
              'estudiante es una decisión pedagógica autónoma que ningún otro órgano '
              'institucional puede revisar bajo ninguna circunstancia.',
  'opcion_c': 'La negativa del docente es correcta únicamente si cuenta con el respaldo previo y '
              'expreso del Consejo Académico institucional para sustraerse del proceso de '
              'reclamación planteado.',
  'opcion_d': 'La negativa del docente es incorrecta, pero solo porque debía haberse formalizado '
              'por escrito ante el rector, y no simplemente manifestado de manera verbal durante '
              'la citación realizada.',
  'respuesta_correcta': 'A',
  'nivel_dificultad': 'muy_alto',
  'proceso_cognitivo': 'evaluacion_juicio',
  'justificacion': 'El derecho de reclamación reconocido a los estudiantes dentro del SIEE exige '
                   'que toda calificación pueda ser objeto de revisión mediante las instancias, '
                   'procedimientos y mecanismos previstos institucionalmente, sin que la '
                   'autonomía pedagógica del docente pueda invocarse para sustraerse por completo '
                   'de ese proceso de reclamación, como ocurrió en la negativa injustificada del '
                   'docente de filosofía a presentarse ante la instancia correspondiente.\n'
                   '\n'
                   'Distractores:\n'
                   '- B) Es plausible porque invoca la autonomía pedagógica del docente en la '
                   'calificación; pero esa autonomía no excluye el derecho de reclamación '
                   'expresamente reconocido a los estudiantes dentro del SIEE institucional.\n'
                   '- C) Es plausible porque condiciona la negativa a un respaldo institucional '
                   'superior; pero ningún respaldo del Consejo Académico puede legitimar la '
                   'sustracción total del docente frente al proceso de reclamación previsto.\n'
                   '- D) Es plausible porque introduce un defecto de forma aparentemente '
                   'relevante; pero el vicio central de la negativa no es la falta de '
                   'formalización escrita, sino el desconocimiento del derecho de reclamación '
                   'como tal.\n'
                   '\n'
                   'Error frecuente del aspirante: Asumir que la autonomía pedagógica del docente '
                   'en la calificación excluye el derecho del estudiante a que esa calificación '
                   'sea revisada mediante los mecanismos de reclamación del SIEE.\n'
                   '\n'
                   'Estrategia mental recomendada: Distinguir entre la autonomía pedagógica para '
                   'calificar y el deber institucional de garantizar el derecho de reclamación '
                   'frente a esa calificación, que no son incompatibles entre sí.\n'
                   '\n'
                   'Subcompetencia: Aplicación contextual del derecho de reclamación frente a '
                   'calificaciones y su relación con la autonomía pedagógica docente',
  'fuente_normativa': 'Decreto 1290 de 2009, artículo 4, numeral 10, sobre el derecho de '
                      'reclamación de los estudiantes frente a las decisiones de evaluación y '
                      'promoción.'},
]
