# -*- coding: utf-8 -*-
"""Banco Oficial de Preguntas - Modulo: Competencias Disciplinares (Modulo 8)
| Sub-banco: Tecnologia e Informatica | Tema 3: Solucion de problemas con
tecnologia (Lote 1). Tercer tema del sub-banco de Tecnologia e Informatica,
desarrollado tras la aprobacion completa de los Temas 1 (Naturaleza y
evolucion) y 2 (Apropiacion y uso). 10 preguntas bajo la regla permanente
desde Modulo 5. Formato estandar de opcion unica A/B/C/D (Caso + opcion
multiple). Contenido enteramente nuevo: ningun caso, protagonista, municipio,
contexto ni distractor se reutiliza de los Temas 1 y 2 ni de otros
modulos/sub-bancos. Dificultad unicamente Alta y Muy Alta. Distribucion de
respuesta_correcta planificada por adelantado (A2/B3/C2/D3) y escrita
directamente en la letra objetivo desde el primer borrador. Contextos
redactados con extension objetivo 220-260 palabras desde el primer borrador
para cumplir sin necesidad de una segunda pasada el rango 180-300 palabras
documentado para Competencias Disciplinares.
"""

CATEGORIA = "Competencias Disciplinares"
SUBCATEGORIA = "Competencias Disciplinares - Tecnología e Informática - Solución de problemas con tecnología"
COMPETENCIA = "Competencia disciplinar aplicada"
AREA = "tecnologia_informatica"

ITEMS = [
 {
  'codigo': 'MOD08-TEC-SOL-001',
  'contexto': 'En una institución de Yarumal (Antioquia), el docente Gustavo Areiza inicia con sus estudiantes de grado sexto una unidad sobre solución de problemas con tecnología, proponiendo un reto real de la institución: el patio de descanso no tiene ningún lugar cubierto para resguardarse cuando llueve durante el recreo. Antes de que los estudiantes empiecen a proponer soluciones, un grupo entusiasta ya está dibujando el diseño de una gran estructura metálica con techo curvo, inspirada en una imagen que uno de ellos vio en internet, sin haber discutido todavía cuántos estudiantes deben caber, qué materiales están realmente disponibles en la institución, ni cuánto tiempo del año escolar tienen para construirla. Gustavo observa que este grupo ya está comprometido emocionalmente con su primera idea, mientras que ni siquiera han conversado sobre qué es exactamente lo que hace que un lugar cubierto funcione bien para el propósito que se necesita. Otros grupos, en cambio, siguen sin proponer nada porque no saben por dónde empezar el ejercicio, y le preguntan a Gustavo cuál sería el primer paso correcto antes de dibujar cualquier solución para este problema real de la institución.',
  'enunciado': '¿Cuál es la orientación MÁS adecuada que debería dar Gustavo a ambos grupos antes de que continúen con sus propuestas de diseño?',
  'opcion_a': 'Orientar a ambos grupos a definir con claridad el problema antes de diseñar una solución: qué necesidad específica debe cumplir el espacio cubierto, cuántos estudiantes debe acoger, qué materiales y tiempo hay realmente disponibles, y solo después generar y comparar varias alternativas posibles.',
  'opcion_b': 'Sugerirles que revisen en internet más imágenes de estructuras similares a la que ya dibujó el primer grupo, ya que la mejor forma de resolver un problema tecnológico es partir de ejemplos visuales ya construidos por otras personas.',
  'opcion_c': 'Indicar que el primer grupo ya tiene la solución correcta por haber avanzado más rápido, y que el segundo grupo simplemente debe copiar y adaptar ese mismo diseño para no atrasar el desarrollo de la actividad completa.',
  'opcion_d': 'Explicar que, en la solución de problemas con tecnología, no es necesario definir el problema con precisión, ya que cualquier estructura que cubra del agua cumple automáticamente con el propósito esperado por la institución.',
  'respuesta_correcta': 'A',
  'nivel_dificultad': 'alto',
  'proceso_cognitivo': 'aplicacion_disciplinar',
  'justificacion': 'El proceso de solución de problemas con tecnología exige, como primer paso, definir con claridad el problema (la necesidad real, las restricciones de materiales, tiempo y espacio) antes de generar y comparar alternativas de solución. Saltar directamente al diseño de una estructura específica, como hizo el primer grupo, sin haber acotado el problema, expone a comprometerse prematuramente con una solución que puede no ajustarse a las restricciones reales de la institución.\n\nDistractores:\n- B) Es plausible porque valora la referencia visual; pero partir de una imagen atractiva sin definir antes el problema real (necesidad, restricciones) no corresponde a un proceso de diseño tecnológico riguroso.\n- C) Es plausible porque premia el avance rápido; pero haber dibujado primero una solución no la hace automáticamente correcta si no se ha definido el problema ni comparado con otras alternativas posibles.\n- D) Es plausible porque simplifica el proceso; pero omitir la definición precisa del problema es precisamente el error que ya está cometiendo el primer grupo, y generalizarlo como válido contradice el proceso de solución de problemas que se busca enseñar.\n\nError frecuente del aspirante: Asumir que la solución de problemas con tecnología comienza por diseñar o dibujar una propuesta, en lugar de comenzar por definir con precisión el problema y sus restricciones reales.\n\nEstrategia mental recomendada: Ante un caso de solución de problemas con tecnología en el aula, verificar que la opción correcta priorice la definición clara del problema y sus restricciones antes de la generación de una solución específica.\n\nSubcompetencia: Aplicación pedagógica de la definición precisa del problema como primer paso del proceso de solución de problemas con tecnología',
  'fuente_normativa': 'Orientaciones Generales para la Educación en Tecnología (MEN, 2008), componente de Solución de Problemas con Tecnología.',
 },
 {
  'codigo': 'MOD08-TEC-SOL-002',
  'contexto': 'En una institución de Santa Rosa de Osos (Antioquia), la docente Liliana Pareja trabaja con sus estudiantes de grado séptimo el paso de generación de alternativas dentro del proceso de solución de problemas con tecnología, usando como reto diseñar un sistema sencillo para regar las plantas del huerto escolar durante el fin de semana, cuando ningún adulto de la institución está presente para hacerlo manualmente. Antes de continuar, Liliana pide a cada grupo que proponga al menos tres alternativas distintas de solución, en lugar de avanzar directamente con la primera idea que se les ocurra. Un grupo, sin embargo, le comenta que ya tienen "la solución perfecta" (un sistema de goteo con botellas recicladas) y que prefieren dedicar todo el tiempo restante de la clase a construirla de una vez, en lugar de perder tiempo pensando en otras alternativas que probablemente no van a usar de todas formas. Liliana nota que este grupo se resiste a la idea de generar varias alternativas, considerando ese paso como una pérdida de tiempo innecesaria frente a una idea que ya les parece suficientemente buena para resolver el problema planteado del huerto escolar institucional.',
  'enunciado': '¿Cuál es la respuesta MÁS adecuada que debería dar Liliana frente a la resistencia de este grupo a generar varias alternativas antes de construir?',
  'opcion_a': 'Aceptar el argumento del grupo y permitirles construir de inmediato el sistema de goteo con botellas recicladas, ya que contar con una idea que parece funcional es suficiente para saltar directamente a la fase de construcción del prototipo.',
  'opcion_b': 'Indicar que generar varias alternativas es un paso opcional del proceso de solución de problemas, relevante solo cuando ningún grupo tiene todavía ninguna idea inicial sobre cómo resolver el reto planteado.',
  'opcion_c': 'Explicar que generar y comparar varias alternativas, incluso cuando una idea inicial parece buena, permite identificar ventajas y desventajas que no son evidentes de inmediato, y podría revelar una opción más adecuada o complementaria a la ya propuesta por el grupo.',
  'opcion_d': 'Señalar que la generación de alternativas solo es necesaria en problemas tecnológicos complejos de nivel industrial, y que un reto escolar sencillo como el riego del huerto no la requiere en ningún caso.',
  'respuesta_correcta': 'C',
  'nivel_dificultad': 'alto',
  'proceso_cognitivo': 'aplicacion_disciplinar',
  'justificacion': 'Generar y comparar varias alternativas de solución, incluso cuando una primera idea parece adecuada, es un paso central del proceso de solución de problemas con tecnología: permite identificar ventajas, desventajas y variantes que no son evidentes al quedarse con la primera ocurrencia, y puede revelar mejoras importantes o combinaciones más eficientes que la idea inicial por sí sola no ofrecía.\n\nDistractores:\n- A) Es plausible porque valora la eficiencia; pero saltar directamente a construir sin comparar alternativas expone a perder oportunidades de mejora que solo se identifican al generar y contrastar varias opciones posibles.\n- B) Es plausible porque limita el alcance del paso; pero generar alternativas es relevante incluso cuando ya existe una idea inicial, precisamente para enriquecerla o identificar una opción superior antes de comprometerse con ella.\n- D) Es plausible porque asocia el paso con la complejidad del problema; pero la generación de alternativas es parte del proceso de solución de problemas independientemente de la escala o complejidad del reto planteado.\n\nError frecuente del aspirante: Considerar que generar varias alternativas de solución es un paso prescindible cuando ya existe una primera idea que parece suficientemente buena, sin reconocer su valor para identificar mejoras u opciones superiores.\n\nEstrategia mental recomendada: Ante un caso donde un grupo se resiste a generar alternativas por tener ya una idea inicial, identificar la opción que defiende el valor de comparar varias alternativas antes de comprometerse con una solución específica.\n\nSubcompetencia: Valoración pedagógica de la generación y comparación de alternativas como paso del proceso de solución de problemas con tecnología',
  'fuente_normativa': 'Orientaciones Generales para la Educación en Tecnología (MEN, 2008), componente de Solución de Problemas con Tecnología.',
 },
 {
  'codigo': 'MOD08-TEC-SOL-003',
  'contexto': 'En una institución de Don Matías (Antioquia), el docente Ferney Ospina propone a sus estudiantes de grado octavo diseñar un organizador de materiales para el salón de clase, con la restricción explícita de que solo pueden usar materiales reciclados disponibles en la institución (cajas de cartón, botellas plásticas, retazos de tela) y un presupuesto de cero pesos, ya que la institución no cuenta con recursos adicionales para esta actividad puntual del periodo. Un grupo de estudiantes presenta un diseño elaborado que requiere comprar bisagras metálicas, pintura especial y láminas de madera contrachapada, argumentando que su propuesta es "la mejor solución posible" para el problema de organización planteado, sin haber considerado en ningún momento la restricción de materiales y presupuesto que Ferney explicó claramente al inicio de la actividad. Cuando Ferney les recuerda la restricción, el grupo responde que "una buena solución tecnológica no debería limitarse por falta de presupuesto", y que prefieren mantener su diseño original tal como lo pensaron desde un principio, sin ningún ajuste a los materiales realmente disponibles en la institución.',
  'enunciado': '¿Cuál es la aclaración MÁS adecuada que debería dar Ferney frente a la respuesta de este grupo sobre la relación entre su diseño y la restricción de materiales?',
  'opcion_a': 'Confirmar que una buena solución tecnológica nunca debe limitarse por restricciones de presupuesto, y permitir que el grupo mantenga su diseño original sin ningún ajuste a los materiales realmente disponibles en la institución.',
  'opcion_b': 'Explicar que las restricciones reales (materiales disponibles, presupuesto, tiempo) son parte constitutiva de cualquier problema tecnológico, y que una solución de calidad es precisamente la que logra resolver el problema planteado dentro de esas restricciones, no a pesar de ignorarlas.',
  'opcion_c': 'Indicar que el grupo debe abandonar por completo la actividad, ya que proponer un diseño que no respeta las restricciones iniciales invalida cualquier posibilidad de participar en el resto del proceso de solución de problemas.',
  'opcion_d': 'Señalar que las restricciones de materiales y presupuesto solo aplican a proyectos tecnológicos de nivel profesional, y que en un contexto escolar como este, los estudiantes pueden diseñar soluciones sin ninguna limitación real de recursos.',
  'respuesta_correcta': 'B',
  'nivel_dificultad': 'muy_alto',
  'proceso_cognitivo': 'evaluacion_juicio',
  'justificacion': 'Las restricciones reales (materiales disponibles, presupuesto, tiempo) son parte constitutiva de cualquier problema tecnológico bien planteado, no un obstáculo externo a ignorar. Una solución de calidad no es la más elaborada en abstracto, sino la que logra resolver el problema planteado trabajando dentro de esas restricciones reales, lo cual exige creatividad adicional, no simplemente más recursos disponibles.\n\nDistractores:\n- A) Es plausible porque valora la ambición del diseño; pero ignorar las restricciones reales del problema no produce una "mejor" solución tecnológica, produce una propuesta que no resuelve el problema tal como fue planteado.\n- C) Es plausible porque parece una consecuencia lógica; pero excluir por completo al grupo del proceso es una respuesta desproporcionada frente a un diseño que puede reorientarse hacia las restricciones reales sin necesidad de descartar la participación del grupo.\n- D) Es plausible porque distingue por nivel de complejidad; pero las restricciones reales de materiales y presupuesto son relevantes en cualquier contexto de solución de problemas con tecnología, incluido el escolar, no son exclusivas de proyectos profesionales.\n\nError frecuente del aspirante: Considerar que una solución tecnológica más elaborada o costosa es automáticamente mejor, sin reconocer que las restricciones reales del problema son parte esencial de lo que debe resolver cualquier solución de calidad.\n\nEstrategia mental recomendada: Ante un caso donde una propuesta de solución ignora las restricciones reales planteadas, identificar la opción que reafirma esas restricciones como parte constitutiva del problema, no como un obstáculo externo a evitar.\n\nSubcompetencia: Reconocimiento de las restricciones reales de recursos como componente esencial del proceso de solución de problemas con tecnología',
  'fuente_normativa': 'Orientaciones Generales para la Educación en Tecnología (MEN, 2008), componente de Solución de Problemas con Tecnología.',
 },
 {
  'codigo': 'MOD08-TEC-SOL-004',
  'contexto': 'En una institución de Entrerríos (Antioquia), la docente Marcela Uribe guía a sus estudiantes de grado noveno en la construcción de un prototipo sencillo de carro impulsado por una liga de caucho, como parte del proceso de solución de problemas con tecnología. Después de construir su primer prototipo, un grupo lo prueba y descubre que el carro avanza solo unos pocos centímetros antes de detenerse, muy por debajo de la distancia esperada según el reto planteado. En lugar de analizar qué parte específica del diseño podría estar fallando (el punto de anclaje de la liga, el peso del carro, la fricción de las ruedas), el grupo decide directamente construir un segundo prototipo completamente distinto desde cero, sin haber registrado ni analizado ninguna observación sobre por qué el primer intento no funcionó como esperaban. Marcela revisa el cuaderno de este grupo y encuentra que no hay ningún registro escrito de la prueba realizada, ni ninguna hipótesis sobre la causa del bajo desempeño del primer prototipo, solamente la decisión de empezar de nuevo con un diseño diferente. Al preguntarles directamente por qué decidieron reconstruir sin analizar primero el resultado, los estudiantes responden que les pareció más rápido intentar algo distinto que detenerse a pensar en qué pudo haber fallado, sin considerar que ese mismo error de diseño podría repetirse en el segundo intento si la causa real no queda identificada con claridad antes de continuar con el proceso.',
  'enunciado': '¿Cuál es la intervención MÁS adecuada que debería hacer Marcela frente a la forma en que este grupo abordó el resultado de su primera prueba?',
  'opcion_a': 'Orientar al grupo a analizar y registrar por qué el prototipo no alcanzó la distancia esperada, identificando causas específicas (anclaje, peso, fricción) antes de ajustar el diseño o construir uno nuevo, con base en evidencia.',
  'opcion_b': 'Indicar que el grupo debe abandonar el reto por completo, dado que no lograr la distancia esperada en el primer intento demuestra que el diseño elegido no es viable para este tipo de actividad.',
  'opcion_c': 'Permitir que el grupo continúe construyendo prototipos completamente nuevos cada vez que uno falla, ya que la única forma válida de mejorar un diseño tecnológico es empezar desde cero en cada intento posterior.',
  'opcion_d': 'Explicar que el registro de pruebas y posibles causas de falla solo es relevante en proyectos tecnológicos de nivel universitario, y que en la educación básica basta con repetir la construcción hasta que un prototipo funcione por azar.',
  'respuesta_correcta': 'A',
  'nivel_dificultad': 'muy_alto',
  'proceso_cognitivo': 'evaluacion_juicio',
  'justificacion': 'La solución de problemas con tecnología incluye un componente de prueba y análisis iterativo: cuando un prototipo no cumple lo esperado, es necesario registrar y analizar posibles causas específicas antes de decidir si se ajusta el diseño actual o se construye uno completamente nuevo. Saltar directamente a un segundo prototipo sin ningún análisis de la causa del primer resultado desaprovecha la evidencia disponible y repite el riesgo de fallar por las mismas razones no identificadas.\n\nDistractores:\n- B) Es plausible porque interpreta el fracaso inicial como definitivo; pero un primer resultado insuficiente no invalida el diseño por completo, es información valiosa para ajustar el prototipo, no una razón para abandonar el reto.\n- C) Es plausible porque valora la persistencia; pero reconstruir sin ningún análisis previo desaprovecha la oportunidad de aprender de la evidencia del primer intento, y puede repetir el mismo error en el segundo prototipo.\n- D) Es plausible porque distingue por nivel educativo; pero el análisis de causas de falla y la iteración basada en evidencia son componentes pedagógicos relevantes desde la educación básica, no exclusivos de niveles superiores de formación.\n\nError frecuente del aspirante: Asumir que la mejora de un prototipo tecnológico ocurre por ensayo y error sin análisis, en lugar de reconocer el valor de registrar y analizar evidencia específica antes de decidir el siguiente paso.\n\nEstrategia mental recomendada: Ante un caso de prototipo que no cumple el resultado esperado, identificar la opción que prioriza el análisis de causas específicas basado en evidencia, antes de decidir si ajustar o reconstruir el prototipo.\n\nSubcompetencia: Aplicación pedagógica de la prueba y el análisis iterativo basado en evidencia dentro del proceso de solución de problemas con tecnología',
  'fuente_normativa': 'Orientaciones Generales para la Educación en Tecnología (MEN, 2008), componente de Solución de Problemas con Tecnología.',
 },
 {
  'codigo': 'MOD08-TEC-SOL-005',
  'contexto': 'En una institución de Belmira (Antioquia), el docente Wilmar Correa culmina con sus estudiantes de grado décimo un proyecto de varias semanas centrado en diseñar un sistema sencillo de clasificación de residuos para la sala de profesores de la institución. Antes de dar por terminado el proyecto, Wilmar pide a cada grupo que evalúe su propia solución, pero varios grupos se limitan a responder únicamente "sí, funciona" o "no, no funciona", sin ningún criterio adicional que sustente esa valoración. Un grupo en particular afirma que su sistema "funciona perfectamente", aunque al observarlo Wilmar nota que los contenedores no están claramente rotulados, que dos de las categorías de residuos se prestan a confusión entre los propios docentes que los usarían, y que el sistema ocupa un espacio considerablemente mayor al que la sala de profesores tiene realmente disponible. El grupo insiste en que, como los residuos efectivamente caen dentro de algún contenedor cuando alguien los deposita, su solución cumple completamente con el propósito del proyecto planteado desde el inicio. Wilmar les pide que se pongan en el lugar de un docente que use el sistema por primera vez sin ninguna explicación previa, y varios integrantes del propio grupo reconocen que ni ellos mismos recordarían con seguridad en qué contenedor va cada tipo de residuo, a pesar de haber diseñado el sistema completo.',
  'enunciado': '¿Cuál es la orientación MÁS adecuada que debería dar Wilmar para que los estudiantes evalúen su solución de manera más rigurosa que un simple "funciona o no funciona"?',
  'opcion_a': 'Aceptar la valoración del grupo, dado que si los residuos caen dentro de algún contenedor del sistema diseñado, eso demuestra por sí solo que la solución tecnológica cumple satisfactoriamente su propósito.',
  'opcion_b': 'Indicar que evaluar una solución tecnológica no es necesario una vez que el prototipo ha sido construido y entregado, ya que la etapa de evaluación solo aplica antes de iniciar la construcción del sistema.',
  'opcion_c': 'Orientar a los estudiantes a evaluar su solución con criterios específicos ya definidos (rotulación, facilidad de uso, ajuste al espacio), en lugar de un juicio binario de funciona o no funciona, para identificar con precisión qué ajustar.',
  'opcion_d': 'Señalar que la evaluación de una solución tecnológica escolar debe hacerla exclusivamente el docente, sin ninguna participación de los estudiantes que diseñaron y construyeron el sistema evaluado.',
  'respuesta_correcta': 'C',
  'nivel_dificultad': 'alto',
  'proceso_cognitivo': 'evaluacion_juicio',
  'justificacion': 'Evaluar una solución tecnológica exige criterios específicos y previamente definidos (funcionalidad, usabilidad, ajuste a las restricciones de espacio, entre otros), no un juicio binario simplificado de "funciona o no funciona". Un sistema puede técnicamente cumplir su función más básica (los residuos caen en algún contenedor) y aun así presentar problemas reales de usabilidad, claridad o ajuste al contexto, que solo se identifican con una evaluación basada en criterios explícitos.\n\nDistractores:\n- A) Es plausible porque usa un criterio funcional mínimo; pero que los residuos caigan en algún contenedor no garantiza que el sistema cumpla adecuadamente su propósito si presenta problemas de rotulación, confusión de categorías o ajuste al espacio disponible.\n- B) Es plausible porque ubica la evaluación en otra etapa; pero evaluar la solución construida, con criterios específicos, es precisamente el paso final del proceso de solución de problemas, no un paso que deba omitirse tras la construcción.\n- D) Es plausible porque menciona el rol docente; pero la autoevaluación de los propios estudiantes frente a criterios explícitos es parte formativa central del proceso de solución de problemas, no una función exclusiva del docente.\n\nError frecuente del aspirante: Aceptar una valoración binaria y superficial ("funciona o no funciona") como suficiente para evaluar una solución tecnológica, sin exigir criterios específicos que permitan un análisis más riguroso.\n\nEstrategia mental recomendada: Ante un caso de evaluación final de una solución tecnológica, identificar la opción que exige criterios específicos y previamente definidos, en lugar de un juicio binario simplificado sobre el funcionamiento general.\n\nSubcompetencia: Aplicación pedagógica de criterios específicos de evaluación de soluciones tecnológicas, más allá del juicio binario de funcionamiento',
  'fuente_normativa': 'Orientaciones Generales para la Educación en Tecnología (MEN, 2008), componente de Solución de Problemas con Tecnología.',
 },
 {
  'codigo': 'MOD08-TEC-SOL-006',
  'contexto': 'En una institución de San Pedro de los Milagros (Antioquia), la docente Estefanía Molina introduce a sus estudiantes de grado séptimo el uso de diagramas de flujo sencillos para representar el proceso de solución de un problema tecnológico, antes de comenzar a construir cualquier prototipo físico. Como ejercicio, pide a los estudiantes que elaboren un diagrama que muestre los pasos que seguirán para resolver el reto de diseñar un soporte para cargar el celular mientras se usa como despertador en la mesa de noche. Un grupo entrega un diagrama que consiste en un único recuadro que dice "construir el soporte", sin ningún paso intermedio de definición del problema, generación de alternativas, selección de una opción o prueba posterior, argumentando que "el diagrama de flujo es solo un formalismo" y que preferirían empezar a construir directamente el soporte sin perder tiempo representando gráficamente el proceso que seguirán. Estefanía revisa los diagramas de otros grupos y encuentra que aquellos que sí detallaron cada etapa lograron anticipar problemas antes de construir, como notar que el soporte necesitaría un hueco para el cable de carga, algo que el grupo del diagrama de un solo recuadro no había considerado en ningún momento antes de empezar a construir su prototipo.',
  'enunciado': '¿Cuál es la aclaración MÁS adecuada que debería dar Estefanía frente al diagrama entregado por este grupo?',
  'opcion_a': 'Aceptar el diagrama de un solo paso, ya que representar gráficamente el proceso de solución de un problema tecnológico es efectivamente un formalismo sin ninguna utilidad real más allá de cumplir con un requisito de la actividad.',
  'opcion_b': 'Indicar que el diagrama de flujo, lejos de ser un simple formalismo, ayuda a visualizar y organizar las etapas del proceso (definición, alternativas, selección, construcción, prueba), evidenciando pasos que un diagrama de un solo recuadro no permite planear.',
  'opcion_c': 'Explicar que los diagramas de flujo solo son útiles quienes se dedican profesionalmente al desarrollo de software, y que no tienen ninguna aplicación real en el proceso de solución de problemas físicos o mecánicos como el reto planteado.',
  'opcion_d': 'Señalar que la construcción de un diagrama de flujo debe hacerse siempre después de haber construido y probado el prototipo, nunca antes de iniciar el proceso de solución del problema planteado.',
  'respuesta_correcta': 'B',
  'nivel_dificultad': 'alto',
  'proceso_cognitivo': 'aplicacion_disciplinar',
  'justificacion': 'Un diagrama de flujo, dentro del proceso de solución de problemas con tecnología, ayuda a visualizar y organizar las distintas etapas del proceso (definición del problema, generación de alternativas, selección, construcción, prueba), permitiendo anticipar y planear pasos que un diagrama de un solo recuadro no representa. Reducir el proceso completo a un único paso ("construir") oculta precisamente las etapas previas que son centrales para una solución bien fundamentada.\n\nDistractores:\n- A) Es plausible porque cuestiona la utilidad del formalismo; pero un diagrama de flujo bien elaborado tiene una función real de planeación y organización del proceso, no es un simple requisito formal sin ningún valor práctico.\n- C) Es plausible porque restringe el uso de diagramas a un campo específico; pero los diagramas de flujo son una herramienta aplicable a cualquier proceso de solución de problemas, incluidos los de naturaleza física o mecánica, no exclusivos del desarrollo de software.\n- D) Es plausible porque invierte el orden del proceso; pero el diagrama de flujo tiene mayor utilidad cuando se elabora antes de construir, ya que ayuda a planear el proceso, no solo a documentarlo después de haberlo ejecutado.\n\nError frecuente del aspirante: Considerar los diagramas de flujo como un formalismo sin utilidad práctica real dentro del proceso de solución de problemas con tecnología, en lugar de reconocerlos como una herramienta de planeación del proceso.\n\nEstrategia mental recomendada: Ante un caso sobre el uso de diagramas de flujo en la solución de problemas tecnológicos, identificar la opción que reconoce su función de planeación y organización de las etapas del proceso, no la que lo trata como un simple requisito formal.\n\nSubcompetencia: Reconocimiento pedagógico del diagrama de flujo como herramienta de planeación del proceso de solución de problemas con tecnología',
  'fuente_normativa': 'Orientaciones Generales para la Educación en Tecnología (MEN, 2008), componente de Solución de Problemas con Tecnología.',
 },
 {
  'codigo': 'MOD08-TEC-SOL-007',
  'contexto': 'En una institución de Angostura (Antioquia), el docente Diego Vahos organiza a sus estudiantes de grado octavo en equipos de cuatro integrantes para resolver el reto de diseñar un sistema sencillo de riego por goteo para las jardineras del patio central de la institución, asignando roles específicos dentro de cada equipo (encargado de materiales, encargado de mediciones, encargado de registro escrito del proceso, encargado de pruebas). Al revisar el avance de un equipo, Diego encuentra que el estudiante asignado como encargado de registro escrito no ha anotado nada durante las últimas dos sesiones, mientras que otro integrante del mismo equipo ha asumido esa tarea además de la suya propia, generando cierta tensión dentro del grupo porque este último siente que está haciendo el trabajo de dos personas mientras su compañero se dedica únicamente a observar sin aportar al proceso colectivo de solución del problema planteado por la institución. Diego se pregunta si debería intervenir de inmediato reasignando el rol, o si primero debería entender qué está pasando realmente con el estudiante que ha dejado de participar en el registro del proceso, antes de tomar cualquier decisión que afecte la dinámica del equipo completo durante las semanas restantes del proyecto.',
  'enunciado': '¿Cuál es la intervención MÁS adecuada que debería hacer Diego frente a esta situación dentro del equipo de trabajo?',
  'opcion_a': 'Ignorar la situación, ya que la distribución interna de tareas dentro de un equipo de trabajo no forma parte de lo que un docente debe supervisar durante el proceso de solución de problemas con tecnología.',
  'opcion_b': 'Reasignar de inmediato y de forma permanente el rol de registro escrito al estudiante que ya lo está asumiendo adicionalmente, sin ninguna conversación previa con el estudiante que no ha estado cumpliendo su rol asignado.',
  'opcion_c': 'Eliminar por completo la asignación de roles específicos dentro de los equipos de trabajo, considerando que esta estrategia genera más conflictos de los que resuelve durante el proceso de solución de problemas con tecnología.',
  'opcion_d': 'Conversar directamente con el equipo para entender por qué el estudiante encargado del registro no ha cumplido su rol, y acordar con todo el grupo ajustes concretos que permitan retomar la distribución equitativa de responsabilidades dentro del proceso colectivo de solución del problema.',
  'respuesta_correcta': 'D',
  'nivel_dificultad': 'alto',
  'proceso_cognitivo': 'analisis_situacional',
  'justificacion': 'El trabajo colaborativo con roles definidos es un componente relevante del proceso de solución de problemas con tecnología, y su gestión efectiva requiere intervención docente cuando surgen desequilibrios reales dentro del equipo. Conversar directamente con el grupo para entender la causa del incumplimiento y acordar ajustes concretos permite retomar una distribución equitativa de responsabilidades, sin imponer una solución unilateral ni ignorar la tensión generada dentro del equipo de trabajo.\n\nDistractores:\n- A) Es plausible porque delimita el alcance de la supervisión docente; pero la distribución equitativa de responsabilidades dentro de un equipo es relevante para el proceso de solución de problemas y sí amerita la atención del docente cuando genera tensiones reales.\n- B) Es plausible porque busca resolver el desequilibrio; pero reasignar el rol de forma unilateral, sin conversar primero con el estudiante que no lo ha cumplido, no aborda la causa real de la situación ni fortalece la corresponsabilidad del equipo completo.\n- C) Es plausible porque cuestiona la estrategia de roles; pero eliminar por completo la asignación de roles no resuelve el problema puntual de este equipo, y prescinde de una estrategia que en general favorece la organización del trabajo colaborativo.\n\nError frecuente del aspirante: Asumir que un desequilibrio de responsabilidades dentro de un equipo de trabajo tecnológico debe resolverse eliminando la estrategia de roles o reasignándolos unilateralmente, sin indagar primero la causa real de la situación con el equipo completo.\n\nEstrategia mental recomendada: Ante un conflicto de distribución de responsabilidades dentro de un equipo de solución de problemas con tecnología, identificar la opción que prioriza el diálogo con el equipo y el ajuste acordado, no la imposición unilateral ni la omisión de la situación.\n\nSubcompetencia: Gestión pedagógica del trabajo colaborativo con roles definidos dentro del proceso de solución de problemas con tecnología',
  'fuente_normativa': 'Orientaciones Generales para la Educación en Tecnología (MEN, 2008), componente de Solución de Problemas con Tecnología.',
 },
 {
  'codigo': 'MOD08-TEC-SOL-008',
  'contexto': 'En una institución de Campamento (Antioquia), la docente Yesenia Bedoya recibe un reporte de que el proyector del salón de tecnología de grado once "se dañó" y ya no proyecta ninguna imagen, por lo que varios estudiantes asumen de inmediato que el aparato debe reemplazarse por uno nuevo, ya que en su experiencia previa "cuando un proyector deja de funcionar, generalmente hay que comprar otro". Antes de aceptar esa conclusión y solicitar formalmente un proyector nuevo a la coordinación de recursos, Yesenia decide guiar a los estudiantes en un proceso de diagnóstico paso a paso: revisar si el cable de conexión está correctamente ajustado, si el proyector recibe alimentación eléctrica, si la fuente de imagen está encendida y correctamente seleccionada como entrada, antes de asumir que el problema está en el proyector mismo. Al revisar juntos cada uno de estos elementos con los estudiantes, descubren que el cable estaba efectivamente desconectado en un extremo, y que el proyector, una vez conectado correctamente, funciona sin ningún problema adicional.',
  'enunciado': '¿Qué principio de la solución de problemas con tecnología aplica Yesenia al guiar este proceso de diagnóstico antes de concluir que el proyector debía reemplazarse?',
  'opcion_a': 'El principio de reemplazo inmediato de cualquier artefacto que deje de funcionar, sin necesidad de ningún diagnóstico previo, ya que intentar diagnosticar la causa real de una falla suele ser más costoso en tiempo que simplemente adquirir un artefacto nuevo.',
  'opcion_b': 'El principio de delegación total del diagnóstico técnico a un proveedor externo especializado, sin ninguna participación de los estudiantes ni del docente en la identificación inicial de la causa del problema reportado.',
  'opcion_c': 'El principio de identificación de la causa real de un problema técnico antes de decidir una solución (como el reemplazo del artefacto), evitando conclusiones apresuradas basadas en experiencias previas que pueden no aplicar al caso específico que se está analizando.',
  'opcion_d': 'El principio de aceptación de la primera hipótesis planteada por los estudiantes sobre la causa de una falla, sin ninguna verificación adicional antes de proceder con la solución sugerida inicialmente por el grupo.',
  'respuesta_correcta': 'C',
  'nivel_dificultad': 'alto',
  'proceso_cognitivo': 'aplicacion_disciplinar',
  'justificacion': 'Identificar la causa real de un problema técnico antes de decidir una solución es un principio central de la solución de problemas con tecnología: evita conclusiones apresuradas basadas en generalizaciones de experiencias previas ("cuando un proyector deja de funcionar, hay que comprar otro") que pueden no aplicar al caso específico. El diagnóstico paso a paso que guía Yesenia revela que la causa real era una simple desconexión, no una falla del artefacto que justificara su reemplazo.\n\nDistractores:\n- A) Es plausible porque prioriza la rapidez; pero reemplazar sin diagnosticar puede generar gastos innecesarios cuando la causa real del problema es simple de resolver, como ocurrió en este caso con la desconexión del cable.\n- B) Es plausible porque menciona apoyo externo especializado; pero el caso describe un diagnóstico inicial guiado por la propia docente con los estudiantes, no una delegación total a un proveedor externo antes de cualquier verificación básica.\n- D) Es plausible porque parece una respuesta rápida; pero aceptar la primera hipótesis sin verificación (que el proyector estaba dañado) es exactamente el error que Yesenia evita al guiar el proceso de diagnóstico paso a paso con los estudiantes.\n\nError frecuente del aspirante: Aceptar generalizaciones basadas en experiencias previas como explicación suficiente de una falla técnica, sin verificar la causa real específica del problema en el caso concreto que se está analizando.\n\nEstrategia mental recomendada: Ante un caso de diagnóstico de una falla técnica, identificar la opción que prioriza verificar la causa real específica antes de decidir una solución, en lugar de aceptar generalizaciones o hipótesis no verificadas.\n\nSubcompetencia: Aplicación pedagógica de la identificación de la causa raíz como principio del diagnóstico técnico en la solución de problemas con tecnología',
  'fuente_normativa': 'Orientaciones Generales para la Educación en Tecnología (MEN, 2008), componente de Solución de Problemas con Tecnología.',
 },
 {
  'codigo': 'MOD08-TEC-SOL-009',
  'contexto': 'En una institución de Anorí (Antioquia), el docente Robinson Zea culmina con sus estudiantes de grado décimo un proyecto de solución de problemas con tecnología centrado en el diseño de un sistema de señalización para orientar a los visitantes dentro de la institución durante la feria anual de servicios a la comunidad. Antes de dar por cerrado el proyecto, Robinson pide a cada equipo que prepare una presentación breve del proceso completo que siguieron, no solo del resultado final construido, incluyendo cómo definieron el problema, qué alternativas consideraron y por qué eligieron la solución final entre esas opciones. Un equipo, sin embargo, prepara una presentación centrada exclusivamente en mostrar el sistema de señalización ya terminado, sin mencionar en ningún momento cómo llegaron a esa solución específica, argumentando que "lo único que realmente importa es el resultado final, no todo el proceso previo que nadie más necesita conocer para entender si la solución funciona bien o no".',
  'enunciado': '¿Cuál es la aclaración MÁS adecuada que debería dar Robinson frente al argumento de este equipo sobre la relevancia de comunicar el proceso completo, no solo el resultado final?',
  'opcion_a': 'Confirmar que, efectivamente, comunicar el proceso completo no tiene ninguna relevancia adicional una vez que la solución final ya está construida y funcionando correctamente ante los visitantes de la feria.',
  'opcion_b': 'Indicar que comunicar el proceso (definición, alternativas consideradas, justificación de la elección final) es parte esencial de la competencia, porque permite a otros evaluar las decisiones y fortalece la capacidad de aprender del propio proceso para futuros retos.',
  'opcion_c': 'Explicar que la documentación del proceso completo solo es relevante en el ámbito universitario o profesional, y que en un proyecto escolar como este, mostrar únicamente el resultado final construido es una práctica completamente adecuada y suficiente.',
  'opcion_d': 'Señalar que la única forma válida de comunicar un proceso de solución de problemas con tecnología es mediante un informe escrito extenso, y que cualquier presentación oral breve del proceso resulta insuficiente para este propósito.',
  'respuesta_correcta': 'B',
  'nivel_dificultad': 'muy_alto',
  'proceso_cognitivo': 'evaluacion_juicio',
  'justificacion': 'Comunicar el proceso completo de solución de un problema tecnológico (no solo el resultado final) es parte esencial de la competencia disciplinar, porque permite a otros comprender y evaluar las decisiones tomadas (por qué se eligió una alternativa y no otra), y porque el ejercicio de documentar y explicar esas decisiones fortalece la capacidad de los propios estudiantes de aprender de su proceso para futuros retos de solución de problemas.\n\nDistractores:\n- A) Es plausible porque prioriza el resultado tangible; pero limitar la comunicación al resultado final desaprovecha el valor formativo y comunicativo de explicar el razonamiento detrás de las decisiones tomadas durante el proceso.\n- C) Es plausible porque distingue por nivel educativo; pero comunicar el proceso de solución de problemas es una práctica pedagógica relevante desde la educación básica y media, no exclusiva de contextos universitarios o profesionales.\n- D) Es plausible porque propone un formato específico; pero el caso no exige necesariamente un informe escrito extenso, una presentación oral breve puede comunicar adecuadamente el proceso si incluye la definición del problema, las alternativas y la justificación de la elección final.\n\nError frecuente del aspirante: Considerar que solo el resultado final de una solución tecnológica es relevante de comunicar, sin reconocer el valor formativo y comunicativo de explicar el proceso completo que llevó a esa solución.\n\nEstrategia mental recomendada: Ante un caso sobre la comunicación de un proceso de solución de problemas con tecnología, identificar la opción que defiende la relevancia de comunicar tanto el proceso como el resultado, no solo el producto final construido.\n\nSubcompetencia: Valoración pedagógica de la comunicación del proceso completo de solución de problemas, más allá del resultado final construido',
  'fuente_normativa': 'Orientaciones Generales para la Educación en Tecnología (MEN, 2008), componente de Solución de Problemas con Tecnología.',
 },
 {
  'codigo': 'MOD08-TEC-SOL-010',
  'contexto': 'En una institución de Gómez Plata (Antioquia), la docente Johana Restrepo acompaña a sus estudiantes de grado once en un proyecto de varias semanas para diseñar un cargador solar sencillo capaz de cargar completamente un teléfono celular en un día soleado, destinado a un punto de la institución donde el acceso a tomas eléctricas es limitado. El primer prototipo de un equipo carga el teléfono solo parcialmente, muy por debajo del objetivo planteado, incluso en condiciones de sol favorable. En lugar de considerar el proyecto un fracaso definitivo, Johana orienta al equipo a documentar con precisión el resultado del primer prototipo, identificar posibles causas del bajo rendimiento (ángulo del panel solar, calidad de la conexión, capacidad de la batería intermedia usada) y diseñar un segundo prototipo que ajuste específicamente esas variables identificadas, en lugar de empezar de nuevo sin ningún criterio o de abandonar el proyecto por completo ante el resultado insuficiente del primer intento. El equipo, motivado por esta orientación, decide además comparar sistemáticamente el desempeño del segundo prototipo frente al primero, usando exactamente las mismas condiciones de prueba para que la comparación resulte válida entre ambos intentos.',
  'enunciado': '¿Qué principio del proceso de solución de problemas con tecnología aplica Johana al orientar al equipo de esta manera tras el resultado insuficiente del primer prototipo?',
  'opcion_a': 'El principio de finalización inmediata del proyecto ante cualquier resultado insuficiente en el primer prototipo construido, ya que un desempeño por debajo del objetivo planteado demuestra que el reto propuesto no es viable para el grupo.',
  'opcion_b': 'El principio de repetición idéntica del primer prototipo sin ningún ajuste, ya que la solución de problemas con tecnología exige mantener siempre el mismo diseño original sin importar los resultados obtenidos en las pruebas realizadas.',
  'opcion_c': 'El principio de sustitución total del equipo de estudiantes responsable del primer prototipo, asignando el reto a otro grupo distinto que no haya tenido ninguna relación previa con el diseño que no alcanzó el objetivo esperado.',
  'opcion_d': 'El principio de iteración basada en evidencia: documentar el resultado, identificar causas específicas del desempeño insuficiente y ajustar deliberadamente esas variables en un nuevo prototipo, comparando su desempeño con el anterior bajo condiciones equivalentes de prueba.',
  'respuesta_correcta': 'D',
  'nivel_dificultad': 'alto',
  'proceso_cognitivo': 'aplicacion_disciplinar',
  'justificacion': 'El principio de iteración basada en evidencia es central en la solución de problemas con tecnología: ante un resultado insuficiente, se documenta el desempeño, se identifican causas específicas (ángulo del panel, conexión, capacidad de la batería) y se ajustan deliberadamente esas variables en un nuevo prototipo, comparando su desempeño con el anterior bajo condiciones equivalentes para que la comparación sea válida. Este proceso permite mejoras fundamentadas, en lugar de reconstrucciones arbitrarias o abandonos prematuros del reto planteado.\n\nDistractores:\n- A) Es plausible porque interpreta el resultado insuficiente como definitivo; pero un desempeño por debajo del objetivo en el primer prototipo es información para ajustar el diseño, no una razón suficiente para finalizar el proyecto de inmediato.\n- B) Es plausible porque valora la consistencia; pero repetir el mismo diseño sin ningún ajuste, tras identificar causas específicas del bajo desempeño, desaprovecha por completo el análisis realizado y no mejora el resultado esperado.\n- C) Es plausible porque busca una solución alternativa; pero sustituir al equipo responsable no aborda las causas técnicas del problema identificado, y desestima el aprendizaje que el propio equipo puede obtener al ajustar su diseño con base en la evidencia recogida.\n\nError frecuente del aspirante: Interpretar un resultado insuficiente en un primer prototipo como fracaso definitivo del proyecto, en lugar de reconocer la iteración basada en evidencia como una etapa esperada y valiosa del proceso de solución de problemas con tecnología.\n\nEstrategia mental recomendada: Ante un caso de prototipo con desempeño insuficiente, identificar la opción que aplica iteración basada en evidencia (documentar, analizar causas, ajustar variables específicas, comparar bajo condiciones equivalentes), no el abandono, la repetición idéntica ni la sustitución del equipo.\n\nSubcompetencia: Aplicación pedagógica de la iteración basada en evidencia como principio de mejora continua en la solución de problemas con tecnología',
  'fuente_normativa': 'Orientaciones Generales para la Educación en Tecnología (MEN, 2008), componente de Solución de Problemas con Tecnología.',
 },
]
