# Generated by Django 6.0.5 on 2026-05-18 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('category_type', models.CharField(choices=[('pedagogia', 'Pedagogía'), ('evaluacion', 'Evaluación'), ('inclusion', 'Inclusión'), ('normatividad', 'Normatividad'), ('tic', 'TIC'), ('simulacros', 'Simulacros')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('short_description', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('difficulty_level', models.CharField(choices=[('medium', 'Media'), ('high', 'Alta'), ('very_high', 'Muy Alta'), ('cnsc_expert', 'CNSC Experto')], default='high', max_length=20)),
                ('estimated_time_minutes', models.PositiveIntegerField(default=120)),
                ('is_active', models.BooleanField(default=True)),
                ('is_premium', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='academics.category')),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='NormativeResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('reference', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('official_url', models.URLField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normative_resources', to='academics.module')),
            ],
            options={
                'verbose_name': 'Recurso normativo',
                'verbose_name_plural': 'Recursos normativos',
            },
        ),
    ]
